import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
import Graphic from '@arcgis/core/Graphic';
export declare class DeadGroundMapper {
    static readonly MESH_LAYER_ID = "dead-ground-mesh";
    static readonly CONTOUR_LAYER_ID = "dead-ground-contours";
    static readonly SPOKE_LAYER_ID = "dead-ground-spokes";
    static readonly OBSERVER_LAYER_ID = "dead-ground-observer";
    private _view;
    private _meshLayer;
    private _contourLayer;
    private _spokeLayer;
    private _observerLayer;
    private _heatmapLayer;
    private _panelEl;
    private _pickHandle;
    private _observerPt;
    private _obsZ;
    private _running;
    private _currentView;
    private _dragOffsetX;
    private _dragOffsetY;
    private _isDragging;
    constructor();
    initialize(view: MapView | SceneView): void;
    open(graphic: Graphic, view: MapView | SceneView): void;
    close(): void;
    destroy(): void;
    private _createLayers;
    private _bindPick;
    private _cancelPick;
    private _setObserver;
    private _runAnalysis;
    private _clearResults;
    private _clearAll;
    private _computeDeadGround;
    private _buildHeatmapLayer;
    private _buildContourGraphics;
    private _buildTerrainMesh;
    private _buildObstructionRingGraphics;
    private _buildSpokeGraphics;
    private _destPt;
    private _depthToRGBA;
    private _cellToRGBA;
    private _lerpRGBA;
    private _showPanel;
    private _hidePanel;
    private _buildPanelHtml;
    private _bindPanelEvents;
    private _makeDraggable;
    private _onDragMove;
    private _onDragEnd;
    private _setStatus;
    private _setProgress;
    private _num;
    private _checked;
    private _selectValue;
    private _setText;
    private _el;
    private _injectStyles;
}
export default DeadGroundMapper;
