define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(z,p,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,t,B,C,A,V,W,X,Y,r,Z,D,aa,E,ba,ca,F,m,q,G){return z([D],{declaredClass:"MilitarySymbology.Symbols.Ambush",SID:"141700",symName:"Ambush",symGeometricType:"Area",constructor:function(b){this.map=b;this.o;this._points=[];this._geometryType=null;this.N;this.m=2;this.j=5;this.C=this.A;this.D=this.F;this.G=this.H;this._tGraphic=new t},init:function(b,d){this.o=d;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();this.m=2;this.j=5;var c;
new q;new F(this.map,this.o);this.m=m.setDefault(b,"TEETH_SIZE",this.m);this.j=m.setDefault(b,"TEETH_GAP",this.j);b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),c=this.v(p.clone(b.CTRL_PTS),b.TEETH_SIZE,b.TEETH_GAP),this.u(this._tGraphic.geometry,c),this._clear()):b.hasOwnProperty("CTRL_PTS")?(c=this.v(p.clone(b.CTRL_PTS),b.TEETH_SIZE,b.TEETH_GAP),this._tGraphic.setGeometry(this.createSymbol(c)),this.u(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=
new t(null,this.o),this.map.graphics.add(this._tGraphic),this.C=r(this.map,"click",p.hitch(this,this.A)),this.D=r(this.map,"dbl-click",p.hitch(this,this.F)))},P:function(b,d,c){var a=Math.sqrt(Math.pow(c.x-b.x,2)+Math.pow(c.y-b.y,2));c=Math.sqrt(Math.pow(c.x-d.x,2)+Math.pow(c.y-d.y,2));b=Math.sqrt(Math.pow(d.x-b.x,2)+Math.pow(d.y-b.y,2));return Math.acos((c*c+a*a-b*b)/(2*c*a))},v:function(b,d,c){var a=new q;a.SCOPE=this;a.SYM_GEO_TYPE=this.symGeometricType;a.SID=this.SID;a.SYM_GEO_TYPE=this.symGeometricType;
a.SYM_NAME=this.symName;a.CTRL_PTS=b;a.AMPLIFIER=this.amplifier;a.TEETH_SIZE=d;a.TEETH_GAP=c;return a},createSymbol:function(b){try{var d;if(b.hasOwnProperty("CTRL_PTS"))d=b.CTRL_PTS;else throw"controlPoints not found";var c=new A(this.map.spatialReference),a=d[0],e=d[1];if(2===d.length)c.addPath([a,e]);else if(3===d.length){var f=d[2],g,h=[],l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),
this.map.toScreen(e),this.map.toScreen(f),60,this.map),h=g.geometry.paths[0],c.addPath(h.slice(0,60)));for(var p=c.getExtent().getCenter(),q=m._2PtLen(e,c.getPoint(0,30))/10,r=q*m.setDefault(b,"TEETH_SIZE",this.m),w=m.angleInRadians(p,c.getPoint(0,30)),v=m.setDefault(b,"TEETH_GAP",this.j),n=v;60>n;n+=v)c.addPath(this.I(c.getPoint(0,n),w,r))}else if(3<d.length){var f=d[2],u=d[d.length-1],t=d[d.length-2],h=[],l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&
(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f),60,this.map),h=g.geometry.paths[0],c.addPath(h.slice(0,60)));p=c.getExtent().getCenter();h=[];h.push(c.getPoint(0,30));for(n=3;n<d.length-1;n++)h.push(d[n]);h=h.concat(u);c.addPath(h);q=m._2PtLen(e,c.getPoint(0,30))/10;r=q*m.setDefault(b,"TEETH_SIZE",this.m);w=m.angleInRadians(p,c.getPoint(0,30));for(n=v=m.setDefault(b,"TEETH_GAP",this.j);60>n;n+=v)c.addPath(this.I(c.getPoint(0,n),w,r));c.addPath(G.arrowHead(u,
m.ArrowFlanksLen(m._2PtLen(t,u),m._2PtLen(a,u)),m.angleInRadians(t,u)))}return c}catch(z){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},H:function(b){b=b.mapPoint;var d=new q;d.CTRL_PTS=this._points.concat(b);d.TEETH_GAP=this.j;d.TEETH_SIZE=this.m;this._tGraphic.setGeometry(this.createSymbol(d));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:d,currentMarker:this.o})},A:function(b){this._points.push(b.mapPoint.offset(0,
0));1==this._points.length&&(this.G=r(this.map,"mouse-move",p.hitch(this,this.H)));this.emit("onDrawClick",{currentPts:this._points})},F:function(b){this._points.push(b.mapPoint);this.K()},K:function(){var b;new q;b=this.v(p.clone(this._points),this.m,this.j);this.u(this._tGraphic.geometry,b);this._clear();this._removeEvents()},u:function(b,d){if(b){var c=this.map.S,a;c&&(c.isWebMercator()?a=C.webMercatorToGeographic(b,!0):4326===c.wkid&&(a=B.fromJson(b.toJson())));this.J(b,a,d)}},J:function(b,d,
c){this.emit("onDrawEnd",{geometry:b,geographicGeometry:d,drawEssentials:c,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.C.remove();this.D.remove();this.G.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},O:function(){},_circleDrawEx:function(b,
d,c){var a,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[b.x,b.y],[d.x,d.y],[c.x,c.y]];for(a=0;3>a;a++)e[a][0]=f[a][0],e[a][1]=f[a][1],e[a][2]=1;b=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][1],e[a][2]=1;d=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][0],e[a][2]=1;c=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][0],e[a][2]=f[a][1];e=this._determinantDrawEx(e,
3);if(0==b)e=0;else{var g=.5*d/b,h=-.5*c/b;e=Math.sqrt(g*g+h*h+e/b)}return{radius:e,center:{x:g,y:h}}},_determinantDrawEx:function(b,d){var c,a,e,f,g,h=[[0,0,0],[0,0,0],[0,0,0]];if(2==d)g=b[0][0]*b[1][1]-b[1][0]*b[0][1];else for(e=g=0;e<d;e++){for(c=1;c<d;c++)for(a=f=0;a<d;a++)a!=e&&(h[c-1][f]=b[c][a],f++);g+=Math.pow(-1,e)*b[0][e]*this._determinantDrawEx(h,d-1)}return g},CreateCircleSegmentFromThreePoints:function(b,d,c,a,e,f){var g=b.center,h=b.radius;b=[];d.x-=g.x;d.y-=g.y;c.x-=g.x;c.y-=g.y;a.x-=
g.x;a.y-=g.y;d=Math.atan2(d.y,d.x);var l=Math.atan2(c.y,c.x);c=Math.atan2(a.y,a.x);d=0>d?2*Math.PI+d:d;l=0>l?2*Math.PI+l:l;c=0>c?2*Math.PI+c:c;a=Math.min(d,l);d=Math.max(d,l);l=d-a;if(c<a||c>d)l-=2*Math.PI;d=l/e;for(l=0;l<=e;l++)c=f.toMap({x:h*Math.cos(a+l*d)+g.x,y:h*Math.sin(a+l*d)+g.y}),b.push(c);f=new A(f.spatialReference);f.addPath(b);return{geometry:f,lastPoint:b[e],backPoint:b[e-5]}},I:function(b,d,c){d=new E(-1*c*Math.cos(d)+b.x,-1*c*Math.sin(d)+b.y,this.map.spatialReference);return[b,d]}})});
