define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(u,m,D,E,v,F,G,H,I,J,K,L,M,N,w,q,r,z,A,O,t,P,Q,R,p,S,B,T,U,V,W,C,X,n){return u([B],{declaredClass:"MilitarySymbology.Symbols.ArcOfFireSD",SID:"152300",symName:"Arc of Fire",symGeometricType:"Area",constructor:function(c){this.map=c;this.j;this._points=[];this._geometryType=null;this.I;this.v=this.u;this.A=this.C;this.D=this.F;this._tGraphic=new r},init:function(c,a){this.j=a;var d=new v;d.setColor(a.color);d.a=.25;this.j=new q(q.STYLE_SOLID,new w(a.style,a.color,a.width),d);this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();new n;new C(this.map,this.j);c.hasOwnProperty("CTRL_PTS")&&c.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(c.GEOM),d=this.o(m.clone(c.CTRL_PTS)),this.m(this._tGraphic.geometry,d),this._clear()):c.hasOwnProperty("CTRL_PTS")?(d=this.o(m.clone(c.CTRL_PTS)),this._tGraphic.setGeometry(this.createSymbol(d)),this.m(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new r(null,this.j),this.map.graphics.add(this._tGraphic),this.v=p(this.map,"click",m.hitch(this,
this.u)),this.A=p(this.map,"dbl-click",m.hitch(this,this.C)))},K:function(c,a,d){var b=Math.sqrt(Math.pow(d.x-c.x,2)+Math.pow(d.y-c.y,2));d=Math.sqrt(Math.pow(d.x-a.x,2)+Math.pow(d.y-a.y,2));c=Math.sqrt(Math.pow(a.x-c.x,2)+Math.pow(a.y-c.y,2));return Math.acos((d*d+b*b-c*c)/(2*d*b))},o:function(c){var a=new n;a.SCOPE=this;a.SYM_GEO_TYPE=this.symGeometricType;a.SID=this.SID;a.SYM_GEO_TYPE=this.symGeometricType;a.SYM_NAME=this.symName;a.CTRL_PTS=c;a.AMPLIFIER=this.amplifier;return a},createSymbol:function(c){try{var a;
if(c.hasOwnProperty("CTRL_PTS"))a=c.CTRL_PTS;else throw"controlPoints not found";var d=new t(this.map.spatialReference),b=a[0],e=a[1];if(2===a.length)d.addRing([b,e]);else if(3===a.length){var f=a[2],h,g=[],l=this._circleDrawEx(this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(h=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f),60,this.map),g=h.geometry.rings[0],d.addRing(g.slice(0,60)))}else 3<a.length&&(f=a[2],g=[],
l=this._circleDrawEx(this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f)),0<l.radius&&(h=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f),60,this.map),g=h.geometry.rings[0],g.push([g[g.length-1][0],g[g.length-1][1]]),g.push([a[a.length-1].x,a[a.length-1].y]),g.push([g[0][0],g[0][1]]),g.push([g[0][0],g[0][1]]),g.push([a[a.length-1].x,a[a.length-1].y]),d.addRing(g.slice(0,g.length-1))));return d}catch(m){console.log(this.declaredClass+
" Can not create Symbol due to invalid geometry")}},F:function(c){c=c.mapPoint;var a=new n;a.CTRL_PTS=this._points.concat(c);this._tGraphic.setGeometry(this.createSymbol(a));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:a,currentMarker:this.j})},u:function(c){this._points.push(c.mapPoint.offset(0,0));1==this._points.length&&(this.D=p(this.map,"mouse-move",m.hitch(this,this.F)));this.emit("onDrawClick",{currentPts:this._points});4===this._points.length&&
(this.emit("onDrawClick",{currentPts:this._points}),this.G())},C:function(c){this._points.push(c.mapPoint);this.G()},G:function(){var c;new n;c=this.o(m.clone(this._points));this.m(this._tGraphic.geometry,c);this._clear();this._removeEvents()},m:function(c,a){if(c){var d=this.map.N,b;d&&(d.isWebMercator()?b=A.webMercatorToGeographic(c,!0):4326===d.wkid&&(b=z.fromJson(c.toJson())));this.H(c,b,a)}},H:function(c,a,d){this.emit("onDrawEnd",{geometry:c,geographicGeometry:a,drawEssentials:d,marker:this.j})},
_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.v.remove();this.A.remove();this.D.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},J:function(){},_circleDrawEx:function(c,a,d){var b,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[c.x,c.y],[a.x,a.y],[d.x,d.y]];for(b=0;3>b;b++)e[b][0]=
f[b][0],e[b][1]=f[b][1],e[b][2]=1;c=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][1],e[b][2]=1;a=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][0],e[b][2]=1;d=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][0],e[b][2]=f[b][1];e=this._determinantDrawEx(e,3);if(0==c)e=0;else{var h=.5*a/c,g=-.5*d/c;e=Math.sqrt(h*h+g*g+e/c)}return{radius:e,center:{x:h,
y:g}}},_determinantDrawEx:function(c,a){var d,b,e,f,h,g=[[0,0,0],[0,0,0],[0,0,0]];if(2==a)h=c[0][0]*c[1][1]-c[1][0]*c[0][1];else for(e=h=0;e<a;e++){for(d=1;d<a;d++)for(b=f=0;b<a;b++)b!=e&&(g[d-1][f]=c[d][b],f++);h+=Math.pow(-1,e)*c[0][e]*this._determinantDrawEx(g,a-1)}return h},CreateCircleSegmentFromThreePoints:function(c,a,d,b,e,f){var h=c.center,g=c.radius;c=[];a.x-=h.x;a.y-=h.y;d.x-=h.x;d.y-=h.y;b.x-=h.x;b.y-=h.y;a=Math.atan2(a.y,a.x);var l=Math.atan2(d.y,d.x);d=Math.atan2(b.y,b.x);a=0>a?2*Math.PI+
a:a;l=0>l?2*Math.PI+l:l;d=0>d?2*Math.PI+d:d;b=Math.min(a,l);a=Math.max(a,l);l=a-b;if(d<b||d>a)l-=2*Math.PI;a=l/e;for(l=0;l<=e;l++)d=f.toMap({x:g*Math.cos(b+l*a)+h.x,y:g*Math.sin(b+l*a)+h.y}),c.push(d);f=new t(f.spatialReference);f.addRing(c);return{geometry:f,lastPoint:c[e],backPoint:c[e-5]}}})});
