define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials".split(" "),
function(w,f,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,v,B,D,C,U,V,W,X,r,Y,E,Z,m,aa,ba,F,d,l){return w([E],{declaredClass:"MilitarySymbology.Symbols.SupportByFirePosition",SID:"152000",symName:"Attk by Fire Posn",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.Z=b;this.m;this._points=[];this.j=[];this._geometryType=null;this.u;this.o;this.K=this.N;this.O=this.P;this.J=this.I;this.C;this.H;this.G;this._tGraphic=new v},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();this.u=d.setDefault(a,"BK_LN_DIST_RATIO",5);this.o=d.setDefault(a,"BK_LN_ANGL_RATIO",5);var c;new l;c=new F(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),c=this.D(f.clone(a.CTRL_PTS),f.clone(a.BASE_LN_PTS),this.u,this.o),this.A(this._tGraphic.geometry,c),this.v();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))c=this.D(f.clone(a.CTRL_PTS),f.clone(a.BASE_LN_PTS),
this.u,this.o);else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(c));this.A(this._tGraphic.geometry,c);this.v()}else this.C=c.on("drawEnd",f.hitch(this,this.X)),this.G=c.on("onBaseLineClick",f.hitch(this,this.W)),this.H=c.on("onBaseLineProgress",f.hitch(this,this.Y)),c.init()},D:function(a,b,c,d){var e=new l;e.SCOPE=this;e.SYM_GEO_TYPE=this.symGeometricType;e.SID=this.SID;e.SYM_GEO_TYPE=this.symGeometricType;
e.SYM_NAME=this.symName;e.BK_LN_DIST_RATIO=c;e.BK_LN_ANGL_RATIO=d;e.CTRL_PTS=a;e.BASE_LN_PTS=b;e.AMPLIFIER=this.amplifier;return e},X:function(a){this.C.remove();this.H.remove();this.G.remove();this._tGraphic=new v(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.O=r(this.map,"mouse-move",f.hitch(this,this.P));this.J=r(this.map,"click",f.hitch(this,this.I));this.K=r(this.map,"dbl-click",f.hitch(this,this.N));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},
Y:function(a){var b=[];b.CTRL_PTS=a.currentGeometry;var c=new C(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:b,currentMarker:a.currentMarker,isBaseLine:!0})},W:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var b,c,f;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";c=d.setDefault(a,"BK_LN_DIST_RATIO",5);f=d.setDefault(a,"BK_LN_ANGL_RATIO",
5);var e=a.BASE_LN_PTS.startPt,l=a.BASE_LN_PTS.endPt,r=b[0],n=b[b.length-1];a=[];if(void 0===e||void 0===l)throw"First Parameter of the Function is an Array with Start and End Point";var g=d.getMidPoint(e,l),p=new C(this.map.spatialReference);1<=b.length&&(n=r);var q=d._2PtLen(g,l),h=Math.atan((g.y-n.y)/(g.x-n.x));switch(d.twoPtsRelationShip(g,n)){case "ne":h+=Math.PI/2;break;case "nw":h+=3*Math.PI/2;break;case "sw":h+=3*Math.PI/2;break;case "se":h+=Math.PI/2}var e=q,t={x:e*Math.cos(h)+g.x,y:e*Math.sin(h)+
g.y},u={x:-1*e*Math.cos(h)+g.x,y:-1*e*Math.sin(h)+g.y};paths=[];paths=paths.concat(t,u);p.addPath(paths);1<=b.length&&a.push(g);for(h=0;h<b.length;h++)a.push(b[h]);p.addPath(a);p.addPath(this.V(b[b.length-1],d.ArrowFlanksLen(d._2PtLen(g,b[b.length-1]),d._2PtLen(t,u)),d.angleInRadians(a[a.length-2],b[b.length-1])));length=d._2PtLen(g,n);angle=d.angleInRadians(g,n);length/=c;var z=new m(t.x-length*Math.cos(angle),t.y-length*Math.sin(angle),this.map.spatialReference),A=new m(u.x-length*Math.cos(angle),
u.y-length*Math.sin(angle),this.map.spatialReference),q=length/f;angle=d.angleInRadians(z,A);var v=new m(-1*q*Math.cos(angle)+z.x,-1*q*Math.sin(angle)+z.y,this.map.spatialReference),w=new m(q*Math.cos(angle)+A.x,q*Math.sin(angle)+A.y,this.map.spatialReference);paths=[];paths=paths.concat(t,v);p.addPath(paths);paths=[];paths=paths.concat(u,w);p.addPath(paths);return p}catch(B){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},ea:function(){return this.j},P:function(a){a=
a.mapPoint;var b=new l;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.j;b.BK_LN_DIST_RATIO=this.u;b.BK_LN_ANGL_RATIO=this.o;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},I:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.Z&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.S())},N:function(a){this._points.push(a.mapPoint);
this.S()},S:function(){var a;new l;a=this.D(f.clone(this._points),f.clone(this.j),this.u,this.o);this.A(this._tGraphic.geometry,a);this.v();this.F()},A:function(a,b){if(a){var c=this.map.oa,d;c&&(c.isWebMercator()?d=D.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=B.fromJson(a.toJson())));this.U(a,d,b)}},U:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},v:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;
this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},F:function(){this.J.remove();this.K.remove();this.O.remove();this.C.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this.v();this.F();this._geometryType=null},V:function(a,b,c){var f=[];c+=15;var e=d.toDegrees(c);c=d.toDegrees(c-30);e=new m(a.x+b*Math.cos(d.toRad(e)),a.y+b*Math.sin(d.toRad(e)),this.map.spatialReference);b=new m(a.x+b*Math.cos(d.toRad(c)),
a.y+b*Math.sin(d.toRad(c)),this.map.spatialReference);return f=f.concat(e,a,b)},$:function(){}})});
