define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(B,p,C,H,I,J,K,L,M,N,O,P,Q,R,S,T,z,D,E,U,w,V,W,X,u,Y,F,Z,aa,ba,ca,G,g,t,A){return B([F],{declaredClass:"MilitarySymbology.Symbols.AxisOfAdvanceFeint",SID:"151406",symName:"Axis Of Advance For Feint",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.O=b;this.o;this._points=[];this._geometryType=null;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new z;this.j=.05;this.m=.07},init:function(a,b){this.o=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
this.m=g.setDefault(a,"HEAD_RATIO",this.m);this.j=g.setDefault(a,"TAIL_FACTOR",this.j);var d;new t;new G(this.map,this.o);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.v(p.clone(a.CTRL_PTS),this.m,this.j),this.u(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.v(p.clone(a.CTRL_PTS),this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(d)),this.u(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new z(null,
this.o),this.map.graphics.add(this._tGraphic),this.D=u(this.map,"click",p.hitch(this,this.C)),this.F=u(this.map,"dbl-click",p.hitch(this,this.G)))},v:function(a,b,d){var c=new t;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.HEAD_RATIO=b;c.TAIL_FACTOR=d;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";
if(2>=b.length){var d=b[0],c=b[b.length-1],h=g._2PtLen(d,c),e=Math.atan((d.y-c.y)/(d.x-c.x));switch(g.twoPtsRelationShip(d,c)){case "ne":e+=Math.PI/2;break;case "nw":e+=3*Math.PI/2;break;case "sw":e+=3*Math.PI/2;break;case "se":e+=Math.PI/2}var n={x:this.j*h*Math.cos(e)+d.x,y:this.j*h*Math.sin(e)+d.y},q={x:-1*this.j*h*Math.cos(e)+d.x,y:-1*this.j*h*Math.sin(e)+d.y},f=(1-this.m)*h,l={x:this.j*f*Math.cos(e)+d.x,y:this.j*f*Math.sin(e)+d.y},p={x:-1*this.j*f*Math.cos(e)+d.x,y:-1*this.j*f*Math.sin(e)+d.y},
v=new w(this.map.spatialReference),m=[];m.push(n);var r=this.CreateArrowHeadPathEx(l,c,p,h,this.m,15),m=m.concat(r.rings);m.push(p);w.prototype.isClockwise(m)||this.Y||(console.debug(this.declaredClass+" :  Polygons drawn in anti-clockwise direction will be reversed to be clockwise."),m.reverse())}else{a=[];d=[];v=new w(this.map.spatialReference);c=b[b.length-1];tempArray=[];a=[];d=[];C.forEach(b,function(a){tempArray.push({x:a.x,y:a.y})});angleArray=g._vertexAngle(tempArray);for(var t=g._ptCollectionLen(tempArray,
0),e=0,h=tempArray.length-1;e<h;e++)f=g._ptCollectionLen(tempArray,e),f+=t/2.4,n={x:this.j*f*Math.cos(angleArray[e])+tempArray[e].x,y:this.j*f*Math.sin(angleArray[e])+tempArray[e].y},q={x:-1*this.j*f*Math.cos(angleArray[e])+tempArray[e].x,y:-1*this.j*f*Math.sin(angleArray[e])+tempArray[e].y},a.push(n),d.push(q);a.push({x:c.x,y:c.y});d.push({x:c.x,y:c.y});a=A.CreateBezierPathPCOnly(a,70);a.splice(Math.floor(70*(1-this.m)),Number.MAX_VALUE);d=A.CreateBezierPathPCOnly(d,70);d.splice(Math.floor(70*(1-
this.m)),Number.MAX_VALUE);var r=this.CreateArrowHeadPathEx(a[a.length-1],c,d[d.length-1],g._ptCollectionLen(tempArray,0),this.m,15),u=r.rings,m=[],m=m.concat(a),m=m.concat(u),m=m.concat(d.reverse())}v.addRing(m);b=g._fracturePts(r.P,r.K,10,this.map.spatialReference);g.addAllRings(b.geometry.paths,v);b=g._fracturePts(r.S,r.K,10,this.map.spatialReference);g.addAllRings(b.geometry.paths,v);return v}catch(da){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},X:function(){return this.A},
I:function(a){a=a.mapPoint;var b=new t;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.A;b.BK_LN_DIST_RATIO=this.W;b.BK_LN_ANGL_RATIO=this.V;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.o})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.H=u(this.map,"mouse-move",p.hitch(this,this.I)));1==this.O&&1==this._points.length&&this.J()},G:function(a){this._points.push(a.mapPoint);
this.J()},J:function(){var a;new t;a=this.v(p.clone(this._points),this.m,this.j);this.u(this._tGraphic.geometry,a);this._clear();this._removeEvents()},u:function(a,b){if(a){var d=this.map.Z,c;d&&(d.isWebMercator()?c=E.webMercatorToGeographic(a,!0):4326===d.wkid&&(c=D.fromJson(a.toJson())));this.N(a,c,b)}},N:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=
null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.A=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},U:function(){},CreateArrowHeadPathEx:function(a,b,d,c,h,e,n){var q=c*h;c=1.07*q;var f=g.twoPtsAngle(b,a);h=g.twoPtsAngle(b,d);var l=Math.abs(f-h)/2;Math.abs(f-h)>1.88*Math.PI&&
(l+=Math.PI);var p=Math.asin(q*Math.sin(l+e/180*Math.PI)/Math.sqrt(q*q+c*c-2*c*q*Math.cos(l+e/180*Math.PI)))+e/180*Math.PI,l=0==n||void 0==n?q*Math.sin(Math.PI-p-l)/Math.sin(p):0;n=[];q={x:b.x+l*Math.cos(f),y:b.y+l*Math.sin(f)};f={x:b.x+c*Math.cos(f-e/180*Math.PI),y:b.y+c*Math.sin(f-e/180*Math.PI)};n.push(q);n.push(f);n.push(b);l={x:b.x+l*Math.cos(h),y:b.y+l*Math.sin(h)};e={x:b.x+c*Math.cos(h+e/180*Math.PI),y:b.y+c*Math.sin(h+e/180*Math.PI)};n.push(e);n.push(l);g.getMidPoint(q,f);g.getMidPoint(l,
e);a=g.getMidPoint(a,d);a=g.twoPtsAngle(a,b);return{rings:n,P:{x:f.x+c/5*Math.cos(a),y:f.y+c/5*Math.sin(a)},K:{x:b.x+c/5*Math.cos(a),y:b.y+c/5*Math.sin(a)},S:{x:e.x+c/5*Math.cos(a),y:e.y+c/5*Math.sin(a)}}}})});
