define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(B,n,z,G,H,I,J,K,L,M,N,O,P,Q,R,S,A,C,D,r,T,U,V,W,w,X,E,Y,p,Z,aa,F,l,u,t){return B([E],{declaredClass:"MilitarySymbology.Symbols.BattlePosition",SID:"151200",symName:"Battle Posn",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.Y=b;this.j;this._points=[];this._geometryType=null;this.Z;this.A=0;this.v=1;this.C=0;this.m=5;this.o=2;this.H=this.G;this.I=this.J;this.K=this.N;this._tGraphic=new A},init:function(a,b){this.j=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var d;new u;new F(this.map,this.j);this.A=a.ECHELON;this.v=a.DRAW_TYPE;this.C=a.FACE_GAP;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.D(n.clone(a.CTRL_PTS),a.ECHELON,a.DRAW_TYPE,a.FACE_GAP),this.u(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.D(n.clone(a.CTRL_PTS),a.ECHELON,a.DRAW_TYPE,a.FACE_GAP),this._tGraphic.setGeometry(this.createSymbol(d)),this.u(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new A(null,
this.j),this.map.graphics.add(this._tGraphic),this.H=w(this.map,"click",n.hitch(this,this.G)),this.I=w(this.map,"dbl-click",n.hitch(this,this.J)))},D:function(a,b,d,g){var e=new u;e.SCOPE=this;e.SYM_GEO_TYPE=this.symGeometricType;e.SID=this.SID;e.SYM_NAME=this.symName;e.CTRL_PTS=a;e.AMPLIFIER=this.amplifier;e.ECHELON=b;e.DRAW_TYPE=d;e.FACE_GAP=g;return e},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var d=b[b.length-1],g=b[0],
e=new r(this.map.spatialReference);switch(a.DRAW_TYPE){case 1:e=this.U(b,g,d,a,e);break;case 2:e=this.S(b,g,d,a,e);break;case 3:e=this.V(b,g,d,a,e)}return e}catch(c){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},N:function(a){a=a.mapPoint;var b=new u;b.CTRL_PTS=this._points.concat(a);b.ECHELON=this.A;b.DRAW_TYPE=this.v;b.FACE_GAP=this.C;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,
currentMarker:this.j})},G:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.K=w(this.map,"mouse-move",n.hitch(this,this.N)));this.emit("onDrawClick",{currentPts:this._points});1==this.Y&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.O())},J:function(a){this._points.push(a.mapPoint);this.O()},O:function(){var a;new u;a=this.D(n.clone(this._points),this.A,this.v,this.C);this.u(this._tGraphic.geometry,a);this._clear();this._removeEvents()},
u:function(a,b){if(a){var d=this.map.ea,g;d&&(d.isWebMercator()?g=D.webMercatorToGeographic(a,!0):4326===d.wkid&&(g=C.fromJson(a.toJson())));this.P(a,g,b)}},P:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.H.remove();this.I.remove();
this.K.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},$:function(){},F:function(a,b,d){var g={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var e=TweenMax.to(g,b,{bezier:a,ease:Linear.easeNone});a=[];var c;for(c=0;c<=b;c++)e.time(c),a.push({x:g.x,y:g.y});b=new r(d.spatialReference);b.addPath(a);
return b},X:function(a,b){var d,g,e,c,f,h;if(1<b.length){for(c=1;c<b.length;c++){b[c].x!=b[c-1].x?(f=(b[c].y-b[c-1].y)/(b[c].x-b[c-1].x),f=Math.abs(f*a.x+(b[c].y-f*b[c].x)-a.y)/Math.sqrt(f*f+1)):f=Math.abs(a.x-b[c].x);var m=Math.pow(b[c].y-b[c-1].y,2)+Math.pow(b[c].x-b[c-1].x,2),v=Math.pow(b[c].y-a.y,2)+Math.pow(b[c].x-a.x,2),l=Math.pow(b[c-1].y-a.y,2)+Math.pow(b[c-1].x-a.x,2),q=Math.pow(f,2),n=v-q+l-q;n>m&&(f=Math.sqrt(Math.min(v,l)));if(null==d||d>f)n>m?l<v?(g=0,e=1):(e=0,g=1):(g=Math.sqrt(l-q)/
Math.sqrt(m),e=Math.sqrt(v-q)/Math.sqrt(m)),d=f,h=c}d=b[h-1].y-b[h].y;c=b[h-1].x-(b[h-1].x-b[h].x)*g;f=b[h-1].y-d*g}return{x:c,y:f,index:h,fTo:g,fFrom:e}},W:function(a,b){var d,g,e,c,f,h;if(1<b.length){for(c=1;c<b.length;c++){b[c][0]!=b[c-1][0]?(f=(b[c][1]-b[c-1][1])/(b[c][0]-b[c-1][0]),f=Math.abs(f*a.x+(b[c][1]-f*b[c][0])-a.y)/Math.sqrt(f*f+1)):f=Math.abs(a.x-b[c][0]);var m=Math.pow(b[c][1]-b[c-1][1],2)+Math.pow(b[c][0]-b[c-1][0],2),l=Math.pow(b[c][1]-a.y,2)+Math.pow(b[c][0]-a.x,2),n=Math.pow(b[c-
1][1]-a.y,2)+Math.pow(b[c-1][0]-a.x,2),q=Math.pow(f,2),p=l-q+n-q;p>m&&(f=Math.sqrt(Math.min(l,n)));if(null==d||d>f)p>m?n<l?(g=0,e=1):(e=0,g=1):(g=Math.sqrt(n-q)/Math.sqrt(m),e=Math.sqrt(l-q)/Math.sqrt(m)),d=f,h=c}d=b[h-1][1]-b[h][1];c=b[h-1][0]-(b[h-1][0]-b[h][0])*g;f=b[h-1][1]-d*g}return{x:c,y:f,index:h,fTo:g,fFrom:e}},U:function(a,b,d,g){var e=new r(this.map.spatialReference);if(2===a.length)e.addPath([d,b]);else if(2<a.length){var c=[];z.forEach(a,function(a){c.push({x:a.x,y:a.y})});var e=this.F(c,
100,this.map),f=e.paths[0][e.paths[0].length-1];a=l.getMidPoint(new p(f[0],f[1],this.map.spatialReference),e.getPoint(0,0));var f=l._2PtLen(new p(f[0],f[1],this.map.spatialReference),e.getPoint(0,0)),h=f/10;h>f/3.6&&(h=f/3.6);b=t.createEchelon(g.ECHELON,a,h,l.angleInRadians(b,d));for(d=0;d<=b.length-1;d++)e.addPath(b[d])}return e},S:function(a,b,d,g){var e=new r(this.map.spatialReference),c=[];if(2===a.length)e.addPath([d,b]);else if(2<a.length){var f=[];z.forEach(a,function(a){f.push({x:a.x,y:a.y})});
f.push({x:b.x,y:b.y});c=this.F(f,100,this.map).paths[0];a=this.W(d,c);b=a.index-this.m-Math.floor(l.setDefault(g,"FACE_GAP",this.m)/2);d=a.index+this.m+Math.floor(l.setDefault(g,"FACE_GAP",this.m)/2);100<=d&&(d=100);e.addPath(c.slice(0,b));e.addPath(c.slice(d,101));b=new p(c[b][0],c[b][1],this.map.spatialReference);var c=new p(c[d][0],c[d][1],this.map.spatialReference),h;d=l._2PtLen(b,c);var m=d/10;m>d/3.6&&(m=d/3.6);isNaN(m)?m=h:h=m;g=t.createEchelon(g.ECHELON,a,m,l.angleInRadians(b,c));for(h=0;h<=
g.length-1;h++)e.addPath(g[h])}return e},V:function(a,b,d,g){var e=new r(this.map.spatialReference);if(2===a.length){b=this.map.toScreen(b);var c=this.map.toScreen(d);a=c.x-b.x;c=c.y-b.y;a=t.createEllipse({center:b,longAxis:a,shortAxis:c,numberOfPoints:60,map:this.map});e.addPath(a)}else if(2<a.length){a=a[1];b=this.map.toScreen(b);c=this.map.toScreen(a);a=c.x-b.x;c=c.y-b.y;a=t.createEllipse({center:b,longAxis:a,shortAxis:c,numberOfPoints:60,map:this.map});d=this.X(d,a);b=d.index-this.o-Math.floor(l.setDefault(g,
"FACE_GAP",this.o)/2);c=d.index+this.o+Math.floor(l.setDefault(g,"FACE_GAP",this.o)/2);0>=b&&(b=0);60<=c&&(c=60);e.addPath(a.slice(0,b));e.addPath(a.slice(c,61));b=new p(a[b].x,a[b].y,this.map.spatialReference);a=new p(a[c].x,a[c].y,this.map.spatialReference);var c=l._2PtLen(b,a),f=c/10;f>c/3.6&&(f=c/3.6);isNaN(f)&&(f=void 0);g=t.createEchelon(g.ECHELON,d,f,l.angleInRadians(b,a));for(d=0;d<=g.length-1;d++)e.addPath(g[d])}return e}})});
