define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials".split(" "),
function(p,d,z,A,B,C,D,E,F,G,H,I,J,K,L,M,l,r,u,t,N,O,P,Q,g,R,v,S,T,U,V,w,q,h){return p([v],{declaredClass:"MilitarySymbology.Symbols.BlockObstacleEffect",SID:"270501",symName:"Block / Obstacle Effect",symGeometricType:"Area",isObstacle:"1",constructor:function(a,c){this.map=a;this.U=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.D=this.F;this.G=this.H;this.C=this.A;this.u;this.N;this.K;this._tGraphic=new l},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();var b;new h;b=new w(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.v(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.v(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";
this._tGraphic.setGeometry(this.createSymbol(b));this.o(this._tGraphic.geometry,b);this._clear()}else this.u=b.on("drawEnd",d.hitch(this,this.P)),this.K=b.on("onBaseLineClick",d.hitch(this,this.O)),this.N=b.on("onBaseLineProgress",d.hitch(this,this.S)),b.init()},v:function(a,c){var b=new h;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_NAME=this.symName;b.V=this.isObstacle;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;return b},P:function(a){this.u.remove();this._tGraphic=
new l(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=g(this.map,"mouse-move",d.hitch(this,this.H));this.C=g(this.map,"click",d.hitch(this,this.A));this.D=g(this.map,"dbl-click",d.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new t(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,currentMarker:a.currentMarker,
isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,d=a.BASE_LN_PTS.endPt,h=c[0],m=c[c.length-1];a=[];if(void 0===b||void 0===d)throw"First Parameter of the Function is an Array with Start and End Point";var e=q.getMidPoint(b,d),g=new t(this.map.spatialReference);1<=c.length&&(m=h);var n=q._2PtLen(e,d),f=Math.atan((e.y-
m.y)/(e.x-m.x));switch(q.twoPtsRelationShip(e,m)){case "ne":f+=Math.PI/2;break;case "nw":f+=3*Math.PI/2;break;case "sw":f+=3*Math.PI/2;break;case "se":f+=Math.PI/2}var l={x:n*Math.cos(f)+e.x,y:n*Math.sin(f)+e.y},p={x:-1*n*Math.cos(f)+e.x,y:-1*n*Math.sin(f)+e.y};paths=[];paths=paths.concat(l,p);g.addPath(paths);1<=c.length&&a.push(e);for(b=0;b<c.length;b++)a.push(c[b]);g.addPath(a);return g}catch(r){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},W:function(){return this.j},
H:function(a){a=a.mapPoint;var c=new h;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.m})},A:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);
this.I()},I:function(){var a;new h;a=this.v(d.clone(this._points),d.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.X,d;b&&(b.isWebMercator()?d=u.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=r.fromJson(a.toJson())));this.J(a,d,c)}},J:function(a,c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=
null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.C.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null}})});
