define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(z,d,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,q,B,E,C,X,Y,Z,aa,m,ba,F,ca,r,da,ea,G,f,e,H){return z([F],{declaredClass:"MilitarySymbology.Symbols.Block",SID:"340100",symName:"Block",symGeometricType:"Area",constructor:function(a,c){this.map=a;this.U=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.D=this.F;this.G=this.H;this.C=this.A;this.u;this.N;this.K;this._tGraphic=new q},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var b;
new e;b=new G(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.v(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.v(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(b));
this.o(this._tGraphic.geometry,b);this._clear()}else this.K=b.on("onBaseLineClick",d.hitch(this,this.O)),this.N=b.on("onBaseLineProgress",d.hitch(this,this.S)),this.u=b.on("drawEnd",d.hitch(this,this.P)),b.init()},v:function(a,c){var b=new e;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;return b},P:function(a){this.u.remove();this._tGraphic=new q(a.geometry,this.m);
this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=m(this.map,"mouse-move",d.hitch(this,this.H));this.C=m(this.map,"click",d.hitch(this,this.A));this.D=m(this.map,"dbl-click",d.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new C(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,currentMarker:a.currentMarker,
isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,d=a.BASE_LN_PTS.endPt,I=c[0],e=c[c.length-1];a=[];if(void 0===b||void 0===d)throw"First Parameter of the Function is an Array with Start and End Point";var g=f.getMidPoint(b,d),n=new C(this.map.spatialReference);1<=c.length&&(e=I);var t=f._2PtLen(g,d),l=Math.atan((g.y-
e.y)/(g.x-e.x));switch(f.twoPtsRelationShip(g,e)){case "ne":l+=Math.PI/2;break;case "nw":l+=3*Math.PI/2;break;case "sw":l+=3*Math.PI/2;break;case "se":l+=Math.PI/2}var m={x:t*Math.cos(l)+g.x,y:t*Math.sin(l)+g.y},A={x:-1*t*Math.cos(l)+g.x,y:-1*t*Math.sin(l)+g.y};paths=[];paths=paths.concat(m,A);n.addPath(paths);1<=c.length&&a.push(g);for(h=0;h<c.length;h++){var u=f._2PtLen(g,c[h]),v=f.angleInRadians(g,c[h]),q=new r(m.x+u*Math.cos(v),m.y+u*Math.sin(v),this.map.spatialReference),z=new r(A.x+u*Math.cos(v),
A.y+u*Math.sin(v),this.map.spatialReference),D=f._2PtLen(q,z);a.push(c[h])}var p;p=f._fracture(a,10,this.map.spatialReference);n.paths=n.paths.concat(p.geometry.paths);for(var w,h=0;h<p.midPoints.length;h++)w=p.midPoints[h].len/2,w>D/3.6&&(w=D/3.6),n.addPath(H.createB(p.midPoints[h].midPt,w,40));return n}catch(B){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},X:function(){return this.j},H:function(a){a=a.mapPoint;var c=new e;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=
this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.m})},A:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new e;a=this.v(d.clone(this._points),d.clone(this.j));
this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.Y,d;b&&(b.isWebMercator()?d=E.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=B.fromJson(a.toJson())));this.J(a,d,c)}},J:function(a,c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=
[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.C.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(a,c,b){var d=[];b+=15;var e=f.toDegrees(b);b=f.toDegrees(b-30);e=new r(a.x+c*Math.cos(f.toRad(e)),a.y+c*Math.sin(f.toRad(e)),this.map.spatialReference);c=new r(a.x+c*Math.cos(f.toRad(b)),a.y+c*Math.sin(f.toRad(b)),this.map.spatialReference);
return d=d.concat(e,a,c)},W:function(){}})});
