define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(t,f,m,D,u,E,F,G,H,I,J,K,L,M,v,p,q,w,z,A,g,N,O,P,n,Q,B,R,r,S,T,U,V,l,C){return t([B],{declaredClass:"MilitarySymbology.Symbols.BOPFreehand",SID:"160207",symName:"Post / BOP Freehand",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.S=b;this.m;this._points=[];this._geometryType=null;this.j=1;this.C=this.A;this.D=this.F;this.G=this.H;this._tGraphic=new q},init:function(a,b){this.m=b;var c=new u;c.setColor(b.color);c.a=.5;this.m=new p(p.STYLE_SOLID,new v(b.style,b.color,b.width),
c);this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();new l;this.j=a.DRAW_TYPE;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.v(f.clone(a.CTRL_PTS),a.DRAW_TYPE),this.o(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.v(f.clone(a.CTRL_PTS),a.DRAW_TYPE),this._tGraphic.setGeometry(this.createSymbol(c)),this.o(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new q(null,this.m),this.map.graphics.add(this._tGraphic),
this.C=n(this.map,"click",f.hitch(this,this.A)),this.D=n(this.map,"dbl-click",f.hitch(this,this.F)))},v:function(a,b){var c=new l;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.DRAW_TYPE=b;c.ISFHAND=1;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=b[b.length-1],d=b[0],e=new g(this.map.spatialReference);switch(a.DRAW_TYPE){case 1:e=
this.K(b,d,c,a,e);break;case 2:e=this.O(b,d,c,a,e);break;case 3:e=this.P(b,d,c,a,e);break;case 4:e=this.N(b,d,c,a,e)}return e}catch(h){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},H:function(a){a=a.mapPoint;var b=new l;b.CTRL_PTS=this._points.concat(a);b.DRAW_TYPE=this.j;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},A:function(a){this._points.push(a.mapPoint.offset(0,
0));1==this._points.length&&(this.G=n(this.map,"mouse-move",f.hitch(this,this.H)));this.emit("onDrawClick",{currentPts:this._points});1==this.S&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.u());3!==this.j&&4!==this.j||2!==this._points.length||(this.emit("onDrawClick",{currentPts:this._points}),this.u())},F:function(a){this._points.push(a.mapPoint);this.u()},u:function(){var a;new l;a=this.v(f.clone(this._points),this.j);this.o(this._tGraphic.geometry,a);this._clear();
this._removeEvents()},o:function(a,b){if(a){var c=this.map.V,d;c&&(c.isWebMercator()?d=z.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=w.fromJson(a.toJson())));this.J(a,d,b)}},J:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.C.remove();
this.D.remove();this.G.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},U:function(){},I:function(a,b,c){var d={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var e=TweenMax.to(d,b,{bezier:a,ease:Linear.easeNone});a=[];var h;for(h=0;h<=b;h++)e.time(h),a.push({x:d.x,y:d.y});b=new g(c.spatialReference);
b.addRing(a);return b},K:function(a,b){var c=new g(this.map.spatialReference),d=[];m.forEach(a,function(a){d.push({x:a.x,y:a.y})});d.push({x:b.x,y:b.y});return c=this.I(d,130,this.map)},O:function(a,b){var c=new g(this.map.spatialReference),d=[];m.forEach(a,function(a){d.push({x:a.x,y:a.y})});d.push({x:b.x,y:b.y});c.addRing(d);return c},P:function(a,b,c){var d=new g(this.map.spatialReference),e=[];m.forEach(a,function(a){e.push({x:a.x,y:a.y})});d.addRing(e);a=d.getExtent();d=new g(this.map.spatialReference);
e=[];e.push(b);e.push(new r(a.xmin,a.ymin,this.map.spatialReference));e.push(c);e.push(new r(a.xmax,a.ymax,this.map.spatialReference));e.push(b);d.addRing(e);return d},N:function(a,b,c){a=new A(this.map.spatialReference);b=this.map.toScreen(b);c=this.map.toScreen(c);c=C.createEllipse({center:b,longAxis:c.x-b.x,shortAxis:c.y-b.y,numberOfPoints:60,map:this.map});a.addPath(c);return a}})});
