define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(F,e,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,A,G,H,E,Z,aa,ba,ca,n,da,I,ea,r,fa,ga,J,d,f,K){return F([I],{declaredClass:"MilitarySymbology.Symbols.Breach",SID:"340200",symName:"Breach",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.V=b;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.F=this.G;this.H=this.I;this.A=this.v;this.u;this.O;this.N;this._tGraphic=new A},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var c;new f;c=new J(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),c=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,c),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))c=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline Pts are required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(c));
this.o(this._tGraphic.geometry,c);this._clear()}else this.u=c.on("drawEnd",e.hitch(this,this.S)),this.N=c.on("onBaseLineClick",e.hitch(this,this.P)),this.O=c.on("onBaseLineProgress",e.hitch(this,this.U)),c.init("B")},C:function(a,b){var c=new f;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.BASE_LN_PTS=b;c.AMPLIFIER=this.amplifier;return c},S:function(a){this.u.remove();this._tGraphic=new A(a.geometry,this.m);
this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.H=n(this.map,"mouse-move",e.hitch(this,this.I));this.A=n(this.map,"click",e.hitch(this,this.v));this.F=n(this.map,"dbl-click",e.hitch(this,this.G));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},U:function(a){var b=[];b.CTRL_PTS=a.currentGeometry;var c=new E(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:b,currentMarker:a.currentMarker,
isBaseLine:!0})},P:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=a.BASE_LN_PTS.startPt,B=a.BASE_LN_PTS.endPt,e=b[0],f=b[b.length-1];a=[];var h=[];if(void 0===c||void 0===B)throw"First Parameter of the Function is an Array with Start and End Point";var g=d.getMidPoint(c,B),l=new E(this.map.spatialReference);1<=b.length&&(f=e);var t=d._2PtLen(g,
B),m=Math.atan((g.y-f.y)/(g.x-f.x));switch(d.twoPtsRelationShip(g,f)){case "ne":m+=Math.PI/2;break;case "nw":m+=3*Math.PI/2;break;case "sw":m+=3*Math.PI/2;break;case "se":m+=Math.PI/2}var p={x:t*Math.cos(m)+g.x,y:t*Math.sin(m)+g.y},q={x:-1*t*Math.cos(m)+g.x,y:-1*t*Math.sin(m)+g.y};paths=[];paths=paths.concat(p,q);var u;u=d._fracturePts(p,q,10,this.map.spatialReference);l.paths=l.paths.concat(u.geometry.paths);var v,n=d._2PtLen(p,q);v=u.len/2;v>n/3.6&&(v=n/3.6);l.addPath(K.createB(u.midPoint,v,40));
1<=b.length&&(a.push(p),h.push(q));for(i=0;i<b.length;i++){var w=d._2PtLen(g,b[i]),z=d.angleInRadians(g,b[i]),C=new r(p.x+w*Math.cos(z),p.y+w*Math.sin(z),this.map.spatialReference),D=new r(q.x+w*Math.cos(z),q.y+w*Math.sin(z),this.map.spatialReference);a.push(C);h.push(D)}l.addPath(a);l.addPath(h);l.addPath(this.D(a[a.length-1],d.ArrowFlanksLen(d._2PtLen(g,b[b.length-1]),d._2PtLen(C,D)),d.angleInRadians(a[a.length-2],a[a.length-1]),0));l.addPath(this.D(h[h.length-1],d.ArrowFlanksLen(d._2PtLen(g,b[b.length-
1]),d._2PtLen(C,D)),d.angleInRadians(h[h.length-2],h[h.length-1]),1));return l}catch(A){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},X:function(){return this.j},I:function(a){a=a.mapPoint;var b=new f;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,
0));this.emit("onDrawClick",{currentPts:this._points});1==this.V&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.J())},G:function(a){this._points.push(a.mapPoint);this.J()},J:function(){var a;new f;a=this.C(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var c=this.map.Y,d;c&&(c.isWebMercator()?d=H.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=G.fromJson(a.toJson())));this.K(a,d,
b)}},K:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.F.remove();this.H.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();
this._geometryType=null},D:function(a,b,c,e){var f=[];e=1==e?d.toDegrees(c-15):d.toDegrees(c+15);c=new r(a.x+b*Math.cos(d.toRad(e)),a.y+b*Math.sin(d.toRad(e)),this.map.spatialReference);b=new r(-1*b*Math.cos(d.toRad(e))+a.x,-1*b*Math.sin(d.toRad(e))+a.y,this.map.spatialReference);return f=f.concat(c,a,b)},W:function(){}})});
