define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(B,d,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,v,E,F,C,W,X,Y,Z,r,aa,G,ba,D,ca,da,H,g,l){return B([G],{declaredClass:"MilitarySymbology.Symbols.Bridge",SID:"271100",symName:"Bridge - Gap",symGeometricType:"Line",constructor:function(a,b){this.map=a;this.X=b;this.u;this._points=[];this.o=[];this._geometryType=null;this.F=this.D;this.H=this.I;this.J=this.K;this.F=this.D;this.C;this.S;this.P;this._tGraphic=new v;this.j=.17;this.m=45},init:function(a,b){this.u=b;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();this.j=g.setDefault(a,"TAIL_FACTOR",this.j);this.m=g.setDefault(a,"FLAP_ANGLE",this.m);var c;new l;c=new H(this.map,this.u);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),c=this.G(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS),this.j,this.m),this.A(this._tGraphic.geometry,c),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))c=this.G(d.clone(a.CTRL_PTS),
d.clone(a.BASE_LN_PTS),this.j,this.m);else throw"Control Points and Baseline Pts are required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(c));this.A(this._tGraphic.geometry,c);this._clear()}else this.C=c.on("drawEnd",d.hitch(this,this.V)),this.P=c.on("onBaseLineClick",d.hitch(this,this.U)),this.S=c.on("onBaseLineProgress",d.hitch(this,this.W)),c.init()},G:function(a,b,c,d){var e=new l;e.SCOPE=this;e.SYM_GEO_TYPE=this.symGeometricType;e.SID=this.SID;e.SYM_GEO_TYPE=
this.symGeometricType;e.SYM_NAME=this.symName;e.CTRL_PTS=a;e.BASE_LN_PTS=b;e.AMPLIFIER=this.amplifier;e.TAIL_FACTOR=c;e.FLAP_ANGLE=d;return e},V:function(a){this.C.remove();this._tGraphic=new v(a.geometry,this.u);this.map.graphics.add(this._tGraphic);this.o=a.geometry._baseLine;this.J=r(this.map,"mouse-move",d.hitch(this,this.K));this.F=r(this.map,"click",d.hitch(this,this.D));this.H=r(this.map,"dbl-click",d.hitch(this,this.I));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},
W:function(a){var b=[];b.CTRL_PTS=a.currentGeometry;var c=new C(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:b,currentMarker:a.currentMarker,isBaseLine:!0})},U:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=a.BASE_LN_PTS.startPt,d=a.BASE_LN_PTS.endPt,e=b[0],f=b[b.length-
1];a=[];var l=[];if(void 0===c||void 0===d)throw"First Parameter of the Function is an Array with Start and End Point";var h=g.getMidPoint(c,d),q=new C(this.map.spatialReference);1<=b.length&&(f=e);var A=g._2PtLen(h,d),m=Math.atan((h.y-f.y)/(h.x-f.x));switch(g.twoPtsRelationShip(h,f)){case "ne":m+=Math.PI/2;break;case "nw":m+=3*Math.PI/2;break;case "sw":m+=3*Math.PI/2;break;case "se":m+=Math.PI/2}var t={x:A*Math.cos(m)+h.x,y:A*Math.sin(m)+h.y},u={x:-1*A*Math.cos(m)+h.x,y:-1*A*Math.sin(m)+h.y};1<=
b.length&&(a.push(t),l.push(u));for(i=0;i<b.length;i++){var n=g._2PtLen(h,b[i]),p=g.angleInRadians(h,b[i]),r=new D(t.x+n*Math.cos(p),t.y+n*Math.sin(p),this.map.spatialReference),v=new D(u.x+n*Math.cos(p),u.y+n*Math.sin(p),this.map.spatialReference),w={x:-1*n/9*Math.cos(p)+r.x,y:-1*n/9*Math.sin(p)+r.y};a.push(w);var z={x:-1*n/9*Math.cos(p)+v.x,y:-1*n/9*Math.sin(p)+v.y};l.push(z);a.push(w);l.push(z)}q.addPath(a);q.addPath(l);paths=[];paths=paths.concat(this.v(t,w,this.j,this.m,0),t);q.addPath(paths);
paths=[];paths=paths.concat(this.v(u,z,this.j,this.m,1),u);q.addPath(paths);paths=[];paths=paths.concat(this.v(w,t,this.j,this.m,1),w);q.addPath(paths);paths=[];paths=paths.concat(this.v(z,u,this.j,this.m,0),z);q.addPath(paths);return q}catch(B){console.log(this.declaredClass+" can not create Symbol due to invalid geometry")}},Z:function(){return this.o},K:function(a){a=a.mapPoint;var b=new l;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.o;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",
{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.u})},D:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.X&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.N())},I:function(a){this._points.push(a.mapPoint);this.N()},N:function(){var a;new l;a=this.G(d.clone(this._points),d.clone(this.o),this.j,this.m);this.A(this._tGraphic.geometry,a);this._clear();this._removeEvents()},
A:function(a,b){if(a){var c=this.map.$,d;c&&(c.isWebMercator()?d=F.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=E.fromJson(a.toJson())));this.O(a,d,b)}},O:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.u})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.o=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.F.remove();
this.H.remove();this.J.remove();this.C.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},Y:function(){},v:function(a,b,c,d,e){c=g._2PtLen(a,b);var f=Math.atan((a.y-b.y)/(a.x-b.x));switch(g.twoPtsRelationShip(a,b)){case "ne":f+=Math.PI/2;break;case "nw":f+=3*Math.PI/2;break;case "sw":f+=3*Math.PI/2;break;case "se":f+=Math.PI/2}0===e?(f+=g.toRad(d),a={x:this.j*c*Math.cos(f)+a.x,y:this.j*c*Math.sin(f)+a.y}):(f-=g.toRad(d),a={x:-1*
this.j*c*Math.cos(f)+a.x,y:-1*this.j*c*Math.sin(f)+a.y});return a}})});
