define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(D,e,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,aa,B,G,I,H,ba,ca,da,ea,v,fa,J,ga,w,ha,ia,K,d,f,L){return D([J],{declaredClass:"MilitarySymbology.Symbols.Clear",SID:"340500",symName:"Clear",symGeometricType:"Area",constructor:function(a,c){this.map=a;this.V=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.C=this.A;this.F=this.G;this.H=this.I;this.C=this.A;this.v;this.O;this.N;this._tGraphic=new B},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var b;new f;b=new K(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.D(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.D(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(b));
this.o(this._tGraphic.geometry,b);this._clear()}else this.v=b.on("drawEnd",e.hitch(this,this.S)),this.N=b.on("onBaseLineClick",e.hitch(this,this.P)),this.O=b.on("onBaseLineProgress",e.hitch(this,this.U)),b.init()},D:function(a,c){var b=new f;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;return b},S:function(a){this.v.remove();this._tGraphic=new B(a.geometry,this.m);
this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.H=v(this.map,"mouse-move",e.hitch(this,this.I));this.C=v(this.map,"click",e.hitch(this,this.A));this.F=v(this.map,"dbl-click",e.hitch(this,this.G));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},U:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new H(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,currentMarker:a.currentMarker,
isBaseLine:!0})},P:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,e=a.BASE_LN_PTS.endPt,M=c[0],f=c[c.length-1];a=[];var n=[],p=[];if(void 0===b||void 0===e)throw"First Parameter of the Function is an Array with Start and End Point";var g=d.getMidPoint(b,e),m=new H(this.map.spatialReference);1<=c.length&&(f=M);var r=d._2PtLen(g,
e),h=Math.atan((g.y-f.y)/(g.x-f.x));switch(d.twoPtsRelationShip(g,f)){case "ne":h+=Math.PI/2;break;case "nw":h+=3*Math.PI/2;break;case "sw":h+=3*Math.PI/2;break;case "se":h+=Math.PI/2}var b=r,v={x:b*Math.cos(h)+g.x,y:b*Math.sin(h)+g.y},E={x:-1*b*Math.cos(h)+g.x,y:-1*b*Math.sin(h)+g.y};1<=c.length&&(a.push(v),n.push(E),p.push(g));for(l=0;l<c.length;l++){var A=d._2PtLen(g,c[l]),q=d.angleInRadians(g,c[l]),t=new w(v.x+A*Math.cos(q),v.y+A*Math.sin(q),this.map.spatialReference),u=new w(E.x+A*Math.cos(q),
E.y+A*Math.sin(q),this.map.spatialReference),r=A/5,F=d._2PtLen(t,u),h=F/4;r>h&&(r=h);var q=d.angleInRadians(t,u),B=new w(-1*r*Math.cos(q)+t.x,-1*r*Math.sin(q)+t.y,this.map.spatialReference),D=new w(r*Math.cos(q)+u.x,r*Math.sin(q)+u.y,this.map.spatialReference);a.push(t);n.push(u);p.push(c[l])}m.addPath(a);m.addPath(n);var z;z=d._fracture(p,10,this.map.spatialReference);m.paths=m.paths.concat(z.geometry.paths);for(var C,l=0;l<z.midPoints.length;l++)C=z.midPoints[l].len/2,C>F/3.6&&(C=F/3.6),m.addPath(L.createCC(z.midPoints[l].midPt.x,
z.midPoints[l].midPt.y,C,this.map.spatialReference));m.addPath(this.u(a[a.length-1],d.ArrowFlanksLen(d._2PtLen(g,c[c.length-1]),d._2PtLen(t,u)),d.angleInRadians(a[a.length-2],a[a.length-1])));m.addPath(this.u(n[n.length-1],d.ArrowFlanksLen(d._2PtLen(g,c[c.length-1]),d._2PtLen(t,u)),d.angleInRadians(n[n.length-2],n[n.length-1])));m.addPath(this.u(p[p.length-1],d.ArrowFlanksLen(d._2PtLen(g,c[c.length-1]),d._2PtLen(t,u)),d.angleInRadians(p[p.length-2],p[p.length-1])));m.addPath([B,D]);return m}catch(G){console.log(this.declaredClass+
" Can not create Symbol due to invalid geometry")}},X:function(){return this.j},I:function(a){a=a.mapPoint;var c=new f;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.m})},A:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.V&&1==this._points.length&&(this.emit("onDrawClick",
{currentPts:this._points}),this.J())},G:function(a){this._points.push(a.mapPoint);this.J()},J:function(){var a;new f;a=this.D(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.Y,d;b&&(b.isWebMercator()?d=I.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=G.fromJson(a.toJson())));this.K(a,d,c)}},K:function(a,c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&
this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.C.remove();this.F.remove();this.H.remove();this.v.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},u:function(a,c,b){var e=[];b+=15;var f=d.toDegrees(b);b=d.toDegrees(b-30);f=new w(a.x+c*Math.cos(d.toRad(f)),
a.y+c*Math.sin(d.toRad(f)),this.map.spatialReference);c=new w(a.x+c*Math.cos(d.toRad(b)),a.y+c*Math.sin(d.toRad(b)),this.map.spatialReference);return e=e.concat(f,a,c)},W:function(){}})});
