define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(F,n,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,B,H,I,G,Z,aa,ba,ca,v,da,J,ea,w,fa,ga,K,g,t,C){return F([J],{declaredClass:"MilitarySymbology.Symbols.Contain",SID:"151204",symName:"Contain",symGeometricType:"Area",constructor:function(b){this.map=b;this.o;this._points=[];this._geometryType=null;this.N;this.m=2;this.j=5;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new B},init:function(b,d){this.o=d;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();this.m=2;this.j=
5;var c;new t;new K(this.map,this.o);this.m=g.setDefault(b,"TEETH_SIZE",this.m);this.j=g.setDefault(b,"TEETH_GAP",this.j);b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),c=this.A(n.clone(b.CTRL_PTS),b.TEETH_SIZE,b.TEETH_GAP),this.v(this._tGraphic.geometry,c),this._clear()):b.hasOwnProperty("CTRL_PTS")?(c=this.A(n.clone(b.CTRL_PTS),b.TEETH_SIZE,b.TEETH_GAP),this._tGraphic.setGeometry(this.createSymbol(c)),this.v(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=
new B(null,this.o),this.map.graphics.add(this._tGraphic),this.D=v(this.map,"click",n.hitch(this,this.C)),this.F=v(this.map,"dbl-click",n.hitch(this,this.G)))},P:function(b,d,c){var a=Math.sqrt(Math.pow(c.x-b.x,2)+Math.pow(c.y-b.y,2));c=Math.sqrt(Math.pow(c.x-d.x,2)+Math.pow(c.y-d.y,2));b=Math.sqrt(Math.pow(d.x-b.x,2)+Math.pow(d.y-b.y,2));return Math.acos((c*c+a*a-b*b)/(2*c*a))},A:function(b,d,c){var a=new t;a.SCOPE=this;a.SYM_GEO_TYPE=this.symGeometricType;a.SID=this.SID;a.SYM_GEO_TYPE=this.symGeometricType;
a.SYM_NAME=this.symName;a.CTRL_PTS=b;a.AMPLIFIER=this.amplifier;a.TEETH_SIZE=d;a.TEETH_GAP=c;return a},createSymbol:function(b){try{var d;if(b.hasOwnProperty("CTRL_PTS"))d=b.CTRL_PTS;else throw"controlPoints not found";var c=new G(this.map.spatialReference),a=d[0],e=d[1];if(2===d.length)c.addPath([a,e]);else if(3===d.length){var h=d[2],m,f=[],z=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(h));0<z.radius&&(m=this.CreateCircleSegmentFromThreePoints(z,this.map.toScreen(a),
this.map.toScreen(e),this.map.toScreen(h),60,this.map),f=m.geometry.paths[0],c.addPath(f.slice(0,28)),c.addPath(f.slice(32,60)));var n=new w(f[30][0],f[30][1],this.map.spatialReference),p,t=new w(f[28][0],f[28][1],this.map.spatialReference),v=new w(f[32][0],f[32][1],this.map.spatialReference),r=g._2PtLen(t,v);p=r/5;p>r/3.6&&(p=r/3.6);c.addPath(C.createCC(n.x,n.y,p,this.map.spatialReference));for(var q=c.getExtent().getCenter(),D=g._2PtLen(e,q)/10,A=D*g.setDefault(b,"TEETH_SIZE",this.m),u=g.setDefault(b,
"TEETH_GAP",this.j),l=u;28>l;l+=u)c.addPath(this.u(c.getPoint(0,l),g.angleInRadians(q,c.getPoint(0,l)),A));for(l=u;28>l;l+=u)c.addPath(this.u(c.getPoint(1,l),g.angleInRadians(q,c.getPoint(1,l)),A))}else if(3<d.length){var h=d[2],f=[],E=d[d.length-1],B=d[d.length-2],z=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(h));0<z.radius&&(m=this.CreateCircleSegmentFromThreePoints(z,this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(h),60,this.map),f=m.geometry.paths[0],
c.addPath(f.slice(0,28)),c.addPath(f.slice(32,60)));n=new w(f[30][0],f[30][1],this.map.spatialReference);t=new w(f[28][0],f[28][1],this.map.spatialReference);v=new w(f[32][0],f[32][1],this.map.spatialReference);r=g._2PtLen(t,v);p=r/5;p>r/3.6&&(p=r/3.6);c.addPath(C.createCC(n.x,n.y,p,this.map.spatialReference));q=c.getExtent().getCenter();D=g._2PtLen(e,q)/10;A=D*g.setDefault(b,"TEETH_SIZE",this.m);for(l=u=g.setDefault(b,"TEETH_GAP",this.j);28>l;l+=u)c.addPath(this.u(c.getPoint(0,l),g.angleInRadians(q,
c.getPoint(0,l)),A));for(l=u;28>l;l+=u)c.addPath(this.u(c.getPoint(1,l),g.angleInRadians(q,c.getPoint(1,l)),A));f=[];f.push(q);for(l=3;l<d.length-1;l++)f.push(d[l]);f=f.concat(E);m=g._fracture(f,10,this.map.spatialReference);c.paths=c.paths.concat(m.geometry.paths);r=g._2PtLen(a,E);for(l=0;l<m.midPoints.length;l++)for(p=m.midPoints[l].len/2,p>r/3.6&&(p=r/3.6),f=C.createENY(m.midPoints[l].midPt.x,m.midPoints[l].midPt.y,p,this.map.spatialReference),b=0;b<f.length;b++)c.addPath(f[b]);c.addPath(C.arrowHeadBackward(q,
g.ArrowFlanksLen(g._2PtLen(q,d[3]),g._2PtLen(E,B)),g.angleInRadians(q,d[3])))}return c}catch(F){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},I:function(b){b=b.mapPoint;var d=new t;d.CTRL_PTS=this._points.concat(b);d.TEETH_GAP=this.j;d.TEETH_SIZE=this.m;this._tGraphic.setGeometry(this.createSymbol(d));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:d,currentMarker:this.o})},C:function(b){this._points.push(b.mapPoint.offset(0,
0));this.emit("onDrawClick",{currentPts:this._points});1==this._points.length&&(this.H=v(this.map,"mouse-move",n.hitch(this,this.I)))},G:function(b){this._points.push(b.mapPoint);this.K()},K:function(){var b;new t;b=this.A(n.clone(this._points),this.m,this.j);this.v(this._tGraphic.geometry,b);this._clear();this._removeEvents()},v:function(b,d){if(b){var c=this.map.S,a;c&&(c.isWebMercator()?a=I.webMercatorToGeographic(b,!0):4326===c.wkid&&(a=H.fromJson(b.toJson())));this.J(b,a,d)}},J:function(b,d,
c){this.emit("onDrawEnd",{geometry:b,geographicGeometry:d,drawEssentials:c,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},O:function(){},_circleDrawEx:function(b,
d,c){var a,e;e=[[0,0,0],[0,0,0],[0,0,0]];var h=[[b.x,b.y],[d.x,d.y],[c.x,c.y]];for(a=0;3>a;a++)e[a][0]=h[a][0],e[a][1]=h[a][1],e[a][2]=1;b=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=h[a][0]*h[a][0]+h[a][1]*h[a][1],e[a][1]=h[a][1],e[a][2]=1;d=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=h[a][0]*h[a][0]+h[a][1]*h[a][1],e[a][1]=h[a][0],e[a][2]=1;c=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=h[a][0]*h[a][0]+h[a][1]*h[a][1],e[a][1]=h[a][0],e[a][2]=h[a][1];e=this._determinantDrawEx(e,
3);if(0==b)e=0;else{var m=.5*d/b,f=-.5*c/b;e=Math.sqrt(m*m+f*f+e/b)}return{radius:e,center:{x:m,y:f}}},_determinantDrawEx:function(b,d){var c,a,e,h,m,f=[[0,0,0],[0,0,0],[0,0,0]];if(2==d)m=b[0][0]*b[1][1]-b[1][0]*b[0][1];else for(e=m=0;e<d;e++){for(c=1;c<d;c++)for(a=h=0;a<d;a++)a!=e&&(f[c-1][h]=b[c][a],h++);m+=Math.pow(-1,e)*b[0][e]*this._determinantDrawEx(f,d-1)}return m},CreateCircleSegmentFromThreePoints:function(b,d,c,a,e,h){var m=b.center,f=b.radius;b=[];d.x-=m.x;d.y-=m.y;c.x-=m.x;c.y-=m.y;a.x-=
m.x;a.y-=m.y;d=Math.atan2(d.y,d.x);var g=Math.atan2(c.y,c.x);c=Math.atan2(a.y,a.x);d=0>d?2*Math.PI+d:d;g=0>g?2*Math.PI+g:g;c=0>c?2*Math.PI+c:c;a=Math.min(d,g);d=Math.max(d,g);g=d-a;if(c<a||c>d)g-=2*Math.PI;d=g/e;for(g=0;g<=e;g++)c=h.toMap({x:f*Math.cos(a+g*d)+m.x,y:f*Math.sin(a+g*d)+m.y}),b.push(c);h=new G(h.spatialReference);h.addPath(b);return{geometry:h,lastPoint:b[e],backPoint:b[e-5]}},u:function(b,d,c){d=new w(-1*c*Math.cos(d)+b.x,-1*c*Math.sin(d)+b.y,this.map.spatialReference);return[b,d]}})});
