define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(r,f,B,C,D,E,F,G,H,I,J,K,L,M,N,O,n,t,u,v,P,Q,R,S,m,T,w,U,V,W,X,z,e,l,A){return r([w],{declaredClass:"MilitarySymbology.Symbols.Corridors",SID:"110101",symName:"Mob Corridors",symGeometricType:"Line",constructor:function(a,b){this.map=a;this.N=b;this.m;this._points=[];this._geometryType=null;this.v=0;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new n;this.j=.17},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();this.j=
e.setDefault(a,"TAIL_FACTOR",this.j);var d;new l;new z(this.map,this.m);this.v=a.ECHELON;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.A(f.clone(a.CTRL_PTS),a.ECHELON,this.j),this.o(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.A(f.clone(a.CTRL_PTS),a.ECHELON,this.j),this._tGraphic.setGeometry(this.createSymbol(d)),this.o(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new n(null,this.m),this.map.graphics.add(this._tGraphic),
this.D=m(this.map,"click",f.hitch(this,this.C)),this.F=m(this.map,"dbl-click",f.hitch(this,this.G)))},A:function(a,b,d){var c=new l;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.ECHELON=b;c.TAIL_FACTOR=d;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";new v(this.map.spatialReference);for(var d=b[b.length-
1],c=b[0],h=e._fracture(b,20,this.map.spatialReference),g=0;g<h.midPoints.length;g++){var f=e.angleInRadians(b[g],h.midPoints[g].midPt);e._2PtLen(b[g],h.midPoints[g].midPt);f+=15;e.toDegrees(f);f-=30;e.toDegrees(f);var l,m=e._2PtLen(b[g],h.midPoints[g].midPt)/6;l=m/6;l>m/4&&(l=m/4);for(var n=A.createEchelon(a.ECHELON,h.midPoints[g].midPt,l,e.angleInRadians(b[g],h.midPoints[g].midPt)),q=0;q<=n.length-1;q++)h.geometry.addPath(n[q])}var p=this.u(c,b[1],this.j);p[1]=c;h.geometry.addPath(p);p=2>=b.length?
this.u(d,c,this.j):this.u(d,b[b.length-2],this.j);p[1]=d;h.geometry.addPath(p);return h.geometry}catch(r){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},I:function(a){a=a.mapPoint;var b=new l;b.CTRL_PTS=this._points.concat(a);b.ECHELON=this.v;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==
this._points.length&&(this.H=m(this.map,"mouse-move",f.hitch(this,this.I)));this.emit("onDrawClick",{currentPts:this._points});1==this.N&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.J())},G:function(a){this._points.push(a.mapPoint);this.J()},J:function(){var a;new l;a=this.A(f.clone(this._points),this.v,this.j);this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var d=this.map.P,c;d&&(d.isWebMercator()?c=u.webMercatorToGeographic(a,
!0):4326===d.wkid&&(c=t.fromJson(a.toJson())));this.K(a,c,b)}},K:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();
this._geometryType=null},O:function(){},u:function(a,b,d){d=e._2PtLen(a,b);var c=Math.atan((a.y-b.y)/(a.x-b.x));switch(e.twoPtsRelationShip(a,b)){case "ne":c+=Math.PI/2;break;case "nw":c+=3*Math.PI/2;break;case "sw":c+=3*Math.PI/2;break;case "se":c+=Math.PI/2}c+=e.toRad(45);b={x:this.j*d*Math.cos(c)+a.x,y:this.j*d*Math.sin(c)+a.y};c-=e.toRad(90);return[b,null,{x:-1*this.j*d*Math.cos(c)+a.x,y:-1*this.j*d*Math.sin(c)+a.y}]}})});
