define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(E,h,F,L,M,N,O,P,Q,R,S,T,U,V,G,W,A,H,I,X,C,Y,Z,aa,w,ba,J,ca,da,ea,fa,K,l,r,B){return E([J],{declaredClass:"MilitarySymbology.Symbols.CounterAttack",SID:"340600",symName:"Counter Attk",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.N=b;this.o;this._points=[];this._geometryType=null;this.O;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new A;this.j=.05;this.m=.07},init:function(a,b){this.o=b;this.o.setStyle(G.STYLE_DASH);this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();this.m=l.setDefault(a,"HEAD_RATIO",.07);this.j=l.setDefault(a,"TAIL_FACTOR",.05);var d;new r;new K(this.map,this.o);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.v(h.clone(a.CTRL_PTS),this.m,this.j),this.u(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.v(h.clone(a.CTRL_PTS),this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(d)),this.u(this._tGraphic.geometry,d),this._clear()):
(this._tGraphic=new A(null,this.o),this.map.graphics.add(this._tGraphic),this.D=w(this.map,"click",h.hitch(this,this.C)),this.F=w(this.map,"dbl-click",h.hitch(this,this.G)))},v:function(a,b,d){var c=new r;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.HEAD_RATIO=b;c.TAIL_FACTOR=d;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";
l.setDefault(a,"HEAD_RATIO",5);if(2>=b.length){var d=b[0],c=b[b.length-1],f=l._2PtLen(d,c),e=Math.atan((d.y-c.y)/(d.x-c.x));switch(l.twoPtsRelationShip(d,c)){case "ne":e+=Math.PI/2;break;case "nw":e+=3*Math.PI/2;break;case "sw":e+=3*Math.PI/2;break;case "se":e+=Math.PI/2}var n={x:this.j*f*Math.cos(e)+d.x,y:this.j*f*Math.sin(e)+d.y},D={x:-1*this.j*f*Math.cos(e)+d.x,y:-1*this.j*f*Math.sin(e)+d.y},p=(1-this.m)*f,h={x:this.j*p*Math.cos(e)+d.x,y:this.j*p*Math.sin(e)+d.y},r={x:-1*this.j*p*Math.cos(e)+d.x,
y:-1*this.j*p*Math.sin(e)+d.y},v=new C(this.map.spatialReference),m=[];m.push(n);var q=this.CreateArrowHeadPathEx(h,c,r,f,this.m,15),m=m.concat(q.rings);m.push(r);var z=l.getMidPoint(d,c),t,u=l._2PtLen(h,r);t=u/2;t>u/3.6&&(t=u/3.6);for(var q=B.CATK(z.x,z.y,t),g=0;g<q.length;g++)v.addRing(q[g]);C.prototype.isClockwise(m)||this.W||(console.debug(this.declaredClass+" :  Polygons drawn in anti-clockwise direction will be reversed to be clockwise."),m.reverse());v.addRing(m)}else{a=[];e=[];v=new C(this.map.spatialReference);
c=b[b.length-1];d=b[0];tempArray=[];a=[];e=[];F.forEach(b,function(a){tempArray.push({x:a.x,y:a.y})});angleArray=l._vertexAngle(tempArray);for(var w=l._ptCollectionLen(tempArray,0),g=0,f=tempArray.length-1;g<f;g++)p=l._ptCollectionLen(tempArray,g),p+=w/2.4,n={x:this.j*p*Math.cos(angleArray[g])+tempArray[g].x,y:this.j*p*Math.sin(angleArray[g])+tempArray[g].y},D={x:-1*this.j*p*Math.cos(angleArray[g])+tempArray[g].x,y:-1*this.j*p*Math.sin(angleArray[g])+tempArray[g].y},a.push(n),e.push(D);a.push({x:c.x,
y:c.y});e.push({x:c.x,y:c.y});a=B.CreateBezierPathPCOnly(a,70);a.splice(Math.floor(70*(1-this.m)),Number.MAX_VALUE);e=B.CreateBezierPathPCOnly(e,70);e.splice(Math.floor(70*(1-this.m)),Number.MAX_VALUE);var q=this.CreateArrowHeadPathEx(a[a.length-1],c,e[e.length-1],l._ptCollectionLen(tempArray,0),this.m,15),A=q.rings,m=[],m=m.concat(a),m=m.concat(A),m=m.concat(e.reverse());v.addRing(m);z=l.getMidPoint(b[b.length-2],c);u=l._2PtLen(a[Math.round(a.length/b.length)],e[Math.round(e.length/b.length)])/b.length;
t=u/2;t>u/3.6&&(t=u/3.6);q=B.CATK(z.x,z.y,t);for(g=0;g<q.length;g++)v.addRing(q[g])}return v}catch(ga){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},V:function(){return this.A},I:function(a){a=a.mapPoint;var b=new r;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.A;b.BK_LN_DIST_RATIO=this.U;b.BK_LN_ANGL_RATIO=this.S;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,
currentMarker:this.o})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.H=w(this.map,"mouse-move",h.hitch(this,this.I)));this.emit("onDrawClick",{currentPts:this._points});1==this.N&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.J())},G:function(a){this._points.push(a.mapPoint);this.J()},J:function(){var a;new r;a=this.v(h.clone(this._points),this.m,this.j);this.u(this._tGraphic.geometry,a);this._clear();this._removeEvents()},
u:function(a,b){if(a){var d=this.map.X,c;d&&(d.isWebMercator()?c=I.webMercatorToGeographic(a,!0):4326===d.wkid&&(c=H.fromJson(a.toJson())));this.K(a,c,b)}},K:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.A=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.D.remove();
this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},P:function(){},CreateArrowHeadPathEx:function(a,b,d,c,f,e,n){f=c*f;c=1.07*f;a=l.twoPtsAngle(b,a);d=l.twoPtsAngle(b,d);var h=Math.abs(a-d)/2;Math.abs(a-d)>1.88*Math.PI&&(h+=Math.PI);var p=Math.asin(f*Math.sin(h+e/180*Math.PI)/Math.sqrt(f*f+c*c-2*c*f*Math.cos(h+e/180*Math.PI)))+e/180*Math.PI;f=0==n||void 0==n?f*Math.sin(Math.PI-p-h)/Math.sin(p):0;n=[];h=
{x:b.x+c*Math.cos(a-e/180*Math.PI),y:b.y+c*Math.sin(a-e/180*Math.PI)};n.push({x:b.x+f*Math.cos(a),y:b.y+f*Math.sin(a)});n.push(h);n.push(b);a={x:b.x+f*Math.cos(d),y:b.y+f*Math.sin(d)};n.push({x:b.x+c*Math.cos(d+e/180*Math.PI),y:b.y+c*Math.sin(d+e/180*Math.PI)});n.push(a);return{rings:n}}})});
