define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(w,m,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,t,z,A,u,R,S,T,U,p,V,B,W,X,Y,Z,C,q,n,v){return w([B],{declaredClass:"MilitarySymbology.Symbols.Delay",SID:"342400",symName:"Delay",symGeometricType:"Area",constructor:function(b){this.map=b;this.j;this._points=[];this._geometryType=null;this.J;this.o=0;this.A=this.v;this.C=this.D;this.F=this.G;this._tGraphic=new t},init:function(b,d){this.j=d;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var c;new n;new C(this.map,this.j);
this.o=b.ECHLON;b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),c=this.u(m.clone(b.CTRL_PTS),b.ECHLON),this.m(this._tGraphic.geometry,c),this._clear()):b.hasOwnProperty("CTRL_PTS")?(c=this.u(m.clone(b.CTRL_PTS),b.ECHLON),this._tGraphic.setGeometry(this.createSymbol(c)),this.m(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new t(null,this.j),this.map.graphics.add(this._tGraphic),this.A=p(this.map,"click",m.hitch(this,this.v)),this.C=p(this.map,
"dbl-click",m.hitch(this,this.D)))},O:function(b,d,c){var a=Math.sqrt(Math.pow(c.x-b.x,2)+Math.pow(c.y-b.y,2));c=Math.sqrt(Math.pow(c.x-d.x,2)+Math.pow(c.y-d.y,2));b=Math.sqrt(Math.pow(d.x-b.x,2)+Math.pow(d.y-b.y,2));return Math.acos((c*c+a*a-b*b)/(2*c*a))},N:function(b,d,c,a,e,f){return Math.atan2(d-f,b-e)-Math.atan2(a-f,c-e)},u:function(b,d){var c=new n;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=b;c.AMPLIFIER=
this.amplifier;c.ECHLON=d;return c},createSymbol:function(b){try{var d;if(b.hasOwnProperty("CTRL_PTS"))d=b.CTRL_PTS;else throw"controlPoints not found";var c=new u(this.map.spatialReference),a=d[0],e=d[1];if(2===d.length)c.addPath([a,e]);else if(3===d.length){var f=d[2],g,h=[],l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f),60,this.map),h=g.geometry.paths[0],
c.addPath(h.slice(0,60)))}else if(3<d.length){var f=d[2],m=d[d.length-1],n=d[d.length-2],h=[],l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f),60,this.map),h=g.geometry.paths[0],c.addPath(h.slice(0,60)));h=[];h.push(c.getPoint(0,0));for(b=3;b<d.length-1;b++)h.push(d[b]);h=h.concat(m);g=q._fracture(h,10,this.map.spatialReference);c.paths=c.paths.concat(g.geometry.paths);
var r,p=q._2PtLen(a,m);for(b=0;b<g.midPoints.length;b++)r=g.midPoints[b].len/2,r>p/3.6&&(r=p/3.6),c.addPath(v.createDD(g.midPoints[b].midPt.x,g.midPoints[b].midPt.y,r,this.map.spatialReference));c.addPath(v.arrowHead(m,q.ArrowFlanksLen(q._2PtLen(n,m),q._2PtLen(a,m)),q.angleInRadians(n,m)))}return c}catch(t){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},G:function(b){b=b.mapPoint;var d=new n;d.CTRL_PTS=this._points.concat(b);d.ECHLON=this.o;this._tGraphic.setGeometry(this.createSymbol(d));
this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:d,currentMarker:this.j})},v:function(b){this._points.push(b.mapPoint.offset(0,0));1==this._points.length&&(this.F=p(this.map,"mouse-move",m.hitch(this,this.G)));this.emit("onDrawClick",{currentPts:this._points})},D:function(b){this._points.push(b.mapPoint);this.I()},I:function(){var b;new n;b=this.u(m.clone(this._points),this.o);this.m(this._tGraphic.geometry,b);this._clear();this._removeEvents()},m:function(b,
d){if(b){var c=this.map.P,a;c&&(c.isWebMercator()?a=A.webMercatorToGeographic(b,!0):4326===c.wkid&&(a=z.fromJson(b.toJson())));this.H(b,a,d)}},H:function(b,d,c){this.emit("onDrawEnd",{geometry:b,geographicGeometry:d,drawEssentials:c,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.A.remove();this.C.remove();this.F.remove();
this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},K:function(){},_circleDrawEx:function(b,d,c){var a,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[b.x,b.y],[d.x,d.y],[c.x,c.y]];for(a=0;3>a;a++)e[a][0]=f[a][0],e[a][1]=f[a][1],e[a][2]=1;b=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][1],e[a][2]=1;d=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=
f[a][0],e[a][2]=1;c=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][0],e[a][2]=f[a][1];e=this._determinantDrawEx(e,3);if(0==b)e=0;else{var g=.5*d/b,h=-.5*c/b;e=Math.sqrt(g*g+h*h+e/b)}return{radius:e,center:{x:g,y:h}}},_determinantDrawEx:function(b,d){var c,a,e,f,g,h=[[0,0,0],[0,0,0],[0,0,0]];if(2==d)g=b[0][0]*b[1][1]-b[1][0]*b[0][1];else for(e=g=0;e<d;e++){for(c=1;c<d;c++)for(a=f=0;a<d;a++)a!=e&&(h[c-1][f]=b[c][a],f++);g+=Math.pow(-1,e)*b[0][e]*this._determinantDrawEx(h,
d-1)}return g},CreateCircleSegmentFromThreePoints:function(b,d,c,a,e,f){var g=b.center,h=b.radius;b=[];d.x-=g.x;d.y-=g.y;c.x-=g.x;c.y-=g.y;a.x-=g.x;a.y-=g.y;d=Math.atan2(d.y,d.x);var l=Math.atan2(c.y,c.x);c=Math.atan2(a.y,a.x);d=0>d?2*Math.PI+d:d;l=0>l?2*Math.PI+l:l;c=0>c?2*Math.PI+c:c;a=Math.min(d,l);d=Math.max(d,l);l=d-a;if(c<a||c>d)l-=2*Math.PI;d=l/e;for(l=0;l<=e;l++)c=f.toMap({x:h*Math.cos(a+l*d)+g.x,y:h*Math.sin(a+l*d)+g.y}),b.push(c);f=new u(f.spatialReference);f.addPath(b);return{geometry:f,
lastPoint:b[e],backPoint:b[e-5]}}})});
