define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(G,e,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,aa,B,I,J,H,ba,ca,da,ea,w,fa,K,ga,z,ha,ia,L,d,h,C){return G([K],{declaredClass:"MilitarySymbology.Symbols.Disrupt",SID:"341000",symName:"Disrupt",symGeometricType:"Area",constructor:function(a,c){this.map=a;this.U=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.D=this.F;this.G=this.H;this.A=this.v;this.u;this.N;this.K;this._tGraphic=new B},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var b;new h;b=new L(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(b));
this.o(this._tGraphic.geometry,b);this._clear()}else this.u=b.on("drawEnd",e.hitch(this,this.P)),this.K=b.on("onBaseLineClick",e.hitch(this,this.O)),this.N=b.on("onBaseLineProgress",e.hitch(this,this.S)),b.init()},C:function(a,c){var b=new h;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;return b},P:function(a){this.u.remove();this._tGraphic=new B(a.geometry,this.m);
this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=w(this.map,"mouse-move",e.hitch(this,this.H));this.A=w(this.map,"click",e.hitch(this,this.v));this.D=w(this.map,"dbl-click",e.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new H(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,currentMarker:a.currentMarker,
isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,e=a.BASE_LN_PTS.endPt,M=c[0],h=c[c.length-1];a=[];var r=[],l=[];if(void 0===b||void 0===e)throw"First Parameter of the Function is an Array with Start and End Point";var f=d.getMidPoint(b,e),n=new H(this.map.spatialReference);1<=c.length&&(h=M);var u=d._2PtLen(f,
e),g=Math.atan((f.y-h.y)/(f.x-h.x));switch(d.twoPtsRelationShip(f,h)){case "ne":g+=Math.PI/2;break;case "nw":g+=3*Math.PI/2;break;case "sw":g+=3*Math.PI/2;break;case "se":g+=Math.PI/2}var b=u,D={x:b*Math.cos(g)+f.x,y:b*Math.sin(g)+f.y},E={x:-1*b*Math.cos(g)+f.x,y:-1*b*Math.sin(g)+f.y};paths=[];paths=paths.concat(D,E);n.addPath(paths);1<=c.length&&(a.push(D),r.push(E),l.push(f));for(m=0;m<c.length;m++){var p=d._2PtLen(f,c[m]),q=d.angleInRadians(f,c[m]),t=new z(D.x+p*Math.cos(q),D.y+p*Math.sin(q),this.map.spatialReference),
v=new z(E.x+p*Math.cos(q),E.y+p*Math.sin(q),this.map.spatialReference),u=p/5,w=d._2PtLen(t,v),b=w/4;u>b&&(u=b);q=d.angleInRadians(t,v);new z(-1*u*Math.cos(q)+t.x,-1*u*Math.sin(q)+t.y,this.map.spatialReference);new z(u*Math.cos(q)+v.x,u*Math.sin(q)+v.y,this.map.spatialReference);g=q=d.angleInRadians(f,c[m]);a.push({x:-1*p/5*Math.cos(g)+t.x,y:-1*p/5*Math.sin(g)+t.y});l.push({x:-1*p/10*Math.cos(g)+c[m].x,y:-1*p/10*Math.sin(g)+c[m].y});r.push(v)}n.addPath(a);n.addPath(r);var A;A=d._fracture(l,10,this.map.spatialReference);
n.paths=n.paths.concat(A.geometry.paths);for(var F,m=0;m<A.midPoints.length;m++)F=A.midPoints[m].len/2,F>w/3.6&&(F=w/3.6),n.addPath(C.createD(A.midPoints[m].midPt,F,40));n.addPath(C.arrowHead(a[a.length-1],d.ArrowFlanksLen(d._2PtLen(f,c[c.length-1]),d._2PtLen(t,v)),d.angleInRadians(a[a.length-2],a[a.length-1])));n.addPath(C.arrowHead(r[r.length-1],d.ArrowFlanksLen(d._2PtLen(f,c[c.length-1]),d._2PtLen(t,v)),d.angleInRadians(r[r.length-2],r[r.length-1])));n.addPath(C.arrowHead(l[l.length-1],d.ArrowFlanksLen(d._2PtLen(f,
c[c.length-1]),d._2PtLen(t,v)),d.angleInRadians(l[l.length-2],l[l.length-1])));var g=d.angleInRadians(f,c[0]),B={x:-1*p/10*Math.cos(g)+f.x,y:-1*p/10*Math.sin(g)+f.y},l=[],l=l.concat(B,f);n.addPath(l);return n}catch(G){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},X:function(){return this.j},H:function(a){a=a.mapPoint;var c=new h;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,
currentDrawEssentials:c,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new h;a=this.C(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.Y,d;b&&(b.isWebMercator()?
d=J.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=I.fromJson(a.toJson())));this.J(a,d,c)}},J:function(a,c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.D.remove();this.G.remove();this.u.remove();
this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(a,c,b){var e=[];b+=15;var h=d.toDegrees(b);b=d.toDegrees(b-30);h=new z(a.x+c*Math.cos(d.toRad(h)),a.y+c*Math.sin(d.toRad(h)),this.map.spatialReference);c=new z(a.x+c*Math.cos(d.toRad(b)),a.y+c*Math.sin(d.toRad(b)),this.map.spatialReference);return e=e.concat(h,a,c)},W:function(){}})});
