define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(D,e,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,z,F,G,E,Y,Z,aa,ba,v,ca,H,da,w,ea,fa,I,d,h,C){return D([H],{declaredClass:"MilitarySymbology.Symbols.DisruptObstacleEffect",SID:"270502",symName:"Disrupt / Obs Effect",symGeometricType:"Area",isObstacle:"1",constructor:function(a,b){this.map=a;this.U=b;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.D=this.F;this.G=this.H;this.A=this.v;this.u;this.N;this.K;this._tGraphic=new z},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();var c;new h;c=new I(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),c=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,c),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))c=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";
this._tGraphic.setGeometry(this.createSymbol(c));this.o(this._tGraphic.geometry,c);this._clear()}else this.u=c.on("drawEnd",e.hitch(this,this.P)),this.K=c.on("onBaseLineClick",e.hitch(this,this.O)),this.N=c.on("onBaseLineProgress",e.hitch(this,this.S)),c.init()},C:function(a,b){var c=new h;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.BASE_LN_PTS=b;c.AMPLIFIER=this.amplifier;return c},P:function(a){this.u.remove();
this._tGraphic=new z(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=v(this.map,"mouse-move",e.hitch(this,this.H));this.A=v(this.map,"click",e.hitch(this,this.v));this.D=v(this.map,"dbl-click",e.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var b=[];b.CTRL_PTS=a.currentGeometry;var c=new E(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:b,
currentMarker:a.currentMarker,isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=a.BASE_LN_PTS.startPt,e=a.BASE_LN_PTS.endPt,J=b[0],h=b[b.length-1];a=[];var p=[],l=[];if(void 0===c||void 0===e)throw"First Parameter of the Function is an Array with Start and End Point";var f=d.getMidPoint(c,e),q=new E(this.map.spatialReference);
1<=b.length&&(h=J);var t=d._2PtLen(f,e),g=Math.atan((f.y-h.y)/(f.x-h.x));switch(d.twoPtsRelationShip(f,h)){case "ne":g+=Math.PI/2;break;case "nw":g+=3*Math.PI/2;break;case "sw":g+=3*Math.PI/2;break;case "se":g+=Math.PI/2}var c=t,A={x:c*Math.cos(g)+f.x,y:c*Math.sin(g)+f.y},B={x:-1*c*Math.cos(g)+f.x,y:-1*c*Math.sin(g)+f.y};paths=[];paths=paths.concat(A,B);q.addPath(paths);1<=b.length&&(a.push(A),p.push(B),l.push(f));for(i=0;i<b.length;i++){var m=d._2PtLen(f,b[i]),n=d.angleInRadians(f,b[i]),u=new w(A.x+
m*Math.cos(n),A.y+m*Math.sin(n),this.map.spatialReference),r=new w(B.x+m*Math.cos(n),B.y+m*Math.sin(n),this.map.spatialReference),t=m/5,v=d._2PtLen(u,r)/4;t>v&&(t=v);n=d.angleInRadians(u,r);new w(-1*t*Math.cos(n)+u.x,-1*t*Math.sin(n)+u.y,this.map.spatialReference);new w(t*Math.cos(n)+r.x,t*Math.sin(n)+r.y,this.map.spatialReference);g=n=d.angleInRadians(f,b[i]);p.push({x:-1*m/5*Math.cos(g)+r.x,y:-1*m/5*Math.sin(g)+r.y});l.push({x:-1*m/10*Math.cos(g)+b[i].x,y:-1*m/10*Math.sin(g)+b[i].y});a.push(u)}q.addPath(a);
q.addPath(p);q.addPath(l);q.addPath(C.arrowHead(a[a.length-1],d.ArrowFlanksLen(d._2PtLen(f,b[b.length-1]),d._2PtLen(u,r)),d.angleInRadians(a[a.length-2],a[a.length-1])));q.addPath(C.arrowHead(p[p.length-1],d.ArrowFlanksLen(d._2PtLen(f,b[b.length-1]),d._2PtLen(u,r)),d.angleInRadians(p[p.length-2],p[p.length-1])));q.addPath(C.arrowHead(l[l.length-1],d.ArrowFlanksLen(d._2PtLen(f,b[b.length-1]),d._2PtLen(u,r)),d.angleInRadians(l[l.length-2],l[l.length-1])));var g=d.angleInRadians(f,b[0]),z={x:-1*m/10*
Math.cos(g)+f.x,y:-1*m/10*Math.sin(g)+f.y},l=[],l=l.concat(z,f);q.addPath(l);return q}catch(D){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},X:function(){return this.j},H:function(a){a=a.mapPoint;var b=new h;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,
0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new h;a=this.C(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var c=this.map.Y,d;c&&(c.isWebMercator()?d=G.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=F.fromJson(a.toJson())));this.J(a,d,
b)}},J:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();
this._geometryType=null},V:function(a,b,c){var e=[];c+=15;var h=d.toDegrees(c);c=d.toDegrees(c-30);h=new w(a.x+b*Math.cos(d.toRad(h)),a.y+b*Math.sin(d.toRad(h)),this.map.spatialReference);b=new w(a.x+b*Math.cos(d.toRad(c)),a.y+b*Math.sin(d.toRad(c)),this.map.spatialReference);return e=e.concat(h,a,b)},W:function(){}})});
