define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(E,h,K,L,F,M,N,O,P,Q,R,S,T,U,V,W,t,G,H,X,I,Y,Z,aa,u,ba,J,ca,A,da,ea,fa,e,n){return E([J],{declaredClass:"MilitarySymbology.Symbols.DitchEmpty",SID:"290201",symName:"DCB",symGeometricType:"Line",isObstacle:"1",constructor:function(a,c){this.map=a;this.K=c;this.o;this._points=[];this._geometryType=null;this.m=3;this.j=20;this.C=this.A;this.D=this.F;this.G=this.H;this._tGraphic=new t},init:function(a,c){this.o=c;this.o.setColor(new F([0,0,0,1]));this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();var d;new n;this.m=e.setDefault(a,"TEETH_SIZE",this.m);this.j=e.setDefault(a,"TEETH_GAP",this.j);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.v(h.clone(a.CTRL_PTS),this.m,this.j),this.u(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.v(h.clone(a.CTRL_PTS),this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(d)),this.u(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=
new t(null,this.o),this.map.graphics.add(this._tGraphic),this.C=u(this.map,"click",h.hitch(this,this.A)),this.D=u(this.map,"dbl-click",h.hitch(this,this.F)))},v:function(a,c,d){var b=new n;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.AMPLIFIER=this.amplifier;b.N=this.isObstacle;b.TEETH_SIZE=c;b.TEETH_GAP=d;return b},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";
var d=new I(this.map.spatialReference);a=[];var b=[],h=e._2PtLen(c[0],c[c.length-1]),b=c,l=b[0],p=b[b.length-1];c=[];var n=[],B=[],q=h/5/this.m,f=Math.atan((l.y-p.y)/(l.x-p.x));switch(e.twoPtsRelationShip(l,p)){case "ne":f+=Math.PI/2;break;case "nw":f+=3*Math.PI/2;break;case "sw":f+=3*Math.PI/2;break;case "se":f+=Math.PI/2}var p=q,C={x:p*Math.cos(f)+l.x,y:p*Math.sin(f)+l.y},D={x:-1*p*Math.cos(f)+l.x,y:-1*p*Math.sin(f)+l.y};a=[];a=a.concat(C,D);1<=b.length&&(c.push(C),n.push(D),B.push(l));for(g=0;g<
b.length;g++){var v=e._2PtLen(l,b[g]),m=e.angleInRadians(l,b[g]),w=new A(C.x+v*Math.cos(m),C.y+v*Math.sin(m),this.map.spatialReference),z=new A(D.x+v*Math.cos(m),D.y+v*Math.sin(m),this.map.spatialReference),q=v/5,h=e._2PtLen(w,z),f=h/4;q>f&&(q=f);m=e.angleInRadians(w,z);new A(-1*q*Math.cos(m)+w.x,-1*q*Math.sin(m)+w.y,this.map.spatialReference);new A(q*Math.cos(m)+z.x,q*Math.sin(m)+z.y,this.map.spatialReference);c.push(w);n.push(z);B.push(b[g])}d.addRing(B);var r=e._2PtLen(b[0],b[b.length-1]),r=r/
this.j;e._2PtLen(b[0],b[b.length-1]);e.getDashPts(n,[r,r]);var u=e.getDashPts(c,[r,r]),t=e.getDashPts(B,[r,r]);a=[];for(var g=1;g<t.length;g++)0===g%2?a.push(u[g]):a.push(t[g]);d.addRing(a);return d}catch(E){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},H:function(a){a=a.mapPoint;var c=new n;c.CTRL_PTS=this._points.concat(a);this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,
currentMarker:this.o})},A:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.G=u(this.map,"mouse-move",h.hitch(this,this.H)));this.emit("onDrawClick",{currentPts:this._points});1==this.K&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new n;a=this.v(h.clone(this._points),this.m,this.j);this.u(this._tGraphic.geometry,a);this._clear();this._removeEvents()},
u:function(a,c){if(a){var d=this.map.P,b;d&&(d.isWebMercator()?b=H.webMercatorToGeographic(a,!0):4326===d.wkid&&(b=G.fromJson(a.toJson())));this.J(a,b,c)}},J:function(a,c,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:d,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.C.remove();this.D.remove();
this.G.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},O:function(){}})});
