define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(H,l,M,N,u,O,P,Q,R,S,T,U,V,W,E,F,G,I,J,X,K,Y,Z,aa,v,ba,L,ca,B,da,ea,fa,f,n){return H([L],{declaredClass:"MilitarySymbology.Symbols.DitchFilledWithWater",SID:"290202",symName:"DCB - Filled With Water",symGeometricType:"Line",isObstacle:"1",constructor:function(a,b){this.map=a;this.N=b;this.u;this._points=[];this._geometryType=null;this.o=3;this.m=20;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new G},init:function(a,b){this.j=1;a.hasOwnProperty("opacity")&&(this.j=a.opacity);this.u=
b;this.u=new F(F.STYLE_SOLID,new E(E.P,new u([0,0,0,this.j]),b.width),new u([0,0,255,this.j]));this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var d;new n;this.o=f.setDefault(a,"TEETH_SIZE",this.o);this.m=f.setDefault(a,"TEETH_GAP",this.m);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.A(l.clone(a.CTRL_PTS),this.o,this.m,this.j),this.v(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.A(l.clone(a.CTRL_PTS),
this.o,this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(d)),this.v(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new G(null,this.u),this.map.graphics.add(this._tGraphic),this.D=v(this.map,"click",l.hitch(this,this.C)),this.F=v(this.map,"dbl-click",l.hitch(this,this.G)))},A:function(a,b,d,c){var e=new n;e.SCOPE=this;e.SYM_GEO_TYPE=this.symGeometricType;e.SID=this.SID;e.SYM_GEO_TYPE=this.symGeometricType;e.SYM_NAME=this.symName;e.CTRL_PTS=a;e.AMPLIFIER=this.amplifier;e.O=this.isObstacle;
e.TEETH_SIZE=b;e.TEETH_GAP=d;e.opacity=c;return e},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var d=new K(this.map.spatialReference);a=[];var c=[],e=f._2PtLen(b[0],b[b.length-1]),c=b,m=c[0],q=c[c.length-1];b=[];var l=[],n=[],r=e/5/this.o,g=Math.atan((m.y-q.y)/(m.x-q.x));switch(f.twoPtsRelationShip(m,q)){case "ne":g+=Math.PI/2;break;case "nw":g+=3*Math.PI/2;break;case "sw":g+=3*Math.PI/2;break;case "se":g+=Math.PI/2}var q=r,C=
{x:q*Math.cos(g)+m.x,y:q*Math.sin(g)+m.y},D={x:-1*q*Math.cos(g)+m.x,y:-1*q*Math.sin(g)+m.y};a=[];a=a.concat(C,D);1<=c.length&&(b.push(C),l.push(D),n.push(m));for(h=0;h<c.length;h++){var w=f._2PtLen(m,c[h]),p=f.angleInRadians(m,c[h]),z=new B(C.x+w*Math.cos(p),C.y+w*Math.sin(p),this.map.spatialReference),A=new B(D.x+w*Math.cos(p),D.y+w*Math.sin(p),this.map.spatialReference),r=w/5,e=f._2PtLen(z,A),g=e/4;r>g&&(r=g);p=f.angleInRadians(z,A);new B(-1*r*Math.cos(p)+z.x,-1*r*Math.sin(p)+z.y,this.map.spatialReference);
new B(r*Math.cos(p)+A.x,r*Math.sin(p)+A.y,this.map.spatialReference);b.push(z);l.push(A);n.push(c[h])}d.addRing(n);var t=f._2PtLen(c[0],c[c.length-1]),t=t/this.m;f._2PtLen(c[0],c[c.length-1]);f.getDashPts(l,[t,t]);var v=f.getDashPts(b,[t,t]),u=f.getDashPts(n,[t,t]);a=[];for(var h=1;h<u.length;h++)0===h%2?a.push(v[h]):a.push(u[h]);d.addRing(a);return d}catch(E){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},I:function(a){a=a.mapPoint;var b=new n;b.CTRL_PTS=this._points.concat(a);
this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.u})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.H=v(this.map,"mouse-move",l.hitch(this,this.I)));this.emit("onDrawClick",{currentPts:this._points});1==this.N&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.J())},G:function(a){this._points.push(a.mapPoint);this.J()},
J:function(){var a;new n;a=this.A(l.clone(this._points),this.o,this.m,this.j);this.v(this._tGraphic.geometry,a);this._clear();this._removeEvents()},v:function(a,b){if(a){var d=this.map.U,c;d&&(d.isWebMercator()?c=J.webMercatorToGeographic(a,!0):4326===d.wkid&&(c=I.fromJson(a.toJson())));this.K(a,c,b)}},K:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,marker:this.u})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=
null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},S:function(){}})});
