define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(M,m,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,da,ea,K,N,O,P,fa,ga,ha,ia,w,ja,Q,ka,E,la,ma,na,b,A,L){return M([Q],{declaredClass:"MilitarySymbology.Symbols.Fix",SID:"341100",symName:"Fixation",symGeometricType:"Line",constructor:function(a,d){this.map=a;this.O=d;this.v;this._points=[];this._geometryType=null;this.u=3;this.o=30;this.m=this.j=10;this.F=this.D;this.G=this.H;this.I=this.J;this._tGraphic=new K},init:function(a,d){this.v=d;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var c;new A;this.m=b.setDefault(a,"TAIL_FACTOR",this.m);this.j=b.setDefault(a,"HEAD_RATIO",this.j);this.u=b.setDefault(a,"TEETH_SIZE",this.u);this.o=b.setDefault(a,"TEETH_GAP",this.o);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.A(m.clone(a.CTRL_PTS),this.m,this.j,this.u,this.o),this.C(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.A(m.clone(a.CTRL_PTS),this.m,this.j,this.u,this.o),this._tGraphic.setGeometry(this.createSymbol(c)),
this.C(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new K(null,this.v),this.map.graphics.add(this._tGraphic),this.F=w(this.map,"click",m.hitch(this,this.D)),this.G=w(this.map,"dbl-click",m.hitch(this,this.H)))},A:function(a,d,c,b,h){var g=new A;g.SCOPE=this;g.SYM_GEO_TYPE=this.symGeometricType;g.SID=this.SID;g.SYM_GEO_TYPE=this.symGeometricType;g.SYM_NAME=this.symName;g.CTRL_PTS=a;g.AMPLIFIER=this.amplifier;g.P=this.isObstacle;g.TAIL_FACTOR=d;g.HEAD_RATIO=c;g.TEETH_SIZE=b;g.TEETH_GAP=
h;return g},createSymbol:function(a){try{var d;if(a.hasOwnProperty("CTRL_PTS"))d=a.CTRL_PTS;else throw"controlPoints not found";var c=new P(this.map.spatialReference);a=[];var f=[],h=d[0],g=d[1],p=d[d.length-1],m=d[d.length-2],F,G,H,l,q=b._2PtLen(h,p);l=q/10;l>q/3&&(l=q/3);c.addPath(L.createF(h.x,h.y,l,h.spatialReference));var e=b.twoPtsAngle(h,g);l=q/8;F={x:l*Math.cos(e)+h.x,y:l*Math.sin(e)+h.y};l=q/this.m;G={x:l*Math.cos(e)+F.x,y:l*Math.sin(e)+F.y};c.addPath(a.concat(F,G));e=b.twoPtsAngle(m,p);
l=q/this.j*1.5;H={x:-1*l*Math.cos(e)+p.x,y:-1*l*Math.sin(e)+p.y};c.addPath(a.concat(H,p));var f=a.concat(G,d.slice(1,d.length-1),H),r=f[0],u=f[f.length-1];d=[];var h=[],v=q/5/this.u,e=Math.atan((r.y-u.y)/(r.x-u.x));switch(b.twoPtsRelationShip(r,u)){case "ne":e+=Math.PI/2;break;case "nw":e+=3*Math.PI/2;break;case "sw":e+=3*Math.PI/2;break;case "se":e+=Math.PI/2}var u=v,I={x:u*Math.cos(e)+r.x,y:u*Math.sin(e)+r.y},J={x:-1*u*Math.cos(e)+r.x,y:-1*u*Math.sin(e)+r.y};a=[];a=a.concat(I,J);1<=f.length&&(d.push(I),
h.push(J));for(n=0;n<f.length;n++){var B=b._2PtLen(r,f[n]),t=b.angleInRadians(r,f[n]),C=new E(I.x+B*Math.cos(t),I.y+B*Math.sin(t),this.map.spatialReference),D=new E(J.x+B*Math.cos(t),J.y+B*Math.sin(t),this.map.spatialReference),v=B/5,q=b._2PtLen(C,D),e=q/4;v>e&&(v=e);t=b.angleInRadians(C,D);new E(-1*v*Math.cos(t)+C.x,-1*v*Math.sin(t)+C.y,this.map.spatialReference);new E(v*Math.cos(t)+D.x,v*Math.sin(t)+D.y,this.map.spatialReference);d.push(C);h.push(D)}var z=b._2PtLen(f[0],f[f.length-1]),z=z/this.o;
b._2PtLen(f[0],f[f.length-1]);var w=b.getDashPts(h,[z,z]),A=b.getDashPts(d,[z,z]);a=[];for(var n=1;n<w.length;n++)0===n%2?a.push(w[n]):a.push(A[n]);c.addPath([G,a[0]]);c.addPath(a);a=[];a=a.concat(b.getLastPtFromPoly(c),H);c.addPath(a);c.addPath(L.arrowHead(p,b.ArrowFlanksLen(b._2PtLen(m,p),b._2PtLen(m,p)),b.angleInRadians(m,p)));return c}catch(K){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},J:function(a){a=this.A(this._points.concat(a.mapPoint),this.m,this.j,
this.u,this.o);this._tGraphic.setGeometry(this.createSymbol(a));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:a,currentMarker:this.v})},D:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.I=w(this.map,"mouse-move",m.hitch(this,this.J)));this.emit("onDrawClick",{currentPts:this._points});1==this.O&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.K())},H:function(a){this._points.push(a.mapPoint);
this.K()},K:function(){var a;new A;a=this.A(m.clone(this._points),this.m,this.j,this.u,this.o);this.C(this._tGraphic.geometry,a);this._clear();this._removeEvents()},C:function(a,b){if(a){var c=this.map.U,f;c&&(c.isWebMercator()?f=O.webMercatorToGeographic(a,!0):4326===c.wkid&&(f=N.fromJson(a.toJson())));this.N(a,f,b)}},N:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.v})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);
this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.F.remove();this.G.remove();this.I.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},S:function(){}})});
