define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(n,d,p,v,w,z,A,B,C,D,E,F,G,H,I,J,m,q,r,h,K,L,M,N,l,O,t,P,Q,R,S,T,e,g,u){return n([t],{declaredClass:"MilitarySymbology.Symbols.FreehandArrow",SID:"000006",symName:"Freehand - Arrow",symGeometricType:"Line",constructor:function(a,b){this.map=a;this.O=b;this.m;this._points=[];this.j=1;this._geometryType=null;this.A=this.v;this.C=this.D;this.F=this.G;this._tGraphic=new m},init:function(a,b){this.m=b;this.j=e.setDefault(a,"DRAW_TYPE",this.j);this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var c;new g;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.u(d.clone(a.CTRL_PTS),this.j),this.o(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.u(d.clone(a.CTRL_PTS),this.j),this._tGraphic.setGeometry(this.createSymbol(c)),this.o(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new m(null,this.m),this.map.graphics.add(this._tGraphic),this.A=l(this.map,"click",d.hitch(this,this.v)),this.C=l(this.map,"dbl-click",
d.hitch(this,this.D)))},u:function(a,b){var c=new g;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.DRAW_TYPE=b;c.ISFHAND=1;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=new h(this.map.spatialReference);switch(a.DRAW_TYPE){case 1:c=this.N(b,a,c);break;case 2:c=this.K(b,a,c)}c.addPath(u.arrowHead(b[b.length-
1],e.ArrowFlanksLen(e._2PtLen(b[0],b[b.length-1]),e._2PtLen(b[0],b[b.length-1])),e.angleInRadians(b[b.length-2],b[b.length-1])));return c}catch(f){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},G:function(a){a=a.mapPoint;var b=new g;b.CTRL_PTS=this._points.concat(a);b.DRAW_TYPE=this.j;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,
0));1==this._points.length&&(this.F=l(this.map,"mouse-move",d.hitch(this,this.G)));this.emit("onDrawClick",{currentPts:this._points});1==this.O&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.H())},D:function(a){this._points.push(a.mapPoint);this.H()},H:function(){var a;new g;a=this.u(d.clone(this._points),this.j);this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var c=this.map.S,f;c&&(c.isWebMercator()?f=r.webMercatorToGeographic(a,
!0):4326===c.wkid&&(f=q.fromJson(a.toJson())));this.J(a,f,b)}},J:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},N:function(a,b,c){c.addPath(a);return c},K:function(a,b,c){b=a[0];var f=a[a.length-1];c=new h(this.map.spatialReference);if(2===a.length)c.addPath([f,
b]);else if(2<a.length){var d=[];p.forEach(a,function(a){d.push({x:a.x,y:a.y})});c=this.I(d,100,this.map)}return c},I:function(a,b,c){var f={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var d=TweenMax.to(f,b,{bezier:a,ease:Linear.easeNone});a=[];var e;for(e=0;e<=b;e++)d.time(e),a.push({x:f.x,y:f.y});b=new h(c.spatialReference);b.addPath(a);return b},_removeEvents:function(){this.A.remove();
this.C.remove();this.F.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},P:function(){}})});
