define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(u,m,D,E,v,F,G,H,I,J,K,L,M,N,w,q,r,z,A,O,t,P,Q,R,p,S,B,T,U,V,W,C,X,n){return u([B],{declaredClass:"MilitarySymbology.Symbols.FreehandSemiCircleFilled",SID:"000140",symName:"Freehand - Semi Circle Filled",symGeometricType:"Area",constructor:function(b){this.map=b;this.j;this._points=[];this._geometryType=null;this.J;this.v=this.u;this.A=this.C;this.D=this.F;this._tGraphic=new r},init:function(b,c){this.G=1;b.hasOwnProperty("opacity")&&(this.G=b.opacity);this.j=c;var d=new v;d.setColor(c.color);
d.a=this.G;this.j=new q(q.STYLE_SOLID,new w(c.style,c.color,c.width),d);this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();new n;new C(this.map,this.j);b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),d=this.o(m.clone(b.CTRL_PTS)),this.m(this._tGraphic.geometry,d),this._clear()):b.hasOwnProperty("CTRL_PTS")?(d=this.o(m.clone(b.CTRL_PTS)),this._tGraphic.setGeometry(this.createSymbol(d)),this.m(this._tGraphic.geometry,d),this._clear()):
(this._tGraphic=new r(null,this.j),this.map.graphics.add(this._tGraphic),this.v=p(this.map,"click",m.hitch(this,this.u)),this.A=p(this.map,"dbl-click",m.hitch(this,this.C)))},N:function(b,c,d){var a=Math.sqrt(Math.pow(d.x-b.x,2)+Math.pow(d.y-b.y,2));d=Math.sqrt(Math.pow(d.x-c.x,2)+Math.pow(d.y-c.y,2));b=Math.sqrt(Math.pow(c.x-b.x,2)+Math.pow(c.y-b.y,2));return Math.acos((d*d+a*a-b*b)/(2*d*a))},o:function(b){var c=new n;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=
this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=b;c.AMPLIFIER=this.amplifier;c.ISFHAND=1;return c},createSymbol:function(b){try{var c;if(b.hasOwnProperty("CTRL_PTS"))c=b.CTRL_PTS;else throw"controlPoints not found";var d=new t(this.map.spatialReference),a=c[0],e=c[1];if(2===c.length)d.addRing([a,e]);else if(3===c.length){var f=c[2],g;b=[];var l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),
this.map.toScreen(e),this.map.toScreen(f),60,this.map),b=g.geometry.rings[0],d.addRing(b.slice(0,60)),d.addRing([b[1],b[59]]))}return d}catch(h){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},F:function(b){b=b.mapPoint;var c=new n;c.CTRL_PTS=this._points.concat(b);this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.j})},u:function(b){this._points.push(b.mapPoint.offset(0,
0));1==this._points.length&&(this.D=p(this.map,"mouse-move",m.hitch(this,this.F)));this.emit("onDrawClick",{currentPts:this._points});3===this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.H())},C:function(b){this._points.push(b.mapPoint);this.H()},H:function(){var b;new n;b=this.o(m.clone(this._points));this.m(this._tGraphic.geometry,b);this._clear();this._removeEvents()},m:function(b,c){if(b){var d=this.map.O,a;d&&(d.isWebMercator()?a=A.webMercatorToGeographic(b,!0):4326===
d.wkid&&(a=z.fromJson(b.toJson())));this.I(b,a,c)}},I:function(b,c,d){this.emit("onDrawEnd",{geometry:b,geographicGeometry:c,drawEssentials:d,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.v.remove();this.A.remove();this.D.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();
this._geometryType=null},K:function(){},_circleDrawEx:function(b,c,d){var a,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[b.x,b.y],[c.x,c.y],[d.x,d.y]];for(a=0;3>a;a++)e[a][0]=f[a][0],e[a][1]=f[a][1],e[a][2]=1;b=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][1],e[a][2]=1;c=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][0],e[a][2]=1;d=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*
f[a][1],e[a][1]=f[a][0],e[a][2]=f[a][1];e=this._determinantDrawEx(e,3);if(0==b)e=0;else{var g=.5*c/b,l=-.5*d/b;e=Math.sqrt(g*g+l*l+e/b)}return{radius:e,center:{x:g,y:l}}},_determinantDrawEx:function(b,c){var d,a,e,f,g,l=[[0,0,0],[0,0,0],[0,0,0]];if(2==c)g=b[0][0]*b[1][1]-b[1][0]*b[0][1];else for(e=g=0;e<c;e++){for(d=1;d<c;d++)for(a=f=0;a<c;a++)a!=e&&(l[d-1][f]=b[d][a],f++);g+=Math.pow(-1,e)*b[0][e]*this._determinantDrawEx(l,c-1)}return g},CreateCircleSegmentFromThreePoints:function(b,c,d,a,e,f){var g=
b.center,l=b.radius;b=[];c.x-=g.x;c.y-=g.y;d.x-=g.x;d.y-=g.y;a.x-=g.x;a.y-=g.y;c=Math.atan2(c.y,c.x);var h=Math.atan2(d.y,d.x);d=Math.atan2(a.y,a.x);c=0>c?2*Math.PI+c:c;h=0>h?2*Math.PI+h:h;d=0>d?2*Math.PI+d:d;a=Math.min(c,h);c=Math.max(c,h);h=c-a;if(d<a||d>c)h-=2*Math.PI;c=h/e;for(h=0;h<=e;h++)d=f.toMap({x:l*Math.cos(a+h*c)+g.x,y:l*Math.sin(a+h*c)+g.y}),b.push(d);f=new t(f.spatialReference);f.addRing(b);return{geometry:f,lastPoint:b[e],backPoint:b[e-5]}}})});
