define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(w,f,E,H,I,J,K,L,M,N,O,P,Q,R,S,T,v,z,A,U,B,V,W,X,u,Y,F,Z,aa,ba,ca,G,m,t,C){return w([F],{declaredClass:"MilitarySymbology.Symbols.FreehandMainAttackArrow",SID:"000008",symName:"Freehand - Main Attk Like Arrow",symGeometricType:"Area",constructor:function(b,a){this.map=b;this.P=a;this.o;this._points=[];this._geometryType=null;this.U;this.G=this.F;this.H=this.I;this.J=this.K;this._tGraphic=new v;this.j=.05;this.m=.07},init:function(b,a){this.o=a;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();this.m=m.setDefault(b,"HEAD_RATIO",this.m);this.j=m.setDefault(b,"TAIL_FACTOR",this.j);var c;new t;new G(this.map,this.o);b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),c=this.v(f.clone(b.CTRL_PTS),this.m,this.j),this.u(this._tGraphic.geometry,c),this._clear()):b.hasOwnProperty("CTRL_PTS")?(c=this.v(f.clone(b.CTRL_PTS),this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(c)),this.u(this._tGraphic.geometry,c),this._clear()):
(this._tGraphic=new v(null,this.o),this.map.graphics.add(this._tGraphic),this.G=u(this.map,"click",f.hitch(this,this.F)),this.H=u(this.map,"dbl-click",f.hitch(this,this.I)))},v:function(b,a,c){var d=new t;d.SCOPE=this;d.SYM_GEO_TYPE=this.symGeometricType;d.SID=this.SID;d.SYM_GEO_TYPE=this.symGeometricType;d.SYM_NAME=this.symName;d.CTRL_PTS=b;d.AMPLIFIER=this.amplifier;d.HEAD_RATIO=a;d.TAIL_FACTOR=c;d.ISFHAND=1;return d},createSymbol:function(b){try{var a;if(b.hasOwnProperty("CTRL_PTS"))a=b.CTRL_PTS;
else throw"controlPoints not found";if(2>=a.length){var c=a[0],d=a[a.length-1],e=m._2PtLen(c,d),g=Math.atan((c.y-d.y)/(c.x-d.x));switch(m.twoPtsRelationShip(c,d)){case "ne":g+=Math.PI/2;break;case "nw":g+=3*Math.PI/2;break;case "sw":g+=3*Math.PI/2;break;case "se":g+=Math.PI/2}var n={x:this.j*e*Math.cos(g)+c.x,y:this.j*e*Math.sin(g)+c.y},D={x:-1*this.j*e*Math.cos(g)+c.x,y:-1*this.j*e*Math.sin(g)+c.y},l=(1-this.m)*e,r={x:this.j*l*Math.cos(g)+c.x,y:this.j*l*Math.sin(g)+c.y},p={x:-1*this.j*l*Math.cos(g)+
c.x,y:-1*this.j*l*Math.sin(g)+c.y},f=new B(this.map.spatialReference),h=[];h.push(n);var q=this.CreateArrowHeadPathEx(r,d,p,e,this.m,15),h=h.concat(q.rings);h.push(p);B.prototype.isClockwise(h)||this.Z||(console.debug(this.declaredClass+" :  Polygons drawn in anti-clockwise direction will be reversed to be clockwise."),h.reverse());f.addRing(h);var t=m.getMidPoint(q.A,q.C),u=m.twoPtsAngle(t,d),v=e*this.m/1.3,w={x:t.x+v*Math.cos(u),y:t.y+v*Math.sin(u)},h=[],h=h.concat(q.A,w,q.C)}else{b=[];c=[];f=new B(this.map.spatialReference);
d=a[a.length-1];tempArray=[];b=[];c=[];E.forEach(a,function(a){tempArray.push({x:a.x,y:a.y})});angleArray=m._vertexAngle(tempArray);var z=m._ptCollectionLen(tempArray,0);a=0;for(e=tempArray.length-1;a<e;a++)l=m._ptCollectionLen(tempArray,a),l+=z/2.4,n={x:this.j*l*Math.cos(angleArray[a])+tempArray[a].x,y:this.j*l*Math.sin(angleArray[a])+tempArray[a].y},D={x:-1*this.j*l*Math.cos(angleArray[a])+tempArray[a].x,y:-1*this.j*l*Math.sin(angleArray[a])+tempArray[a].y},b.push(n),c.push(D);b.push({x:d.x,y:d.y});
c.push({x:d.x,y:d.y});b=C.CreateBezierPathPCOnly(b,70);b.splice(Math.floor(70*(1-this.m)),Number.MAX_VALUE);c=C.CreateBezierPathPCOnly(c,70);c.splice(Math.floor(70*(1-this.m)),Number.MAX_VALUE);var q=this.CreateArrowHeadPathEx(b[b.length-1],d,c[c.length-1],m._ptCollectionLen(tempArray,0),this.m,15),A=q.rings,h=[],h=h.concat(b),h=h.concat(A),h=h.concat(c.reverse());f.addRing(h);h=[];h=h.concat(q.A,q.S,q.C)}f.addRing(h);return f}catch(da){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},
Y:function(){return this.D},K:function(b){b=b.mapPoint;var a=new t;a.CTRL_PTS=this._points.concat(b);a.BASE_LN_PTS=this.D;a.BK_LN_DIST_RATIO=this.X;a.BK_LN_ANGL_RATIO=this.W;this._tGraphic.setGeometry(this.createSymbol(a));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:a,currentMarker:this.o})},F:function(b){this._points.push(b.mapPoint.offset(0,0));1==this._points.length&&(this.J=u(this.map,"mouse-move",f.hitch(this,this.K)));this.emit("onDrawClick",{currentPts:this._points});
1==this.P&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.N())},I:function(b){this._points.push(b.mapPoint);this.N()},N:function(){var b;new t;b=this.v(f.clone(this._points),this.m,this.j);this.u(this._tGraphic.geometry,b);this._clear();this._removeEvents()},u:function(b,a){if(b){var c=this.map.$,d;c&&(c.isWebMercator()?d=A.webMercatorToGeographic(b,!0):4326===c.wkid&&(d=z.fromJson(b.toJson())));this.O(b,d,a)}},O:function(b,a,c){this.emit("onDrawEnd",{geometry:b,
geographicGeometry:a,drawEssentials:c,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.D=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.G.remove();this.H.remove();this.J.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(){},CreateArrowHeadPathEx:function(b,
a,c,d,e,g,n){d*=e;e=1.07*d;var f=m.twoPtsAngle(a,b),l=m.twoPtsAngle(a,c),r=Math.abs(f-l)/2;Math.abs(f-l)>1.88*Math.PI&&(r+=Math.PI);var p=Math.asin(d*Math.sin(r+g/180*Math.PI)/Math.sqrt(d*d+e*e-2*e*d*Math.cos(r+g/180*Math.PI)))+g/180*Math.PI,p=0==n||void 0==n?d*Math.sin(Math.PI-p-r)/Math.sin(p):0;n=[];r={x:a.x+p*Math.cos(f),y:a.y+p*Math.sin(f)};f={x:a.x+e*Math.cos(f-g/180*Math.PI),y:a.y+e*Math.sin(f-g/180*Math.PI)};n.push(r);n.push(f);n.push(a);p={x:a.x+p*Math.cos(l),y:a.y+p*Math.sin(l)};e={x:a.x+
e*Math.cos(l+g/180*Math.PI),y:a.y+e*Math.sin(l+g/180*Math.PI)};n.push(e);n.push(p);g=m.getMidPoint(r,f);e=m.getMidPoint(p,e);b=m.getMidPoint(b,c);a=m.twoPtsAngle(b,a);return{rings:n,A:g,C:e,S:{x:b.x+d*Math.cos(a),y:b.y+d*Math.sin(a)}}}})});
