define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(q,g,r,z,A,B,C,D,E,F,G,H,I,J,K,L,n,t,u,h,M,N,O,P,m,Q,v,R,S,T,U,V,e,l,w){return q([v],{declaredClass:"MilitarySymbology.Symbols.FreehandDottedArrow",SID:"000007",symName:"Freehand - Dotted Arrow",symGeometricType:"Line",constructor:function(a,b){this.map=a;this.P=b;this.o;this._points=[];this.m=1;this.j=30;this._geometryType=null;this.C=this.A;this.D=this.F;this.G=this.H;this._tGraphic=new n},init:function(a,b){this.o=b;this.m=e.setDefault(a,"DRAW_TYPE",this.m);this.j=e.setDefault(a,"TEETH_GAP",
this.j);this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var d;new l;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.v(g.clone(a.CTRL_PTS),this.m,this.j),this.u(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.v(g.clone(a.CTRL_PTS),this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(d)),this.u(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new n(null,this.o),this.map.graphics.add(this._tGraphic),
this.C=m(this.map,"click",g.hitch(this,this.A)),this.D=m(this.map,"dbl-click",g.hitch(this,this.F)))},v:function(a,b,d){var c=new l;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.DRAW_TYPE=b;c.TEETH_GAP=d;c.ISFHAND=1;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var d=new h(this.map.spatialReference);
switch(a.DRAW_TYPE){case 1:d=this.O(b,a,d);break;case 2:d=this.N(b,a,d)}d.addPath(w.arrowHead(b[b.length-1],e.ArrowFlanksLen(e._2PtLen(b[0],b[b.length-1]),e._2PtLen(b[0],b[b.length-1])),e.angleInRadians(b[b.length-2],b[b.length-1])));return d}catch(c){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},H:function(a){a=a.mapPoint;var b=new l;b.CTRL_PTS=this._points.concat(a);b.DRAW_TYPE=this.m;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",
{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.o})},A:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.G=m(this.map,"mouse-move",g.hitch(this,this.H)));this.emit("onDrawClick",{currentPts:this._points});1==this.P&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new l;a=this.v(g.clone(this._points),this.m,this.j);this.u(this._tGraphic.geometry,
a);this._clear();this._removeEvents()},u:function(a,b){if(a){var d=this.map.U,c;d&&(d.isWebMercator()?c=u.webMercatorToGeographic(a,!0):4326===d.wkid&&(c=t.fromJson(a.toJson())));this.K(a,c,b)}},K:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},O:function(a,b,d){d=
new h(this.map.spatialReference);var c;b=e._2PtLen(a[0],a[a.length-1]);b/=this.j;e._2PtLen(a[0],a[a.length-1]);a=e.getDashPts(a,[b,b]);for(var f=0;f<a.length;f+=2)b=a[f],void 0!=a[f+1]&&(c=a[f+1]),d.addPath([b,c]);return d},N:function(a,b,d){var c=a[0],f=a[a.length-1];b=[];b=[];var p;d=new h(this.map.spatialReference);if(2===a.length)d.addPath([f,c]);else if(2<a.length){var g=[];r.forEach(a,function(a){g.push({x:a.x,y:a.y})});b=this.J(g,100,this.map);a=e._2PtLen(b[0],b[b.length-1]);a/=this.j;f=e._2PtLen(b[0],
b[b.length-1])/7;c=f/7;c>f/3.6&&(c=f/3.6);b=e.getDashPts(b,[a,a]);for(c=0;c<b.length;c+=2)a=b[c],void 0!=b[c+1]&&(p=b[c+1]),d.addPath([a,p])}return d},J:function(a,b,d){var c={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a=TweenMax.to(c,b,{bezier:a,ease:Linear.easeNone});var f=[],e;for(e=0;e<=b;e++)a.time(e),f.push({x:c.x,y:c.y});(new h(d.spatialReference)).addPath(f);
return f},_removeEvents:function(){this.C.remove();this.D.remove();this.G.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},S:function(){}})});
