define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(n,d,p,w,z,A,B,C,D,E,F,G,H,I,J,K,m,q,r,g,L,M,N,O,l,P,t,Q,R,S,T,u,v,h){return n([t],{declaredClass:"MilitarySymbology.Symbols.FreehandLine",SID:"000001",symName:"Freehand - Line",symGeometricType:"Line",constructor:function(a,b){this.map=a;this.O=b;this.m;this._points=[];this.j=1;this._geometryType=null;this.A=this.v;this.C=this.D;this.F=this.G;this._tGraphic=new m},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var c;new h;new u(this.map,
this.m);this.j=v.setDefault(a,"DRAW_TYPE",this.j);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.u(d.clone(a.CTRL_PTS),this.j),this.o(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.u(d.clone(a.CTRL_PTS),this.j),this._tGraphic.setGeometry(this.createSymbol(c)),this.o(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new m(null,this.m),this.map.graphics.add(this._tGraphic),this.A=l(this.map,"click",d.hitch(this,
this.v)),this.C=l(this.map,"dbl-click",d.hitch(this,this.D)))},u:function(a,b){var c=new h;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.DRAW_TYPE=b;c.ISFHAND=1;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=new g(this.map.spatialReference),e=b[0],d=b[b.length-1];switch(a.DRAW_TYPE){case 1:c=this.N(b);
break;case 2:c=this.K(b,e,d,a,c)}return c}catch(f){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},G:function(a){a=a.mapPoint;var b=new h;b.CTRL_PTS=this._points.concat(a);b.DRAW_TYPE=this.j;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.F=l(this.map,"mouse-move",
d.hitch(this,this.G)));this.emit("onDrawClick",{currentPts:this._points});1==this.O&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.H())},D:function(a){this._points.push(a.mapPoint);this.H()},N:function(a){var b=new g(this.map.spatialReference);b.addPath(a);return b},K:function(a,b,c){var e=new g(this.map.spatialReference);if(2===a.length)e.addPath([c,b]);else if(2<a.length){var d=[];p.forEach(a,function(a){d.push({x:a.x,y:a.y})});e=this.I(d,100,this.map)}return e},
I:function(a,b,c){var e={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var d=TweenMax.to(e,b,{bezier:a,ease:Linear.easeNone});a=[];var f;for(f=0;f<=b;f++)d.time(f),a.push({x:e.x,y:e.y});b=new g(c.spatialReference);b.addPath(a);return b},H:function(){var a;new h;a=this.u(d.clone(this._points),this.j);this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,
b){if(a){var c=this.map.S,d;c&&(c.isWebMercator()?d=r.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=q.fromJson(a.toJson())));this.J(a,d,b)}},J:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.A.remove();this.C.remove();this.F.remove();
this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},P:function(){}})});
