define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(C,e,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,v,D,G,H,Y,Z,aa,ba,q,ca,I,da,r,ea,fa,J,f,n){return C([I],{declaredClass:"MilitarySymbology.Symbols.FreehandDoubleLineArrow",SID:"000004",symName:"Freehand - Double Line Arrow",symGeometricType:"Area",constructor:function(a,c){this.map=a;this.V=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.D=this.F;this.G=this.H;this.A=this.v;this.u;this.O;this.N;this._tGraphic=new v},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();var b;new n;b=new J(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";
this._tGraphic.setGeometry(this.createSymbol(b));this.o(this._tGraphic.geometry,b);this._clear()}else this.u=b.on("drawEnd",e.hitch(this,this.S)),this.N=b.on("onBaseLineClick",e.hitch(this,this.P)),this.O=b.on("onBaseLineProgress",e.hitch(this,this.U)),b.init()},C:function(a,c){var b=new n;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;b.ISFHAND=1;return b},S:function(a){this.u.remove();
this._tGraphic=new v(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=q(this.map,"mouse-move",e.hitch(this,this.H));this.A=q(this.map,"click",e.hitch(this,this.v));this.D=q(this.map,"dbl-click",e.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},U:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new H(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,
currentMarker:a.currentMarker,isBaseLine:!0})},P:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,d=a.BASE_LN_PTS.endPt,e=c[0],n=c[c.length-1];a=[];var z=[],q=[];if(void 0===b||void 0===d)throw"First Parameter of the Function is an Array with Start and End Point";var h=f.getMidPoint(b,d),w=new H(this.map.spatialReference);
1<=c.length&&(n=e);var p=f._2PtLen(h,d),g=Math.atan((h.y-n.y)/(h.x-n.x));switch(f.twoPtsRelationShip(h,n)){case "ne":g+=Math.PI/2;break;case "nw":g+=3*Math.PI/2;break;case "sw":g+=3*Math.PI/2;break;case "se":g+=Math.PI/2}var b=p,A={x:b*Math.cos(g)+h.x,y:b*Math.sin(g)+h.y},B={x:-1*b*Math.cos(g)+h.x,y:-1*b*Math.sin(g)+h.y};paths=[];paths=paths.concat(A,B);w.addPath(paths);1<=c.length&&(a.push(A),z.push(B),q.push(h));for(i=0;i<c.length;i++){var l=f._2PtLen(h,c[i]),m=f.angleInRadians(h,c[i]),t=new r(A.x+
l*Math.cos(m),A.y+l*Math.sin(m),this.map.spatialReference),u=new r(B.x+l*Math.cos(m),B.y+l*Math.sin(m),this.map.spatialReference),p=l/5,v=f._2PtLen(t,u)/4;p>v&&(p=v);m=f.angleInRadians(t,u);new r(-1*p*Math.cos(m)+t.x,-1*p*Math.sin(m)+t.y,this.map.spatialReference);new r(p*Math.cos(m)+u.x,p*Math.sin(m)+u.y,this.map.spatialReference);var g=m=f.angleInRadians(h,c[i]),E={x:-1*l/10*Math.cos(g)+t.x,y:-1*l/5*Math.sin(g)+t.y};a.push(E);var F={x:-1*l/10*Math.cos(g)+u.x,y:-1*l/5*Math.sin(g)+u.y};z.push(F);
q.push({x:-1*l/10*Math.cos(g)+c[i].x,y:-1*l/10*Math.sin(g)+c[i].y})}w.addPath(a);w.addPath(z);var C=this.J(E,a[0]),D=this.J(F,z[0]);w.addPath([E,C[1],c[c.length-1],D[0],F]);return w}catch(G){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},J:function(a,c){var b,d=f._2PtLen(a,c)/4;b=d/4;b>d/2&&(b=d/2);d=Math.atan((a.y-c.y)/(a.x-c.x));switch(f.twoPtsRelationShip(a,c)){case "ne":d+=Math.PI/2;break;case "nw":d+=3*Math.PI/2;break;case "sw":d+=3*Math.PI/2;break;case "se":d+=
Math.PI/2}return[{x:b*Math.cos(d)+a.x,y:b*Math.sin(d)+a.y},{x:-1*b*Math.cos(d)+a.x,y:-1*b*Math.sin(d)+a.y}]},Y:function(){return this.j},H:function(a){a=a.mapPoint;var c=new n;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});
1==this.V&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new n;a=this.C(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.Z,d;b&&(b.isWebMercator()?d=G.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=D.fromJson(a.toJson())));this.K(a,d,c)}},K:function(a,c,b){this.emit("onDrawEnd",{geometry:a,
geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},W:function(a,c,
b){var d=[];b+=15;var e=f.toDegrees(b);b=f.toDegrees(b-30);e=new r(a.x+c*Math.cos(f.toRad(e)),a.y+c*Math.sin(f.toRad(e)),this.map.spatialReference);c=new r(a.x+c*Math.cos(f.toRad(b)),a.y+c*Math.sin(f.toRad(b)),this.map.spatialReference);return d=d.concat(e,a,c)},X:function(){}})});
