define("dojo/_base/declare dojo/_base/lang esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon dojo/on dojo/Evented esri/geometry/Point MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),function(H,f,t,L,M,I,P,u,N,A,O,b,l){return H([N],{declaredClass:"MilitarySymbology.Symbols.Funnel",SID:"151407",symName:"Funnel",symGeometricType:"Area",constructor:function(a){this.map=
a;this.m;this._points=[];this.j=[];this._geometryType=null;this.u;this.v;this.o;this.F=this.D;this.H=this.I;this.J=this.K;this.F=this.D;this.C;this.S;this.P;this._tGraphic=new t},init:function(a,e){this.m=e;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();this.u=b.setDefault(a,"FRNT_LN_ANGL_RATIO",.8);this.v=b.setDefault(a,"FRNT_LN_DIST_RATIO",1.5);this.o=b.setDefault(a,"FLAP_DIST_RATIO",3);var c;new l;c=new O(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&
a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),c=this.G(f.clone(a.CTRL_PTS),f.clone(a.BASE_LN_PTS),this.u,this.v,this.o),this.A(this._tGraphic.geometry,c),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))c=this.G(f.clone(a.CTRL_PTS),f.clone(a.BASE_LN_PTS),this.u,this.v,this.o);else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(c));this.A(this._tGraphic.geometry,
c);this._clear()}else this.C=c.on("drawEnd",f.hitch(this,this.V)),this.P=c.on("onBaseLineClick",f.hitch(this,this.U)),this.S=c.on("onBaseLineProgress",f.hitch(this,this.W)),c.init()},G:function(a,e,c,b,f){var d=new l;d.SCOPE=this;d.SYM_GEO_TYPE=this.symGeometricType;d.SID=this.SID;d.SYM_GEO_TYPE=this.symGeometricType;d.SYM_NAME=this.symName;d.FRNT_LN_ANGL_RATIO=c;d.FRNT_LN_DIST_RATIO=b;d.FLAP_DIST_RATIO=f;d.CTRL_PTS=a;d.BASE_LN_PTS=e;d.AMPLIFIER=this.amplifier;return d},V:function(a){this.C.remove();
this._tGraphic=new t(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.J=u(this.map,"mouse-move",f.hitch(this,this.K));this.F=u(this.map,"click",f.hitch(this,this.D));this.H=u(this.map,"dbl-click",f.hitch(this,this.I));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},W:function(a){var e=[];e.CTRL_PTS=a.currentGeometry;var c=new I(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:e,
currentMarker:a.currentMarker,isBaseLine:!0})},U:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){var e,c,f,p,d;try{var g;if(a.hasOwnProperty("CTRL_PTS"))g=a.CTRL_PTS;else throw"controlPoints not found";e=b.setDefault(a,"FRNT_LN_ANGL_RATIO",.8);c=b.setDefault(a,"FRNT_LN_DIST_RATIO",1.5);f=b.setDefault(a,"FLAP_DIST_RATIO",3);var n=a.BASE_LN_PTS.startPt,l=a.BASE_LN_PTS.endPt,u=g[0],B=g[g.length-1];a=[];var C=[];if(void 0===n||void 0===l)throw"First Parameter of the Function is an Array with Start and End Point";
var h=b.getMidPoint(n,l),v=new I(this.map.spatialReference);1<=g.length&&(B=u);var q=b._2PtLen(h,l),m=Math.atan((h.y-B.y)/(h.x-B.x));switch(b.twoPtsRelationShip(h,B)){case "ne":m+=Math.PI/2;break;case "nw":m+=3*Math.PI/2;break;case "sw":m+=3*Math.PI/2;break;case "se":m+=Math.PI/2}var n=q,D={x:n*Math.cos(m)+h.x,y:n*Math.sin(m)+h.y},E={x:-1*n*Math.cos(m)+h.x,y:-1*n*Math.sin(m)+h.y},r=[],r=r.concat(D,E);v.addPath(r);if(1<=g.length){a.push(D);C.push(E);if(void 0===g[0])throw"Insufficient Pts";p=b._2PtLen(h,
g[0])/c;d=b.angleInRadians(h,g[0]);var w=new A(D.x+p*Math.cos(d),D.y+p*Math.sin(d),this.map.spatialReference),z=new A(E.x+p*Math.cos(d),E.y+p*Math.sin(d),this.map.spatialReference);a.push(w);C.push(z)}q=p/f+b._2PtLen(g[0],g[g.length-1]);d=b.angleInRadians(w,z)-e;var F=new A(-1*q*Math.cos(d)+w.x,-1*q*Math.sin(d)+w.y,this.map.spatialReference);d=b.angleInRadians(w,z)+e;var G=new A(q*Math.cos(d)+z.x,q*Math.sin(d)+z.y,this.map.spatialReference);a.push(F);C.push(G);var t=g[g.length-1],J,r=[],K=b._circleDrawEx(this.map.toScreen(F),
this.map.toScreen(G),this.map.toScreen(t));0<K.radius&&(J=b.CreateCircleSegmentFromThreePoints(K,this.map.toScreen(F),this.map.toScreen(G),this.map.toScreen(t),60,this.map),r=J.geometry.paths[0],v.addPath(r.slice(0,61)));v.addPath(a);v.addPath(C);return v}catch(H){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},Y:function(){return this.j},K:function(a){a=a.mapPoint;var e=new l;e.CTRL_PTS=this._points.concat(a);e.BASE_LN_PTS=this.j;e.FRNT_LN_ANGL_RATIO=this.u;e.FRNT_LN_DIST_RATIO=
this.v;e.FLAP_DIST_RATIO=this.o;this._tGraphic.setGeometry(this.createSymbol(e));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:e,currentMarker:this.m})},D:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});2==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.N())},I:function(a){1<=this._points.length&&(this._points.push(a.mapPoint),this.N())},N:function(){var a;new l;a=this.G(f.clone(this._points),
f.clone(this.j),this.u,this.v,this.o);this.A(this._tGraphic.geometry,a);this._clear();this._removeEvents()},A:function(a,e){if(a){var c=this.map.Z,b;c&&(c.isWebMercator()?b=M.webMercatorToGeographic(a,!0):4326===c.wkid&&(b=L.fromJson(a.toJson())));this.O(a,b,e)}},O:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);
this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.F.remove();this.H.remove();this.J.remove();this.C.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},X:function(){}})});
