define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(C,e,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,B,D,E,F,X,Y,Z,aa,w,ba,G,ca,z,da,ea,H,n,h,I){return C([G],{declaredClass:"MilitarySymbology.Symbols.HighWireFence",SID:"290305",symName:"Wire Obs - High Wire Fence",symGeometricType:"Line",isObstacle:"1",constructor:function(a,b){this.map=a;this.I=b;this.j;this._points=[];this._geometryType=null;this.v=this.u;this.A=this.C;this.D=this.F;this._tGraphic=new B},init:function(a,b){this.j=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var c;new h;new H(this.map,this.j);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.o(e.clone(a.CTRL_PTS)),this.m(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.o(e.clone(a.CTRL_PTS)),this._tGraphic.setGeometry(this.createSymbol(c)),this.m(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new B(null,this.j),this.map.graphics.add(this._tGraphic),this.v=w(this.map,"click",e.hitch(this,this.u)),this.A=w(this.map,
"dbl-click",e.hitch(this,this.C)))},o:function(a){var b=new h;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.AMPLIFIER=this.amplifier;b.J=this.isObstacle;return b},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=new F(this.map.spatialReference),d=n._2PtLen(b[0],b[b.length-1]),d=d/20,f,q,e=n._2PtLen(b[0],b[b.length-1])/7;f=e/7;f>e/3.6&&
(f=e/3.6);var r=n.getDashPts(b,[d,d]);for(a=0;a<r.length;a++)for(q=I.createEchelon("18",r[a],f),d=0;d<=q.length-1;d++)c.addPath(q[d]);var l=b[0],p=b[b.length-1];q=[];var r=[],d=[],g=Math.atan((l.y-p.y)/(l.x-p.x));switch(n.twoPtsRelationShip(l,p)){case "ne":g+=Math.PI/2;break;case "nw":g+=3*Math.PI/2;break;case "sw":g+=3*Math.PI/2;break;case "se":g+=Math.PI/2}var p=f,h={x:p*Math.cos(g)+l.x,y:p*Math.sin(g)+l.y},A={x:-1*p*Math.cos(g)+l.x,y:-1*p*Math.sin(g)+l.y};paths=[];paths=paths.concat(h,A);1<=b.length&&
(q.push(h),r.push(A));for(a=0;a<b.length;a++){var t=n._2PtLen(l,b[a]),m=n.angleInRadians(l,b[a]),u=new z(h.x+t*Math.cos(m),h.y+t*Math.sin(m),this.map.spatialReference),v=new z(A.x+t*Math.cos(m),A.y+t*Math.sin(m),this.map.spatialReference);f=t/5;e=n._2PtLen(u,v);g=e/4;f>g&&(f=g);m=n.angleInRadians(u,v);new z(-1*f*Math.cos(m)+u.x,-1*f*Math.sin(m)+u.y,this.map.spatialReference);new z(f*Math.cos(m)+v.x,f*Math.sin(m)+v.y,this.map.spatialReference);q.push(u);r.push(v);d.push(b[a])}c.addPath(q);c.addPath(r);
return c}catch(w){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},F:function(a){a=a.mapPoint;var b=new h;b.CTRL_PTS=this._points.concat(a);this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.j})},u:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.D=w(this.map,"mouse-move",e.hitch(this,this.F)));this.emit("onDrawClick",{currentPts:this._points});
1==this.I&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.G())},C:function(a){this._points.push(a.mapPoint);this.G()},G:function(){var a;new h;a=this.o(e.clone(this._points));this.m(this._tGraphic.geometry,a);this._clear();this._removeEvents()},m:function(a,b){if(a){var c=this.map.N,d;c&&(c.isWebMercator()?d=E.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=D.fromJson(a.toJson())));this.H(a,d,b)}},H:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,
drawEssentials:c,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.v.remove();this.A.remove();this.D.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},K:function(){}})});
