define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(A,n,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,z,C,E,D,W,X,Y,Z,v,aa,F,ba,q,ca,da,G,p,r,H){return A([F],{declaredClass:"MilitarySymbology.Symbols.Isolate",SID:"341500",symName:"Isolate",symGeometricType:"Area",constructor:function(c){this.map=c;this.o;this._points=[];this._geometryType=null;this.j=2;this.C=this.A;this.D=this.F;this.G=this.H;this._tGraphic=new z},init:function(c,d){this.o=d;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();this.j=2;var a;new r;new G(this.map,
this.o);this.j=p.setDefault(c,"TEETH_SIZE",this.j);c.hasOwnProperty("CTRL_PTS")&&c.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(c.GEOM),a=this.v(n.clone(c.CTRL_PTS),c.TEETH_SIZE),this.u(this._tGraphic.geometry,a),this._clear()):c.hasOwnProperty("CTRL_PTS")?(a=this.v(n.clone(c.CTRL_PTS),c.TEETH_SIZE),this._tGraphic.setGeometry(this.createSymbol(a)),this.u(this._tGraphic.geometry,a),this._clear()):(this._tGraphic=new z(null,this.o),this.map.graphics.add(this._tGraphic),this.C=v(this.map,"click",
n.hitch(this,this.A)),this.D=v(this.map,"dbl-click",n.hitch(this,this.F)))},O:function(c,d,a){var b=Math.sqrt(Math.pow(a.x-c.x,2)+Math.pow(a.y-c.y,2));a=Math.sqrt(Math.pow(a.x-d.x,2)+Math.pow(a.y-d.y,2));c=Math.sqrt(Math.pow(d.x-c.x,2)+Math.pow(d.y-c.y,2));return Math.acos((a*a+b*b-c*c)/(2*a*b))},N:function(c,d,a,b,e,f){return Math.atan2(d-f,c-e)-Math.atan2(b-f,a-e)},v:function(c,d){var a=new r;a.SCOPE=this;a.SYM_GEO_TYPE=this.symGeometricType;a.SID=this.SID;a.SYM_GEO_TYPE=this.symGeometricType;a.SYM_NAME=
this.symName;a.CTRL_PTS=c;a.AMPLIFIER=this.amplifier;a.TEETH_SIZE=d;return a},createSymbol:function(c){try{var d;if(c.hasOwnProperty("CTRL_PTS"))d=c.CTRL_PTS;else throw"controlPoints not found";var a=new D(this.map.spatialReference),b=d[0],e=d[1];if(2===d.length)a.addPath([b,e]);else if(2<d.length){var f=d[2],g;d=[];var m=this._circleDrawEx(this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f));if(0<m.radius){g=this.CreateCircleSegmentFromThreePoints(m,this.map.toScreen(b),this.map.toScreen(e),
this.map.toScreen(f),60,this.map);d=g.geometry.paths[0];a.addPath(d.slice(0,25));a.addPath(d.slice(35,60));var h=new q(d[30][0],d[30][1],this.map.spatialReference),n,r=new q(d[25][0],d[25][1],this.map.spatialReference),v=new q(d[35][0],d[35][1],this.map.spatialReference),B=p._2PtLen(r,v);n=B/5;n>B/3.6&&(n=B/3.6);a.addPath(H.createI(h.x,h.y,n,this.map.spatialReference));new q(this.map.spatialReference);var w=p._2PtLen(e,h)/10,l=p.twoPtsAngle(g.backPoint,g.lastPoint),l=3.14159>l?l+2.35619:l-2.35619,
z=new q(e.x+w*Math.cos(l),e.y+w*Math.sin(l),this.map.spatialReference),l=p.twoPtsAngle(g.backPoint,g.lastPoint),l=3.14159<l?l+2.35619:l-2.35619,A=new q(e.x+w*Math.cos(l),e.y+w*Math.sin(l),this.map.spatialReference);a.addPath([z,e]);a.addPath([A,e]);var t=w*p.setDefault(c,"TEETH_SIZE",this.j),u=a.getExtent().getCenter();a.addPath(this.m(a.getPoint(0,1),a.getPoint(0,7),u,t));a.addPath(this.m(a.getPoint(0,9),a.getPoint(0,15),u,t));a.addPath(this.m(a.getPoint(0,17),a.getPoint(0,23),u,t));a.addPath(this.m(a.getPoint(1,
1),a.getPoint(1,7),u,t));a.addPath(this.m(a.getPoint(1,9),a.getPoint(1,15),u,t));a.addPath(this.m(a.getPoint(1,17),a.getPoint(1,23),u,t))}}return a}catch(C){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},H:function(c){c=c.mapPoint;var d=new r;d.CTRL_PTS=this._points.concat(c);d.TEETH_SIZE=this.j;this._tGraphic.setGeometry(this.createSymbol(d));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:d,currentMarker:this.o})},A:function(c){this._points.push(c.mapPoint.offset(0,
0));1==this._points.length&&(this.G=v(this.map,"mouse-move",n.hitch(this,this.H)));this.emit("onDrawClick",{currentPts:this._points});3==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(c){this._points.push(c.mapPoint);this.I()},I:function(){var c;new r;c=this.v(n.clone(this._points),this.j);this.u(this._tGraphic.geometry,c);this._clear();this._removeEvents()},u:function(c,d){if(c){var a=this.map.P,b;a&&(a.isWebMercator()?b=E.webMercatorToGeographic(c,
!0):4326===a.wkid&&(b=C.fromJson(c.toJson())));this.J(c,b,d)}},J:function(c,d,a){this.emit("onDrawEnd",{geometry:c,geographicGeometry:d,drawEssentials:a,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.C.remove();this.D.remove();this.G.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();
this._geometryType=null},K:function(){},_circleDrawEx:function(c,d,a){var b,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[c.x,c.y],[d.x,d.y],[a.x,a.y]];for(b=0;3>b;b++)e[b][0]=f[b][0],e[b][1]=f[b][1],e[b][2]=1;c=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][1],e[b][2]=1;d=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][0],e[b][2]=1;a=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*
f[b][1],e[b][1]=f[b][0],e[b][2]=f[b][1];e=this._determinantDrawEx(e,3);if(0==c)e=0;else{var g=.5*d/c,m=-.5*a/c;e=Math.sqrt(g*g+m*m+e/c)}return{radius:e,center:{x:g,y:m}}},_determinantDrawEx:function(c,d){var a,b,e,f,g,m=[[0,0,0],[0,0,0],[0,0,0]];if(2==d)g=c[0][0]*c[1][1]-c[1][0]*c[0][1];else for(e=g=0;e<d;e++){for(a=1;a<d;a++)for(b=f=0;b<d;b++)b!=e&&(m[a-1][f]=c[a][b],f++);g+=Math.pow(-1,e)*c[0][e]*this._determinantDrawEx(m,d-1)}return g},CreateCircleSegmentFromThreePoints:function(c,d,a,b,e,f){var g=
c.center,m=c.radius;c=[];d.x-=g.x;d.y-=g.y;a.x-=g.x;a.y-=g.y;b.x-=g.x;b.y-=g.y;d=Math.atan2(d.y,d.x);var h=Math.atan2(a.y,a.x);a=Math.atan2(b.y,b.x);d=0>d?2*Math.PI+d:d;h=0>h?2*Math.PI+h:h;a=0>a?2*Math.PI+a:a;b=Math.min(d,h);d=Math.max(d,h);h=d-b;if(a<b||a>d)h-=2*Math.PI;d=h/e;for(h=0;h<=e;h++)a=f.toMap({x:m*Math.cos(b+h*d)+g.x,y:m*Math.sin(b+h*d)+g.y}),c.push(a);f=new D(f.spatialReference);f.addPath(c);return{geometry:f,lastPoint:c[e],backPoint:c[e-5]}},m:function(c,d,a,b){var e=p.getMidPoint(c,
d);a=p.twoPtsAngle(a,e);b=new q(-1*b*Math.cos(a)+e.x,-1*b*Math.sin(a)+e.y,this.map.spatialReference);return[c,b,d]}})});
