define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(t,f,n,B,C,D,E,F,G,H,I,J,K,L,M,N,r,u,v,O,h,P,Q,R,p,S,w,T,l,U,V,z,q,m,A){return t([w],{declaredClass:"MilitarySymbology.Symbols.LandingZone",SID:"242304",symName:"Landing Zone",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.S=b;this.j;this._points=[];this._geometryType=null;this.m=1;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new r},init:function(a,b){this.j=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var c;new m;new z(this.map,
this.j);this.m=a.DRAW_TYPE;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.v(f.clone(a.CTRL_PTS),a.DRAW_TYPE),this.o(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.v(f.clone(a.CTRL_PTS),a.DRAW_TYPE),this._tGraphic.setGeometry(this.createSymbol(c)),this.o(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new r(null,this.j),this.map.graphics.add(this._tGraphic),this.D=p(this.map,"click",f.hitch(this,this.C)),this.F=
p(this.map,"dbl-click",f.hitch(this,this.G)))},v:function(a,b){var c=new m;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.DRAW_TYPE=b;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=b[b.length-1],e=b[0],d=new h(this.map.spatialReference);switch(a.DRAW_TYPE){case 1:d=this.N(b,e,c,a,d);break;case 2:d=this.O(b,e,c,a,d);break;case 3:d=
this.P(b,e,c,a,d)}return d}catch(g){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},I:function(a){a=a.mapPoint;var b=new m;b.CTRL_PTS=this._points.concat(a);b.DRAW_TYPE=this.m;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.j})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.H=p(this.map,"mouse-move",f.hitch(this,
this.I)));this.emit("onDrawClick",{currentPts:this._points});1==this.S&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.u());3===this.m&&2===this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.u())},G:function(a){this._points.push(a.mapPoint);this.u()},u:function(){var a;new m;a=this.v(f.clone(this._points),this.m);this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var c=this.map.V,e;c&&(c.isWebMercator()?
e=v.webMercatorToGeographic(a,!0):4326===c.wkid&&(e=u.fromJson(a.toJson())));this.K(a,e,b)}},K:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();
this._removeEvents();this._geometryType=null},U:function(){},J:function(a,b,c){var e={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var d=TweenMax.to(e,b,{bezier:a,ease:Linear.easeNone});a=[];var g;for(g=0;g<=b;g++)d.time(g),a.push({x:e.x,y:e.y});b=new h(c.spatialReference);b.addRing(a);return b},A:function(a,b,c){try{var e=a.getExtent().getCenter(),d,g=q._2PtLen(b,c);d=
g/10;d>g/3.6&&(d=g/3.6);var f=A.createLZ(e.x,e.y,d,e.spatialReference);for(b=0;b<=f.length-1;b++)a.addRing(f[b]);return a}catch(h){console.log("Can not create Inner Text")}},N:function(a,b,c){var e=new h(this.map.spatialReference),d=[];n.forEach(a,function(a){d.push({x:a.x,y:a.y})});d.push({x:b.x,y:b.y});e=this.J(d,130,this.map);return e=this.A(e,b,c)},O:function(a,b,c){var e=new h(this.map.spatialReference),d=[];n.forEach(a,function(a){d.push({x:a.x,y:a.y})});d.push({x:b.x,y:b.y});e.addRing(d);return e=
this.A(e,b,c)},P:function(a,b,c){var e=new h(this.map.spatialReference),d=[];n.forEach(a,function(a){d.push({x:a.x,y:a.y})});e.addRing(d);a=e.getExtent();e=new h(this.map.spatialReference);d=[];d.push(b);d.push(new l(a.xmin,a.ymin,this.map.spatialReference));d.push(c);d.push(new l(a.xmax,a.ymax,this.map.spatialReference));d.push(b);e.addRing(d);q._2PtLen(b,c);q._2PtLen(new l(a.xmin,a.ymin,this.map.spatialReference),new l(a.xmax,a.ymax,this.map.spatialReference));return e=this.A(e,b,c)}})});
