define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(D,e,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,w,E,F,B,W,X,Y,Z,m,aa,G,ba,p,ca,da,H,d,f,C){return D([G],{declaredClass:"MilitarySymbology.Symbols.ObstacleBypassEasy",SID:"270601",symName:"Obs Bypass Easy",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.U=b;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.D=this.F;this.G=this.H;this.A=this.v;this.u;this.N;this.K;this._tGraphic=new w},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();var c;new f;c=new H(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),c=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,c),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))c=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";
this._tGraphic.setGeometry(this.createSymbol(c));this.o(this._tGraphic.geometry,c);this._clear()}else this.u=c.on("drawEnd",e.hitch(this,this.P)),this.K=c.on("onBaseLineClick",e.hitch(this,this.O)),this.N=c.on("onBaseLineProgress",e.hitch(this,this.S)),c.init()},C:function(a,b){var c=new f;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.BASE_LN_PTS=b;c.AMPLIFIER=this.amplifier;return c},P:function(a){this.u.remove();
this._tGraphic=new w(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=m(this.map,"mouse-move",e.hitch(this,this.H));this.A=m(this.map,"click",e.hitch(this,this.v));this.D=m(this.map,"dbl-click",e.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var b=[];b.CTRL_PTS=a.currentGeometry;var c=new B(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:b,
currentMarker:a.currentMarker,isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=a.BASE_LN_PTS.startPt,z=a.BASE_LN_PTS.endPt,e=b[0],f=b[b.length-1];a=[];var h=[];if(void 0===c||void 0===z)throw"First Parameter of the Function is an Array with Start and End Point";var g=d.getMidPoint(c,z),n=new B(this.map.spatialReference);1<=b.length&&
(f=e);var q=d._2PtLen(g,z),l=Math.atan((g.y-f.y)/(g.x-f.x));switch(d.twoPtsRelationShip(g,f)){case "ne":l+=Math.PI/2;break;case "nw":l+=3*Math.PI/2;break;case "sw":l+=3*Math.PI/2;break;case "se":l+=Math.PI/2}var r={x:q*Math.cos(l)+g.x,y:q*Math.sin(l)+g.y},t={x:-1*q*Math.cos(l)+g.x,y:-1*q*Math.sin(l)+g.y};paths=[];paths=paths.concat(r,t);n.addPath(paths);1<=b.length&&(a.push(r),h.push(t));for(i=0;i<b.length;i++){var u=d._2PtLen(g,b[i]),v=d.angleInRadians(g,b[i]),m=new p(r.x+u*Math.cos(v),r.y+u*Math.sin(v),
this.map.spatialReference),A=new p(t.x+u*Math.cos(v),t.y+u*Math.sin(v),this.map.spatialReference);a.push(m);h.push(A)}n.addPath(a);n.addPath(h);n.addPath(C.arrowHead(a[a.length-1],d.ArrowFlanksLen(d._2PtLen(g,b[b.length-1]),d._2PtLen(m,A)),d.angleInRadians(a[a.length-2],a[a.length-1])));n.addPath(C.arrowHead(h[h.length-1],d.ArrowFlanksLen(d._2PtLen(g,b[b.length-1]),d._2PtLen(m,A)),d.angleInRadians(h[h.length-2],h[h.length-1])));return n}catch(w){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},
X:function(){return this.j},H:function(a){a=a.mapPoint;var b=new f;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);
this.I()},I:function(){var a;new f;a=this.C(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var c=this.map.Y,d;c&&(c.isWebMercator()?d=F.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=E.fromJson(a.toJson())));this.J(a,d,b)}},J:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=
null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(a,b,c,e){var f=[];e=1==e?d.toDegrees(c-15):d.toDegrees(c+15);c=new p(a.x+b*Math.cos(d.toRad(e)),a.y+b*Math.sin(d.toRad(e)),this.map.spatialReference);
b=new p(-1*b*Math.cos(d.toRad(e))+a.x,-1*b*Math.sin(d.toRad(e))+a.y,this.map.spatialReference);return f=f.concat(c,a,b)},W:function(){}})});
