define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(w,n,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,u,z,A,C,U,V,W,X,t,Y,D,Z,p,aa,ba,E,v,r,F){return w([D],{declaredClass:"MilitarySymbology.Symbols.Occupy",SID:"341700",symName:"Occupy",symGeometricType:"Area",constructor:function(a){this.map=a;this.j;this._points=[];this._geometryType=null;this.J;this.o=0;this.A=this.v;this.C=this.D;this.F=this.G;this._tGraphic=new u},init:function(a,d){this.j=d;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var c;new r;new E(this.map,this.j);
this.o=a.ECHLON;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.u(n.clone(a.CTRL_PTS),a.ECHLON),this.m(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.u(n.clone(a.CTRL_PTS),a.ECHLON),this._tGraphic.setGeometry(this.createSymbol(c)),this.m(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new u(null,this.j),this.map.graphics.add(this._tGraphic),this.A=t(this.map,"click",n.hitch(this,this.v)),this.C=t(this.map,
"dbl-click",n.hitch(this,this.D)))},O:function(a,d,c){var b=Math.sqrt(Math.pow(c.x-a.x,2)+Math.pow(c.y-a.y,2));c=Math.sqrt(Math.pow(c.x-d.x,2)+Math.pow(c.y-d.y,2));a=Math.sqrt(Math.pow(d.x-a.x,2)+Math.pow(d.y-a.y,2));return Math.acos((c*c+b*b-a*a)/(2*c*b))},N:function(a,d,c,b,e,f){return Math.atan2(d-f,a-e)-Math.atan2(b-f,c-e)},u:function(a,d){var c=new r;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=
this.amplifier;c.ECHLON=d;return c},createSymbol:function(a){try{var d;if(a.hasOwnProperty("CTRL_PTS"))d=a.CTRL_PTS;else throw"controlPoints not found";var c=new C(this.map.spatialReference),b=d[0],e=d[1];if(2===d.length)c.addPath([b,e]);else if(2<d.length){var f=d[2],g;a=[];var m=this._circleDrawEx(this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f));if(0<m.radius){g=this.CreateCircleSegmentFromThreePoints(m,this.map.toScreen(b),this.map.toScreen(e),this.map.toScreen(f),60,this.map);a=
g.geometry.paths[0];c.addPath(a.slice(0,25));c.addPath(a.slice(35,60));var h=new p(a[30][0],a[30][1],this.map.spatialReference),n,r=new p(a[25][0],a[25][1],this.map.spatialReference),t=new p(a[35][0],a[35][1],this.map.spatialReference),B=v._2PtLen(r,t);n=B/5;n>B/3.6&&(n=B/3.6);c.addPath(F.createO(h.x,h.y,n,this.map.spatialReference));new p(this.map.spatialReference);var q=v._2PtLen(e,h)/10,l=v.twoPtsAngle(g.backPoint,g.lastPoint),l=3.14159>l?l+2.35619:l-2.35619,u=new p(e.x+q*Math.cos(l),e.y+q*Math.sin(l),
this.map.spatialReference),w=new p(-1*q*Math.cos(l)+e.x,-1*q*Math.sin(l)+e.y,this.map.spatialReference),l=v.twoPtsAngle(g.backPoint,g.lastPoint),l=3.14159<l?l+2.35619:l-2.35619,z=new p(e.x+q*Math.cos(l),e.y+q*Math.sin(l),this.map.spatialReference),A=new p(-1*q*Math.cos(l)+e.x,-1*q*Math.sin(l)+e.y,this.map.spatialReference);c.addPath([w,e,u]);c.addPath([A,e,z])}}return c}catch(D){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},G:function(a){a=a.mapPoint;var d=new r;
d.CTRL_PTS=this._points.concat(a);d.ECHLON=this.o;this._tGraphic.setGeometry(this.createSymbol(d));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:d,currentMarker:this.j})},v:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.F=t(this.map,"mouse-move",n.hitch(this,this.G)));this.emit("onDrawClick",{currentPts:this._points});3==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.H())},D:function(a){this._points.push(a.mapPoint);
this.H()},H:function(){var a;new r;a=this.u(n.clone(this._points),this.o);this.m(this._tGraphic.geometry,a);this._clear();this._removeEvents()},m:function(a,d){if(a){var c=this.map.P,b;c&&(c.isWebMercator()?b=A.webMercatorToGeographic(a,!0):4326===c.wkid&&(b=z.fromJson(a.toJson())));this.I(a,b,d)}},I:function(a,d,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:d,drawEssentials:c,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;
this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.A.remove();this.C.remove();this.F.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},K:function(){},_circleDrawEx:function(a,d,c){var b,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[a.x,a.y],[d.x,d.y],[c.x,c.y]];for(b=0;3>b;b++)e[b][0]=f[b][0],e[b][1]=f[b][1],e[b][2]=1;a=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=
f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][1],e[b][2]=1;d=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][0],e[b][2]=1;c=this._determinantDrawEx(e,3);for(b=0;3>b;b++)e[b][0]=f[b][0]*f[b][0]+f[b][1]*f[b][1],e[b][1]=f[b][0],e[b][2]=f[b][1];e=this._determinantDrawEx(e,3);if(0==a)e=0;else{var g=.5*d/a,m=-.5*c/a;e=Math.sqrt(g*g+m*m+e/a)}return{radius:e,center:{x:g,y:m}}},_determinantDrawEx:function(a,d){var c,b,e,f,g,m=[[0,0,0],[0,0,0],[0,0,0]];if(2==
d)g=a[0][0]*a[1][1]-a[1][0]*a[0][1];else for(e=g=0;e<d;e++){for(c=1;c<d;c++)for(b=f=0;b<d;b++)b!=e&&(m[c-1][f]=a[c][b],f++);g+=Math.pow(-1,e)*a[0][e]*this._determinantDrawEx(m,d-1)}return g},CreateCircleSegmentFromThreePoints:function(a,d,c,b,e,f){var g=a.center,m=a.radius;a=[];d.x-=g.x;d.y-=g.y;c.x-=g.x;c.y-=g.y;b.x-=g.x;b.y-=g.y;d=Math.atan2(d.y,d.x);var h=Math.atan2(c.y,c.x);c=Math.atan2(b.y,b.x);d=0>d?2*Math.PI+d:d;h=0>h?2*Math.PI+h:h;c=0>c?2*Math.PI+c:c;b=Math.min(d,h);d=Math.max(d,h);h=d-b;
if(c<b||c>d)h-=2*Math.PI;d=h/e;for(h=0;h<=e;h++)c=f.toMap({x:m*Math.cos(b+h*d)+g.x,y:m*Math.sin(b+h*d)+g.y}),a.push(c);f=new C(f.spatialReference);f.addPath(a);return{geometry:f,lastPoint:a[e],backPoint:a[e-5]}}})});
