define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(A,e,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,p,F,G,B,Y,Z,aa,ba,m,ca,H,da,r,ea,fa,I,d,f,C){return A([H],{declaredClass:"MilitarySymbology.Symbols.Penetrate",SID:"341800",symName:"Penetrate",symGeometricType:"Area",constructor:function(a,c){this.map=a;this.U=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.D=this.F;this.G=this.H;this.A=this.v;this.u;this.N;this.K;this._tGraphic=new p},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var b;new f;b=new I(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.C(e.clone(a.CTRL_PTS),e.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(b));
this.o(this._tGraphic.geometry,b);this._clear()}else this.u=b.on("drawEnd",e.hitch(this,this.P)),this.K=b.on("onBaseLineClick",e.hitch(this,this.O)),this.N=b.on("onBaseLineProgress",e.hitch(this,this.S)),b.init()},C:function(a,c){var b=new f;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;return b},P:function(a){this.u.remove();this._tGraphic=new p(a.geometry,this.m);
this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=m(this.map,"mouse-move",e.hitch(this,this.H));this.A=m(this.map,"click",e.hitch(this,this.v));this.D=m(this.map,"dbl-click",e.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new B(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,currentMarker:a.currentMarker,
isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,e=a.BASE_LN_PTS.endPt,J=c[0],f=c[c.length-1];a=[];if(void 0===b||void 0===e)throw"First Parameter of the Function is an Array with Start and End Point";var g=d.getMidPoint(b,e),n=new B(this.map.spatialReference);1<=c.length&&(f=J);var t=d._2PtLen(g,e),l=Math.atan((g.y-
f.y)/(g.x-f.x));switch(d.twoPtsRelationShip(g,f)){case "ne":l+=Math.PI/2;break;case "nw":l+=3*Math.PI/2;break;case "sw":l+=3*Math.PI/2;break;case "se":l+=Math.PI/2}var m={x:t*Math.cos(l)+g.x,y:t*Math.sin(l)+g.y},z={x:-1*t*Math.cos(l)+g.x,y:-1*t*Math.sin(l)+g.y};paths=[];paths=paths.concat(m,z);n.addPath(paths);1<=c.length&&a.push(g);for(h=0;h<c.length;h++){var u=d._2PtLen(g,c[h]),v=d.angleInRadians(g,c[h]),p=new r(m.x+u*Math.cos(v),m.y+u*Math.sin(v),this.map.spatialReference),D=new r(z.x+u*Math.cos(v),
z.y+u*Math.sin(v),this.map.spatialReference),E=d._2PtLen(p,D);a.push(c[h])}n.addPath(C.arrowHeadBackward(g,d.ArrowFlanksLen(d._2PtLen(g,c[c.length-1]),d._2PtLen(p,D)),d.angleInRadians(g,a[1])));var q;q=d._fracture(a,10,this.map.spatialReference);n.paths=n.paths.concat(q.geometry.paths);for(var w,h=0;h<q.midPoints.length;h++)w=q.midPoints[h].len/2,w>E/3.6&&(w=E/3.6),n.addPath(C.createP(q.midPoints[h].midPt,w,40));return n}catch(A){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},
W:function(){return this.j},H:function(a){a=a.mapPoint;var c=new f;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);
this.I()},I:function(){var a;new f;a=this.C(e.clone(this._points),e.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.X,d;b&&(b.isWebMercator()?d=G.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=F.fromJson(a.toJson())));this.J(a,d,c)}},J:function(a,c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=
null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(a,c,b){var e=[];b+=15;var f=d.toDegrees(b);b=d.toDegrees(b-30);f=new r(a.x+c*Math.cos(d.toRad(f)),a.y+c*Math.sin(d.toRad(f)),this.map.spatialReference);
c=new r(a.x+c*Math.cos(d.toRad(b)),a.y+c*Math.sin(d.toRad(b)),this.map.spatialReference);return e=e.concat(f,a,c)}})});
