define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(t,e,u,B,C,D,E,F,G,H,I,J,K,L,M,N,q,v,w,m,O,P,Q,R,n,S,z,T,U,V,W,A,p,g,r){return t([z],{declaredClass:"MilitarySymbology.Symbols.PhaseLine",SID:"140300",symName:"Phase Line",symGeometricType:"Line",constructor:function(a,b){this.map=a;this.O=b;this.m;this._points=[];this.j=1;this._geometryType=null;this.A=this.v;this.C=this.D;this.F=this.G;this._tGraphic=new q},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var c;new g;new A(this.map,
this.m);this.j=p.setDefault(a,"DRAW_TYPE",this.j);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.u(e.clone(a.CTRL_PTS),this.j),this.o(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.u(e.clone(a.CTRL_PTS),this.j),this._tGraphic.setGeometry(this.createSymbol(c)),this.o(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new q(null,this.m),this.map.graphics.add(this._tGraphic),this.A=n(this.map,"click",e.hitch(this,
this.v)),this.C=n(this.map,"dbl-click",e.hitch(this,this.D)))},u:function(a,b){var c=new g;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_GEO_TYPE=this.symGeometricType;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;c.DRAW_TYPE=b;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var c=new m(this.map.spatialReference),d=b[0],h=b[b.length-1];switch(a.DRAW_TYPE){case 1:c=this.N(b);break;
case 2:c=this.K(b,d,h,a,c)}var f=p._2PtLen(d,h)/20,e=p.angleInRadians(d,h),l=r.createPL(-1*f*Math.cos(e)+d.x,-1*f*Math.sin(e)+d.y,f/2,map.spatialReference);for(a=0;a<l.length;a++)c.addPath(l[a]);l=r.createPL(f*Math.cos(e)+h.x,f*Math.sin(e)+h.y,f/2,map.spatialReference);for(a=0;a<l.length;a++)c.addPath(l[a]);return c}catch(g){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},G:function(a){a=a.mapPoint;var b=new g;b.CTRL_PTS=this._points.concat(a);b.DRAW_TYPE=this.j;
this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.F=n(this.map,"mouse-move",e.hitch(this,this.G)));this.emit("onDrawClick",{currentPts:this._points});1==this.O&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.H())},D:function(a){this._points.push(a.mapPoint);this.H()},
N:function(a){var b=new m(this.map.spatialReference);b.addPath(a);return b},K:function(a,b,c){var d=new m(this.map.spatialReference);if(2===a.length)d.addPath([c,b]);else if(2<a.length){var e=[];u.forEach(a,function(a){e.push({x:a.x,y:a.y})});d=this.I(e,100,this.map)}return d},I:function(a,b,c){var d={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var e=TweenMax.to(d,b,{bezier:a,
ease:Linear.easeNone});a=[];var f;for(f=0;f<=b;f++)e.time(f),a.push({x:d.x,y:d.y});b=new m(c.spatialReference);b.addPath(a);return b},H:function(){var a;new g;a=this.u(e.clone(this._points),this.j);this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,b){if(a){var c=this.map.S,d;c&&(c.isWebMercator()?d=w.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=v.fromJson(a.toJson())));this.J(a,d,b)}},J:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,
marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.A.remove();this.C.remove();this.F.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},P:function(){}})});
