define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(B,f,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,A,C,D,E,V,W,X,Y,w,Z,F,aa,p,ba,ca,G,d,l,z){return B([F],{declaredClass:"MilitarySymbology.Symbols.Screen",SID:"342203",symName:"Screen",symGeometricType:"Area",constructor:function(a){this.map=a;this.j;this._points=[];this._geometryType=null;this.o=0;this.A=this.v;this.C=this.D;this.F=this.G;this._tGraphic=new A},init:function(a,c){this.j=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var b;new l;new G(this.map,this.j);
this.o=a.ECHLON;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),b=this.u(f.clone(a.CTRL_PTS),a.ECHLON),this.m(this._tGraphic.geometry,b),this._clear()):a.hasOwnProperty("CTRL_PTS")?(b=this.u(f.clone(a.CTRL_PTS),a.ECHLON),this._tGraphic.setGeometry(this.createSymbol(b)),this.m(this._tGraphic.geometry,b),this._clear()):(this._tGraphic=new A(null,this.j),this.map.graphics.add(this._tGraphic),this.A=w(this.map,"click",f.hitch(this,this.v)),this.C=w(this.map,
"dbl-click",f.hitch(this,this.D)))},u:function(a,c){var b=new l;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.AMPLIFIER=this.amplifier;b.ECHLON=c;return b},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=new E(this.map.spatialReference),g=c[1],q=c[0];b.addPath(z.arrowHeadBackward(q,d.ArrowFlanksLen(d._2PtLen(q,g),d._2PtLen(q,g)),d.angleInRadians(q,
g)));var m=d.getMidPoint(q,g),n=d._2PtLen(q,m)/3,e=d.toDegrees(16),f=new p(m.x+n*Math.cos(this.toRad(e)),m.y+n*Math.sin(this.toRad(e)),this.map.spatialReference),e=d.angleInRadians(f,g),t=new p(f.x+2*n*Math.cos(e),f.y+2*n*Math.sin(e),this.map.spatialReference),h,u=d._2PtLen(q,g);h=u/25;h>u/3.6&&(h=u/3.6);var v=new p(t.x+1.5*h*Math.cos(e),t.y+1.5*h*Math.sin(e),this.map.spatialReference);b.addPath(z.createS(v.x,v.y,h,this.map.spatialReference));b.addPath([q,m,f,t]);if(3===c.length){var r=c[2],m=d.getMidPoint(r,
g),n=d._2PtLen(r,m)/3,e=d.toDegrees(-32),l=new p(m.x+n*Math.cos(d.toRad(e)),m.y+n*Math.sin(d.toRad(e)),this.map.spatialReference),e=d.angleInRadians(l,g),t=new p(l.x+2*n*Math.cos(e),l.y+2*n*Math.sin(e),this.map.spatialReference),u=d._2PtLen(r,g);h=u/25;h>u/3.6&&(h=u/3.6);v=new p(t.x+1.5*h*Math.cos(e),t.y+1.5*h*Math.sin(e),this.map.spatialReference);b.addPath(z.createS(v.x,v.y,h,this.map.spatialReference));b.addPath([r,m,l,t]);b.addPath(z.arrowHead(r,d.ArrowFlanksLen(d._2PtLen(g,r),d._2PtLen(g,r)),
d.angleInRadians(g,r)))}return b}catch(w){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},G:function(a){a=a.mapPoint;var c=new l;c.CTRL_PTS=this._points.concat(a);c.ECHLON=this.o;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.j})},v:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.F=w(this.map,"mouse-move",f.hitch(this,
this.G)));this.emit("onDrawClick",{currentPts:this._points});3==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.H())},D:function(a){this._points.push(a.mapPoint);this.H()},H:function(){var a;new l;a=this.u(f.clone(this._points),this.o);this.m(this._tGraphic.geometry,a);this._clear();this._removeEvents()},m:function(a,c){if(a){var b=this.map.O,d;b&&(b.isWebMercator()?d=D.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=C.fromJson(a.toJson())));this.I(a,d,c)}},I:function(a,
c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.A.remove();this.C.remove();this.F.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},K:function(){},J:function(a,c,b,d){var f=
[];b=new p(a.x+c*Math.cos(this.toRad(b)),a.y+c*Math.sin(this.toRad(b)),this.map.spatialReference);c=new p(a.x+c*Math.cos(this.toRad(d)),a.y+c*Math.sin(this.toRad(d)),this.map.spatialReference);return f=f.concat(b,a,c)},P:function(a){a=((180/Math.PI*a+360)%360).toFixed(1);isNaN(a)&&(a=0);return a},toRad:function(a){return Math.PI/180*a},N:function(a,c){return Math.atan2(c.y-a.y,c.x-a.x)}})});
