define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(B,c,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,A,C,D,E,W,X,Y,Z,p,aa,F,ba,v,ca,da,G,l,q,H){return B([F],{declaredClass:"MilitarySymbology.Symbols.SingleConcertina",SID:"290307",symName:"Wire Obs - Single Concertina",symGeometricType:"Line",isObstacle:"1",constructor:function(a,b){this.map=a;this.I=b;this.j;this._points=[];this._geometryType=null;this.v=this.u;this.A=this.C;this.D=this.F;this._tGraphic=new A},init:function(a,b){this.j=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var d;new q;new G(this.map,this.j);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.o(c.clone(a.CTRL_PTS)),this.m(this._tGraphic.geometry,d),this._clear()):a.hasOwnProperty("CTRL_PTS")?(d=this.o(c.clone(a.CTRL_PTS)),this._tGraphic.setGeometry(this.createSymbol(d)),this.m(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new A(null,this.j),this.map.graphics.add(this._tGraphic),this.v=p(this.map,"click",c.hitch(this,this.u)),this.A=p(this.map,
"dbl-click",c.hitch(this,this.C)))},o:function(a){var b=new q;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.AMPLIFIER=this.amplifier;b.J=this.isObstacle;return b},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var d=new E(this.map.spatialReference),m=l._2PtLen(b[0],b[b.length-1]),m=m/20,e,r,c=l._2PtLen(b[0],b[b.length-1])/7;e=c/7;e>c/3.6&&
(e=c/3.6);var q=l.getDashPts(b,[m,m]);for(a=0;a<q.length;a++)for(r=H.createEchelon("120",q[a],e),m=0;m<=r.length-1;m++)d.addPath(r[m]);var g=b[0],n=b[b.length-1];r=[];var f=Math.atan((g.y-n.y)/(g.x-n.x));switch(l.twoPtsRelationShip(g,n)){case "ne":f+=Math.PI/2;break;case "nw":f+=3*Math.PI/2;break;case "sw":f+=3*Math.PI/2;break;case "se":f+=Math.PI/2}var n=e,p={x:n*Math.cos(f)+g.x,y:n*Math.sin(f)+g.y},w={x:-1*n*Math.cos(f)+g.x,y:-1*n*Math.sin(f)+g.y};paths=[];paths=paths.concat(p,w);1<=b.length&&r.push(w);
for(a=0;a<b.length;a++){var t=l._2PtLen(g,b[a]),h=l.angleInRadians(g,b[a]),z=new v(p.x+t*Math.cos(h),p.y+t*Math.sin(h),this.map.spatialReference),u=new v(w.x+t*Math.cos(h),w.y+t*Math.sin(h),this.map.spatialReference);e=t/5;c=l._2PtLen(z,u);f=c/4;e>f&&(e=f);h=l.angleInRadians(z,u);new v(-1*e*Math.cos(h)+z.x,-1*e*Math.sin(h)+z.y,this.map.spatialReference);new v(e*Math.cos(h)+u.x,e*Math.sin(h)+u.y,this.map.spatialReference);r.push(u)}d.addPath(r);return d}catch(A){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},
F:function(a){a=a.mapPoint;var b=new q;b.CTRL_PTS=this._points.concat(a);this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.j})},u:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.D=p(this.map,"mouse-move",c.hitch(this,this.F)));this.emit("onDrawClick",{currentPts:this._points});1==this.I&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),
this.G())},C:function(a){this._points.push(a.mapPoint);this.G()},G:function(){var a;new q;a=this.o(c.clone(this._points));this.m(this._tGraphic.geometry,a);this._clear();this._removeEvents()},m:function(a,b){if(a){var d=this.map.N,c;d&&(d.isWebMercator()?c=D.webMercatorToGeographic(a,!0):4326===d.wkid&&(c=C.fromJson(a.toJson())));this.H(a,c,b)}},H:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);
this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.v.remove();this.A.remove();this.D.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},K:function(){}})});
