define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(A,m,w,F,G,H,I,J,K,L,M,N,O,P,Q,R,z,B,C,q,S,T,U,V,v,W,D,X,n,Y,Z,E,l,t,r){return A([D],{declaredClass:"MilitarySymbology.Symbols.StrongPoint",SID:"151203",symName:"Strong Pt",symGeometricType:"Area",constructor:function(b,a){this.map=b;this.Z=a;this.j;this._points=[];this._geometryType=null;this.$;this.C=0;this.A=1;this.D=0;this.o=5;this.u=2;this.I=this.H;this.J=this.K;this.N=this.O;this._tGraphic=new z},init:function(b,a){this.j=a;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var e;new t;new E(this.map,this.j);this.C=b.ECHELON;this.A=b.DRAW_TYPE;this.D=b.FACE_GAP;b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),e=this.F(m.clone(b.CTRL_PTS),b.ECHELON,b.DRAW_TYPE,b.FACE_GAP),this.v(this._tGraphic.geometry,e),this._clear()):b.hasOwnProperty("CTRL_PTS")?(e=this.F(m.clone(b.CTRL_PTS),b.ECHELON,b.DRAW_TYPE,b.FACE_GAP),this._tGraphic.setGeometry(this.createSymbol(e)),this.v(this._tGraphic.geometry,e),this._clear()):(this._tGraphic=new z(null,
this.j),this.map.graphics.add(this._tGraphic),this.I=v(this.map,"click",m.hitch(this,this.H)),this.J=v(this.map,"dbl-click",m.hitch(this,this.K)))},F:function(b,a,e,g){var d=new t;d.SCOPE=this;d.SYM_GEO_TYPE=this.symGeometricType;d.SID=this.SID;d.SYM_NAME=this.symName;d.CTRL_PTS=b;d.AMPLIFIER=this.amplifier;d.ECHELON=a;d.DRAW_TYPE=e;d.FACE_GAP=g;return d},m:function(b,a,e,g,d){var c=new n(b[0].x,b[0].y,this.map.spatialReference),f=b[b.length-1],h=l._2PtLen(c,f),h=h/a;a=l._2PtLen(c,f);1===d?(d=a/2,
d>a/2&&(d=a/2)):2===d?(d=a/12,d>a/12&&(d=a/12)):(d=a/10,d>a/10&&(d=a/10));b=l.getDashPts(b,[h,h],5);for(a=0;a<b.length;a+=2)h=l.twoPtsAngle(b[a],e),h+=Math.PI,g.addPath([new n(d*Math.cos(h)+b[a].x,d*Math.sin(h)+b[a].y,this.map.spatialReference),b[a]]);return g},createSymbol:function(b){try{var a;if(b.hasOwnProperty("CTRL_PTS"))a=b.CTRL_PTS;else throw"controlPoints not found";var e=a[a.length-1],g=a[0],d=new q(this.map.spatialReference);switch(b.DRAW_TYPE){case 1:d=this.V(a,g,e,b,d);break;case 2:d=
this.U(a,g,e,b,d);break;case 3:d=this.W(a,g,e,b,d)}return d}catch(c){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},O:function(b){b=b.mapPoint;var a=new t;a.CTRL_PTS=this._points.concat(b);a.ECHELON=this.C;a.DRAW_TYPE=this.A;a.FACE_GAP=this.D;this._tGraphic.setGeometry(this.createSymbol(a));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:a,currentMarker:this.j})},H:function(b){this._points.push(b.mapPoint.offset(0,0));1==
this._points.length&&(this.N=v(this.map,"mouse-move",m.hitch(this,this.O)));this.emit("onDrawClick",{currentPts:this._points});1==this.Z&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.P())},K:function(b){this._points.push(b.mapPoint);this.P()},P:function(){var b;new t;b=this.F(m.clone(this._points),this.C,this.A,this.D);this.v(this._tGraphic.geometry,b);this._clear();this._removeEvents()},v:function(b,a){if(b){var e=this.map.oa,g;e&&(e.isWebMercator()?g=C.webMercatorToGeographic(b,
!0):4326===e.wkid&&(g=B.fromJson(b.toJson())));this.S(b,g,a)}},S:function(b,a,e){this.emit("onDrawEnd",{geometry:b,geographicGeometry:a,drawEssentials:e,marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.I.remove();this.J.remove();this.N.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();
this._geometryType=null},ea:function(){},G:function(b,a,e){var g={x:b[0].x,y:b[0].y};b[b.length-1].x===b[b.length-2].x&&b[b.length-1].y===b[b.length-2].y&&b.pop();b[b.length-1].x===b[b.length-2].x&&b[b.length-1].y===b[b.length-2].y&&b.pop();var d=TweenMax.to(g,a,{bezier:b,ease:Linear.easeNone});b=[];var c;for(c=0;c<=a;c++)d.time(c),b.push({x:g.x,y:g.y});a=new q(e.spatialReference);a.addPath(b);return a},Y:function(b,a){var e,g,d,c,f,h;if(1<a.length){for(c=1;c<a.length;c++){a[c].x!=a[c-1].x?(f=(a[c].y-
a[c-1].y)/(a[c].x-a[c-1].x),f=Math.abs(f*b.x+(a[c].y-f*a[c].x)-b.y)/Math.sqrt(f*f+1)):f=Math.abs(b.x-a[c].x);var l=Math.pow(a[c].y-a[c-1].y,2)+Math.pow(a[c].x-a[c-1].x,2),u=Math.pow(a[c].y-b.y,2)+Math.pow(a[c].x-b.x,2),n=Math.pow(a[c-1].y-b.y,2)+Math.pow(a[c-1].x-b.x,2),p=Math.pow(f,2),m=u-p+n-p;m>l&&(f=Math.sqrt(Math.min(u,n)));if(null==e||e>f)m>l?n<u?(g=0,d=1):(d=0,g=1):(g=Math.sqrt(n-p)/Math.sqrt(l),d=Math.sqrt(u-p)/Math.sqrt(l)),e=f,h=c}e=a[h-1].y-a[h].y;c=a[h-1].x-(a[h-1].x-a[h].x)*g;f=a[h-1].y-
e*g}return{x:c,y:f,index:h,fTo:g,fFrom:d}},X:function(b,a){var e,g,d,c,f,h;if(1<a.length){for(c=1;c<a.length;c++){a[c][0]!=a[c-1][0]?(f=(a[c][1]-a[c-1][1])/(a[c][0]-a[c-1][0]),f=Math.abs(f*b.x+(a[c][1]-f*a[c][0])-b.y)/Math.sqrt(f*f+1)):f=Math.abs(b.x-a[c][0]);var l=Math.pow(a[c][1]-a[c-1][1],2)+Math.pow(a[c][0]-a[c-1][0],2),n=Math.pow(a[c][1]-b.y,2)+Math.pow(a[c][0]-b.x,2),m=Math.pow(a[c-1][1]-b.y,2)+Math.pow(a[c-1][0]-b.x,2),p=Math.pow(f,2),q=n-p+m-p;q>l&&(f=Math.sqrt(Math.min(n,m)));if(null==e||
e>f)q>l?m<n?(g=0,d=1):(d=0,g=1):(g=Math.sqrt(m-p)/Math.sqrt(l),d=Math.sqrt(n-p)/Math.sqrt(l)),e=f,h=c}e=a[h-1][1]-a[h][1];c=a[h-1][0]-(a[h-1][0]-a[h][0])*g;f=a[h-1][1]-e*g}return{x:c,y:f,index:h,fTo:g,fFrom:d}},getPolylineCenter:function(b){var a=l.getLastPtFromPoly(b);b=b.getPoint(0,0);return new n((a.x+b.x)/2,(a.y+b.y)/2)},V:function(b,a,e,g){var d=new q(this.map.spatialReference);if(2===b.length)d.addPath([e,a]);else if(2<b.length){var c=[];w.forEach(b,function(a){c.push({x:a.x,y:a.y})});var d=
this.G(c,100,this.map),d=this.m(l.createPolyFromObject(d.paths[0]),5,this.getPolylineCenter(d),d,1),f=d.paths[0][d.paths[0].length-1];b=l.getMidPoint(new n(f[0],f[1],this.map.spatialReference),d.getPoint(0,0));var f=l._2PtLen(new n(f[0],f[1],this.map.spatialReference),d.getPoint(0,0)),h=f/10;h>f/3.6&&(h=f/3.6);a=r.createEchelon(g.ECHELON,b,h,l.angleInRadians(a,e));for(e=0;e<=a.length-1;e++)d.addPath(a[e])}return d},U:function(b,a,e,g){var d=new q(this.map.spatialReference),c=[];if(2===b.length)d.addPath([e,
a]);else if(2<b.length){var f=[];w.forEach(b,function(a){f.push({x:a.x,y:a.y})});f.push({x:a.x,y:a.y});c=this.G(f,100,this.map).paths[0];b=this.X(e,c);a=b.index-this.o-Math.floor(l.setDefault(g,"FACE_GAP",this.o)/2);e=b.index+this.o+Math.floor(l.setDefault(g,"FACE_GAP",this.o)/2);100<=e&&(e=100);d.addPath(c.slice(0,a));d.addPath(c.slice(e,101));d=this.m(l.createPolyFromObject(d.paths[0]),5,this.getPolylineCenter(d),d,2);d=this.m(l.createPolyFromObject(d.paths[1]),5,this.getPolylineCenter(d),d,2);
a=new n(c[a][0],c[a][1],this.map.spatialReference);var c=new n(c[e][0],c[e][1],this.map.spatialReference),h;e=l._2PtLen(a,c);var m=e/10;m>e/3.6&&(m=e/3.6);isNaN(m)?m=h:h=m;g=r.createEchelon(g.ECHELON,b,m,l.angleInRadians(a,c));for(h=0;h<=g.length-1;h++)d.addPath(g[h])}return d},W:function(b,a,e,g){var d=new q(this.map.spatialReference);if(2===b.length){a=this.map.toScreen(a);var c=this.map.toScreen(e);b=c.x-a.x;c=c.y-a.y;b=r.createEllipse({center:a,longAxis:b,shortAxis:c,numberOfPoints:60,map:this.map});
d.addPath(b)}else if(2<b.length){b=b[1];a=this.map.toScreen(a);c=this.map.toScreen(b);b=c.x-a.x;c=c.y-a.y;b=r.createEllipse({center:a,longAxis:b,shortAxis:c,numberOfPoints:60,map:this.map});e=this.Y(e,b);a=e.index-this.u-Math.floor(l.setDefault(g,"FACE_GAP",this.u)/2);c=e.index+this.u+Math.floor(l.setDefault(g,"FACE_GAP",this.u)/2);0>=a&&(a=0);60<=c&&(c=60);d.addPath(b.slice(0,a));d.addPath(b.slice(c,61));d=this.m(l.createPolyFromObject(d.paths[0]),5,this.getPolylineCenter(d),d,3);d=this.m(l.createPolyFromObject(d.paths[1]),
5,this.getPolylineCenter(d),d,3);a=new n(b[a].x,b[a].y,this.map.spatialReference);b=new n(b[c].x,b[c].y,this.map.spatialReference);var c=l._2PtLen(a,b),f=c/10;f>c/3.6&&(f=c/3.6);isNaN(f)&&(f=void 0);g=r.createEchelon(g.ECHELON,e,f,l.angleInRadians(a,b));for(e=0;e<=g.length-1;e++)d.addPath(g[e])}return d}})});
