define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(t,h,z,E,F,G,H,I,J,K,L,M,N,O,P,Q,r,A,B,R,u,S,T,U,p,V,C,W,X,Y,Z,D,m,q,v){return t([C],{declaredClass:"MilitarySymbology.Symbols.SupportingAttack",SID:"151404",symName:"Sp Attk",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.N=b;this.o;this._points=[];this._geometryType=null;this.O;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new r;this.j=.05;this.m=.07},init:function(a,b){this.o=b;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
this.m=m.setDefault(a,"HEAD_RATIO",.07);this.j=m.setDefault(a,"TAIL_FACTOR",.05);var c;new q;new D(this.map,this.o);a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),c=this.v(h.clone(a.CTRL_PTS),this.m,this.j),this.u(this._tGraphic.geometry,c),this._clear()):a.hasOwnProperty("CTRL_PTS")?(c=this.v(h.clone(a.CTRL_PTS),this.m,this.j),this._tGraphic.setGeometry(this.createSymbol(c)),this.u(this._tGraphic.geometry,c),this._clear()):(this._tGraphic=new r(null,this.o),
this.map.graphics.add(this._tGraphic),this.D=p(this.map,"click",h.hitch(this,this.C)),this.F=p(this.map,"dbl-click",h.hitch(this,this.G)))},v:function(a,b,c){var d=new q;d.SCOPE=this;d.SYM_GEO_TYPE=this.symGeometricType;d.SID=this.SID;d.SYM_GEO_TYPE=this.symGeometricType;d.SYM_NAME=this.symName;d.CTRL_PTS=a;d.AMPLIFIER=this.amplifier;d.HEAD_RATIO=b;d.TAIL_FACTOR=c;return d},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";m.setDefault(a,
"HEAD_RATIO",5);if(2>=b.length){var c=b[0],d=b[b.length-1],e=m._2PtLen(c,d),f=Math.atan((c.y-d.y)/(c.x-d.x));switch(m.twoPtsRelationShip(c,d)){case "ne":f+=Math.PI/2;break;case "nw":f+=3*Math.PI/2;break;case "sw":f+=3*Math.PI/2;break;case "se":f+=Math.PI/2}var n={x:this.j*e*Math.cos(f)+c.x,y:this.j*e*Math.sin(f)+c.y},w={x:-1*this.j*e*Math.cos(f)+c.x,y:-1*this.j*e*Math.sin(f)+c.y},l=(1-this.m)*e,h={x:this.j*l*Math.cos(f)+c.x,y:this.j*l*Math.sin(f)+c.y},q={x:-1*this.j*l*Math.cos(f)+c.x,y:-1*this.j*
l*Math.sin(f)+c.y},p=new u(this.map.spatialReference),g=[];g.push(n);g=g.concat(this.CreateArrowHeadPathEx(h,d,q,e,this.m,15));g.push(q);u.prototype.isClockwise(g)||this.W||(console.debug(this.declaredClass+" :  Polygons drawn in anti-clockwise direction will be reversed to be clockwise."),g.reverse())}else{a=[];c=[];p=new u(this.map.spatialReference);d=b[b.length-1];tempArray=[];a=[];c=[];z.forEach(b,function(a){tempArray.push({x:a.x,y:a.y})});angleArray=m._vertexAngle(tempArray);var r=m._ptCollectionLen(tempArray,
0);b=0;for(e=tempArray.length-1;b<e;b++)l=m._ptCollectionLen(tempArray,b),l+=r/2.4,n={x:this.j*l*Math.cos(angleArray[b])+tempArray[b].x,y:this.j*l*Math.sin(angleArray[b])+tempArray[b].y},w={x:-1*this.j*l*Math.cos(angleArray[b])+tempArray[b].x,y:-1*this.j*l*Math.sin(angleArray[b])+tempArray[b].y},a.push(n),c.push(w);a.push({x:d.x,y:d.y});c.push({x:d.x,y:d.y});a=v.CreateBezierPathPCOnly(a,70);a.splice(Math.floor(70*(1-this.m)),Number.MAX_VALUE);c=v.CreateBezierPathPCOnly(c,70);c.splice(Math.floor(70*
(1-this.m)),Number.MAX_VALUE);var t=this.CreateArrowHeadPathEx(a[a.length-1],d,c[c.length-1],m._ptCollectionLen(tempArray,0),this.m,15),g=[],g=g.concat(a),g=g.concat(t),g=g.concat(c.reverse())}p.addRing(g);return p}catch(aa){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},V:function(){return this.A},I:function(a){a=a.mapPoint;var b=new q;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.A;b.BK_LN_DIST_RATIO=this.U;b.BK_LN_ANGL_RATIO=this.S;this._tGraphic.setGeometry(this.createSymbol(b));
this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.o})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.H=p(this.map,"mouse-move",h.hitch(this,this.I)));this.emit("onDrawClick",{currentPts:this._points});1==this.N&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.J())},G:function(a){this._points.push(a.mapPoint);this.J()},J:function(){var a;new q;a=this.v(h.clone(this._points),
this.m,this.j);this.u(this._tGraphic.geometry,a);this._clear();this._removeEvents()},u:function(a,b){if(a){var c=this.map.X,d;c&&(c.isWebMercator()?d=B.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=A.fromJson(a.toJson())));this.K(a,d,b)}},K:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,marker:this.o})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);
this._points=[];this.A=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},P:function(){},CreateArrowHeadPathEx:function(a,b,c,d,e,f,n){e=d*e;d=1.07*e;a=m.twoPtsAngle(b,a);c=m.twoPtsAngle(b,c);var h=Math.abs(a-c)/2;Math.abs(a-c)>1.88*Math.PI&&(h+=Math.PI);var l=Math.asin(e*Math.sin(h+f/180*Math.PI)/Math.sqrt(e*e+d*d-2*d*e*Math.cos(h+
f/180*Math.PI)))+f/180*Math.PI;n=0==n||void 0==n?e*Math.sin(Math.PI-l-h)/Math.sin(l):0;e=[];e.push({x:b.x+n*Math.cos(a),y:b.y+n*Math.sin(a)});e.push({x:b.x+d*Math.cos(a-f/180*Math.PI),y:b.y+d*Math.sin(a-f/180*Math.PI)});e.push(b);e.push({x:b.x+d*Math.cos(c+f/180*Math.PI),y:b.y+d*Math.sin(c+f/180*Math.PI)});e.push({x:b.x+n*Math.cos(c),y:b.y+n*Math.sin(c)});return e}})});
