define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials".split(" "),
function(D,d,O,P,Q,R,S,T,U,V,W,X,Y,Z,aa,ba,C,J,L,E,ca,da,ea,fa,w,ga,M,ha,q,ia,ja,N,c,l){return D([M],{declaredClass:"MilitarySymbology.Symbols.SupportByFirePosition",SID:"152100",symName:"BOF",symGeometricType:"Area",constructor:function(a,b){this.map=a;this.Y=b;this.m;this._points=[];this.j=[];this._geometryType=null;this.u;this.o;this.v;this.I=this.J;this.K=this.N;this.H=this.G;this.C;this.U;this.S;this._tGraphic=new C},init:function(a,b){this.m=b;this.map.navigationManager.setImmediateClick(!1);
this.map.disableDoubleClickZoom();this.u=c.setDefault(a,"BK_LN_DIST_RATIO",5);this.o=c.setDefault(a,"BK_LN_ANGL_RATIO",5);this.v=c.setDefault(a,"FRNT_LN_ANGL_RATIO",5);var e;new l;e=new N(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),e=this.D(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS),this.u,this.o,this.v),this.A(this._tGraphic.geometry,e),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))e=
this.D(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS),this.u,this.o,this.v);else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(e));this.A(this._tGraphic.geometry,e);this._clear()}else this.C=e.on("drawEnd",d.hitch(this,this.W)),this.S=e.on("onBaseLineClick",d.hitch(this,this.V)),this.U=e.on("onBaseLineProgress",d.hitch(this,this.X)),e.init()},D:function(a,b,e,c,d){var f=new l;f.SCOPE=this;f.SYM_GEO_TYPE=this.symGeometricType;
f.SID=this.SID;f.SYM_GEO_TYPE=this.symGeometricType;f.SYM_NAME=this.symName;f.BK_LN_DIST_RATIO=e;f.BK_LN_ANGL_RATIO=c;f.FRNT_LN_ANGL_RATIO=d;f.CTRL_PTS=a;f.BASE_LN_PTS=b;f.AMPLIFIER=this.amplifier;return f},W:function(a){this.C.remove();this._tGraphic=new C(a.geometry,this.m);this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.K=w(this.map,"mouse-move",d.hitch(this,this.N));this.H=w(this.map,"click",d.hitch(this,this.G));this.I=w(this.map,"dbl-click",d.hitch(this,this.J));this.emit("onBaseLineDrawEnd",
{currentPts:a.geometry.controlPoints})},X:function(a){var b=[];b.CTRL_PTS=a.currentGeometry;var c=new E(map.spatialReference);c.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:c,currentDrawEssentials:b,currentMarker:a.currentMarker,isBaseLine:!0})},V:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var b,e,d,K;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";e=c.setDefault(a,"BK_LN_DIST_RATIO",
5);d=c.setDefault(a,"BK_LN_ANGL_RATIO",5);K=c.setDefault(a,"FRNT_LN_ANGL_RATIO",5);var f=a.BASE_LN_PTS.startPt,l=a.BASE_LN_PTS.endPt,w=b[0],v=b[b.length-1];a=[];var z=[];if(void 0===f||void 0===l)throw"First Parameter of the Function is an Array with Start and End Point";var h=c.getMidPoint(f,l),r=new E(this.map.spatialReference);1<=b.length&&(v=w);var p=c._2PtLen(h,l),m=Math.atan((h.y-v.y)/(h.x-v.x));switch(c.twoPtsRelationShip(h,v)){case "ne":m+=Math.PI/2;break;case "nw":m+=3*Math.PI/2;break;case "sw":m+=
3*Math.PI/2;break;case "se":m+=Math.PI/2}var f=p,t={x:f*Math.cos(m)+h.x,y:f*Math.sin(m)+h.y},u={x:-1*f*Math.cos(m)+h.x,y:-1*f*Math.sin(m)+h.y};paths=[];paths=paths.concat(t,u);r.addPath(paths);1<=b.length&&(a.push(t),z.push(u));for(m=0;m<b.length;m++){var n=c._2PtLen(h,b[m]),g=c.angleInRadians(h,b[m]),A=new q(t.x+n*Math.cos(g),t.y+n*Math.sin(g),this.map.spatialReference),B=new q(u.x+n*Math.cos(g),u.y+n*Math.sin(g),this.map.spatialReference),p=n/K,g=c.angleInRadians(A,B),F=new q(-1*p*Math.cos(g)+A.x,
-1*p*Math.sin(g)+A.y,this.map.spatialReference),G=new q(p*Math.cos(g)+B.x,p*Math.sin(g)+B.y,this.map.spatialReference);a.push(F);z.push(G)}r.addPath(a);r.addPath(z);r.addPath(this.F(F,c.ArrowFlanksLen(c._2PtLen(h,b[b.length-1]),c._2PtLen(A,B)),c.angleInRadians(a[a.length-2],F)));r.addPath(this.F(G,c.ArrowFlanksLen(c._2PtLen(h,b[b.length-1]),c._2PtLen(A,B)),c.angleInRadians(z[z.length-2],G)));var n=c._2PtLen(h,v),g=c.angleInRadians(h,v),n=n/e,H=new q(t.x-n*Math.cos(g),t.y-n*Math.sin(g),this.map.spatialReference),
I=new q(u.x-n*Math.cos(g),u.y-n*Math.sin(g),this.map.spatialReference),p=n/d,g=c.angleInRadians(H,I),C=new q(-1*p*Math.cos(g)+H.x,-1*p*Math.sin(g)+H.y,this.map.spatialReference),D=new q(p*Math.cos(g)+I.x,p*Math.sin(g)+I.y,this.map.spatialReference);paths=[];paths=paths.concat(t,C);r.addPath(paths);paths=[];paths=paths.concat(u,D);r.addPath(paths);return r}catch(J){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},$:function(){return this.j},N:function(a){a=a.mapPoint;
new E(this.map.spatialReference);var b=new l;b.CTRL_PTS=this._points.concat(a);b.BASE_LN_PTS=this.j;b.BK_LN_DIST_RATIO=this.u;b.BK_LN_ANGL_RATIO=this.o;b.FRNT_LN_ANGL_RATIO=this.v;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.m})},G:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.Y&&1==this._points.length&&(this.emit("onDrawClick",
{currentPts:this._points}),this.O())},J:function(a){this._points.push(a.mapPoint);this.O()},O:function(){var a;new l;a=this.D(d.clone(this._points),d.clone(this.j),this.u,this.o,this.v);this.A(this._tGraphic.geometry,a);this._clear();this._removeEvents()},A:function(a,b){if(a){var c=this.map.ea,d;c&&(c.isWebMercator()?d=L.webMercatorToGeographic(a,!0):4326===c.wkid&&(d=J.fromJson(a.toJson())));this.P(a,d,b)}},P:function(a,b,c){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:c,
marker:this.m})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.H.remove();this.I.remove();this.K.remove();this.C.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},F:function(a,b,e){var d=[];e+=15;var l=c.toDegrees(e);
e=c.toDegrees(e-30);l=new q(a.x+b*Math.cos(c.toRad(l)),a.y+b*Math.sin(c.toRad(l)),this.map.spatialReference);b=new q(a.x+b*Math.cos(c.toRad(e)),a.y+b*Math.sin(c.toRad(e)),this.map.spatialReference);return d=d.concat(l,a,b)},Z:function(){}})});
