define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(L,d,Q,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,da,G,M,N,K,ea,fa,ga,ha,u,ia,O,ja,w,ka,la,P,f,m,D){return L([O],{declaredClass:"MilitarySymbology.Symbols.UARoute",SID:"170700",symName:"UAV Route",symGeometricType:"Line",constructor:function(a,c){this.map=a;this.U=c;this.m;this._points=[];this.j=[];this._geometryType=null;this.A=this.v;this.D=this.F;this.G=this.H;this.A=this.v;this.u;this.N;this.K;this._tGraphic=new G},init:function(a,c){this.m=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var b;new m;b=new P(this.map,this.m);if(a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("BASE_LN_PTS")&&a.hasOwnProperty("GEOM"))this._tGraphic.setGeometry(a.GEOM),b=this.C(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS)),this.o(this._tGraphic.geometry,b),this._clear();else if(a.hasOwnProperty("CTRL_PTS")){if(a.hasOwnProperty("BASE_LN_PTS"))b=this.C(d.clone(a.CTRL_PTS),d.clone(a.BASE_LN_PTS));else throw"Control Points and Baseline or Distance is required to create symbol non-interactively";this._tGraphic.setGeometry(this.createSymbol(b));
this.o(this._tGraphic.geometry,b);this._clear()}else this.u=b.on("drawEnd",d.hitch(this,this.P)),this.K=b.on("onBaseLineClick",d.hitch(this,this.O)),this.N=b.on("onBaseLineProgress",d.hitch(this,this.S)),b.init()},C:function(a,c){var b=new m;b.SCOPE=this;b.SYM_GEO_TYPE=this.symGeometricType;b.SID=this.SID;b.SYM_GEO_TYPE=this.symGeometricType;b.SYM_NAME=this.symName;b.CTRL_PTS=a;b.BASE_LN_PTS=c;b.AMPLIFIER=this.amplifier;return b},P:function(a){this.u.remove();this._tGraphic=new G(a.geometry,this.m);
this.map.graphics.add(this._tGraphic);this.j=a.geometry._baseLine;this.G=u(this.map,"mouse-move",d.hitch(this,this.H));this.A=u(this.map,"click",d.hitch(this,this.v));this.D=u(this.map,"dbl-click",d.hitch(this,this.F));this.emit("onBaseLineDrawEnd",{currentPts:a.geometry.controlPoints})},S:function(a){var c=[];c.CTRL_PTS=a.currentGeometry;var b=new K(map.spatialReference);b.addPath(a.currentGeometry);this.emit("onDrawProgress",{currentGeometry:b,currentDrawEssentials:c,currentMarker:a.currentMarker,
isBaseLine:!0})},O:function(a){this.emit("onDrawClick",{currentPts:a.currentGeometry,isBaseLine:!0})},createSymbol:function(a){try{var c;if(a.hasOwnProperty("CTRL_PTS"))c=a.CTRL_PTS;else throw"controlPoints not found";var b=a.BASE_LN_PTS.startPt,d=a.BASE_LN_PTS.endPt,g=c[0],m=c[c.length-1];a=[];var u=[],v=[];if(void 0===b||void 0===d)throw"First Parameter of the Function is an Array with Start and End Point";var h=f.getMidPoint(b,d),q=new K(this.map.spatialReference);1<=c.length&&(m=g);var r=f._2PtLen(h,
d),t=Math.atan((h.y-m.y)/(h.x-m.x));switch(f.twoPtsRelationShip(h,m)){case "ne":t+=Math.PI/2;break;case "nw":t+=3*Math.PI/2;break;case "sw":t+=3*Math.PI/2;break;case "se":t+=Math.PI/2}var g=r,H={x:g*Math.cos(t)+h.x,y:g*Math.sin(t)+h.y},I={x:-1*g*Math.cos(t)+h.x,y:-1*g*Math.sin(t)+h.y};1<=c.length&&(a.push(H),u.push(I),v.push(h));for(var E=f._2PtLen(d,b),n,e=0;e<c.length;e++){var A=f._2PtLen(h,c[e]),p=f.angleInRadians(h,c[e]),B=new w(H.x+A*Math.cos(p),H.y+A*Math.sin(p),this.map.spatialReference),C=
new w(I.x+A*Math.cos(p),I.y+A*Math.sin(p),this.map.spatialReference),r=A/5,J=f._2PtLen(B,C),b=J/4;r>b&&(r=b);p=f.angleInRadians(B,C);new w(-1*r*Math.cos(p)+B.x,-1*r*Math.sin(p)+B.y,this.map.spatialReference);new w(r*Math.cos(p)+C.x,r*Math.sin(p)+C.y,this.map.spatialReference);a.push(B);u.push(C);v.push(c[e]);q.addPath(this.createACP(c[e],E/2));n=D.createACP(c[e].x,c[e].y,E/10,c[e].spatialReference);for(var l=0;l<=n.length-1;l++)q.addPath(n[l])}q.addPath(a);q.addPath(u);q.addPath(this.createACP(v[0],
E/2));n=D.createACP(v[0].x,v[0].y,E/10,v[0].spatialReference);for(l=0;l<=n.length-1;l++)q.addPath(n[l]);var z;z=f._fracture(v,10,this.map.spatialReference);for(var F,e=0;e<z.midPoints.length;e++)for(F=z.midPoints[e].len/2,F>J/3.6&&(F=J/3.6),n=D.createUA(z.midPoints[e].midPt.x,z.midPoints[e].midPt.y,F,z.midPoints[e].midPt.spatialReference),l=0;l<=n.length-1;l++)q.addPath(n[l]);return q}catch(G){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},createACP:function(a,
c){return D.createCircle(a,c,60)},Z:function(){return[]},X:function(){return this.j},H:function(a){a=a.mapPoint;var c=new m;c.CTRL_PTS=this._points.concat(a);c.BASE_LN_PTS=this.j;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.m})},v:function(a){this._points.push(a.mapPoint.offset(0,0));this.emit("onDrawClick",{currentPts:this._points});1==this.U&&1==this._points.length&&(this.emit("onDrawClick",
{currentPts:this._points}),this.I())},F:function(a){this._points.push(a.mapPoint);this.I()},I:function(){var a;new m;a=this.C(d.clone(this._points),d.clone(this.j));this.o(this._tGraphic.geometry,a);this._clear();this._removeEvents()},o:function(a,c){if(a){var b=this.map.Y,d;b&&(b.isWebMercator()?d=N.webMercatorToGeographic(a,!0):4326===b.wkid&&(d=M.fromJson(a.toJson())));this.J(a,d,c)}},J:function(a,c,b){this.emit("onDrawEnd",{geometry:a,geographicGeometry:c,drawEssentials:b,marker:this.m})},_clear:function(){this._tGraphic&&
this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[];this.j=[];this._curvePt1=this._curvePt2=null},_removeEvents:function(){this.A.remove();this.D.remove();this.G.remove();this.u.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(a,c,b){var d=[];b+=15;var g=f.toDegrees(b);b=f.toDegrees(b-30);g=new w(a.x+c*Math.cos(f.toRad(g)),
a.y+c*Math.sin(f.toRad(g)),this.map.spatialReference);c=new w(a.x+c*Math.cos(f.toRad(b)),a.y+c*Math.sin(f.toRad(b)),this.map.spatialReference);return d=d.concat(g,a,c)},W:function(){}})});
