define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/PictureFillSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(t,f,n,B,C,D,E,F,G,H,I,J,K,L,M,u,N,q,v,w,O,g,P,Q,R,p,S,z,T,l,U,V,A,r,m){return t([z],{declaredClass:"MilitarySymbology.Symbols.UnspecifiedMine",SID:"270706",symName:"Minefield - Unspecified Mine",symGeometricType:"Area",isObstacle:"1",constructor:function(a,b){this.map=a;this.S=b;this.j;this._points=[];this._geometryType=null;this.o=1;this.D=this.C;this.F=this.G;this.H=this.I;this._tGraphic=new q},init:function(a,b){this.m=1;a.hasOwnProperty("opacity")&&(this.m=a.opacity);this.j=b;this.j=
new u(dojoConfig.paths.MilSymbologySymbolsImages+"/"+this.declaredClass.substr(this.declaredClass.lastIndexOf(".")+1,this.declaredClass.length)+".png",this.j,40,40);this.j.color.a=this.m;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();var d;new m;new A(this.map,this.j);this.o=a.DRAW_TYPE;a.hasOwnProperty("CTRL_PTS")&&a.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(a.GEOM),d=this.A(f.clone(a.CTRL_PTS),a.DRAW_TYPE,this.m),this.u(this._tGraphic.geometry,d),this._clear()):
a.hasOwnProperty("CTRL_PTS")?(d=this.A(f.clone(a.CTRL_PTS),a.DRAW_TYPE,this.m),this._tGraphic.setGeometry(this.createSymbol(d)),this.u(this._tGraphic.geometry,d),this._clear()):(this._tGraphic=new q(null,this.j),this.map.graphics.add(this._tGraphic),this.D=p(this.map,"click",f.hitch(this,this.C)),this.F=p(this.map,"dbl-click",f.hitch(this,this.G)))},A:function(a,b,d){var c=new m;c.SCOPE=this;c.SYM_GEO_TYPE=this.symGeometricType;c.SID=this.SID;c.SYM_NAME=this.symName;c.CTRL_PTS=a;c.AMPLIFIER=this.amplifier;
c.DRAW_TYPE=b;c.U=this.isObstacle;c.opacity=d;return c},createSymbol:function(a){try{var b;if(a.hasOwnProperty("CTRL_PTS"))b=a.CTRL_PTS;else throw"controlPoints not found";var d=b[b.length-1],c=b[0],e=new g(this.map.spatialReference);switch(a.DRAW_TYPE){case 1:e=this.N(b,c,d,a,e);break;case 2:e=this.O(b,c,d,a,e);break;case 3:e=this.P(b,c,d,a,e)}return e}catch(h){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},I:function(a){a=a.mapPoint;var b=new m;b.CTRL_PTS=this._points.concat(a);
b.DRAW_TYPE=this.o;this._tGraphic.setGeometry(this.createSymbol(b));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:b,currentMarker:this.j})},C:function(a){this._points.push(a.mapPoint.offset(0,0));1==this._points.length&&(this.H=p(this.map,"mouse-move",f.hitch(this,this.I)));this.emit("onDrawClick",{currentPts:this._points});1==this.S&&1==this._points.length&&(this.emit("onDrawClick",{currentPts:this._points}),this.v());3===this.o&&2===this._points.length&&
(this.emit("onDrawClick",{currentPts:this._points}),this.v())},G:function(a){this._points.push(a.mapPoint);this.v()},v:function(){var a;new m;a=this.A(f.clone(this._points),this.o,this.m);this.u(this._tGraphic.geometry,a);this._clear();this._removeEvents()},u:function(a,b){if(a){var d=this.map.W,c;d&&(d.isWebMercator()?c=w.webMercatorToGeographic(a,!0):4326===d.wkid&&(c=v.fromJson(a.toJson())));this.K(a,c,b)}},K:function(a,b,d){this.emit("onDrawEnd",{geometry:a,geographicGeometry:b,drawEssentials:d,
marker:this.j})},_clear:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},_removeEvents:function(){this.D.remove();this.F.remove();this.H.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},V:function(){},J:function(a,b,d){var c={x:a[0].x,y:a[0].y};a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-
2].y&&a.pop();a[a.length-1].x===a[a.length-2].x&&a[a.length-1].y===a[a.length-2].y&&a.pop();var e=TweenMax.to(c,b,{bezier:a,ease:Linear.easeNone});a=[];var h;for(h=0;h<=b;h++)e.time(h),a.push({x:c.x,y:c.y});b=new g(d.spatialReference);b.addRing(a);return b},N:function(a,b){var d=new g(this.map.spatialReference),c=[];n.forEach(a,function(a){c.push({x:a.x,y:a.y})});c.push({x:b.x,y:b.y});return d=this.J(c,130,this.map)},O:function(a,b){var d=new g(this.map.spatialReference),c=[];n.forEach(a,function(a){c.push({x:a.x,
y:a.y})});c.push({x:b.x,y:b.y});d.addRing(c);return d},P:function(a,b,d){var c=new g(this.map.spatialReference),e=[];n.forEach(a,function(a){e.push({x:a.x,y:a.y})});c.addRing(e);a=c.getExtent();c=new g(this.map.spatialReference);e=[];e.push(b);e.push(new l(a.xmin,a.ymin,this.map.spatialReference));e.push(d);e.push(new l(a.xmax,a.ymax,this.map.spatialReference));e.push(b);c.addRing(e);r._2PtLen(b,d);r._2PtLen(new l(a.xmin,a.ymin,this.map.spatialReference),new l(a.xmax,a.ymax,this.map.spatialReference));
return c}})});
