define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point esri/geometry/geometryEngine esri/geometry/scaleUtils MilSymbologyComponents/BaseLine MilSymbologyExt/GeoTools MilSymbologySymbolsEngine/DrawEssentials MilSymbologyComponents/Shapes".split(" "),
function(w,m,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,t,z,A,u,R,S,T,U,p,V,B,W,X,Y,Z,C,q,n,v){return w([B],{declaredClass:"MilitarySymbology.Symbols.WithdrawUnderPressure",SID:"342500",symName:"Withdraw Under Pressure",symGeometricType:"Area",constructor:function(b){this.map=b;this.j;this._points=[];this._geometryType=null;this.N;this.u=0;this.C=this.A;this.D=this.F;this.G=this.H;this._tGraphic=new t},init:function(b,c){this.j=c;this.map.navigationManager.setImmediateClick(!1);this.map.disableDoubleClickZoom();
var d;new n;new C(this.map,this.j);this.u=b.ECHLON;b.hasOwnProperty("CTRL_PTS")&&b.hasOwnProperty("GEOM")?(this._tGraphic.setGeometry(b.GEOM),d=this.v(m.clone(b.CTRL_PTS),b.ECHLON),this.o(this._tGraphic.geometry,d),this.m()):b.hasOwnProperty("CTRL_PTS")?(d=this.v(m.clone(b.CTRL_PTS),b.ECHLON),this._tGraphic.setGeometry(this.createSymbol(d)),this.o(this._tGraphic.geometry,d),this.m()):(this._tGraphic=new t(null,this.j),this.map.graphics.add(this._tGraphic),this.C=p(this.map,"click",m.hitch(this,this.A)),
this.D=p(this.map,"dbl-click",m.hitch(this,this.F)))},S:function(b,c,d){var a=Math.sqrt(Math.pow(d.x-b.x,2)+Math.pow(d.y-b.y,2));d=Math.sqrt(Math.pow(d.x-c.x,2)+Math.pow(d.y-c.y,2));b=Math.sqrt(Math.pow(c.x-b.x,2)+Math.pow(c.y-b.y,2));return Math.acos((d*d+a*a-b*b)/(2*d*a))},P:function(b,c,d,a,e,f){return Math.atan2(c-f,b-e)-Math.atan2(a-f,d-e)},v:function(b,c){var d=new n;d.SCOPE=this;d.SYM_GEO_TYPE=this.symGeometricType;d.SID=this.SID;d.SYM_GEO_TYPE=this.symGeometricType;d.SYM_NAME=this.symName;
d.CTRL_PTS=b;d.AMPLIFIER=this.amplifier;d.ECHLON=c;return d},createSymbol:function(b){try{var c;if(b.hasOwnProperty("CTRL_PTS"))c=b.CTRL_PTS;else throw"controlPoints not found";var d=new u(this.map.spatialReference),a=c[0],e=c[1];if(2===c.length)d.addPath([a,e]);else if(3===c.length){var f=c[2],g,h=[],l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f),
60,this.map),h=g.geometry.paths[0],d.addPath(h.slice(0,60)))}else if(3<c.length){var f=c[2],m=c[c.length-1],n=c[c.length-2],h=[],l=this._circleDrawEx(this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f));0<l.radius&&(g=this.CreateCircleSegmentFromThreePoints(l,this.map.toScreen(a),this.map.toScreen(e),this.map.toScreen(f),60,this.map),h=g.geometry.paths[0],d.addPath(h.slice(0,60)));h=[];h.push(d.getPoint(0,0));for(b=3;b<c.length-1;b++)h.push(c[b]);h=h.concat(m);g=q._fracture(h,10,this.map.spatialReference);
d.paths=d.paths.concat(g.geometry.paths);var r,p=q._2PtLen(a,m);for(b=0;b<g.midPoints.length;b++)for(r=g.midPoints[b].len/2,r>p/3.6&&(r=p/3.6),h=v.createWP(g.midPoints[b].midPt.x,g.midPoints[b].midPt.y,r,this.map.spatialReference),c=0;c<h.length;c++)d.addPath(h[c]);d.addPath(v.arrowHead(m,q.ArrowFlanksLen(q._2PtLen(n,m),q._2PtLen(a,m)),q.angleInRadians(n,m)))}return d}catch(t){console.log(this.declaredClass+" Can not create Symbol due to invalid geometry")}},H:function(b){b=b.mapPoint;var c=new n;
c.CTRL_PTS=this._points.concat(b);c.ECHLON=this.u;this._tGraphic.setGeometry(this.createSymbol(c));this.emit("onDrawProgress",{currentGeometry:this._tGraphic.geometry,currentDrawEssentials:c,currentMarker:this.j})},A:function(b){this._points.push(b.mapPoint.offset(0,0));1==this._points.length&&(this.G=p(this.map,"mouse-move",m.hitch(this,this.H)));this.emit("onDrawClick",{currentPts:this._points})},F:function(b){this._points.push(b.mapPoint);this.K()},K:function(){var b;new n;b=this.v(m.clone(this._points),
this.u);this.o(this._tGraphic.geometry,b);this.m();this.J()},o:function(b,c){if(b){var d=this.map.U,a;d&&(d.isWebMercator()?a=A.webMercatorToGeographic(b,!0):4326===d.wkid&&(a=z.fromJson(b.toJson())));this.I(b,a,c)}},I:function(b,c,d){this.emit("onDrawEnd",{geometry:b,geographicGeometry:c,drawEssentials:d,marker:this.j})},m:function(){this._tGraphic&&this.map.graphics.remove(this._tGraphic);this._tGraphic=null;this.map.snappingManager&&this.map.snappingManager._setGraphic(null);this._points=[]},J:function(){this.C.remove();
this.D.remove();this.G.remove();this.map.enableDoubleClickZoom()},deactivate:function(){this._clear();this._removeEvents();this._geometryType=null},O:function(){},_circleDrawEx:function(b,c,d){var a,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[b.x,b.y],[c.x,c.y],[d.x,d.y]];for(a=0;3>a;a++)e[a][0]=f[a][0],e[a][1]=f[a][1],e[a][2]=1;b=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][1],e[a][2]=1;c=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*
f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][0],e[a][2]=1;d=this._determinantDrawEx(e,3);for(a=0;3>a;a++)e[a][0]=f[a][0]*f[a][0]+f[a][1]*f[a][1],e[a][1]=f[a][0],e[a][2]=f[a][1];e=this._determinantDrawEx(e,3);if(0==b)e=0;else{var g=.5*c/b,h=-.5*d/b;e=Math.sqrt(g*g+h*h+e/b)}return{radius:e,center:{x:g,y:h}}},_determinantDrawEx:function(b,c){var d,a,e,f,g,h=[[0,0,0],[0,0,0],[0,0,0]];if(2==c)g=b[0][0]*b[1][1]-b[1][0]*b[0][1];else for(e=g=0;e<c;e++){for(d=1;d<c;d++)for(a=f=0;a<c;a++)a!=e&&(h[d-1][f]=b[d][a],f++);
g+=Math.pow(-1,e)*b[0][e]*this._determinantDrawEx(h,c-1)}return g},CreateCircleSegmentFromThreePoints:function(b,c,d,a,e,f){var g=b.center,h=b.radius;b=[];c.x-=g.x;c.y-=g.y;d.x-=g.x;d.y-=g.y;a.x-=g.x;a.y-=g.y;c=Math.atan2(c.y,c.x);var l=Math.atan2(d.y,d.x);d=Math.atan2(a.y,a.x);c=0>c?2*Math.PI+c:c;l=0>l?2*Math.PI+l:l;d=0>d?2*Math.PI+d:d;a=Math.min(c,l);c=Math.max(c,l);l=c-a;if(d<a||d>c)l-=2*Math.PI;c=l/e;for(l=0;l<=e;l++)d=f.toMap({x:h*Math.cos(a+l*c)+g.x,y:h*Math.sin(a+l*c)+g.y}),b.push(d);f=new u(f.spatialReference);
f.addPath(b);return{geometry:f,lastPoint:b[e],backPoint:b[e-5]}}})});
