goog.provide("jive.eae.common.activityAuthor");goog.provide("jive.eae.common.activityAuthorAndOnBehalfOfNoVerb");goog.provide("jive.eae.common.activityAuthorNoVerb");goog.provide("jive.eae.common.activityContainer");goog.provide("jive.eae.common.activityContainerJoSubject");goog.provide("jive.eae.common.activityContentCommon");goog.provide("jive.eae.common.activityContentText");goog.provide("jive.eae.common.activityHeadingHref");goog.provide("jive.eae.common.activityHeadingHrefWithReferringUser");
goog.provide("jive.eae.common.activityHelpfulCounts");goog.provide("jive.eae.common.activityNavActions");goog.provide("jive.eae.common.collapsedExcerptText");goog.provide("jive.eae.common.contentTypeClassName");goog.provide("jive.eae.common.contentTypeDisplayName");goog.provide("jive.eae.common.contentTypeParentPreviewStylingClassName");goog.provide("jive.eae.common.currentCountText");goog.provide("jive.eae.common.digestSubItem");goog.provide("jive.eae.common.displayParentAuthor");goog.provide("jive.eae.common.embeddedPreview");
goog.provide("jive.eae.common.entryRepost");goog.provide("jive.eae.common.formatMediaLinkUrl");goog.provide("jive.eae.common.formatMediaLinkUrl__C2bf6");goog.provide("jive.eae.common.generateUserMetaData");goog.provide("jive.eae.common.groupedUsers");goog.provide("jive.eae.common.hiddenComment");goog.provide("jive.eae.common.jsI18nHelper");goog.provide("jive.eae.common.loadingSpinner");goog.provide("jive.eae.common.microRTEContainer");goog.provide("jive.eae.common.parentPreviewLinks");goog.provide("jive.eae.common.parentPreviewLinksInline");
goog.provide("jive.eae.common.readingPaneBottomReplyLinkKey");goog.provide("jive.eae.common.renderStreamAttachments");goog.provide("jive.eae.common.repliedToIcon");goog.provide("jive.eae.common.replyCountText");goog.provide("jive.eae.common.replyingToText");goog.provide("jive.eae.common.repostModal");goog.provide("jive.eae.common.repostModalSuccess");goog.provide("jive.eae.common.rtePanel");goog.provide("jive.eae.common.rteTextArea");goog.provide("jive.eae.common.sharedVia");goog.provide("jive.eae.common.streamImage");
goog.provide("jive.eae.common.subactivity");goog.require("soy");goog.require("soydata");goog.require("soy.StringBuilder");goog.require("jive.content.comment.rte_message");goog.require("jive.eae.acclaim.acclaimControl");goog.require("jive.eae.activitystream.include.activityVerbPhrase");goog.require("jive.eae.shared.subactivity.outcome");goog.require("jive.outcomes.badge.badgeContainer");goog.require("jive.outcomes.helpful.displayHelpfulCounts");goog.require("jive.outcomes.helpful.renderHelpfulActionControls");
goog.require("jive.shared.displayutil.avatar");goog.require("jive.shared.displayutil.containerDisplayNameLink");goog.require("jive.shared.displayutil.renderGuestDisplayName");goog.require("jive.shared.displayutil.userDisplayName");goog.require("jive.shared.displayutil.userDisplayNameLink");goog.require("jive.shared.displayutil.userRoleBadgeImage");goog.require("jive.shared.soy.escapeHelper");goog.require("jive.shared.soy.i18nHelper");goog.require("jive.shared.soy.render");goog.require("jive.shared.soy.resourceInlineJs");
goog.require("jive.soy.share.control");goog.require("jive.statusinput.containers.microbloggingCommentStatusInput");goog.require("jive.statusinput.containers.renderAttachmentsContainer");goog.require("jive.statusinput.containers.repostStatusInput");
jive.eae.common.rteTextArea=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<textarea id="',soy.$$escapeHtmlAttribute(jive.soy.func.randomString()),'" class=\'wysiwygtext\' name="body" rows="15" cols="30" ></textarea>');return opt_sb?"":output.toString()};
jive.eae.common.rtePanel=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<div class="j-panel-rte-wrap clearfix"><div class="j-panel-rte-loading j-act-reply" style="display:none"><div class="j-rte-placeholder"></div></div><div class="j-panel-rte j-act-reply" style="display:none"><div class="j-reply-to j-js-reply-to"></div><div class="j-act-reply-form">',opt_data.user.anonymous?'<div class="jive-reply-post-anonymous j-form"><div><label for="replyGuestName-id">'+soy.$$escapeHtml(jive.i18n._i18n("d24d93",
[]))+'<span class="font-color-meta-light"> '+soy.$$escapeHtml(jive.i18n._i18n("4881b3",[]))+'</span><input class="replyGuestName" type="text" name="replyGuestName" id="replyGuestName-id"></label></div><div><label for="replyGuestName-id">'+soy.$$escapeHtml(jive.i18n._i18n("b829ed",[]))+'<span class="font-color-meta-light"> '+soy.$$escapeHtml(jive.i18n._i18n("03799a",[]))+'</span><input class="replyGuestEmail" type="text" name="replyGuestEmail" id="replyGuestEmail-id"></label></div>'+(!opt_data.hideGuestURLField?
'<div><label for="replyGuestUrl-id">'+soy.$$escapeHtml(jive.i18n._i18n("3339ea",[]))+'<input class="replyGuestUrl" type="text" name="replyGuestUrl" id="replyGuestUrl-id"></label></div>':"")+"</div>":"",'<p class="jive-error-text jive-comment-error" style="display:none"></p><form method="post" action="javascript:void(0);" name="jive-comment-post-form" class="j-panel-rte-view sammy-app-1288289329294-553-">');jive.eae.common.rteTextArea(null,output);jive.content.comment.rte_message(opt_data,output);
output.append('<div class="jive-form-buttons"><input type="submit" name="post" class="j-btn-global j-btn-callout" value="',soy.$$escapeHtmlAttribute(jive.i18n._i18n("bd781c",[])),"\" /><a href='#' class='j-panel-hide-rte-link j-btn-global'>",soy.$$escapeHtml(jive.i18n._i18n("889192",[])),"</a></div></form></div></div></div>");return opt_sb?"":output.toString()};
jive.eae.common.replyingToText=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.type=="user"){var param38=new soy.StringBuilder;jive.shared.displayutil.userDisplayNameLink(opt_data.object,param38);jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("7eb89a"),arg0:param38.toString(),noAutoEscape:true},output)}else if(opt_data.type=="content")jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("6bb17e"),arg0:opt_data.object.contentTypeName?soy.$$escapeHtml(String(opt_data.object.contentTypeName).toLowerCase()):
"",noAutoEscape:true},output);output.append(' <img src="',soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(jive.soy.func.buildUrl(window._jive_base_url,"/images/inline-reply-arrow.png"))),'" alt=""/>',opt_data.externallyVisible=="true"?"":"");return opt_sb?"":output.toString()};
jive.eae.common.replyCountText=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<strong class="j-act-replycount">',opt_data.activityContainer.jiveObject.typeThread||opt_data.activityContainer.jiveObject.typeDirectMessage?'<a href="'+soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.activityContainer.jiveObject.jiveObjectURL))+'" class="font-color-meta-light">'+(opt_data.activityContainer.replyCount==1?soy.$$escapeHtml(jive.i18n._i18n("b26c26",
[opt_data.activityContainer.replyCount])):soy.$$escapeHtml(jive.i18n._i18n("034452",[opt_data.activityContainer.replyCount])))+"</a>":opt_data.activityContainer.activityList[0]&&opt_data.activityContainer.activityList[0].content.commentContentResource&&opt_data.activityContainer.activityList[0].content.commentContentResource.objectType==129?'<a href="'+soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.activityContainer.jiveObject.jiveObjectURL))+'#comments" class="font-color-meta-light">'+
(opt_data.activityContainer.replyCount==1?soy.$$escapeHtml(jive.i18n._i18n("99b206",[opt_data.activityContainer.replyCount])):soy.$$escapeHtml(jive.i18n._i18n("958b09",[opt_data.activityContainer.replyCount])))+"</a>":'<a href="'+soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.activityContainer.jiveObject.jiveObjectURL))+'#comments" class="font-color-meta-light">'+(opt_data.activityContainer.replyCount==1?soy.$$escapeHtml(jive.i18n._i18n("30308d",[opt_data.activityContainer.replyCount])):
soy.$$escapeHtml(jive.i18n._i18n("8342cc",[opt_data.activityContainer.replyCount])))+"</a>");if(opt_data.showCurrentCount)jive.eae.common.currentCountText(opt_data,output);output.append("</strong>");return opt_sb?"":output.toString()};
jive.eae.common.currentCountText=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activityContainer.numCurrent?'<span class="j-new-count font-color-new">'+(opt_data.activityContainer.numCurrentSubActivities?opt_data.activityContainer.numCurrentSubActivities>=opt_data.activityContainer.maxUnread?soy.$$escapeHtml(jive.i18n._i18n("b26884",[opt_data.activityContainer.maxUnread])):opt_data.activityContainer.numCurrentSubActivities==1?soy.$$escapeHtml(jive.i18n._i18n("4732ab",
[opt_data.activityContainer.numCurrentSubActivities])):soy.$$escapeHtml(jive.i18n._i18n("3aea04",[opt_data.activityContainer.numCurrentSubActivities])):opt_data.streamType!="communications"?soy.$$escapeHtml(jive.i18n._i18n("27922f",[])):"")+"</span>":opt_data.forceCount?'<span class="j-new-count font-color-new">'+soy.$$escapeHtml(jive.i18n._i18n("4732ab",[1]))+"</span>":"");return opt_sb?"":output.toString()};
jive.eae.common.collapsedExcerptText=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.deletedType=="reply"?"<em>"+soy.$$escapeHtml(jive.i18n._i18n("925266",[]))+"</em>":opt_data.deletedType=="comment"?"<em>"+soy.$$escapeHtml(jive.i18n._i18n("0ca93e",[]))+"</em>":opt_data.deletedType=="mentioned"?"<em>"+soy.$$escapeHtml(jive.i18n._i18n("d105d7",[]))+"</em>":opt_data.deletedType=="bookmarked"?"<em>"+soy.$$escapeHtml(jive.i18n._i18n("4f31d6",[]))+"</em>":opt_data.deletedType==
"expertise"?"<em>"+soy.$$escapeHtml(jive.i18n._i18n("401e0b",[]))+"</em>":opt_data.text?(opt_data.moderated?'<div class="jive-warn-box" aria-live="polite" aria-atomic="true"><span class="jive-icon-med jive-icon-warn"></span>'+soy.$$escapeHtml(jive.i18n._i18n("97750c",[]))+"</div>":"")+soy.$$filterNoAutoescape(opt_data.text)+(opt_data.hasMoreText?"&hellip;":""):"");return opt_sb?"":output.toString()};
jive.eae.common.subactivity=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.activityContainer.jiveObject.activityContentExcerptTemplate)jive.shared.soy.render({templateName:opt_data.activityContainer.jiveObject.activityContentExcerptTemplate,data:function(){var map={};var pairs=[["activityContainer",opt_data.activityContainer],["activity",opt_data.activity],["streamType",opt_data.streamType],["filterData",opt_data.filterData],["user",opt_data.user],["canCreateMbImage",
opt_data.canCreateMbImage],["canCreateMbVideo",opt_data.canCreateMbVideo],["isHidden",opt_data.isHidden],["addedInline",opt_data.addedInline],["hideStub",opt_data.hideStub],["forceCurrent",opt_data.forceCurrent]];for(var i=0;i<pairs.length;i+=1)map[pairs[i][0]]=pairs[i][1];return map}(),failGracefully:true},output);else if(opt_data.activity.content.activityContentExcerptTemplate)jive.shared.soy.render({templateName:opt_data.activity.content.activityContentExcerptTemplate,data:function(){var map={};
var pairs=[["activityContainer",opt_data.activityContainer],["activity",opt_data.activity],["streamType",opt_data.streamType],["filterData",opt_data.filterData],["user",opt_data.user],["canCreateMbImage",opt_data.canCreateMbImage],["canCreateMbVideo",opt_data.canCreateMbVideo],["isHidden",opt_data.isHidden],["addedInline",opt_data.addedInline],["hideStub",opt_data.hideStub],["forceCurrent",opt_data.forceCurrent]];for(var i=0;i<pairs.length;i+=1)map[pairs[i][0]]=pairs[i][1];return map}(),failGracefully:true},
output);else if(opt_data.activity.content.typeOutcome)jive.eae.shared.subactivity.outcome(opt_data,output);else if(opt_data.activity.content.hasAcclaimedOutcome)jive.eae.shared.subactivity.outcome(soy.$$augmentMap(opt_data,{activity:opt_data.activity.content.acclaimedOutcomeActivity}),output);else{output.append('<div id="node-collapsed-',soy.$$escapeHtmlAttribute(opt_data.activity.content.domIDPostfix),'" class="j-act-node',opt_data.addedInline?" j-js-addedInline":"",opt_data.activityContainer.canReply?
" j-act-rte-replyable":"",opt_data.streamType=="communications"&&(opt_data.activity.current||opt_data.forceCurrent)?" j-current":"",opt_data.streamType=="communications"&&(opt_data.activity.content.typeMention||opt_data.activity.containsMention)?" j-act-contains-mention":"",'" data-extVisible="',soy.$$escapeHtmlAttribute(opt_data.activity.visibleToExtCollaborator),'" data-extendedAuthors="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.warnVisibleToExtendedAuthors),'" data-objectID="',opt_data.activity.content.typeMention?
soy.$$escapeHtmlAttribute(opt_data.activity.content.context.id):soy.$$escapeHtmlAttribute(opt_data.activity.targetObjectID),'" data-objectType="',opt_data.activity.content.typeMention?soy.$$escapeHtmlAttribute(opt_data.activity.content.context.objectType):soy.$$escapeHtmlAttribute(opt_data.activity.targetObjectType),'" data-current="',opt_data.activity.current||opt_data.forceCurrent?"true":"",'" style="',opt_data.isHidden?"display:none;":"",'"><div id="excerpt_',soy.$$escapeHtmlAttribute(opt_data.activity.content.domIDPostfix),
'" class="',opt_data.activity.content.deleted?"j-mod font-color-meta-light":"reply j-act-comment",'">');if(opt_data.activity.content.deleted){jive.eae.common.collapsedExcerptText({text:"",hasMoreText:false,deletedType:opt_data.activity.content.deletedType!=null?opt_data.activity.content.deletedType:"comment",moderated:false},output);output.append(" ",opt_data.activity.creationTime?soy.$$escapeHtml(opt_data.activity.creationTime):soy.$$escapeHtml(jive.i18n._i18n("176cfc",[])))}else{output.append(opt_data.streamType==
"communications"&&(opt_data.activity.content.typeMention||opt_data.activity.containsMention)?'<div class="j-act-mentioned font-color-okay"><span class="jive-icon-med jive-icon-mention-label"></span><span class="j-mention-label">'+soy.$$escapeHtml(jive.i18n._i18n("99950f",[]))+"</span></div>":"",'<div class="j-act-avatar">');jive.shared.displayutil.avatar(soy.$$augmentMap(opt_data.activity.activityUser,{size:32,currentUserPartner:opt_data.user.partner}),output);output.append('</div><div class="j-excerpt',
!opt_data.activity.content.summaryIsExcerpt?" j-non-excerpt":"",' clearfix" ',opt_data.hideStub?'style="display:none;"':"",">");if(!opt_data.hideStub){var param254=new soy.StringBuilder;jive.eae.common.activityContentText({activity:opt_data.activity,noAutoescape:true},param254);jive.eae.common.activityContentCommon({contentTxt:param254.toString(),hasMoreText:opt_data.activity.hasMoreText},output)}output.append('</div><div class="j-act-sub-preview" ',!opt_data.hideStub?'style="display:none;"':"",">");
if(opt_data.activity.content.deleted){output.append('<div class="j-excerpt-full-html-content">');if(opt_data.hideStub)jive.eae.common.activityContentText({activity:opt_data.activity,noAutoescape:true},output);output.append('</div><div class="j-author-act font-color-meta-light">',opt_data.activity.creationTime?soy.$$escapeHtml(opt_data.activity.creationTime):soy.$$escapeHtml(jive.i18n._i18n("176cfc",[])),"</div>")}else{output.append('<div class="j-author-act font-color-meta-light">');jive.eae.common.activityAuthorNoVerb({activityUser:opt_data.activity.activityUser,
object:opt_data.activity.content},output);output.append(" ",opt_data.activity.type=="mentioned"&&opt_data.activity.content.context.jiveObjectURL?'<a href="'+soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.activity.content.context.jiveObjectURL))+'" class="font-color-meta-light">':opt_data.activity.content.jiveObjectURL?'<a href="'+soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.activity.content.jiveObjectURL))+'" class="font-color-meta-light">':
"",opt_data.activity.creationTime?soy.$$escapeHtml(opt_data.activity.creationTime):soy.$$escapeHtml(jive.i18n._i18n("176cfc",[])),opt_data.activity.type=="mentioned"&&opt_data.activity.content.context.jiveObjectURL||opt_data.activity.content.jiveObjectURL?"</a>":"",'</div><div class="j-excerpt-full-html-content">');if(opt_data.hideStub)jive.eae.common.activityContentText({activity:opt_data.activity,noAutoescape:true},output);output.append("</div>");jive.eae.common.renderStreamAttachments({idPrefix:"expanded",
object:opt_data.activity.content,domIDPostfix:opt_data.activity.domIDPostfix},output);jive.outcomes.badge.badgeContainer({objectType:opt_data.activity.targetObjectType,objectId:opt_data.activity.targetObjectID},output);output.append('<div class="j-meta-actions font-color-meta">');jive.eae.common.activityNavActions({object:opt_data.activity.parentActivity?opt_data.activityContainer.jiveObject:opt_data.activity.content,activityContainer:opt_data.activityContainer,amAnAuthor:opt_data.user.id==opt_data.activity.activityUser.id,
objectType:opt_data.activity.content.typeMention?opt_data.activity.content.context.objectType:opt_data.activity.content.objectType,objectId:opt_data.activity.content.typeMention?opt_data.activity.content.context.id:opt_data.activity.content.id,liked:opt_data.activity.liked,likeCount:opt_data.activity.likeCount,likable:opt_data.activity.likable,user:opt_data.user,location:"subActivity",streamType:opt_data.streamType,filterData:opt_data.filterData},output);output.append("</div>")}output.append("</div>")}output.append("</div></div>")}return opt_sb?
"":output.toString()};
jive.eae.common.activityAuthor=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(!opt_data.activityUser.anonymous)if(opt_data.displayAuthorLink)jive.shared.displayutil.userDisplayNameLink(soy.$$augmentMap(opt_data.activityUser,{renderInvisible:opt_data.object.typeExternalActivity}),output);else if(opt_data.deleted);else output.append(soy.$$escapeHtml(opt_data.activityUser.displayName));else jive.shared.displayutil.renderGuestDisplayName({message:opt_data.activityUser},output);
if(!opt_data.object.typeShare){output.append(" ");jive.eae.activitystream.include.activityVerbPhrase(opt_data,output)}else output.append(" ",soy.$$escapeHtml(jive.i18n._i18n("8fbeca",[]))," ");return opt_sb?"":output.toString()};
jive.eae.common.activityAuthorNoVerb=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(!opt_data.activityUser.anonymous)jive.shared.displayutil.userDisplayNameLink(opt_data.activityUser,output);else jive.shared.displayutil.renderGuestDisplayName({message:opt_data.activityUser},output);output.append(" ");if(!opt_data.hideGroupRoleBadge&&opt_data.activityUser.prop.roleBadgeInfo)jive.shared.displayutil.userRoleBadgeImage(opt_data.activityUser.prop.roleBadgeInfo,output);output.append(" ");
if(opt_data.object.parentAuthor&&!opt_data.object.typeWallEntryComment)jive.eae.common.displayParentAuthor({parentAuthor:opt_data.object.parentAuthor},output);else if(opt_data.object.context&&opt_data.object.context.parentAuthor&&!opt_data.object.context.typeWallEntryComment)jive.eae.common.displayParentAuthor({parentAuthor:opt_data.object.context.parentAuthor},output);return opt_sb?"":output.toString()};
jive.eae.common.activityAuthorAndOnBehalfOfNoVerb=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.object.onBehalfOfUser){var param387=new soy.StringBuilder;jive.eae.common.activityAuthorNoVerb(opt_data,param387);jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("4b618b"),arg0:param387.toString(),arg1:'<strong class="font-color-light"> '+soy.$$escapeHtml(opt_data.object.onBehalfOfUser)+"  </strong>",noAutoEscape:"true"},output)}else jive.eae.common.activityAuthorNoVerb(opt_data,
output);return opt_sb?"":output.toString()};
jive.eae.common.displayParentAuthor=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.parentAuthor.username!="SYSTEM"){var param406=new soy.StringBuilder;var param407=new soy.StringBuilder;jive.shared.displayutil.userDisplayNameLink(opt_data.parentAuthor,param407);jive.shared.soy.escapeHelper({stringToEscape:param407.toString()},param406);jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("b45a47"),arg0:param406.toString(),noAutoEscape:true},output)}return opt_sb?"":
output.toString()};
jive.eae.common.activityContainer=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.location!="subActivity")if(opt_data.activityContainer.container.type&&opt_data.activityContainer.container.type!=-2)if(opt_data.activityContainer.container.type==2020){var param421=new soy.StringBuilder;jive.shared.displayutil.userDisplayNameLink(opt_data.activityContainer.originalAuthor,param421);jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("4314b0"),arg0:param421.toString(),arg1:String(opt_data.activityContainer.jiveObject.contentTypeFeatureName).toLowerCase(),
noAutoEscape:true},output)}else{var param429=new soy.StringBuilder;jive.shared.displayutil.containerDisplayNameLink({container:opt_data.activityContainer.container},param429);jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("d6dba5"),arg0:param429.toString(),noAutoEscape:true},output)}return opt_sb?"":output.toString()};
jive.eae.common.activityNavActions=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<span style="display: none;">');jive.eae.common.activityContainer(opt_data,output);output.append("</span>");if(opt_data.likable&&!opt_data.object.deleted&&!opt_data.activityContainer.jiveObject.typeDirectMessage){output.append('<span class="js-liking-control j-liking-control">');jive.eae.acclaim.acclaimControl({canApply:opt_data.user&&!opt_data.user.anonymous&&(!opt_data.object.typeWallEntry||
opt_data.object.canRate)&&!opt_data.amAnAuthor,applied:opt_data.liked,acclaimCount:opt_data.likeCount,acclaimType:"like",objectId:opt_data.objectId,objectType:opt_data.objectType,showIcon:false,type:"mini"},output);output.append("</span>")}if(opt_data.object.helpfulAcclaim&&opt_data.object.helpfulAcclaim.enabled){output.append(!opt_data.amAnAuthor?' <span class="j-bullet">&#8226;</span> ':"");jive.outcomes.helpful.renderHelpfulActionControls({canMarkHelpful:!opt_data.amAnAuthor,canMarkUnhelpful:!opt_data.amAnAuthor,
renderMode:"text",currentlyHelpful:opt_data.object.helpfulAcclaim.applied,currentlyUnhelpful:opt_data.object.unhelpfulAcclaim&&opt_data.object.unhelpfulAcclaim.applied,unhelpfulEnabled:opt_data.object.unhelpfulAcclaim&&opt_data.object.unhelpfulAcclaim.enabled,objectType:opt_data.objectType,objectId:opt_data.objectId,context:"stream",extraClasses:"j-stream-outcome-helpful-container"},output)}output.append(opt_data.activityContainer.canReply&&!opt_data.object.deleted&&!opt_data.activityContainer.jiveObject.typeWallEntry&&
!opt_data.activityContainer.jiveObject.typeDirectMessage&&!opt_data.activityContainer.jiveObject.typeShare&&!opt_data.object.bookmarkedContent&&!opt_data.isQuestionComment?' <span class="j-bullet">&#8226;</span> <a class="j-reply-rte" href="javascript:void(0);">'+(opt_data.object.typeDocument&&!(opt_data.activityContainer.activityList[0]&&opt_data.activityContainer.activityList[0].content.commentContentResource&&opt_data.activityContainer.activityList[0].content.commentContentResource.objectType==
129)||opt_data.object.typeBlogPost||opt_data.object.typeExternalActivity||opt_data.object.typeTileStreamEntry||opt_data.object.typeExternalURL||opt_data.object.typePoll||opt_data.activityContainer.jiveObject.hasQuestion&&opt_data.location!="subActivity"?soy.$$escapeHtml(jive.i18n._i18n("f80114",[])):opt_data.object.typeDocument&&opt_data.activityContainer.activityList[0]&&opt_data.activityContainer.activityList[0].content.commentContentResource&&opt_data.activityContainer.activityList[0].content.commentContentResource.objectType==
129?soy.$$escapeHtml(jive.i18n._i18n("b1655c",[])):opt_data.object.typeThread||opt_data.object.typeMessage||opt_data.activityContainer.jiveObject.hasQuestion||opt_data.object.typeComment||opt_data.object.typeMention?soy.$$escapeHtml(jive.i18n._i18n("733e4e",[])):soy.$$escapeHtml(jive.i18n._i18n("f80114",[])))+"</a>":"",opt_data.object.typeWallEntry&&opt_data.activityContainer.canReply&&!opt_data.object.deleted&&opt_data.streamType!="communications"&&opt_data.location=="parentPreview"?' <span class="j-bullet">&#8226;</span> <a id="showMicroRTE_'+
soy.$$escapeHtmlAttribute(opt_data.activityContainer.jiveObject.domIDPostfix)+'" class="j-reply-micro" href="#">'+soy.$$escapeHtml(jive.i18n._i18n("f80114",[]))+"</a>":"",opt_data.object.canRepost?' <span class="j-bullet">&#8226;</span> <span class="j-repost-item" id="j-repost-item-'+soy.$$escapeHtmlAttribute(jive.soy.func.randomString())+"-"+soy.$$escapeHtmlAttribute(opt_data.object.id)+'"><a href="#" class="j-repost" title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("e8905b",[]))+'">'+soy.$$escapeHtml(jive.i18n._i18n("4e667b",
[]))+"</a></span>":"");if(opt_data.user&&!opt_data.user.anonymous&&opt_data.activityContainer.sharable&&!opt_data.object.typeExternalActivity&&(opt_data.location=="Title"||opt_data.location=="parentPreview")){output.append(' <span class="j-bullet">&#8226;</span> ');jive.soy.share.control({objectId:soy.$$escapeHtml(opt_data.activityContainer.jiveObject.typeThread?opt_data.activityContainer.jiveObject.threadID:opt_data.objectId),objectType:soy.$$escapeHtml(opt_data.activityContainer.jiveObject.typeThread?
1:opt_data.objectType),type:"text"},output)}if(opt_data.user&&!opt_data.user.anonymous&&opt_data.object.typeExternalActivity&&opt_data.activityContainer.sharable){output.append(' <span class="j-bullet">&#8226;</span> ');jive.soy.share.control({objectId:opt_data.objectId,objectType:opt_data.objectType,type:"text"},output)}output.append((opt_data.location=="Title"||opt_data.location=="parentPreview")&&opt_data.streamType!="all"&&opt_data.streamType!="profile"&&opt_data.streamType!="context"&&opt_data.streamType!=
"communications"&&opt_data.streamType!="publication"&&opt_data.filterData.selectedFilter.type=="all"&&!opt_data.filterData.excluding?' <span class="j-bullet">&#8226;</span> <a href="#" class="js-act-hidemenu" title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("df75ef",[]))+'">'+soy.$$escapeHtml(jive.i18n._i18n("33f5d1",[]))+"</a>":"");return opt_sb?"":output.toString()};
jive.eae.common.activityHelpfulCounts=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.object.helpfulAcclaim&&opt_data.object.helpfulAcclaim.enabled){var score__soy525=new soy.StringBuilder(opt_data.object.unhelpfulAcclaim&&opt_data.object.unhelpfulAcclaim.score?soy.$$escapeHtml(opt_data.object.helpfulAcclaim.score+opt_data.object.unhelpfulAcclaim.score):soy.$$escapeHtml(opt_data.object.helpfulAcclaim.score));score__soy525=score__soy525.toString();jive.outcomes.helpful.displayHelpfulCounts({objectType:opt_data.objectType,
objectId:opt_data.objectId,helpfulCount:opt_data.object.helpfulAcclaim.score,overallCount:score__soy525,displayOverall:opt_data.object.unhelpfulAcclaim?opt_data.object.unhelpfulAcclaim.enabled:false},output)}return opt_sb?"":output.toString()};
jive.eae.common.repostModal=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<div class="jive-modal j-repost-modal" id="jive-js-repost-modal"><header><h2>',soy.$$escapeHtml(jive.i18n._i18n("324052",[])),'</h2></header><label class="j-508-label" id="close-modal-508">',soy.$$escapeHtml(jive.i18n._i18n("a94563",[])),'</label><a href="#" class="j-modal-close-top close" aria-labelledby="close-modal-508" title="',soy.$$escapeHtmlAttribute(jive.i18n._i18n("a94563",[])),'">',
soy.$$escapeHtml(jive.i18n._i18n("1ce366",[])),'<span class="j-close-icon jive-icon-glyph icon-close-med" role="img"></span></a><div class="j-act-mb"><div class="jive-modal-content clearfix">',opt_data.mbCreationModerated?'<div class="jive-content-moderation-box"><span class="jive-icon-med jive-icon-warn"></span>'+soy.$$escapeHtml(jive.i18n._i18n("58f17f",[]))+"</div>":"");jive.eae.common.entryRepost(opt_data,output);output.append("<h4>",soy.$$escapeHtml(jive.i18n._i18n("698c2d",[])),"</h4>");jive.statusinput.containers.repostStatusInput({statusID:"eae-editor-repost-"+
opt_data.object.domIDPostfix,jiveObject:opt_data.object,canCreateMbImage:opt_data.canCreateMbImage,canCreateMbVideo:opt_data.canCreateMbVideo,canAtMention:opt_data.canAtMention},output);output.append("</div></div></div>");return opt_sb?"":output.toString()};
jive.eae.common.repostModalSuccess=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append("<p>",opt_data.wallentry.status!="AWAITING_MODERATION"?soy.$$escapeHtml(jive.i18n._i18n("1d685c",[])):soy.$$escapeHtml(jive.i18n._i18n("4a2bff",[])),"</p>");return opt_sb?"":output.toString()};
jive.eae.common.entryRepost=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<div class="j-wall-repost-content"><div class="j-wall-repost-header">');var param577=new soy.StringBuilder;if(!opt_data.author.anonymous)jive.shared.displayutil.userDisplayNameLink(opt_data.author,param577);else jive.shared.displayutil.renderGuestDisplayName({message:opt_data.object},param577);jive.shared.soy.i18nHelper({i18nKey:soy.$$escapeHtml("7aa1a9"),arg0:param577.toString(),noAutoEscape:"true"},
output);output.append("</div>",opt_data.object&&opt_data.object.text?soy.$$filterNoAutoescape(opt_data.object.text):"");jive.eae.common.renderStreamAttachments({idPrefix:"reposted-attachments",object:opt_data.object,domIDPostfix:opt_data.object.domIDPostfix},output);output.append("</div>");return opt_sb?"":output.toString()};
jive.eae.common.parentPreviewLinks=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<span class="font-color-meta-light paren">(</span><a href=\'#\' class="j-js-show-full-content j-act-preview font-color-meta" data-extVisible="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.visibleToExtCollaborator),'" data-extendedAuthors="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.warnVisibleToExtendedAuthors),'" data-objectID="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.jiveObject.id),
'" data-objectType="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.jiveObject.objectType),'" ',opt_data.activityContainer.jiveObject.typePoll?'data-containerID="'+soy.$$escapeHtmlAttribute(opt_data.activityContainer.container.id)+'" data-containerType="'+soy.$$escapeHtmlAttribute(opt_data.activityContainer.container.type)+'" ':"",' aria-hidden="false" ',opt_data.activityContainer.jiveObject.typeTask||opt_data.activityContainer.jiveObject.typeExternalActivity?'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("fdfa98",
[]))+'">':'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("062032",[]))+'">','<span class="lnk">',soy.$$escapeHtml(jive.i18n._i18n("866792",[])),'</span></a><a href=\'#\' class="j-js-hide-full-content j-act-preview font-color-meta" style="display:none;" aria-hidden="true" ',opt_data.activityContainer.jiveObject.typeTask||opt_data.activityContainer.jiveObject.typeExternalActivity?'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("fdfa98",[]))+'">':'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("084537",
[]))+'">','<span class="lnk">',soy.$$escapeHtml(jive.i18n._i18n("5960e9",[])),'</span></a><span class="font-color-meta-light paren">)</span>');return opt_sb?"":output.toString()};
jive.eae.common.parentPreviewLinksInline=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<span class="font-color-meta-light paren">(</span><a href=\'#\' class="j-js-show-full-content j-act-preview font-color-meta" data-extVisible="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.visibleToExtCollaborator),'" data-extendedAuthors="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.warnVisibleToExtendedAuthors),'" data-objectID="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.jiveObject.id),
'" data-objectType="',soy.$$escapeHtmlAttribute(opt_data.activityContainer.jiveObject.objectType),'" ',opt_data.activityContainer.jiveObject.typePoll?'data-containerID="'+soy.$$escapeHtmlAttribute(opt_data.activityContainer.container.id)+'" data-containerType="'+soy.$$escapeHtmlAttribute(opt_data.activityContainer.container.type)+'" ':"",' aria-hidden="false" ',opt_data.activityContainer.jiveObject.typeTask||opt_data.activityContainer.jiveObject.typeExternalActivity?'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("fdfa98",
[]))+'">':'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("062032",[]))+'">','<span class="lnk">',soy.$$escapeHtml(jive.i18n._i18n("866792",[])),'</span></a><a href=\'#\' class="j-js-hide-full-content j-act-preview font-color-meta" style="display:none;" aria-hidden="true" ',opt_data.activityContainer.jiveObject.typeTask||opt_data.activityContainer.jiveObject.typeExternalActivity?'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("fdfa98",[]))+'">':'title="'+soy.$$escapeHtmlAttribute(jive.i18n._i18n("084537",
[]))+'">','<span class="lnk">',soy.$$escapeHtml(jive.i18n._i18n("5960e9",[])),'</span></a><span class="font-color-meta-light paren">)</span>');return opt_sb?"":output.toString()};
jive.eae.common.microRTEContainer=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.activityContainer.jiveObject&&(opt_data.activityContainer.canReply||opt_data.activityContainer.jiveObject.typeCollaboration||opt_data.activityContainer.jiveObject.typeWallEntry&&opt_data.activityContainer.jiveObject.canComment&&opt_data.activityContainer.jiveObject.id==opt_data.object.id)){output.append('<div id="microRTEContainer_',soy.$$escapeHtmlAttribute(opt_data.object.domIDPostfix),
'" class="j-act-reply j-act-micro-rte" ',!opt_data.showOnLoad?'style="display:none;"':"",'><div class="r-active">');if(!opt_data.activityContainer.jiveObject.typeCollaboration&&!opt_data.activityContainer.jiveObject.typeShare&&!opt_data.activityContainer.jiveObject.typeWallEntry){output.append('<div class="j-act-replyinfo">',soy.$$escapeHtml(jive.i18n._i18n("a0a106",[])),' <span class="jive-icon-sml ',soy.$$escapeHtmlAttribute(opt_data.activityContainer.jiveObject.jiveObjectCSS),'"></span><strong>');
jive.eae.common.activityContainerJoSubject(opt_data,output);output.append("</strong></div>")}output.append(opt_data.user.anonymous?'<div class="jive-reply-post-anonymous j-form"><div><label for="replyGuestName-id">'+soy.$$escapeHtml(jive.i18n._i18n("d24d93",[]))+'<span class="font-color-meta-light"> '+soy.$$escapeHtml(jive.i18n._i18n("4881b3",[]))+'</span><input class="replyGuestName" type="text" name="replyGuestName" id="replyGuestName-id"></label></div><div><label for="replyGuestEmail-id">'+soy.$$escapeHtml(jive.i18n._i18n("b829ed",
[]))+'<span class="font-color-meta-light"> '+soy.$$escapeHtml(jive.i18n._i18n("03799a",[]))+'</span><input class="replyGuestEmail" type="text" name="replyGuestEmail" id="replyGuestEmail-id"></label></div><div><label for="replyGuestUrl-id">'+soy.$$escapeHtml(jive.i18n._i18n("3339ea",[]))+'<input class="replyGuestUrl" type="text" name="replyGuestUrl" id="replyGuestUrl-id"></label></div></div>':"");if(opt_data.activityContainer.jiveObject.typeWallEntry&&opt_data.activityContainer.jiveObject.canComment||
opt_data.activityContainer.jiveObject.typeCollaboration||opt_data.activityContainer.jiveObject.typeShare&&opt_data.activityContainer.canReply)jive.statusinput.containers.microbloggingCommentStatusInput({statusID:"eae-mb-comment-editor-"+opt_data.object.domIDPostfix,jiveObject:opt_data.activityContainer.jiveObject,canAtMention:opt_data.canAtMention,addCssClass:opt_data.addCssClass,showOnLoad:opt_data.showOnLoad,hideAtMentionBtn:opt_data.hideAtMentionBtn,visibleToExtCollaborator:opt_data.object.visibleToExtCollaborator,
hideCancelBtn:opt_data.activityContainer.jiveObject.typeCollaboration,i18nSubmitKey:opt_data.i18nSubmitKey,defaultTextKey:opt_data.defaultTextKey},output);output.append("</div></div>")}return opt_sb?"":output.toString()};jive.eae.common.repliedToIcon=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<span class="jive-icon-glyph icon-chevron-circle-up"></span>');return opt_sb?"":output.toString()};
jive.eae.common.activityContentCommon=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.contentTxt!=""?"<p>"+soy.$$filterNoAutoescape(opt_data.contentTxt)+(opt_data.hasMoreText?"&hellip;":"")+"</p>":"");return opt_sb?"":output.toString()};
jive.eae.common.generateUserMetaData=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append("{anonymous: ",soy.$$escapeHtml(opt_data.user.anonymous),", avatarID: ",soy.$$escapeHtml(opt_data.user.avatarID),", displayName: '",soy.$$escapeHtml(opt_data.user.displayName),"', email: '",soy.$$escapeHtml(opt_data.user.email),"', enabled: ",soy.$$escapeHtml(opt_data.user.enabled),", entitled: ",soy.$$escapeHtml(opt_data.user.entitled),", id: ",soy.$$escapeHtml(opt_data.user.id),
", objectType: ",soy.$$escapeHtml(opt_data.user.objectType),", username: '",soy.$$escapeHtml(opt_data.user.username),"'}");return opt_sb?"":output.toString()};
jive.eae.common.renderStreamAttachments=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.object.meta&&opt_data.object.meta.length>0){jive.statusinput.containers.renderAttachmentsContainer({id:opt_data.idPrefix?soy.$$escapeHtml(opt_data.idPrefix+"-attachmentContainer-"+opt_data.domIDPostfix):soy.$$escapeHtml("attachmentContainer-"+opt_data.domIDPostfix),entry:opt_data.object,visible:true,hideFirstImage:opt_data.hideFirstImage},output);jive.shared.soy.resourceInlineJs({code:"require(['apps/microblogging/views/attachment_view'],function(AttachmentView){var id = '"+
(opt_data.idPrefix?soy.$$escapeHtml(opt_data.idPrefix+"-attachmentContainer-"+opt_data.domIDPostfix):soy.$$escapeHtml("attachmentContainer-"+opt_data.domIDPostfix))+"', attachmentView = new AttachmentView({selector:'#' + id}); attachmentView.postRender(); AttachmentView.views[id] = attachmentView;});"},output)}else if(opt_data.object.typeExternalActivity&&opt_data.object.mediaLink){output.append('<div class="j-act-attachment"><a href="');jive.eae.common.formatMediaLinkUrl__C2bf6(opt_data.object,output);
output.append('" target="_blank" title="',soy.$$escapeHtmlAttribute(opt_data.object.mediaLink.filename?opt_data.object.mediaLink.filename:""),'">',opt_data.object.mediaLink.thumbnailUrl?'<div class="j-media-attachment"><img src="'+soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(opt_data.object.mediaLink.thumbnailUrl))+'" title="'+soy.$$escapeHtmlAttribute(opt_data.object.mediaLink.title)+'" alt="" width="'+soy.$$escapeHtmlAttribute(opt_data.object.mediaLink.thumbnailWidth)+'" height="'+soy.$$escapeHtmlAttribute(opt_data.object.mediaLink.thumbnailHeight)+
'"/></div>':opt_data.object.mediaLink.iconClass?'<span class="jive-icon-med '+soy.$$escapeHtmlAttribute(opt_data.object.mediaLink.iconClass)+'"></span><span>'+soy.$$escapeHtml(opt_data.object.mediaLink.title)+"</span>":"","</a></div>")}return opt_sb?"":output.toString()};
jive.eae.common.formatMediaLinkUrl=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.mediaLink.contentUrl?opt_data.mediaLink.contentUrl.match(new RegExp("/^https?:\\/\\//",""))||[]?soy.$$filterNoAutoescape(opt_data.mediaLink.contentUrl):soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.mediaLink.contentUrl)):opt_data.mediaLink.imageUrl.match(new RegExp("/^https?:\\/\\//",""))||[]?soy.$$filterNoAutoescape(opt_data.mediaLink.imageUrl):
soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.mediaLink.imageUrl)));return opt_sb?"":output.toString()};jive.eae.common.activityContainerJoSubject=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activityContainer&&opt_data.activityContainer.jiveObject&&opt_data.activityContainer.jiveObject.subject?soy.$$filterNoAutoescape(opt_data.activityContainer.jiveObject.subject):"");return opt_sb?"":output.toString()};
jive.eae.common.activityContentText=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activity&&opt_data.activity.content?opt_data.activity.content.deleted?opt_data.activity.content.typeThread?"<em>"+soy.$$escapeHtml(jive.i18n._i18n("925266",[]))+"</em>":"<em>"+soy.$$escapeHtml(jive.i18n._i18n("925266",[]))+"</em>":opt_data.activity.content.typeExternalActivity?opt_data.activity.content.summary?opt_data.noAutoescape?soy.$$filterNoAutoescape(opt_data.activity.content.summary):
soy.$$escapeHtml(opt_data.activity.content.summary):"":(opt_data.activity.moderated?opt_data.activity.content.status=="REJECTED"?'<div class="jive-error-box" aria-live="polite" aria-atomic="true"><div><span class="jive-icon-med jive-icon-redalert"></span>'+soy.$$escapeHtml(jive.i18n._i18n("5393f1",[]))+"</div></div>":(opt_data.activity.content.status=="AWAITING_MODERATION"?'<div class="jive-warn-box" aria-live="polite" aria-atomic="true" style= "width:initial;"><div><span class="jive-icon-med jive-icon-warn"></span>'+
soy.$$escapeHtml(jive.i18n._i18n("97750c",[]))+"</div>":"")+"</div>":"")+(opt_data.activity.content.html?opt_data.noAutoescape?soy.$$filterNoAutoescape(opt_data.activity.content.html):soy.$$escapeHtml(opt_data.activity.content.html):opt_data.activity.content.text?opt_data.noAutoescape?soy.$$filterNoAutoescape(opt_data.activity.content.text):soy.$$escapeHtml(opt_data.activity.content.text):""):"");return opt_sb?"":output.toString()};
jive.eae.common.jsI18nHelper=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(soy.$$escapeHtml(jive.i18n._i18n(opt_data.key,[])));return opt_sb?"":output.toString()};
jive.eae.common.groupedUsers=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;var noOverflow__soy884=opt_data.groupedUserList.length<=opt_data.groupAfterNum;var singleUserOverflow__soy885=opt_data.groupedUserList.length==opt_data.groupAfterNum+1;var multiUserOverflow__soy886=opt_data.groupedUserList.length>opt_data.groupAfterNum+1;var singleUser__soy887=opt_data.groupedUserList.length==1;var multipleUsers__soy888=opt_data.groupedUserList.length!=1;var groupedUserList889=opt_data.groupedUserList;
var groupedUserListLen889=groupedUserList889.length;for(var groupedUserIndex889=0;groupedUserIndex889<groupedUserListLen889;groupedUserIndex889++){var groupedUserData889=groupedUserList889[groupedUserIndex889];var userIsNextToLastGrouped__soy890=groupedUserIndex889==opt_data.groupAfterNum-1;var userIsLastGrouped__soy891=groupedUserIndex889==opt_data.groupAfterNum;var userIsNotLastGrouped__soy892=groupedUserIndex889<opt_data.groupAfterNum;var userIsLastTotal__soy893=groupedUserIndex889==opt_data.groupedUserList.length-
1;if(groupedUserData889&&(userIsNotLastGrouped__soy892||userIsLastGrouped__soy891&&singleUserOverflow__soy885)){output.append(groupedUserIndex889==groupedUserListLen889-1&&opt_data.groupedUserList.length>1?soy.$$escapeHtml(jive.i18n._i18n("3b6373",[]))+" ":"");if((groupedUserData889.username.match(new RegExp("^__invited__",""))||[]).length)output.append(soy.$$escapeHtml(groupedUserData889.email));else if(!groupedUserData889.anonymous)if(!opt_data.hideLinks)jive.shared.displayutil.userDisplayNameLink(groupedUserData889,
output);else jive.shared.displayutil.userDisplayName(groupedUserData889,output);else jive.shared.displayutil.renderGuestDisplayName({message:groupedUserData889},output);output.append(multipleUsers__soy888&&(noOverflow__soy884&&!userIsLastTotal__soy893||singleUserOverflow__soy885&&!userIsLastGrouped__soy891||multiUserOverflow__soy886&&!userIsNextToLastGrouped__soy890)?(opt_data.groupedUserList.length>2?",":"")+" ":"")}}if(opt_data.groupedUserList.length>opt_data.groupAfterNum+1){output.append(" ",
soy.$$escapeHtml(jive.i18n._i18n("3b6373",[]))," ",!opt_data.hideLinks?"<a href='#' class=\"js-show-grouped-users jive-username-link\">":"",soy.$$escapeHtml(opt_data.groupedUserList.length-opt_data.groupAfterNum)," ",opt_data.groupedUserList.length>opt_data.groupAfterNum+1?soy.$$escapeHtml(jive.i18n._i18n("3d6825",[])):soy.$$escapeHtml(jive.i18n._i18n("e8a1ea",[])));if(!opt_data.hideLinks){output.append('</a><div class="js-grouped-users-popover j-grouped-users-popover" style="display:none"><ul class="j-grouped-user-list j-simple-list">');
var groupedUserList937=opt_data.groupedUserList;var groupedUserListLen937=groupedUserList937.length;for(var groupedUserIndex937=0;groupedUserIndex937<groupedUserListLen937;groupedUserIndex937++){var groupedUserData937=groupedUserList937[groupedUserIndex937];if(groupedUserData937&&groupedUserIndex937>=opt_data.groupAfterNum)if((groupedUserData937.displayName.match(new RegExp("^__invited__",""))||[]).length)output.append(soy.$$escapeHtml(groupedUserData937.email));else if(!groupedUserData937.anonymous){output.append('<li class="j-grouped-user">');
jive.shared.displayutil.userDisplayNameLink(groupedUserData937,output);output.append("</li>")}else{output.append('<li class="j-grouped-user">');jive.shared.displayutil.renderGuestDisplayName({message:groupedUserData937},output);output.append("</li>")}}output.append("</ul></div>")}}return opt_sb?"":output.toString()};
jive.eae.common.contentTypeClassName=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activityContainer.jiveObject.typeExternalActivity?"j-act-app":opt_data.activityContainer.jiveObject.typeCollaboration?"j-act-collaboration":opt_data.activityContainer.jiveObject.typeAnnouncement?"j-act-announcement":opt_data.activityContainer.jiveObject.typeMention?"j-act-mention":opt_data.activityContainer.jiveObject.typeShare?"j-act-share":opt_data.activityContainer.jiveObject.typeExternalURL?
"j-act-bookmark":opt_data.activityContainer.jiveObject.typeThread?"j-act-discussion j-thread-post":opt_data.activityContainer.jiveObject.typeDocument?"j-act-document":opt_data.activityContainer.jiveObject.typeBlogPost?"j-act-blog":opt_data.activityContainer.jiveObject.typePoll?"j-act-poll":opt_data.activityContainer.jiveObject.typeTask?"j-act-task":"j-act-generic");return opt_sb?"":output.toString()};
jive.eae.common.contentTypeDisplayName=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activityContainer.jiveObject.typeExternalActivity?soy.$$escapeHtml(jive.i18n._i18n("c4e101",[])):opt_data.activityContainer.jiveObject.typeDirectMessage?soy.$$escapeHtml(jive.i18n._i18n("c4b056",[])):opt_data.activityContainer.jiveObject.typeAnnouncement?soy.$$escapeHtml(jive.i18n._i18n("68b425",[])):opt_data.activityContainer.jiveObject.typeMention?soy.$$escapeHtml(jive.i18n._i18n("4657e3",
[])):opt_data.activityContainer.jiveObject.typeShare?soy.$$escapeHtml(jive.i18n._i18n("41922c",[])):opt_data.activityContainer.jiveObject.typeExternalURL?soy.$$escapeHtml(jive.i18n._i18n("97babe",[])):opt_data.activityContainer.jiveObject.typeThread?soy.$$escapeHtml(jive.i18n._i18n("cb9b05",[])):opt_data.activityContainer.jiveObject.typeDocument?soy.$$escapeHtml(jive.i18n._i18n("b67d0f",[])):opt_data.activityContainer.jiveObject.typeBlogPost?soy.$$escapeHtml(jive.i18n._i18n("92ee84",[])):opt_data.activityContainer.jiveObject.typePoll?
soy.$$escapeHtml(jive.i18n._i18n("205cd1",[])):opt_data.activityContainer.jiveObject.typeTask?soy.$$escapeHtml(jive.i18n._i18n("7c71b3",[])):soy.$$escapeHtml(jive.i18n._i18n("22ed1b",[])));return opt_sb?"":output.toString()};
jive.eae.common.contentTypeParentPreviewStylingClassName=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activityContainer.jiveObject.typeThread?"j-thread-post":opt_data.activityContainer.jiveObject.typeDocument?"j-doc jive-content":opt_data.activityContainer.jiveObject.typeBlogPost?"jive-content":opt_data.activityContainer.jiveObject.typeTask?"j-task":opt_data.activityContainer.activityList[0].content&&opt_data.activityContainer.activityList[0].content.typeExternalActivity&&
opt_data.activityContainer.activityList[0].content.verb=="uri:jiveName:app_install"?"jive-content j-appinstall  j-rc5":"jive-content j-rc5");return opt_sb?"":output.toString()};
jive.eae.common.loadingSpinner=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<img src="',soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(jive.soy.func.resourceUrl("/images/jive-icon-working-16x16.gif"))),'" class="j-eae-spinner js-loading-spinner" width="16" height="16" border="0" alt=""/>');return opt_sb?"":output.toString()};
jive.eae.common.digestSubItem=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.activity.content.deleted){output.append('<div class="font-color-meta-light">');jive.eae.common.collapsedExcerptText({text:"",hasMoreText:false,deletedType:opt_data.activity.content.deletedType!=null?opt_data.activity.content.deletedType:"expertise",moderated:false},output);output.append("</div>")}else if(opt_data.activity.content.activityTemplate)if(opt_data.user)jive.shared.soy.render({templateName:opt_data.activity.content.activityTemplate,
data:function(){var map={};var pairs=[["activity",opt_data.activity],["activityContainer",opt_data.activityContainer],["user",opt_data.user],["streamType",opt_data.streamType],["filterData",opt_data.filterData],["fromTemplate",opt_data.fromTemplate]];for(var i=0;i<pairs.length;i+=1)map[pairs[i][0]]=pairs[i][1];return map}(),failGracefully:true},output);else jive.shared.soy.render({templateName:opt_data.activity.content.activityTemplate,data:function(){var map={};var pairs=[["activity",opt_data.activity],
["activityContainer",opt_data.activityContainer],["streamType",opt_data.streamType],["filterData",opt_data.filterData],["fromTemplate",opt_data.fromTemplate]];for(var i=0;i<pairs.length;i+=1)map[pairs[i][0]]=pairs[i][1];return map}(),failGracefully:true},output);else{output.append("<div>");jive.eae.common.subactivity({activity:opt_data.activity,activityContainer:opt_data.activityContainer,user:opt_data.user,isHidden:false,streamType:opt_data.streamType,filterData:opt_data.filterData,canCreateMbImage:opt_data.canCreateMbImage,
canCreateMbVideo:opt_data.canCreateMbVideo,addedInline:false,hideStub:false,forceCurrent:false},output);output.append("</div>")}return opt_sb?"":output.toString()};
jive.eae.common.readingPaneBottomReplyLinkKey=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.activityContainer.jiveObject.typeDocument?soy.$$escapeHtml(jive.i18n._i18n("fb92f1",[])):opt_data.activityContainer.jiveObject.typeBlogPost?soy.$$escapeHtml(jive.i18n._i18n("97344c",[])):opt_data.activityContainer.jiveObject.typeExternalURL?soy.$$escapeHtml(jive.i18n._i18n("a5fe20",[])):opt_data.activityContainer.jiveObject.typePoll?soy.$$escapeHtml(jive.i18n._i18n("806c9d",
[])):opt_data.activityContainer.jiveObject.typeThread&&!opt_data.activityContainer.jiveObject.hasQuestion?soy.$$escapeHtml(jive.i18n._i18n("76919e",[])):opt_data.activityContainer.jiveObject.typeThread&&opt_data.activityContainer.jiveObject.hasQuestion?soy.$$escapeHtml(jive.i18n._i18n("7f6508",[])):soy.$$escapeHtml(jive.i18n._i18n("6bb17e",[])));return opt_sb?"":output.toString()};
jive.eae.common.embeddedPreview=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<div id="emb-preview-',soy.$$escapeHtmlAttribute(opt_data.domIDPostfix),'" class="j-act-tile ',opt_data.imageURL?"hasImg":"",' clearfix">',opt_data.imageURL?(opt_data.externalURL?'<a href="'+soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(opt_data.externalURL))+'" class="j-act-tile-img j-rc3">':'<span class="j-act-tile-img j-rc3">')+'<img class="act-tile-image" src="'+soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(opt_data.imageURL))+
'" alt=""/>'+(opt_data.externalURL?"</a>":"</span>"):"",'<div class="j-act-tile-text">',opt_data.subject?(opt_data.externalURL?'<a class="tileTitle" href="'+soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(opt_data.externalURL))+'">':"")+soy.$$filterNoAutoescape(opt_data.subject)+(opt_data.externalURL?"</a>":""):"",opt_data.textContent?'<div class="tileContent">'+soy.$$filterNoAutoescape(opt_data.textContent)+"</div>":"",opt_data.externalURLHost&&opt_data.externalURLRoot?'<p class="j-act-tile-url"><a class="font-color-meta-light" href="'+
soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(opt_data.externalURLRoot))+'">'+soy.$$filterNoAutoescape(opt_data.externalURLHost)+"</a></p>":"","</div>");jive.eae.common.sharedVia(opt_data,output);output.append("</div>");return opt_sb?"":output.toString()};
jive.eae.common.sharedVia=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<div class="act-tile-shared-via font-color-meta"><img class="jive-icon-med jive-ext-icon-16" src="',soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(opt_data.viaIconURL?opt_data.viaIconURL:jive.soy.func.buildUrl(window._jive_base_url,"/images/transparent.png"))),'" alt=""/>',soy.$$escapeHtml(jive.i18n._i18n("2bb68d",[opt_data.viaName])),"</div>");return opt_sb?"":output.toString()};
jive.eae.common.activityHeadingHref=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.activityContainer.activityList&&opt_data.activityContainer.activityList.length)if(opt_data.user)if(opt_data.activityContainer.activityList[opt_data.activityContainer.activityList.length-1].activityUser.id!=opt_data.user.id)jive.eae.common.activityHeadingHrefWithReferringUser({url:opt_data.url,source:opt_data.source,referringUserId:opt_data.activityContainer.activityList[opt_data.activityContainer.activityList.length-
1].activityUser.id},output);else output.append(soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.url,{"sr":opt_data.source})));else jive.eae.common.activityHeadingHrefWithReferringUser({url:opt_data.url,source:opt_data.source,referringUserId:opt_data.activityContainer.activityList[opt_data.activityContainer.activityList.length-1].activityUser.id},output);else if(opt_data.activityContainer.latestAuthor)if(opt_data.user)if(opt_data.activityContainer.latestAuthor.id!=opt_data.user.id)jive.eae.common.activityHeadingHrefWithReferringUser({url:opt_data.url,
source:opt_data.source,referringUserId:opt_data.activityContainer.latestAuthor.id},output);else output.append(soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.url,{"sr":opt_data.source})));else jive.eae.common.activityHeadingHrefWithReferringUser({url:opt_data.url,source:opt_data.source,referringUserId:opt_data.activityContainer.latestAuthor.id},output);else output.append(soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.url,{"sr":opt_data.source})));
return opt_sb?"":output.toString()};jive.eae.common.activityHeadingHrefWithReferringUser=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append((opt_data.url.match(new RegExp("#","g"))||[]).length==0?soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.url,{"sr":opt_data.source,"ru":opt_data.referringUserId})):soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.url)));return opt_sb?"":output.toString()};
jive.eae.common.streamImage=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;if(opt_data.activityContainer.image){var image__soy1190=opt_data.activityContainer.previewImage;output.append('<a href="',soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.activityContainer.jiveObject.jiveObjectURL)),'"><img src="',soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(image__soy1190.ref)),'" class="j-act-entry-image" alt="',soy.$$escapeHtmlAttribute(jive.i18n._i18n("9235c1",
[])),'"/></a>')}return opt_sb?"":output.toString()};jive.eae.common.hiddenComment=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append('<div class="jive-comment-content jive-comment-content-hidden"><p class="font-color-meta"> ',soy.$$escapeHtml(jive.i18n._i18n("fa51c8",[]))," </p></div>');");return opt_sb?"":output.toString()};
jive.eae.common.formatMediaLinkUrl__C2bf6=function(opt_data,opt_sb){var output=opt_sb||new soy.StringBuilder;output.append(opt_data.mediaLink.contentUrl?opt_data.mediaLink.contentUrl.match(new RegExp("/^https?:\\/\\//",""))||[]?soy.$$filterNoAutoescape(opt_data.mediaLink.contentUrl):soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.mediaLink.contentUrl)):opt_data.mediaLink.imageUrl.match(new RegExp("/^https?:\\/\\//",""))||[]?soy.$$filterNoAutoescape(opt_data.mediaLink.imageUrl):
soy.$$filterNoAutoescape(jive.soy.func.buildUrl(window._jive_base_url,opt_data.mediaLink.imageUrl)));return opt_sb?"":output.toString()};