import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
import SerializationEngine from '../ImportExport/SerializationEngine';
declare class DeploymentBuilderEngine {
    private static _instance;
    private _view;
    private _enabled;
    private _widget;
    private _ghostLayer;
    private _serializationEngine;
    private _phase;
    private _selectedPlanData;
    private _selectedPlanEntry;
    private _selectedPlanMetrics;
    private _anchorPoint;
    private _formationType;
    private _spacingMeters;
    private _pointerMoveHandle;
    private _pointerDownHandle;
    private _bgClickHandle;
    private _rightClickHandle;
    private _keyDownHandler;
    private _ghostRafId;
    private _pendingGhostBearing;
    private _pendingGhostCursor;
    private _bearingHUD;
    private _placementInstructions;
    private _bgPopup;
    private _registry;
    private _registryBaseUrl;
    private _minimized;
    private _searchText;
    private _collapsedCategories;
    private _widgetHeight;
    private constructor();
    static getInstance(): DeploymentBuilderEngine;
    start(view: MapView | SceneView, serialEngine: SerializationEngine): void;
    onViewChanged(view: MapView | SceneView): void;
    enable(): void;
    disable(): void;
    destroy(): void;
    openWidget(): void;
    private _closeWidget;
    private _minimizeWidget;
    private _applyMinimizeState;
    private _buildWidget;
    private _injectWidgetStyles;
    private _makeDraggable;
    private _makeResizable;
    private _resolveRegistryBase;
    private _loadRegistry;
    private _loadPlanFile;
    private _loadRegistryIntoWidget;
    private _renderPlanList;
    private _selectPlan;
    private _importSavedPlanFromFile;
    private _selectImportedPlan;
    private _onPlaceClicked;
    private _startPlacement;
    private _startBearingPhase;
    private _commitFormation;
    private _cancelPlacement;
    private _updateAnchorHover;
    private _updateGhostPreview;
    private _clearGhostGraphics;
    private _addGhostDot;
    private _getAsIsGhostProjectedPoints;
    private _showBearingHUD;
    private _removeBearingHUD;
    private _showPlacementInstructions;
    private _removePlacementInstructions;
    private _radiansToDegrees;
    private _bearingToCardinal;
    private _computeBearing;
    private _computeFormationPoint;
    private _offsetPoint;
    private _addMetersToPoint;
    private _toProjected;
    private _pointToWGS84;
    private _isProjected;
    private _toWGS84;
    private _applyAsIsSpacingToPlan;
    /**
     * Deep-clone the plan and shift every symbol so its centroid lands on its
     * assigned formation slot.  All control points within a symbol are offset by
     * the same (slotPos − symbolCentroid) delta, preserving the symbol's shape.
     */
    private _applyFormationToPlan;
    private _countPlanSymbols;
    private _getSelectedPlanMetrics;
    private _buildPlanMetrics;
    private _extractPlanPoints;
    private _extractPlanPointGroups;
    private _computeCentroid;
    private _removePointerHandles;
    private _removeBgClickHandle;
    private _removeBgPopup;
    private _getViewContainer;
    private _setStatus;
}
export default DeploymentBuilderEngine;
