define(["esri/geometry/Polyline","esri/geometry/Point","MilSymbologyExt/GeoTools","MilSymbologyComponents/Echelons"],function(p,f,l,m){return{createC:function(b,c,a){var d=[];a=2*Math.PI/a;for(var e=b.x,n=b.y,g=1.1;g<1.1+Math.PI;g+=a)d.push(new f(e+c*Math.cos(g),n-c*Math.sin(g),b.spatialReference));return d},createEllipse:function(b){var c=b.center.x,a=b.center.y,d=b.longAxis,e=b.shortAxis,f=b.numberOfPoints;b=b.map;var g,h,l=[],m=2*Math.PI/f;for(h=0;h<f;h++)g=b.toMap({x:d*Math.cos(h*m)+c,y:e*Math.sin(h*
m)+a}),l.push(g);l.push(l[0]);(new p(b.spatialReference)).addPath(l);return l},createCircle:function(b,c,a){var d=[];a=2*Math.PI/a;for(var e=b.x,n=b.y,g=0;g<2*Math.PI;g+=a)d.push(new f(e+c*Math.cos(g),n-c*Math.sin(g),b.spatialReference));return d},createHalfCircle:function(b,c,a,d,e){var n=[];e=2*Math.PI/e;for(var g=b.x,h=b.y;a<2*Math.PI+d;a+=e)n.push(new f(g+c*Math.cos(a),h-c*Math.sin(a),b.spatialReference));return n},createFLOTHalfCircle:function(b,c,a){var d=[],e;e=2*Math.PI/30;for(var n=b.x,g=
b.y,h=0;3.1765>=h;h+=e)d.push(new f(n+a*Math.cos(h),g-a*Math.sin(h),b.spatialReference));return this.ownRotate(d,b.x,b.y,c)},createB:function(b,c,a){a=[];return a=a.concat(this.createHalfCircle(new f(b.x-c/5.6,b.y-c/2,b.spatialReference),c/2,4.7,2,40),this.createHalfCircle(new f(b.x-c/5.6,b.y+c/2,b.spatialReference),c/2,4.4,1.6,40))},createPL:function(b,c,a,d){var e;e=this.createDD(b,c+a/2,a/2,d);e.push(new f(b-a/2/3,c,d));e.push(new f(b-a/2/3,c-a,d));return[e,this.createL(b+1.3*a,c,a,d)]},createSL:function(b,
c,a,d){return[this.createS(b,c,a,d),this.createL(b+1.3*a,c,a,d)]},createKG:function(b,c,a,d){var e;e=this.createK(b-a,c,a,d);b=this.createG(b+1.5*a,c,a,d);return[e,b[0],b[1]]},createKZ:function(b,c,a,d){return[this.createK(b-1.2*a,c,a,d),this.createZ(b,c,a,d)]},createLZ:function(b,c,a,d){return[this.createL(b-1.2*a,c,a,d),this.createZ(b,c,a,d)]},createVG:function(b,c,a,d){var e;e=this.createV(b-a,c,a,d);b=this.createG(b+1.2*a,c,a,d);return[e,b[0],b[1]]},createVA:function(b,c,a,d){return[this.createV(b,
c,a,d),this.createA(b+1.2*a,c,a,d)]},createBL:function(b,c,a,d){return[this.createB(new f(b,c),a,60),this.createL(b+.7*a,c,a,d)]},createDLNP:function(b,c,a,d){return[this.createDD(b-5*a,c,a,d),this.createL(b-2.8*a,c,a,d),this.createN(b-.8*a,c,a,d),this.createPP(b+.8*a,c,a,d)]},createLNP:function(b,c,a,d){return[this.createL(b-2.4*a,c,a,d),this.createN(b-.5*a,c,a,d),this.createPP(b+.8*a,c,a,d)]},createCLD:function(b,c,a,d){return[this.createCC(b-2.4*a,c,a,d),this.createL(b-1.3*a,c,a,d),this.createDD(b+
.5*a,c,a,d)]},createALD:function(b,c,a,d){return[this.createA(b-2.4*a,c,a,d),this.createL(b-1.3*a,c,a,d),this.createDD(b+.5*a,c,a,d)]},createBHOL:function(b,c,a,d,e){return[this.createB(new f(b-5*a,c),a,60),this.createH(b-2.8*a,c,a,d,e),this.createO(b-.8*a,c,a,d),this.createL(b+.8*a,c,a,d)]},createDash:function(b,c,a,d){var e=[];e.push(new f((b+(b+a/1.75))/2,(c+a+(c-a))/2,d));e.push(new f((b-a/1.75+b)/2,(c-a+(c+a))/2,d));return e},createH:function(b,c,a,d,e){e=[];e.push(new f(b-a/1.5,c-a,d));e.push(new f(b-
a/1.5,c+a,d));e.push(new f(b-.7*a,c,d));e.push(new f(b+.3*a,c,d));e.push(new f(b+a/4,c-a,d));e.push(new f(b+a/4,c+a,d));return e},createL:function(b,c,a,d){var e=[];e.push(new f(b,c-a,d));e.push(new f(b,c+a,d));e.push(new f(b,c-a,d));e.push(new f(b+a,c-a,d));return e},createD:function(b,c,a){a=[];a=a.concat(this.createHalfCircle(b,c,4.4,2,40));a.push(new f(b.x-c/3,b.y-c));a.push(new f(b.x-c/3,b.y+c));return a},createP:function(b,c,a){a=[];a=a.concat(this.createHalfCircle(new f(b.x-c/5.6,b.y+c/2,b.spatialReference),
c/2,4.4,2,40));a.push(new f(b.x-c/3,b.y-c));a.push(new f(b.x-c/3,b.y+c));return a},CATK:function(b,c,a,d){var e,f,g;e=this.createCC(b-1.67*a,c,a,d);f=this.createA(b-.5*a,c,a,d);g=this.createT(b+.83*a,c,a,d);b=this.createK(b+1.83*a,c,a,d);return[e,f,g,b]},createCC:function(b,c,a,d){for(var e=[],n=2*Math.PI/180,g=65*Math.PI/180;g<295*Math.PI/180;g+=n)e.push(new f(b+a*Math.cos(g),c-a*Math.sin(g),d));return e},createG:function(b,c,a,d){for(var e=[],n=[],g=2*Math.PI/180,h=65*Math.PI/180;h<295*Math.PI/
180;h+=g)e.push(new f(b+a*Math.cos(h),c-a*Math.sin(h),d));b=e[0];c=l.getMidPoint(b,e[e.length-1]);a=new f(c.x-.5*a,c.y,d);n.push(b);n.push(c);n.push(a);return[e,n]},createT:function(b,c,a,d){var e=[];e.push(new f(b,c-a,d));e.push(new f(b,c+a,d));e.push(new f(b,c+a,d));e.push(new f(b-.7*a,c+a,d));e.push(new f(b,c+a,d));e.push(new f(b+.7*a,c+a,d));return e},createJ:function(b,c,a,d){var e=[];e.push(new f(b-.5*a,c+a,d));e.push(new f(b+.5*a,c+a,d));e.push(new f(b,c+a,d));new f(b,c,d);b=new f(b-.5*a,c-
a/2,d);return e=e.concat(this.createHalfCircle(b,a/2,l.toRad(360),l.toRad(180),30))},createA:function(b,c,a,d){var e=[];e.push(new f(b-a/1.75,c-a,d));e.push(new f(b,c+a,d));e.push(new f(b+a/1.75,c-a,d));e.push(new f((b+(b+a/1.75))/2,(c+a+(c-a))/2,d));e.push(new f((b-a/1.75+b)/2,(c-a+(c+a))/2,d));return e},createAA:function(b,c,a,d){return[this.createA(b-1.3*a,c,a,d),this.createA(b+1.3*a,c,a,d)]},createAO:function(b,c,a,d){return[this.createA(b-1.3*a,c,a,d),this.createO(b+1.3*a,c,a,d)]},createUA:function(b,
c,a,d){return[this.createU(b-1.3*a,c,a,d),this.createA(b+.85*a,c,a,d)]},createNAI:function(b,c,a,d){return[this.createN(b-1.3*a,c,a,d),this.createA(b,c,a,d),this.createI(b+.8*a,c,a,d)]},createTAI:function(b,c,a,d){return[this.createT(b-1.3*a,c,a,d),this.createA(b,c,a,d),this.createI(b+.8*a,c,a,d)]},createZOR:function(b,c,a,d){return[this.createZ(b-1.8*a,c,a,d),this.createO(b,c,a,d),this.createR(b+1.2*a,c,a,d)]},createFAA:function(b,c,a,d){return[this.createF(b-1.8*a,c,a,d),this.createA(b,c,a,d),this.createA(b+
1.2*a,c,a,d)]},createFUP:function(b,c,a,d){return[this.createF(b-2.5*a,c,a,d),this.createU(b,c,a,d),this.createPP(b+1.7*a,c,a,d)]},createDAA:function(b,c,a,d){return[this.createDD(b-1.8*a,c,a,d),this.createA(b,c,a,d),this.createA(b+1.2*a,c,a,d)]},createOBJ:function(b,c,a,d){return[this.createO(b-1.5*a,c,a,d),this.createB(new f(b,c),a,60),this.createJ(b+1.5*a,c,a,d)]},createSAA:function(b,c,a,d){return[this.createS(b-1.6*a,c,a,d),this.createA(b,c,a,d),this.createA(b+1.6*a,c,a,d)]},createDA:function(b,
c,a,d){return[this.createDD(b-2*a,c,a,d),this.createA(b,c,a,d)]},createCAA:function(b,c,a,d){return[this.createCC(b-1.2*a,c,a,d),this.createA(b,c,a,d),this.createA(b+1.2*a,c,a,d)]},createBAA:function(b,c,a,d){return[this.createB(new f(b-a,c),a,60),this.createA(b,c,a,d),this.createA(b+1.2*a,c,a,d)]},createACP:function(b,c,a,d){return[this.createA(b-1.8*a,c,a,d),this.createCC(b,c,a,d),this.createPP(b+1.2*a,c,a,d)]},createZ:function(b,c,a,d){var e=[];e.push(new f(b,c+a,d));e.push(new f(b+a,c+a,d));e.push(new f(b,
c-a,d));e.push(new f(b+a,c-a,d));return e},createR:function(b,c,a,d){var e;e=this.createDD(b,c+a/2,a/2,d);e.push(new f(b-a/2/3,c,d));e.push(new f(b-a/2/3,c-a,d));e.push(new f(b-a/2/3,c,d));e.push(new f(b+a/2,c-a,d));return e},createK:function(b,c,a,d){var e=[];e.push(new f(b,c+a,d));e.push(new f(b,c-a,d));e.push(new f(b,c,d));e.push(new f(b+.8*a,c-a,d));e.push(new f(b,c,d));e.push(new f(b+.8*a,c+a,d));return e},createS:function(b,c,a,d){var e=[],n=2*Math.PI/180,g=a/2;e.push(new f(b+.3*a,c+a,d));e.push(new f(b,
c+a,d));for(var h=90*Math.PI/180;h<270*Math.PI/180;h+=n){var l=b+g*Math.cos(h),m=c+g+g*Math.sin(h);e.push(new f(l,m,d))}for(h=90*Math.PI/180;h>0*Math.PI/180;h-=n)l=b+g*Math.cos(h),m=c-g+g*Math.sin(h),e.push(new f(l,m,d));for(h=360*Math.PI/180;h>270*Math.PI/180;h-=n)l=b+g*Math.cos(h),m=c-g+g*Math.sin(h),e.push(new f(l,m,d));e.push(new f(b,c-a,d));e.push(new f(b-.3*a,c-a,d));return e},createO:function(b,c,a,d){for(var e=[],n=2*Math.PI/180,g=0*Math.PI/180;g<360*Math.PI/180;g+=n)e.push(new f(b+.5*a*Math.cos(g),
c-a*Math.sin(g),d));return e},arrowHead:function(b,c,a){var d=[];a+=15;var e=l.toDegrees(a);a=l.toDegrees(a-30);e=new f(b.x+c*Math.cos(l.toRad(e)),b.y+c*Math.sin(l.toRad(e)),b.spatialReference);c=new f(b.x+c*Math.cos(l.toRad(a)),b.y+c*Math.sin(l.toRad(a)),b.spatialReference);return d=d.concat(e,b,c)},arrowHeadBackward:function(b,c,a){var d=[];a+=100;var e=l.toDegrees(a);a=l.toDegrees(a-30);e=new f(b.x+c*Math.cos(l.toRad(e)),b.y+c*Math.sin(l.toRad(e)),b.spatialReference);c=new f(b.x+c*Math.cos(l.toRad(a)),
b.y+c*Math.sin(l.toRad(a)),b.spatialReference);return d=d.concat(e,b,c)},CreateArrowHeadPathEx:function(b,c,a,d,e,f,g){e*=d;d=1.1*e;b=l.twoPtsAngle(c,b);a=l.twoPtsAngle(c,a);var h=Math.abs(b-a)/2;Math.abs(b-a)>1.88*Math.PI&&(h+=Math.PI);var m=Math.asin(e*Math.sin(h+f/180*Math.PI)/Math.sqrt(e*e+d*d-2*d*e*Math.cos(h+f/180*Math.PI)))+f/180*Math.PI;g=0==g||void 0==g?e*Math.sin(Math.PI-m-h)/Math.sin(m):0;e=[];e.push({x:c.x+g*Math.cos(b),y:c.y+g*Math.sin(b)});e.push({x:c.x+d*Math.cos(b-f/180*Math.PI),y:c.y+
d*Math.sin(b-f/180*Math.PI)});e.push(c);e.push({x:c.x+d*Math.cos(a+f/180*Math.PI),y:c.y+d*Math.sin(a+f/180*Math.PI)});e.push({x:c.x+g*Math.cos(a),y:c.y+g*Math.sin(a)});return e},CreateBezierPathPCOnly:function(b,c){var a={x:b[0].x,y:b[0].y};b[b.length-1].x===b[b.length-2].x&&b[b.length-1].y===b[b.length-2].y&&b.pop();b[b.length-1].x===b[b.length-2].x&&b[b.length-1].y===b[b.length-2].y&&b.pop();for(var d=TweenMax.to(a,c,{bezier:b,ease:Linear.easeNone}),e=[],f=0;f<=c;f++)d.time(f),e.push({x:a.x,y:a.y});
return e},createI:function(b,c,a,d){var e=[];e.push(new f(b,c-a,d));e.push(new f(b,c+a,d));return e},createX:function(b,c,a,d){var e=[];e.push(new f(b-a/2,c-a,d));e.push(new f(b,c,d));e.push(new f(b+a/2,c+a,d));e.push(new f(b,c,d));e.push(new f(b+a/2,c-a,d));e.push(new f(b,c,d));e.push(new f(b-a/2,c+a,d));return e},createW:function(b,c,a,d){var e=[];e.push(new f(b-.7*a,c-a,d));e.push(new f(b-.7*a,c+a,d));e.push(new f(b-.7*a,c-a,d));e.push(new f(b,c,d));e.push(new f(b,c,d));e.push(new f(b+.7*a,c-a,
d));e.push(new f(b+.7*a,c-a,d));e.push(new f(b+.7*a,c+a,d));return e},createV:function(b,c,a,d){var e=[];e.push(new f(b-.7*a,c+a,d));e.push(new f(b,c-.9*a,d));e.push(new f(b+.7*a,c+a,d));return e},createDD:function(b,c,a,d){var e=[],l=2*Math.PI/180;e.push(new f(b-a/3,c+a,d));e.push(new f(b,c+a,d));for(var g=270*Math.PI/180;g<360*Math.PI/180;g+=l){var h=b+a*Math.cos(g),m=c-a*Math.sin(g);e.push(new f(h,m,d))}for(g=0*Math.PI/180;g<91*Math.PI/180;g+=l)h=b+a*Math.cos(g),m=c-a*Math.sin(g),e.push(new f(h,
m,d));e.push(new f(b-a/3,c-a,d));e.push(new f(b,c-a,d));e.push(new f(b-a/3,c-a,d));e.push(new f(b-a/3,c+a,d));return e},createPP:function(b,c,a,d){var e;e=this.createDD(b,c+a/2,a/2,d);e.push(new f(b-a/2/3,c,d));e.push(new f(b-a/2/3,c-a,d));return e},createWP:function(b,c,a,d){return[this.createW(b-.5*a,c,a,d),this.createPP(b+.7*a,c,a,d)]},createENY:function(b,c,a,d){return[this.createE(b-1.667*a,c,a,d),this.createN(b+.083*a,c,a,d),this.createY(b+1.38*a,c,a,d)]},createE:function(b,c,a,d){var e=[];
e.push(new f(b,c-a,d));e.push(new f(b,c+a,d));e.push(new f(b,c+a,d));e.push(new f(b+a,c+a,d));e.push(new f(b,c+a,d));e.push(new f(b,c,d));e.push(new f(b+.8*a,c,d));e.push(new f(b,c,d));e.push(new f(b,c-a,d));e.push(new f(b+a,c-a,d));return e},createF:function(b,c,a,d){var e=[];e.push(new f(b,c-a,d));e.push(new f(b,c+a,d));e.push(new f(b,c+a,d));e.push(new f(b+a,c+a,d));e.push(new f(b,c+a,d));e.push(new f(b,c,d));e.push(new f(b+.8*a,c,d));return e},createN:function(b,c,a,d){var e=[];e.push(new f(b-
.5*a,c-a,d));e.push(new f(b-.5*a,c+a,d));e.push(new f(b+.5*a,c-a,d));e.push(new f(b+.5*a,c+a,d));return e},createU:function(b,c,a,d){var e=[];e.push(new f(b+a/.97,c+a,d));e=e.concat(this.createHalfCircle(new f(b,c,d),a,l.toRad(360),l.toRad(180),40));e.push(new f(b-a,c+a/.97,d));e.push(e[e.length-1]);return e},createY:function(b,c,a,d){var e=[];e.push(new f(b,c,d));e.push(new f(b,c-a,d));e.push(new f(b,c,d));e.push(new f(b-.6*a,c+a,d));e.push(new f(b,c,d));e.push(new f(b+.6*a,c+a,d));return e},ownRotate:function(b,
c,a,d){for(var e=0;e<b.length;e++)b[e].x-=c;for(e=0;e<b.length;e++)b[e].y-=a;for(e=0;e<b.length;e++){var f=b[e].x,g=b[e].y;b[e].x=f*Math.cos(d)-g*Math.sin(d);b[e].y=f*Math.sin(d)+g*Math.cos(d)}for(e=0;e<b.length;e++)b[e].x+=c;for(e=0;e<b.length;e++)b[e].y+=a;return b},rotate:function(b,c,a,d){for(var e,f,g=0;g<b.length;g++)b[g].x-=c,b[g].y-=a,e=b[g].x,f=b[g].y,b[g].x=e*Math.cos(d)-f*Math.sin(d),b[g].y=e*Math.sin(d)+f*Math.cos(d),b[g].x+=c,b[g].y+=a;return b},createEchelon:function(b,c,a,d){var e=
[];switch(b){case "12":e=m.createSQUAD(c.x,c.y,a,c.spatialReference);break;case "120":e=m.createHollowOval(c.x,c.y,a,c.spatialReference);break;case "13":e=m.createSECTION(c.x,c.y,a,c.spatialReference);break;case "14":e=m.createPLATOON(c.x,c.y,a,c.spatialReference);break;case "15":e=m.createCoy(c.x,c.y,a,c.spatialReference);break;case "16":e=m.createBn(c.x,c.y,a,c.spatialReference);break;case "17":e=m.createREGIMENT(c.x,c.y,a,c.spatialReference);break;case "18":e=m.createBRIGADE(c.x,c.y,a,c.spatialReference);
break;case "21":e=m.createDIV(c.x,c.y,a,c.spatialReference);break;case "22":e=m.createCORPS(c.x,c.y,a,c.spatialReference);break;case "26":e=m.createComd(c.x,c.y,a,c.spatialReference)}if(void 0!==d){b=[];for(a=0;a<e.length;a++)b.push(this.rotate(e[a],c.x,c.y,d));return b}return e}}});
