import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
import Graphic from '@arcgis/core/Graphic';
import Point from '@arcgis/core/geometry/Point';
export type FactorId = 'obs' | 'fof' | 'cff' | 'cfv' | 'egr' | 'dg';
export type ScoreMap = Record<FactorId, number>;
export interface DefensibilitySummary {
    point: Point;
    scores: ScoreMap;
    composite: number;
    grade: string;
    label: string;
}
export interface DefensibilityScoreOptions {
    observerHeightM?: number;
    obsRadius?: number;
    slopeRadius?: number;
    rayResolutionDeg?: number;
    threatBearingDeg?: number;
    maxSlopeDeg?: number;
}
export declare class PosDefScorerEngine {
    static readonly OVERLAY_LAYER_ID = "pos-def-viewshed-overlay";
    static readonly SPOKES_LAYER_ID = "pos-def-los-spokes";
    static readonly POSITION_LAYER_ID = "pos-def-position-marker";
    static readonly EGRESS_LAYER_ID = "pos-def-egress-routes";
    static readonly HISTORY_LAYER_ID = "pos-def-position-history";
    private _view;
    private _overlayLayer;
    private _spokesLayer;
    private _posLayer;
    private _egrLayer;
    private _histLayer;
    private _mediaLayers;
    private _scorePanelEl;
    private _controlPanelEl;
    private _hintEl;
    private _clickHandle;
    private _currentPos;
    private _egressPts;
    private _history;
    private _running;
    private _addingEgress;
    constructor();
    initialize(view: MapView | SceneView): void;
    open(graphic: Graphic, view: MapView | SceneView): void;
    openWidget(view?: MapView | SceneView): void;
    scorePoint(point: Point, options?: DefensibilityScoreOptions): Promise<DefensibilitySummary>;
    close(): void;
    destroy(): void;
    private _createLayers;
    private _ensurePanels;
    private _scorePanelHtml;
    private _controlPanelHtml;
    private _sliderRow;
    private _weightRow;
    private _toggleRow;
    private _bindPanelEvents;
    private _bindMapClick;
    private _unbindMapClick;
    private _runAnalysis;
    private _scorePosition;
    private _drawRasterOverlay;
    private _buildViewshedCanvas;
    private _buildLOSSpokes;
    private _drawPosition;
    private _addEgressPoint;
    private _redrawEgressMarkers;
    private _drawEgressLines;
    private _updateScoreUI;
    private _drawRadar;
    private _renderHistory;
    private _renderEgressList;
    private _toggleEgressMode;
    private _clearAll;
    private _clearOverlays;
    private _computeComposite;
    private _weights;
    private _gradeDescription;
    private _goToPoint;
    private _showPanels;
    private _hidePanels;
    private _textSymbol;
    private _setStatus;
    private _setProgress;
    private _tick;
    private _el;
    private _input;
    private _button;
    private _num;
    private _checked;
    private _setText;
    private _setStyle;
    private _injectStyles;
}
export default PosDefScorerEngine;
