define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/Color dojo/_base/window dojo/has dojo/keys dojo/dom-construct dojo/dom-style esri/kernel esri/sniff esri/toolbars/_toolbar esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/graphic esri/geometry/jsonUtils esri/geometry/webMercatorUtils esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Multipoint esri/geometry/Rect dojo/i18n!esri/nls/jsapi dojo/on esri/layers/GraphicsLayer dojo/Evented esri/SnappingManager esri/geometry/Point dojo/dom-style dojox/gfx/Moveable dojox/gfx/matrix esri/lang esri/geometry/jsonUtils dojo/_base/json MilSymbologyExt/GeoTools".split(" "),
function(v,h,k,w,p,C,D,E,F,G,H,I,J,r,m,K,u,L,x,y,M,N,O,P,Q,R,z,S,q,T,A,n,U,V,W,B){return v([z],{declaredClass:"MilitarySymbology.Extensions.ControlPointsEditor",constructor:function(a,b,c,e){this._cpAnchors;this._toolbar=c;this._rotate=this._scale=!0;this._defaultEventArgs={};this._scaleEvent="Scale";this._rotateEvent="Rotate";this._uniformScaling=!0;this.map=a;this.cPoints=e;this._markerSymbol2=new r(r.STYLE_CROSS,15,new m(m.STYLE_SOLID,new p([0,0,0]),2),new p([255,0,255,.25]));this._markerSymbol=
new r(r.STYLE_CIRCLE,13,new m(m.STYLE_SOLID,new p([0,0,0]),2),new p([255,255,255,.25]));this._controlSymbol=new r(r.STYLE_CIRCLE,13,new m(m.STYLE_SOLID,new p([0,0,0]),2),new p([255,0,0,1]));this._lineSymbol=new m(m.STYLE_DASH,new p([64,64,64]),1);this._moveStartHandler=h.hitch(this,this._moveStartHandler);this._firstMoveHandler=h.hitch(this,this._firstMoveHandler);this._moveStopHandler=h.hitch(this,this._moveStopHandler);this._moveHandler=h.hitch(this,this._moveHandler);this._scaleStopHandler=h.hitch(this,
this._scaleStop);this._defaultEventArgs={};this._scratchGL=b;this._baseLinePts=[]},_scaleStop:function(a,b){},_move:function(a){this._startTx=a.graphic.getDojoShape().getTransform();var b=this._graphic;this._toolbar._geo&&x.geographicToWebMercator(a.graphic.geometry);var c=b.getDojoShape().getTransform();a.transform&&k.forEach(this._graphic.drawEssentials.controlPoints,function(b,d){var g=this._updateControlPt(this._graphic.geometry,b,c);this._graphic.drawEssentials.controlPoints[d].update(g.x,g.y);
console.log(this._graphic.drawEssentials.controlPoints[d]);B.displayPoint(a.target._map,this._graphic.drawEssentials.controlPoints[d])},this)},_setUp:function(a){this._graphic=void 0==this._graphic?this._setGraphic(a.graphic):this._graphic},_scaleRotateMove:function(a,b){var c,e=[],d;for(d in this._controlPoints)c=this._controlPoints[d],c=this._updateControlPoints(c,this._graphic.getDojoShape().getTransform(),this._graphic.getLayer()._div.getTransform()),e[d]=new q(c.x,c.y,this.map.spatialReference);
this._graphic.attributes.tempCpoints=e;this._graphic.drawEssentials.DRAW_TYPE=this._drawExtendType;e=[];if(this._graphic.drawEssentials.hasOwnProperty("BASE_LN_PTS")){for(d in this._baseLinePts)c=this._baseLinePts[d],c=this._updateControlPoints(c,this._graphic.getDojoShape().getTransform(),this._graphic.getLayer()._div.getTransform()),e[d]=new q(c.x,c.y,this.map.spatialReference);this._graphic.attributes.tempBpoints=e}},_onGraphicMove:function(a,b){},_setGraphic:function(a){this._graphic=a;a.drawEssentials.CTRL_PTS&&
(this._controlPoints=a.drawEssentials.CTRL_PTS);a.drawEssentials.BASE_LN_PTS&&(this._baseLinePts=a.drawEssentials.BASE_LN_PTS);a.drawEssentials.DRAW_TYPE&&(this._drawExtendType=a.drawEssentials.DRAW_TYPE)},activate:function(a){this._setGraphic(a);this.emit("cpActivate",{state:1,graphic:this._graphic});this._init()},_draw:function(){if(this._graphic.getDojoShape()){this._graphic.getDojoShape().moveToFront();var a=this._getBoxCoords(null,this.map),b=new y(this.map.spatialReference),c=h.clone(k.filter(a,
function(a,c){return 8!==c&&0===c%2}));c[0]&&c.push([c[0][0],c[0][1]]);b.addPath(c);this._rotate&&b.addPath([a[1],a[8]]);this._box?this._box.setGeometry(b):(this._box=new u(b,this._lineSymbol),this._scratchGL.add(this._box));this._controlPoints&&(this._cpAnchors?k.forEach(this._cpAnchors,function(a,c){var b=new q(this._cpAnchors[c].graphic.geometry,this.map.spatialReference);a.graphic.controlPoints=!0;a.graphic.setGeometry(b);var b=a.moveable,f=a.graphic.getDojoShape();f&&(b?f!==b.shape&&(b.destroy(),
a.moveable=this._getMoveable(a.graphic,c,!0,c)):a.moveable=this._getMoveable(a.graphic,c,!0,c))},this):(this._cpAnchors=[],this._connects=[],k.forEach(this._controlPoints,function(a,c){a=new q(a,this.map.spatialReference);var b=new u(a,this._controlSymbol);b.controlPoints=!0;this._scratchGL.add(b);this._cpAnchors.push({graphic:b,moveable:this._getMoveable(b,c,!0,c)})},this)))}},_getBoxCoords:function(a,b){var c=this._getTransformedBoundingBox(this._graphic),e=[],d,g,f;k.forEach(c,function(c,t,k){d=
c;(g=k[t+1])||(g=k[0]);f={x:(d.x+g.x)/2,y:(d.y+g.y)/2};a||(d=b.toMap(d),f=b.toMap(f));e.push([d.x,d.y]);e.push([f.x,f.y])});this._rotate&&(c=h.clone(e[1]),c=a?{x:c[0],y:c[1]}:this.map.toScreen({x:c[0],y:c[1],spatialReference:this.map.spatialReference}),c.y-=30,a||(c=this.map.toMap(c)),e.push([c.x,c.y]));return e},_getTransformedBoundingBox:function(a){var b=a.geometry.getExtent(),c=a.geometry.spatialReference;a=new q(b.xmin,b.ymax,c);b=new q(b.xmax,b.ymin,c);a=this.map.toScreen(a);b=this.map.toScreen(b);
return[{x:a.x,y:a.y},{x:b.x,y:a.y},{x:b.x,y:b.y},{x:a.x,y:b.y}]},_getMoveable:function(a,b,c,e){if(a=a.getDojoShape())return a=new A(a),a._index=b,a.controlPointIndex=e,a._control=c,a.onMoveStart=h.hitch(this,this._moveStartHandler),a.onFirstMove=h.hitch(this,this._firstMoveHandler),a.onMoveStop=h.hitch(this,this._moveStopHandler),a.onMove=h.hitch(this,this._moveHandler),a},_moveStartHandler:function(a){},_firstMoveHandler:function(a){var b=this._wrapOffset=a.host.shape._wrapOffsets[0]||0;a=this._graphic.getLayer()._div.getTransform();
var c;c=k.map(this._getBoxCoords(!0),function(a){return{x:a[0]+b,y:a[1]}});c={x:c[1].x,y:c[3].y};this._centerCoord=n.multiplyPoint(n.invert(a),c);this._controlPoints&&(this._cpScreen=[],k.forEach(this._controlPoints,function(a,c){this._cpScreen.push(this.map.toScreen(a))},this))},_moveHandler:function(a,b){var c=a.host._index,e=this._defaultEventArgs,d,g,f,l=0,t=0;e.angle=0;e.scaleX=1;e.scaleY=1;if(8!==c||a.host._control)if(a.host._control){var h=a.host.controlPointIndex;this._cpScreen[h].x+=b.dx;
this._cpScreen[h].y+=b.dy;this._controlPoints[h]=this.map.toMap(this._cpScreen[h]);this.emit("cpMoved",{graphic:this._graphic,drawEssentials:this._graphic.drawEssentials});this._draw();k.forEach(this._cpAnchors,function(a,c){if(c===h){var b=new q(this._controlPoints[h],this.map.spatialReference);a.graphic.controlPoints=!0;a.graphic.setGeometry(b);a.graphic.getDojoShape().moveToFront()}else b=a.graphic.getDojoShape(),null!==b&&b.moveToFront()},this);this._graphic.drawEssentials.CTRL_PTS=this._controlPoints}else{c=
this._startBox;d=this._moveBox;d.width+=b.dx*this._xfactor;d.height+=b.dy*this._yfactor;this._uniformScaling?(g=d.x+this._xfactor*d.width,d=d.y+this._yfactor*d.height,d=Math.sqrt((g-this._centerCoord.x)*(g-this._centerCoord.x)+(d-this._centerCoord.y)*(d-this._centerCoord.y)),g=f=d/this._firstMoverToCenter,l=this._xfactor*c.width/2,t=this._yfactor*c.height/2):(g=d.width/c.width,f=d.height/c.height);if(isNaN(g)||Infinity===g||-Infinity===g)g=1;if(isNaN(f)||Infinity===f||-Infinity===f)f=1;d=n.scaleAt(g,
f,c.x+l,c.y+t);this._graphic.getDojoShape().setTransform(d);e.transform=d;e.scaleX=g;e.scaleY=f;e.around={x:c.x+l,y:c.y+t}}else g=this._startLine,f=this._moveLine,l=f[1],l.x+=b.dx,l.y+=b.dy,f=this._getAngle(g,f),l=n.rotategAt(f,g[0]),this._graphic.getDojoShape().setTransform(l),e.transform=l,e.angle=f,e.around=g[0]},_moveStopHandler:function(a){this._graphic.drawEssentials.CTRL_PTS=this._controlPoints;this._graphic.drawEssentials.drawExtendType=this._drawExtendType;this._draw();var b=null;k.forEach(this._anchors,
function(a){b=a.graphic.getDojoShape();null!==b&&b.moveToFront()});b=null;k.forEach(this._cpAnchors,function(a){b=a.graphic.getDojoShape();null!==b&&b.moveToFront()})},_updateSegments:function(a,b,c,e,d){var g=this._wrapOffset||0;k.forEach(b,function(b){k.forEach(b,function(b){var f=a.toScreen({x:b[0],y:b[1],spatialReference:d},!0);f.x+=g;f=n.multiplyPoint([e,c,n.invert(e)],f);f.x-=g;f=a.toMap(f);b[0]=f.x;b[1]=f.y})})},_updateControlPt:function(a,b,c){a=a.getPoint(0,0);var e=this.map.toMap(this.map.toScreen(a).offset(c.dx,
c.dy));c=e.x-a.x;return b=b.offset(c,e.y-a.y)},_updateControlPoints:function(a,b,c){var e=this._wrapOffset||0;a=this.map.toScreen(a,!0);a.x+=e;a=n.multiplyPoint([c,b,n.invert(c)],a);a.x-=e;return a=this.map.toMap(a)},_getAngle:function(a,b){return 180*Math.atan2(b[0].y-b[1].y,b[0].x-b[1].x)/Math.PI-180*Math.atan2(a[0].y-a[1].y,a[0].x-a[1].x)/Math.PI},_init:function(){this._draw()},deactivate:function(a){this.emit("cpDeActivate",{state:0,graphic:this._graphic});this._cleanUp(a);this._removeEvents()},
_cleanUp:function(a){this._connects&&k.forEach(this._connects,w.disconnect);this._anchors&&k.forEach(this._anchors,function(b){a.remove(b.graphic);(b=b.moveable)&&b.destroy()});this._cpAnchors&&k.forEach(this._cpAnchors,function(b){a.remove(b.graphic);(b=b.moveable)&&b.destroy()});this._box&&a.remove(this._box);this._box=this._anchors=this._connects=this._cpAnchors=null},_removeEvents:function(){}})});
