define("esri/geometry/Polyline esri/graphic esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/geometry/Circle esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/Color esri/layers/GraphicsLayer esri/symbols/SimpleFillSymbol esri/geometry/geometryEngine esri/units esri/geometry/ScreenPoint esri/geometry/Multipoint esri/geometry/Extent esri/layers/FeatureLayer esri/renderers/HeatmapRenderer esri/tasks/FeatureSet esri/symbols/TextSymbol dojo/fx dojox/gfx/fx dojo/_base/lang dojo/aspect".split(" "),
function(w,u,m,z,v,C,D,A,E,F,I,B,R,t,J,G,H,K,L,M,N,O,P,Q){return{angleInRadians:function(a,b){return Math.atan2(b.y-a.y,b.x-a.x)},angleInDegrees:function(a,b){return 180*Math.atan2(b.y-a.y,b.x-a.x)/Math.PI},twoPtsAngle:function(a,b){var c=Math.acos((b.x-a.x)/this._2PtLen(a,b));b.y<a.y&&(c=2*Math.PI-c);return!0===isNaN(c)?0:c},toDegrees:function(a){a=((180/Math.PI*a+360)%360).toFixed(1);isNaN(a)&&(a=0);return a},toRad:function(a){return Math.PI/180*a},degreesToRadians:function(a){return a%360*Math.PI/
180},radiansToDegrees:function(a){return a%(2*Math.PI)*180/Math.PI},displayPoint:function(a,b){this._markerSymbol=new D;a.graphics.add(new u(new m(b.x,b.y,a.spatialReference),this._markerSymbol))},displayPointText:function(a,b,c){a.graphics.add(new u(new m(b.x,b.y,a.spatialReference),new M(c)));this._markerSymbol=new D(D.STYLE_CROSS,10,new A(A.STYLE_SOLID,new E([255,0,0]),1),new E([0,255,0]));a.graphics.add(new u(new m(b.x,b.y,a.spatialReference),this._markerSymbol))},getMidPoint:function(a,b){var c=
[],d=new w(map.spatialReference),c=c.concat(a,b);d.addPath(c);return d.getExtent().getCenter()},_calculateMidPoint:function(a,b){return new m((a.x+b.x)/2,(a.y+b.y)/2,map.spatialReference)},getLastPtFromPoly:function(a){var b=a.paths.length-1;return a.getPoint(b,a.paths[b].length-1)},getLastPtFromPolygon:function(a){var b=a.rings.length-1;return a.getPoint(b,a.rings[b].length-1)},addAllRings:function(a,b){for(var c=0;c<a.length;c++)b.addRing(a[c]);return b},setDefault:function(a,b,c){a=a.hasOwnProperty(b)?
a[b]:c;return void 0===a?c:a},factors:{centimeters:637100880,centimetres:637100880,degrees:57.22891354143274,feet:2.0902260511392E7,inches:6371008.8*39.37,kilometers:6371.0088,kilometres:6371.0088,meters:6371008.8,metres:6371008.8,miles:3958.761333810546,millimeters:6371008800,millimetres:6371008800,nauticalmiles:6371008.8/1852,radians:1,yards:6371008.8/1.0936},destination:function(a,b,c,d){var e=Math.PI/180,f=180/Math.PI,g=e*a.x;a=e*a.y;c*=e;b=this.distanceToRadians(b,d);d=Math.asin(Math.sin(a)*
Math.cos(b)+Math.cos(a)*Math.sin(b)*Math.cos(c));return new m(f*(g+Math.atan2(Math.sin(c)*Math.sin(b)*Math.cos(a),Math.cos(b)-Math.sin(a)*Math.sin(d))),f*d)},distanceToRadians:function(a,b){if(void 0===a||null===a)throw Error("Distance is Required");if(b&&"string"!==typeof b)throw Error("Units must be a string");var c=this.factors[b||"kilometers"];if(!c)throw Error(b+"units is invalid");return a/c},radiansToLength:function(a,b){var c=this.factors[b];if(!c)throw Error(b+" units is invalid");return a*
c},distance:function(a,b,c){var d=this.degreesToRadians(b.y-a.y),e=this.degreesToRadians(b.x-a.y);a=this.degreesToRadians(a.y);b=this.degreesToRadians(b.y);d=Math.pow(Math.sin(d/2),2)+Math.pow(Math.sin(e/2),2)*Math.cos(a)*Math.cos(b);return this.radiansToLength(2*Math.atan2(Math.sqrt(d),Math.sqrt(1-d)),c)},bearing:function(a,b,c){void 0===c&&(c=!1);if(!0===c)return this.calculateFinalBearing(a,b);c=this.degreesToRadians(a.x);var d=this.degreesToRadians(b.x);a=this.degreesToRadians(a.y);b=this.degreesToRadians(b.y);
return this.radiansToDegrees(Math.atan2(Math.sin(d-c)*Math.cos(b),Math.cos(a)*Math.sin(b)-Math.sin(a)*Math.cos(b)*Math.cos(d-c)))},calculateFinalBearing:function(a,b){return(this.bearing(b,a)+180)%360},_calculateAngle:function(a,b){var c=180*Math.atan2(b.x-a.x,b.y-a.y)/Math.PI-90;-90>c&&(c+=180);return c},translateGeometry:function(a,b){var c,d,e;if("polyline"===a.type){c=new v(a.paths);c=c.getExtent().getCenter(c);for(var f=0;f<a.paths.length;f++)for(var g=0;g<a.paths[f].length;g++)d=a.paths[f][g][0]-
c.x,e=a.paths[f][g][1]-c.y,a.paths[f][g][0]=b.x+d,a.paths[f][g][1]=b.y+e}else if("polygon"===a.type)for(c=new v(a.rings),c=c.getExtent().getCenter(),f=0;f<a.rings.length;f++)for(g=0;g<a.rings[f].length;g++)d=a.rings[f][g][0]-c.x,e=a.rings[f][g][1]-c.y,a.rings[f][g][0]=b.x+d,a.rings[f][g][1]=b.y+e;else"point"===a.type&&(a=this.translatePts(a,a,b));return a},translatePts:function(a,b,c){for(var d=0;d<a.length;d++)x=a[d].x-b.x,y=a[d].y-b.y,a[d].x=c.x+x,a[d].y=c.y+y;return a},movePt:function(a,b,c){var d=
new m(b.spatialReference);d.x=c.x-b.x;d.y=c.y-b.y;a.x+=d.x;a.y+=d.y;return new m(a.x,a.y,b.spatialReference)},moveGeometry:function(a,b,c){var d=new m(b.spatialReference);d.x=c.x-b.x;d.y=c.y-b.y;if("polyline"===a.type)for(b=0;b<a.paths.length;b++)for(c=0;c<a.paths[b].length;c++)a.paths[b][c][0]+=d.x,a.paths[b][c][1]+=d.y;else if("polygon"===a.type)for(b=0;b<a.rings.length;b++)for(c=0;c<a.rings[b].length;c++)a.rings[b][c][0]+=d.x,a.rings[b][c][1]+=d.y;else"point"===a.type&&(a=this.movePt(a,b,c));return a},
getCenteroid:function(a,b){for(var c=[],d=0;d<=a.length-1;d++)c.push([a[d].x,a[d].y]);return(1===b?new v(c):new z(c)).getExtent().getCenter()},createPolyFromObject:function(a){for(var b=[],c=0;c<a.length;c++)b.push({x:a[c][0],y:a[c][1]});return b},_2PtLen:function(a,b){if(void 0!=a&&void 0!=b)return Math.sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y))},twoPtsRelationShip:function(a,b){return b.x>a.x&&b.y>=a.y?"ne":b.x<=a.x&&b.y>a.y?"nw":b.x<a.x&&b.y<=a.y?"sw":"se"},getArea:function(a){return void 0!==
a?a.getWidth()*a.getWidth():0},getPolylineCenter:function(a){var b=a.paths[a.paths.length/2],c=(b.length-1)/2;a=b[c];b=b[c+1];return new m((a[0]+b[0])/2,(a[1]+b[1])/2)},ArrowFlanksLen:function(a,b){return a/10>=b/2.8?b/2.8:a/10},_fracturePts:function(a,b,c,d){var e=new w(d),f=this._2PtLen(a,b),g=this.getMidPoint(a,b);d=[];f/=c;k=this.angleInRadians(a,b);c={x:f*Math.cos(k)+g.x,y:f*Math.sin(k)+g.y};d=d.concat(a,{x:-1*f*Math.cos(k)+g.x,y:-1*f*Math.sin(k)+g.y});e.addPath(d);d=[];d=d.concat(c,b);e.addPath(d);
return{geometry:e,midPoint:g,len:f}},getFracturedPts:function(a,b,c){},_fracture:function(a,b,c){var d=new w(c),e,f,g,h;if(1>=a.length)throw"points.length <= 1";f=[];for(var l=0;l<a.length-1;l++)for(g=a[l],void 0!=a[l+1]&&(h=a[l+1]),e=this._fracturePts(g,h,b,c),g=e.geometry.paths,f.push({midPt:e.midPoint,len:e.len}),e=0;e<g.length;e++)d.addPath(g[e]);return{geometry:d,midPoints:f}},dashedLine:function(a,b,c){var d=[];c||(c=[10,5]);var e=c.length,f=b.x-a.x,g=b.y-a.y;b=f?g/f:1E15;for(var g=Math.sqrt(f*
f+g*g),h=0;.1<=g;){var l=c[h++%e];l>g&&(l=g);var m=Math.sqrt(l*l/(1+b*b));0>f&&(m=-m);a.x+=m;a.y+=b*m;d.push({0:a.x,1:a.y});g-=l}return d},createHalfCircle:function(a,b,c,d,e){var f=[];e=2*Math.PI/e;for(var g=a.x,h=a.y;c<2*Math.PI+d;c+=e)f.push(new m(g+b*Math.cos(c),h-b*Math.sin(c),a.spatialReference));return f},createDashLines:function(a,b){for(var c=[],d={},e={},f=0;f<a.length;f++)d.x=a[f].x,d.y=a[f].y,e.x=a[f+1].x,e.y=a[f+1].y,c=c.concat(this.dashedLine(d,e,b)),f++;return c},_vertexAngle:function(a){for(var b=
[],c=[],d=0,e=a.length-1;d<e;d++){var f=this.twoPtsAngle(a[d],a[d+1]);b.push(f)}f=this.twoPtsAngle(a[0],a[1]);c.push(f+Math.PI/2);for(d=1;d<e;d++)f=(b[d-1]+b[d])/2,b[d-1]<Math.PI&&b[d]-Math.PI>b[d-1]?f+=Math.PI:b[d-1]>Math.PI&&b[d]<b[d-1]-Math.PI&&(f+=Math.PI),f+=Math.PI/2,c.push(f);return c},_ptCollectionLen:function(a,b){for(var c=0,d=b,e=a.length-1;d<e;d++)c+=this._2PtLen(a[d],a[d+1]);return c},getDashPts:function(a,b,c){for(var d=[],e=0;e<a.length;e++)p1=a[e],void 0!=a[e+1]&&(p2=a[e+1],d=d.concat(this.dashes(p1.x,
p1.y,p2.x,p2.y,b,c)));return d},dashes:function(a,b,c,d,e,f){var g=[];e||(e=[10,5]);var h=e.length;g.push(new m(a,b));c-=a;f=d-b;d=c?f/c:1E15;var l=Math.sqrt(c*c+f*f),p=0;for(f=e[p++%h];l>f;){f>l&&(f=l);var n=Math.sqrt(f*f/(1+d*d));0>c&&(n=-n);a+=n;b+=d*n;g.push(new m(a,b));l-=f;f=e[p++%h]}return g},getDashPtsWithAngles:function(a,b){for(var c=[],d=0;d<a.length;d++)p1=a[d],void 0!=a[d+1]&&(p2=a[d+1],c.push({midPt:this.dashesWithAngles(p1.x,p1.y,p2.x,p2.y,b),angle:this.twoPtsAngle(p1,p2)}));return c},
dashesWithAngles:function(a,b,c,d,e){var f=[];e||(e=[10,5]);var g=e.length;f.push(new m(a,b));c-=a;var h=d-b;d=c?h/c:1E15;for(var h=Math.sqrt(c*c+h*h),l=0,p=e[l++%g];h>p;){p>h&&(p=h);var n=Math.sqrt(p*p/(1+d*d));0>c&&(n=-n);a+=n;b+=d*n;f.push(new m(a,b));h-=p;p=e[l++%g]}return f},_circleDrawEx:function(a,b,c){var d,e;e=[[0,0,0],[0,0,0],[0,0,0]];var f=[[a.x,a.y],[b.x,b.y],[c.x,c.y]];for(d=0;3>d;d++)e[d][0]=f[d][0],e[d][1]=f[d][1],e[d][2]=1;a=this._determinantDrawEx(e,3);for(d=0;3>d;d++)e[d][0]=f[d][0]*
f[d][0]+f[d][1]*f[d][1],e[d][1]=f[d][1],e[d][2]=1;b=this._determinantDrawEx(e,3);for(d=0;3>d;d++)e[d][0]=f[d][0]*f[d][0]+f[d][1]*f[d][1],e[d][1]=f[d][0],e[d][2]=1;c=this._determinantDrawEx(e,3);for(d=0;3>d;d++)e[d][0]=f[d][0]*f[d][0]+f[d][1]*f[d][1],e[d][1]=f[d][0],e[d][2]=f[d][1];e=this._determinantDrawEx(e,3);if(0==a)e=0;else{var g=.5*b/a,h=-.5*c/a;e=Math.sqrt(g*g+h*h+e/a)}return{radius:e,center:{x:g,y:h}}},_determinantDrawEx:function(a,b){var c,d,e,f,g,h=[[0,0,0],[0,0,0],[0,0,0]];if(2==b)g=a[0][0]*
a[1][1]-a[1][0]*a[0][1];else for(e=g=0;e<b;e++){for(c=1;c<b;c++)for(d=f=0;d<b;d++)d!=e&&(h[c-1][f]=a[c][d],f++);g+=Math.pow(-1,e)*a[0][e]*this._determinantDrawEx(h,b-1)}return g},CreateCircleSegmentFromThreePoints:function(a,b,c,d,e,f){var g=a.center,h=a.radius;a=[];b.x-=g.x;b.y-=g.y;c.x-=g.x;c.y-=g.y;d.x-=g.x;d.y-=g.y;b=Math.atan2(b.y,b.x);var l=Math.atan2(c.y,c.x);c=Math.atan2(d.y,d.x);b=0>b?2*Math.PI+b:b;l=0>l?2*Math.PI+l:l;c=0>c?2*Math.PI+c:c;d=Math.min(b,l);b=Math.max(b,l);l=b-d;if(c<d||c>b)l-=
2*Math.PI;b=l/e;for(l=0;l<=e;l++)c=f.toMap({x:h*Math.cos(d+l*b)+g.x,y:h*Math.sin(d+l*b)+g.y}),a.push(c);f=new w(f.spatialReference);f.addPath(a);return{geometry:f,lastPoint:a[e],backPoint:a[e-5]}},getHeatMapLayer:function(a,b,c,d,e){var f=new L;f.features=a;f.geometryType="esriGeometryPoint";a=new H({objectIdField:"OBJECTID",layerDefinition:{geometryType:"esriGeometryPoint",fields:[{name:"OBJECTID",type:"esriFieldTypeOID"},{name:b,type:"esriFieldTypeDouble"}]},featureSet:f},{mode:H.MODE_SNAPSHOT,
outFields:[b],blurRadius:e,maxPixelIntensity:d,minPixelIntensity:c});b=new K({field:b,colorStops:[{ratio:0,color:"rgba(250,0,255,0)"},{ratio:.25,color:"rgb(0,0,255)"},{ratio:.5,color:"rgb(0,255,0)"},{ratio:.75,color:"rgb(255,255,0)"},{ratio:1,color:"rgb(255,0,0)"}]});a.setRenderer(b);return a},_calculateMidPointWithOffset:function(a,b){var c=(a.x+b.x)/2,d=(a.y+b.y)/2,e=this._calculateDistanceFromPixels(10),f=a.x-b.x,g=f/(a.y-b.y),e=Math.sqrt(Math.abs(Math.pow(e,2)-Math.pow(f,2)))/g+c;return new m(e,
g*(e-c)+d,this.map.spatialReference)},_calculateDistanceFromPixels:function(a){var b=this.map.toScreen(this.map.extent.getCenter()),c=new m(b.x-a,b.y-a);a=new m(b.x+a,b.y+a);c=this.map.toMap(c);a=this.map.toMap(a);return(new G(c.x,c.y,a.x,a.y,this.map.spatialReference)).getWidth()},getCenterOfExtent:function(a){return new m(a.xmax-(a.xmax-a.xmin)/2,a.ymax-(a.ymax-a.ymin)/2,a.spatialReference)},getMidpointTop:function(a){return new m(a.xmax-(a.xmax-a.xmin)/2,a.ymax,a.spatialReference)},getMidpointBottom:function(a){return new m(a.xmax-
(a.xmax-a.xmin)/2,a.ymin,a.spatialReference)},getMidpointLeft:function(a){return new m(a.xmax-(a.xmax-a.xmin),a.ymax-(a.ymax-a.ymin)/2,a.spatialReference)},getMidpointRight:function(a){return new m(a.xmax,a.ymax-(a.ymax-a.ymin)/2,a.spatialReference)},getLowerLeft:function(a){return new m(a.xmin,a.ymin,a.spatialReference)},getUpperLeft:function(a){return new m(a.xmin,a.ymax,a.spatialReference)},getLowerRight:function(a){return new m(a.xmax,a.ymin,a.spatialReference)},getUpperRight:function(a){return new m(a.xmax,
a.ymax,a.spatialReference)},getTopLeftQuadrant:function(a){return this.createExtentEnvelope(this.getMidpointLeft(),this.getMidpointTop())},getTopRightQuadrant:function(a){return this.createExtentEnvelope(this.getCenterOfExtent(),this.getUpperRight())},getBottomLeftQuadrant:function(a,b){return this.createExtentEnvelope(a,this.getLowerLeft(b),this.getCenterOfExtent(b))},getBottomRightQuadrant:function(a,b){return this.createExtentEnvelope(a,this.getMidpointBottom(b),this.getMidpointRight(b))},getQuardrants:function(a,
b){return{topLeft:this.getTopLeftQuadrant(),topRight:this.getTopRightQuadrant(),bottomLeft:this.getBottomLeftQuadrant(a),bottomRight:this.getBottomRightQuadrant(a)}},createExtentEnvelope:function(a,b,c){return new G({xmin:b.x,ymin:b.y,xmax:c.x,ymax:c.y,spatialReference:{wkid:a.spatialReference}})},generateRandomPoints:function(a,b,c){for(var d=[],e=0;e<c;e++)d.push(this.generateRandomPoint(a,b));return d},generateRandomPoint:function(a,b){var c=a.y,d=b/111300*Math.sqrt(Math.random()),e=2*Math.PI*
Math.random();return new m(d*Math.cos(e)/Math.cos(c)+a.x,d*Math.sin(e)+c,a.spatialReference)},generateRandomLocations:function(a,b,c,d){for(var e=[],f=0;f<c;f++)e.push(this.getRandomLocation(a.x,a.y,b,d));return e},animate_graphics_as_flag:function(a,b,c,d){var e=new F;e.id="graphicsLayer1";a.addLayer(e);e=new F;e.id="ladderingLayer";a.addLayer(e);void 0===d&&(d=500);e=b.length;c=new C({center:c.center,radius:c.radius,numberOfPoints:b.length,radiusUnit:c.radiusUnit});for(var f=0;f<=b.length;f++)this.animate_feature_in_flag(a,
b[f],c,e,f,d)},animate_feature_in_flag:function(a,b,c,d,e,f){var g=a.getLayer("graphicsLayer1"),h=this.getLadderExtent(a,g.graphics,a.spatialReference);c=new u(h,new I);d=a.getLayer("ladderingLayer");d.add(c);e=this.getPtDistance(h.getPoint(0,0),h.getPoint(0,1));f=this.getPtDistance(h.getPoint(0,2),h.getPoint(0,3));this.displayPointText(a,h.getPoint(0,0),"L1");this.displayPointText(a,h.getPoint(0,1),"L2");this.displayPointText(a,h.getPoint(0,2),"W1");this.displayPointText(a,h.getPoint(0,3),"W2");
var l=this.getPtDistance(new m(a.extent.xmax,a.extent.ymin,a.spatialReference),new m(a.extent.xmin,a.extent.ymax,a.spatialReference));b=this.getPtDistance(new m(a.extent.xmax,a.extent.ymin,a.spatialReference),new m(a.extent.xmax,a.extent.ymax,a.spatialReference));var h=Math.ceil(l/e),p=Math.ceil(b/f);console.log(l);console.log(b);console.log("Total Dabbay L "+l/e);console.log("Total Dabbay W "+b/f);b=a.toMap(new t(0,0));for(var g=a.toMap(new t(0,0)),n=0;n<=p+2;n++){for(l=0;l<h;l++)this.displayPointText(a,
g,"RP "+l),g=this.destination(g,e,180,"meters");b=g=this.destination(b,f,90,"meters")}var q=a.toMap(new t(0,0));this.displayPointText(a,q,"START");for(var g=a.getLayer("graphicsLayer1"),r,l=0;l<g.graphics.length;l++)b=g.graphics[l],r=this.getSymbolSize(b.drawEssentials.SIDC,{size:b.drawEssentials.OPTIONS.size}),n=r.width,r=r.height,q=a.toScreen(q),q.x+=1.5*n,q.y-=1.1*r,r=a.toMap(q),this.displayPointText(a,r,l),b.setGeometry(new m(r.x,r.y,a.spatialReference)),b.draw(),q.x-=1.5*n,q=r=a.toMap(q);this.displayPointText(a,
new m(a.extent.xmin,a.extent.ymin,a.spatialReference),"BL");this.displayPointText(a,new m(a.extent.xmin,a.extent.ymax,a.spatialReference),"TL");this.displayPointText(a,new m(a.extent.xmax,a.extent.ymax,a.spatialReference),"TR");this.displayPointText(a,new m(a.extent.xmax,a.extent.ymin,a.spatialReference),"BR");b=new m(a.extent.xmin,a.extent.ymax,a.spatialReference);g=new m(a.extent.xmin,a.extent.ymax,a.spatialReference);this.displayPointText(a,b,"0");for(n=1;n<=p+1;n++)for(b=this.destination(b,f,
90,"meters"),this.displayPointText(a,b,""),0!==n&&(g=b),l=1;l<h-2;l++)g=this.destination(g,e,180,"meters"),this.displayPointText(a,g,"**");b=a.toMap(new t(0,0));this.displayPointText(a,b,"0");for(n=1;n<=p+2;n++)b=this.destination(b,f,90,"meters"),this.displayPointText(a,b,n);g=a.toMap(new t(0,0));g=this.destination(g,e,180,"meters");this.displayPointText(a,g,"0");for(n=1;n<=h+2;n++)g=this.destination(g,e,90,"meters"),this.displayPointText(a,g,n);d.add(c)},animate_laddering:function(a,b,c,d,e,f,g){if("textsymbol"!==
e.symbol.type){void 0===g&&(g=!1);void 0===f&&(f=500);var h=[];e=this.get_graphic_extent(a,e).polygon;for(var l,m=0;m<c.graphics.length;m++)l=!0===g&&"FPoint"===c.graphics[m].drawEssentials.SYM_GEO_TYPE&&"10"===c.graphics[m].drawEssentials.SIDC.substr(4,2)?this.get_graphic_extent(a,c.graphics[m]):!1===g?this.get_graphic_extent(a,c.graphics[m]):void 0,void 0===l||B.disjoint(l.polygon,e)||(e=B.union([l.polygon,e]),h.push(c.graphics[m]));1<h.length&&this.animate_graphics_in_ladder(a,d,h,f,b)}},animate_cartwheel:function(a,
b,c,d){if("textsymbol"!==d.symbol.type){for(var e=[],f=this.get_graphic_extent(a,d).polygon,g=0;g<b.graphics.length;g++){var h=this.get_graphic_extent(a,b.graphics[g]);void 0===h||B.disjoint(h.polygon,f)||(f=B.union([h.polygon,f]),e.push(b.graphics[g]))}1<e.length&&(b=new C({center:d.geometry,radius:a.getScale()/1E3*e.length*2,numberOfPoints:e.length,radiusUnit:"esriMeters"}),this.animate_graphics_in_circle(a,c,e,b))}},get_graphic_extent:function(a,b){var c,d,e,f,g={},h={};if("textsymbol"!==b.symbol.type){if("Point"===
b.drawEssentials.SYM_GEO_TYPE)e=a.toScreen(b.geometry),c=e.x,d=e.y,f=e=b.symbol.size;else if("FPoint"===b.drawEssentials.SYM_GEO_TYPE){if(null===b.getDojoShape())return;e=a.toScreen(b.geometry);c=e.x;d=e.y;f=this.getSymbolSize(b.drawEssentials.SIDC,{size:b.drawEssentials.OPTIONS.size});e=f.height;f=f.width}else return;c=new t(c,d);d=a.toMap(c);g.TL={x:c.x,y:c.y};h.TL={x:d.x,y:d.y};d=new t(c.x,c.y+e);var l=a.toMap(d);g.BL={x:d.x,y:d.y};h.BL={x:l.x,y:l.y};d=new t(c.x+f,c.y);l=a.toMap(d);g.TR={x:d.x,
y:d.y};h.TR={x:l.x,y:l.y};c=new t(c.x+f,c.y+e);d=a.toMap(c);g.BR={x:c.x,y:c.y};h.BR={x:d.x,y:d.y};c=new v(a.spatialReference);c.addRing([h.TL,h.TR,h.BR,h.BL,h.TL]);return{screen_coords:g,map_coords:h,polygon:c,height:e,width:f}}},animate_graphics_in_ladder:function(a,b,c,d,e){void 0===d&&(d=500);var f;f=a.getScale()/800*c.length*2;f=this.destination(e,f,60,"meters");for(var g=this.getLadderExtent(a,f,c),h=0;h<c.length;h++)this.animate_feature(a,b,c[h],g.locs,c.length,h,d);b=[];for(c=0;c<g.locs.points.length;c++)d=
new m(g.locs.points[c][0],g.locs.points[c][1],a.spatialReference),b.push(d);b.push(f);b.push(e);e=new A(A.STYLE_SOLID,new E([255,0,0,.5]),2);f=new z(a.spatialReference);f.addPath(b);e=new u(f,e);a.graphics.add(e)},animate_graphics_in_circle:function(a,b,c,d,e){if("esri.geometry.Circle"===d.declaredClass){void 0===e&&(e=500);var f=c.length;d=new C({center:d.center,radius:d.radius,numberOfPoints:c.length,radiusUnit:d.radiusUnit});for(var g=0;g<c.length;g++)this.animate_feature(a,b,c[g],d,f,g,e)}},animate_feature:function(a,
b,c,d,e,f,g){if(c.getShape()){var h=c.geometry;"multipoint"===d.type?d=d.getPoint(f):(e=0===f?0:Math.floor(d.rings[0].length/e),d=new m(d.rings[0][e*f]));this.animate_transform_graphic(a,b,c,h,d,g);if("Point"===c.drawEssentials.SYM_GEO_TYPE&&(c=this.get_child_labels(b,c.id),0<c.length))for(h=0;h<c.length;h++)f=c[h],e=a.toScreen(d).offset(f.symbol.xoffset,f.symbol.yoffset),this.animate_transform_graphic(a,b,f,f.geometry,a.toMap(e),g)}},animate_transform_graphic:function(a,b,c,d,e,f){if(b=c.getShape()){d=
a.toScreen(d);var g=a.toScreen(e);a=O.animateTransform({duration:f,shape:b,transform:[{name:"translate",start:[0,0],end:[g.x-d.x,g.y-d.y]},{name:"original"}],onEnd:P.hitch([a,c,e],function(){})});a=N.combine([a]).play();Q.after(a,"onEnd",function(a){})}},get_child_labels:function(a,b){var c=[];for(i=a.graphics.length-1;0<=i;i--)a.graphics[i].parentId==b&&c.push(a.graphics[i]);return c},getLadderExtent:function(a,b,c){var d,e,f,g=[],h=new v(a.spatialReference),l,p=new J(a.spatialReference);for(e=0;e<
c.length;e++)d=c[e],f="Point"===d.drawEssentials.SYM_GEO_TYPE?this.get_graphic_extent(a,d):this.getSymbolSize(d.drawEssentials.SIDC,{size:d.drawEssentials.OPTIONS.size}),d=f.width,f=f.height,b=a.toScreen(b),b.x+=1.5*d,b.y-=1.5*f,b.x-=1.5*d,g.push(1.5*d),b=a.toMap(b),p.addPoint(new m(b.x,b.y,a.spatialReference)),0===e&&(l=new m(b.x,b.y,a.spatialReference));b=a.toScreen(b);b.y-=f;b=a.toMap(b);c=new m(b.x,b.y,a.spatialReference);g=g.sort()[g.length-1];e=a.toScreen(b);e.x+=2*g;e=a.toMap(e);b=a.toScreen(l);
b.x+=2*g;b=a.toMap(b);h.addRing([b,l,c,e,b]);return{resPlgn:h,locs:p}},getSymbolSize:function(a,b){var c=(new MS.symbol(a,b)).getMarker();return{height:c.height,width:c.width}},getPtDistance:function(a,b){return this.distance(a,b,"meters")},createFishNet:function(a,b){var c,d;c=new m(a.xmin,a.ymax);d=new m(a.xmax,a.ymin);var e=Math.floor(c.x,b),f=Math.ceil(d.x,b),g=Math.floor(d.y,b);c=Math.ceil(c.y,b);e=parseFloat(e);c=parseFloat(c);f=parseFloat(f);g=parseFloat(g);b=parseFloat(b);d=[];for(var h=e+
b/2;h<f;h+=b){var l=new z;l.addPath([[h,g],[h,c]]);d.push(l)}for(g+=b/2;g<c;g+=b)h=new z,h.addPath([[e,g],[f,g]]),d.push(h);return d},getRandomLocation:function(a,b,c,d){var e=Math.random(),f=Math.random();d&&f<e&&(d=f,f=e,e=d);return new m(a+f*c*Math.cos(2*Math.PI*e/f)/6378137*(180/Math.PI),b+f*c*Math.sin(2*Math.PI*e/f)/(6378137*Math.cos(a/180*Math.PI))*(180/Math.PI))}}});
