import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
import Graphic from '@arcgis/core/Graphic';
import Point from '@arcgis/core/geometry/Point';
export interface OpRankSummary {
    candidates: Array<{
        point: Point;
        rank: number;
        uniquePct: number;
        totalPct: number;
        optimal: boolean;
    }>;
    combinedCoveragePct: number;
    gapPct: number;
    optimalIndices: number[];
}
export interface OpRankHeadlessOptions {
    observerHeightM?: number;
    maxRangeM?: number;
    aoRadiusM?: number;
    cellM?: number;
    optimalCount?: number;
}
export declare class OpRankerEngine {
    static readonly OP_LAYER_ID = "op-ranker-markers";
    static readonly RANGE_LAYER_ID = "op-ranker-range-rings";
    static readonly AO_LAYER_ID = "op-ranker-ao-boundary";
    private _view;
    private _opLayer;
    private _rangeLayer;
    private _aoLayer;
    private _mediaLayers;
    private _listPanelEl;
    private _controlPanelEl;
    private _hintEl;
    private _clickHandle;
    private _ops;
    private _running;
    private _analysed;
    private _ovState;
    private _dragTarget;
    private _dragOffsetX;
    private _dragOffsetY;
    constructor();
    initialize(view: MapView | SceneView): void;
    open(graphic: Graphic, view: MapView | SceneView): void;
    openWidget(view?: MapView | SceneView): void;
    rankCandidates(points: Point[], options?: OpRankHeadlessOptions): Promise<OpRankSummary>;
    close(): void;
    destroy(): void;
    private _createLayers;
    private _ensurePanels;
    private _listPanelHtml;
    private _controlPanelHtml;
    private _bindPanelEvents;
    private _bindMapClick;
    private _unbindMapClick;
    private _addOP;
    private _runAnalysis;
    private _computeViewshedRaster;
    private _analyseCoverage;
    private _selectOptimalSet;
    private _buildHeatmapLayer;
    private _buildIndividualViewshedLayer;
    private _buildAOBoundary;
    private _buildOPMarker;
    private _buildOPLabel;
    private _buildRangeRing;
    private _renderEmptyList;
    private _renderOPListPre;
    private _renderRankedList;
    private _renderOptimalResult;
    private _removeOP;
    private _rebuildMarkers;
    private _clearAll;
    private _syncSummary;
    private _addMediaLayer;
    private _clearMedia;
    private _flyTo;
    private _showPanels;
    private _hidePanels;
    private _makeDraggable;
    private _onDragMove;
    private _onDragEnd;
    private _setStatus;
    private _setProgress;
    private _el;
    private _input;
    private _button;
    private _num;
    private _checked;
    private _setText;
    private _tick;
    private _injectStyles;
}
export default OpRankerEngine;
