import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
export interface MagneticCompassOptions {
    enabled?: boolean;
    size?: number;
    opacity?: number;
    northColor?: [number, number, number];
    bezelColor?: [number, number, number];
    declination?: number;
}
export declare class MagneticCompass {
    private _view;
    private _layer;
    private _is3D;
    private _enabled;
    private _placing;
    private _activeId;
    private _counter;
    private _instances;
    private _size;
    private _opacity;
    private _northColor;
    private _bezelColor;
    private _declination;
    private _dragHandle;
    private _pointerMoveHandle;
    private _clickHandle;
    private _watchHandle;
    private _widget;
    private _widgetOpen;
    private _styleEl;
    start(view: MapView | SceneView): void;
    enable(): void;
    disable(): void;
    openWidget(): void;
    closeWidget(): void;
    onViewChanged(view: MapView | SceneView): void;
    setOptions(opts: MagneticCompassOptions): void;
    destroy(): void;
    private _buildFaceSVG;
    private _buildBezelSVG;
    private _buildNeedleSVG;
    private _makeSymbol;
    private _placeCompass;
    private _removeInstance;
    private _clearAllInstances;
    private _refreshAll;
    private _refreshBezel;
    private _refreshNeedles;
    private _getNeedleCorrection;
    private _getDisplayHeading;
    private _compassScreenPt;
    private _screenAngleTo;
    private _isOnBezelRing;
    private _findHitInstance;
    private _setupViewEvents;
    private _setupWatchers;
    private _removeViewEvents;
    private _createWidget;
    private _widgetHTML;
    private _bindWidgetEvents;
    private _updateWidget;
    private _updateCompassList;
    private _updateWidgetEnabledState;
    private _injectStyles;
    private _toDataURL;
    private _rgb2hex;
    private _hex2rgb;
    private _getOrCreateLayer;
}
export default MagneticCompass;
