import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
export interface MagneticCompassOptions {
    enabled?: boolean;
    size?: number;
    opacity?: number;
    northColor?: [number, number, number];
    bezelColor?: [number, number, number];
    declination?: number;
}
export interface SectorConeOptions {
    centerBearingDeg: number;
    arcWidthDeg: number;
    radiusKm: number;
    color?: [number, number, number];
    fillOpacity?: number;
    outlineOpacity?: number;
    outlineWidth?: number;
    extrudeHeightM?: number;
    label?: string;
}
export declare class MagneticCompass {
    private _view;
    private _layer;
    private _is3D;
    private _enabled;
    private _placing;
    private _activeId;
    private _counter;
    private _instances;
    private _defaultSectorColor;
    private _activeSectorId;
    private _size;
    private _opacity;
    private _northColor;
    private _bezelColor;
    private _declination;
    private _dragHandle;
    private _pointerMoveHandle;
    private _clickHandle;
    private _watchHandle;
    private _widget;
    private _widgetOpen;
    private _styleEl;
    private _hoveredInstId;
    private _hoverRingEl;
    start(view: MapView | SceneView): void;
    enable(): void;
    disable(): void;
    openWidget(): void;
    closeWidget(): void;
    onViewChanged(view: MapView | SceneView): void;
    setOptions(opts: MagneticCompassOptions): void;
    destroy(): void;
    addSector(compassId: string, opts: SectorConeOptions): string | null;
    removeSector(compassId: string, sectorId: string): void;
    updateSector(compassId: string, sectorId: string, opts: Partial<SectorConeOptions>): void;
    clearSectors(compassId: string): void;
    private _buildFaceSVG;
    private _buildBezelSVG;
    private _buildNeedleSVG;
    private _makeSymbol;
    private _geodesicDestination;
    private _buildSectorPolygon;
    private _makeSectorSymbol;
    private _refreshSector;
    private _placeCompass;
    private _removeInstance;
    private _clearAllInstances;
    private _refreshAll;
    private _refreshBezel;
    private _refreshNeedles;
    private _getNeedleCorrection;
    private _getDisplayHeading;
    private _compassScreenPt;
    private _screenAngleTo;
    private _isOnBezelRing;
    private _findHitInstance;
    private _setupViewEvents;
    private _setupWatchers;
    private _removeViewEvents;
    private _createWidget;
    private _widgetHTML;
    private _bindWidgetEvents;
    private _updateWidget;
    private _updateCompassList;
    private _updateSectorList;
    private _updateWidgetEnabledState;
    private _injectStyles;
    private _setBezelHovered;
    private _createHoverRingEl;
    private _showHoverRing;
    private _hideHoverRing;
    private _updateHoverRingPos;
    private _toDataURL;
    private _rgb2hex;
    private _hex2rgb;
    private _getOrCreateLayer;
}
export default MagneticCompass;
