define("esri/geometry/Polyline esri/symbols/TextSymbol esri/graphic esri/symbols/Font MilSymbologyExt/GeoTools esri/geometry/Point esri/Color".split(" "),function(L,d,r,E,I,A,B){return{annotate:function(m,c,a,e,n,f,g,h,C){var b=1;void 0!==C&&C.hasOwnProperty("opacity")&&(b=C.opacity);if(!e.hasOwnProperty("UEI"))if(f=new E({family:"Helvetica",size:f+"pt"}),void 0===h&&(h={}),"Area"==e.SYM_GEO_TYPE){I.getArea(c.getExtent());if(a.hasOwnProperty("UNIQUE_DESIG")&&0!==a.UNIQUE_DESIG.length)try{var q=c.getExtent().getCenter();
if(!1===isNaN(q.x)||!1===isNaN(q.x)){var l=new d(a.UNIQUE_DESIG,f);l.color.a=b;l.setAlign(d.ALIGN_MIDDLE);var p=new r(q,l);p.parentId=n;p.isFreeHand=g;m.add(p)}else console.log("Can not calculate extent")}catch(t){console.log("Malformed Geometry Found")}if(a.hasOwnProperty("DTG")&&void 0!==a.DTG&&0!==a.DTG.length)try{var J=new A(c.getExtent().getCenter().x,c.getExtent().getCenter().y+c.getExtent().getHeight()/2),F=J,u=new d(a.DTG,f);u.color.a=b;u.setAlign(d.ALIGN_MIDDLE);var v=new r(F,u);v.parentId=
n;v.isFreeHand=g;m.add(v)}catch(t){console.log("Malformed Geometry Found")}if(a.hasOwnProperty("EDTG")&&void 0!==a.EDTG&&0!==a.EDTG.length)try{var B=new A(c.getExtent().getCenter().x,c.getExtent().getCenter().y-c.getExtent().getHeight()/2),G=B,w=new d(a.EDTG,f);w.color.a=b;w.setAlign(d.ALIGN_MIDDLE);var z=new r(G,w);z.parentId=n;z.isFreeHand=g;m.add(z)}catch(t){console.log("Malformed Geometry Found")}}else if("Line"==e.SYM_GEO_TYPE){I.getArea(c.getExtent());if(a.hasOwnProperty("UNIQUE_DESIG"))try{if("Boundary"==
e.SYM_NAME){if(0!==a.UNIQUE_DESIG.length)try{q=c.getExtent().getCenter(),l=new d(a.UNIQUE_DESIG,f),l.color.a=b,l.setAlign(d.ALIGN_MIDDLE),l.yoffset=30,l.xoffset=-20,p=new r(q,l),p.parentId=n,p.isFreeHand=g,m.add(p)}catch(t){console.log("Malformed Geometry Found in Unique Designation")}if(a.hasOwnProperty("HIGHER_FORM")&&0!==a.HIGHER_FORM.length)try{var K=c.getExtent().getCenter(),D=new d(a.HIGHER_FORM,f);D.color.a=b;D.setAlign(d.ALIGN_MIDDLE);D.yoffset=-30;D.xoffset=30;var H=new r(K,D);H.parentId=
n;H.isFreeHand=g;m.add(H)}catch(t){console.log("Malformed Geometry Found in Higher Formation")}}else q=c.getExtent().getCenter(),l=new d(a.UNIQUE_DESIG,f),l.color.a=b,l.setAlign(d.ALIGN_MIDDLE),p=new r(q,l),p.parentId=n,p.isFreeHand=g,m.add(p)}catch(t){console.log("Malformed Geometry Found")}if(a.hasOwnProperty("DTG")&&void 0!==a.DTG&&0!==a.DTG.length)try{F=J=new A(c.getPoint(0,0)),u=new d(a.DTG,f),u.color.a=b,u.setAlign(d.ALIGN_MIDDLE),v=new r(F,u),v.parentId=n,v.isFreeHand=g,m.add(v)}catch(t){console.log("Malformed Geometry Found")}if(a.hasOwnProperty("EDTG")&&
void 0!==a.EDTG&&0!==a.EDTG.length)try{h=e=0,"polyline"===c.type?(e=c.paths.length-1,h=c.paths[e].length-1):(e=c.rings.length-1,h=c.rings[e].length-1),G=B=new A(c.getPoint(e,h)),w=new d(a.EDTG,f),w.color.a=b,w.setAlign(d.ALIGN_MIDDLE),z=new r(G,w),z.parentId=n,z.isFreeHand=g,m.add(z)}catch(t){console.log("Malformed Geometry Found")}}else"Point"==e.SYM_GEO_TYPE&&("160303"===e.SID?(e.OFFSET="0",a.hasOwnProperty("UNIQUE_DESIG")&&this.createLabelFromPropoerty(m,c,"UNIQUE_DESIG",g,n,a,e,f,b,h,"bottom",
"right",-5,0),a.hasOwnProperty("TARGET_DESIGNATOR")&&this.createLabelFromPropoerty(m,c,"TARGET_DESIGNATOR",g,n,a,e,f,b,h,"bottom","left",5,0),a.hasOwnProperty("STAFF_COM")&&this.createLabelFromPropoerty(m,c,"STAFF_COM",g,n,a,e,f,b,h,"top","right",-5,-3),a.hasOwnProperty("ADDL_INFO")&&this.createLabelFromPropoerty(m,c,"ADDL_INFO",g,n,a,e,f,b,h,"top","left",5,-3)):this.createLabelFromPropoerty(m,c,"UNIQUE_DESIG",g,n,a,e,f,b,h))},createLabelFromPropoerty:function(m,c,a,e,n,f,g,h,C,b,q,l,p,A){f.hasOwnProperty(a)&&
0!==f[a].length&&(a=new d(f[a],h),void 0!==q&&a.setVerticalAlignment(q),void 0!==l&&a.setHorizontalAlignment(l),a.color.a=C,ptGeom=c,"0"===g.OFFSET?a.setOffset(p,A):"1"===g.OFFSET?a.setOffset(0,g.SIZE/2):a.setOffset(0,g.SIZE-8),b.hasOwnProperty("color")&&a.setColor(new B(b.color)),b.hasOwnProperty("haloColorSize")&&(a.setHaloSize(b.haloColorSize),b.hasOwnProperty("haloColor")&&a.setHaloColor(new B(b.haloColor))),b.hasOwnProperty("textSize")&&h.setSize(b.textSize+"pt"),b.hasOwnProperty("bold")&&1===
b.bold&&h.setWeight(E.WEIGHT_BOLDER),b.hasOwnProperty("italic")&&1===b.italic&&h.setStyle(E.STYLE_ITALIC),b.hasOwnProperty("uLine")&&1===b.uLine&&a.setDecoration(d.DECORATION_UNDERLINE),b.hasOwnProperty("oLine")&&1===b.oLine&&a.setDecoration(d.DECORATION_OVERLINE),b.hasOwnProperty("tLine")&&1===b.tLine&&a.setDecoration(d.DECORATION_LINETHROUGH),c=new r(ptGeom,a),c.parentId=n,c.isFreehnd=e,m.add(c))},deAnnotate:function(d,c){for(i=d.graphics.length-1;0<=i;i--)d.graphics[i].parentId==c&&d.remove(d.graphics[i])}}});
