define("dojo/_base/declare esri/toolbars/draw esri/toolbars/edit dojo/Evented MilSymbologyExt/ControlPointsEditor MilSymbologySymbolsEngine/AnnotationEngine".split(" "),function(f,g,e,h,k,d){return f([h],{declaredClass:"MilitarySymbology.Engines.EditEngine",constructor:function(a,b,c){this.graphicLayer=b;this.textGraphicsLayer=c;this.map=a;this.draw=new g;this.editToolbar=new e(this.map);this._controlPoints=[];this.controlPtsEditor=new k(this.map,this.graphicLayer,this.editToolbar,this._controlPoints)},
init:function(){},activateCp:function(a,b){a.editToolbar.deactivate();d.deAnnotate(a.textGraphicsLayer,b.graphic.id)},deactivateCp:function(a,b){void 0!=b.graphic&&(d.annotate(a.textGraphicsLayer,b.graphic.geometry,b.graphic.drawEssentials.AMPLIFIER,b.graphic.drawEssentials,b.graphic.id,b.graphic.attributes.FRHNDSZ,b.graphic.attributes.ISFHAND,void 0,{opacity:b.graphic.symbol.color.a}),a.emit("CPchanged",{drawEssentials:b.graphic.drawEssentials,amplifier:b.graphic.drawEssentials.AMPLIFIER,geometry:b.graphic.geometry,
attributes:b.graphic.attributes,id:b.graphic.id,graphic:b.graphic}))},scale:function(a,b){a.controlPtsEditor._scaleRotateMove(b);a.removeCtrlPtsFromAttribs(b.graphic,!0)},scaleStart:function(a,b){a.controlPtsEditor._setGraphic(b.graphic);d.deAnnotate(a.textGraphicsLayer,b.graphic.id)},scaleStop:function(a,b){var c=a.removeCtrlPtsFromAttribs(b.graphic,!0);d.annotate(a.textGraphicsLayer,c.geometry,c.drawEssentials.AMPLIFIER,c.drawEssentials,c.id,c.attributes.FRHNDSZ,c.attributes.ISFHAND,void 0,a.getOpacityValue(c));
a.emit("changeInSymbol",{graphic:c})},rotate:function(a,b){a.controlPtsEditor._scaleRotateMove(b);a.removeCtrlPtsFromAttribs(b.graphic,!0)},rotateStart:function(a,b){a.controlPtsEditor._setGraphic(b.graphic);d.deAnnotate(a.textGraphicsLayer,b.graphic.id)},rotateStop:function(a,b){var c=a.removeCtrlPtsFromAttribs(b.graphic,!0);d.annotate(a.textGraphicsLayer,c.geometry,c.drawEssentials.AMPLIFIER,c.drawEssentials,c.id,c.attributes.FRHNDSZ,c.attributes.ISFHAND,void 0,a.getOpacityValue(c));a.emit("changeInSymbol",
{graphic:c})},graphicMove:function(a,b){"point"!==b.graphic.geometry.type&&(a.controlPtsEditor._scaleRotateMove(b),a.removeCtrlPtsFromAttribs(b.graphic,!0))},graphicMoveStart:function(a,b){"point"!==b.graphic.geometry.type&&a.controlPtsEditor._setGraphic(b.graphic);d.deAnnotate(a.textGraphicsLayer,b.graphic.id)},graphicMoveStop:function(a,b){var c=a.removeCtrlPtsFromAttribs(b.graphic,!0);d.annotate(a.textGraphicsLayer,c.geometry,c.drawEssentials.AMPLIFIER,c.drawEssentials,c.id,c.attributes.FRHNDSZ,
c.attributes.ISFHAND,c.drawEssentials.hasOwnProperty("labelOptions")?c.drawEssentials.labelOptions:{},a.getOpacityValue(c));a.emit("changeInSymbol",{graphic:c})},getOpacityValue:function(a){var b={};"polyline"===a.geometry.type||"polygon"===a.geometry.type?b.opacity=a.symbol.color.a:"Point"===a.drawEssentials.SYM_GEO_TYPE&&(b.opacity="000110"===a.drawEssentials.SID?a.symbol.color.a:a.symbol.outline.color.a);return b},cpMoved:function(a,b){b.graphic.setGeometry(b.drawEssentials.SCOPE.createSymbol(b.drawEssentials));
a.emit("controlPointMoved",{graphic:b.graphic})},removeCtrlPtsFromAttribs:function(a,b){void 0===b&&(b=!1);a.attributes.hasOwnProperty("tempCpoints")&&(a.drawEssentials.CTRL_PTS=a.attributes.tempCpoints,delete a.attributes.tempCpoints);a.attributes.hasOwnProperty("tempBpoints")&&(a.attributes.tempBpoints.hasOwnProperty("startPt")&&(a.drawEssentials.BASE_LN_PTS.startPt=a.attributes.tempBpoints.startPt),a.attributes.tempBpoints.hasOwnProperty("endPt")&&(a.drawEssentials.BASE_LN_PTS.endPt=a.attributes.tempBpoints.endPt),
a.attributes.tempBpoints.hasOwnProperty("midPt")&&(a.drawEssentials.BASE_LN_PTS.midPt=a.attributes.tempBpoints.midPt),delete a.attributes.tempBpoints);!0===b&&this.emit("editEvent",{graphic:a});return a},activateEdit:function(a){this.wireUpEditEvents();"point"===a.geometry.type?this.editToolbar.activate(e.MOVE,a):this.editToolbar.activate(e.ROTATE|e.SCALE|e.MOVE,a,{uniformScaling:"true"})},deactivateEdit:function(){this.unWireUpEditEvents();this.editToolbar.deactivate()},unWireUpEvents:function(){void 0!==
this.cpMovedEvt&&(this.cpMovedEvt.remove(),this.cpActivateEvt.remove(),this.cpDeActivateEvt.remove())},wireUpEditEvents:function(){this.scaleEvt=this.editToolbar.on("scale",dojo.partial(this.scale,this));this.scaleStartEvt=this.editToolbar.on("scale-start",dojo.partial(this.rotateStart,this));this.scaleStopEvt=this.editToolbar.on("scale-stop",dojo.partial(this.scaleStop,this));this.rotateEvt=this.editToolbar.on("rotate",dojo.partial(this.rotate,this));this.rotateStartEvt=this.editToolbar.on("rotate-start",
dojo.partial(this.rotateStart,this));this.rotateStopEvt=this.editToolbar.on("rotate-stop",dojo.partial(this.rotateStop,this));this.graphicMovEvt=this.editToolbar.on("graphic-move",dojo.partial(this.graphicMove,this));this.graphicMoveStartEvt=this.editToolbar.on("graphic-move-start",dojo.partial(this.graphicMoveStart,this));this.graphicMoveStopEvt=this.editToolbar.on("graphic-move-stop",dojo.partial(this.graphicMoveStop,this))},unWireUpEditEvents:function(){void 0!==this.scaleEvt&&(this.scaleEvt.remove(),
this.scaleStartEvt.remove(),this.scaleStopEvt.remove(),this.rotateEvt.remove(),this.rotateStartEvt.remove(),this.rotateStopEvt.remove(),this.graphicMovEvt.remove(),this.graphicMoveStartEvt.remove(),this.graphicMoveStopEvt.remove())},wireUpCPEvents:function(){this.activateEvt=this.editToolbar.on("activate",dojo.partial(this.activate,this));this.deActivateEvt=this.editToolbar.on("deactivate",dojo.partial(this.deactivate,this))},unWireUpCPEvents:function(){null!==this.activateEvt&&(this.activateEvt.remove(),
this.deActivateEvt.remove())},activateEditPts:function(a){this.cpMovedEvt=this.controlPtsEditor.on("cpMoved",dojo.partial(this.cpMoved,this));this.cpActivateEvt=this.controlPtsEditor.on("cpActivate",dojo.partial(this.activateCp,this));this.cpDeActivateEvt=this.controlPtsEditor.on("cpDeActivate",dojo.partial(this.deactivateCp,this));0==this.editToolbar.getCurrentState().tool?this.wireUpCPEvents():this.deactivateEdit();this.controlPtsEditor.activate(a)},deactivateEditPts:function(a){this.controlPtsEditor.deactivate(a);
this.cpMovedEvt.remove();this.cpActivateEvt.remove();this.cpDeActivateEvt.remove()},deactivateEngine:function(a){this.unWireUpCPEvents();this.unWireUpEditEvents()}})});
