define(["dojo/_base/declare","dojo/Evented","esri/toolbars/draw","esri/toolbars/edit","esri/symbols/SimpleLineSymbol","dojo/_base/Color","esri/graphic","MilSymbologySymbolsEngine/SIDC","dojo/json","MilSymbologySymbolsEngine/Mapper","MilSymbologySymbolsEngine/AnnotationEngine","esri/geometry/Point","esri/geometry/Polyline","esri/geometry/Polygon","esri/SpatialReference","dojo/text!"+location.origin+"/MilitarySymbology/Data/Symbols.json","dojo/text!"+location.origin+"/MilitarySymbology/Data/Settings.json"],
function(k,l,u,v,w,x,m,n,y,p,q,h,z,A,g,r,t){return k([l],{declaredClass:"MilitarySymbology.Engines.SymbolEngine",SIDC:"",amplifier:"",symbolData:"",settings:"",endEvent:"",drawProgressEvent:"",drawBaseLineEndEvent:"",drawClickEvent:"",isDrawing:!0,map:"",attrs:"",LCC1SP:'PROJCS["Lambert_Conformal_Conic",GEOGCS["GCS_EVEREST_INDIA_NEPAL",DATUM["D_EVEREST_INDIA_NEPAL",SPHEROID["Everest_1830_1975_Adjustment",6377299.151,300.8017254981305]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["false_easting",2743195.5],PARAMETER["false_northing",914398.5],PARAMETER["central_meridian",68.0],PARAMETER["standard_parallel_1",32.5],PARAMETER["standard_parallel_2",32.5],PARAMETER["scale_factor",0.99878641],PARAMETER["latitude_of_origin",32.5],UNIT["Meter",1.0]]',
LCC2SP:'PROJCS["Lambert_Conformal_Conic",GEOGCS["GCS_EVEREST_INDIA_NEPAL",DATUM["D_EVEREST_INDIA_NEPAL",SPHEROID["Everest_1830_1975_Adjustment",6377299.151,300.8017254981305]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["false_easting",2743195.5],PARAMETER["false_northing",914398.5],PARAMETER["central_meridian",74.0],PARAMETER["standard_parallel_1",26.0],PARAMETER["standard_parallel_2",26.0],PARAMETER["scale_factor",0.99878641],PARAMETER["latitude_of_origin",26.0],UNIT["Meter",1.0]]',
WGS1SP:4326,WGS1PROJSP:"EPSG:4326",WGS2SP:'GEOGCS["Geographic Coordinate System",DATUM["D_WGS84",SPHEROID["WGS84",6378137.0,298.257223560493]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]',constructor:function(a,b,c,e,d,f){this.settings=JSON.parse(t);this.SIDC=new n(a,this.settings);this.attrs=f;try{if(1==this.SIDC.validateSIDC(a))this.amplifier=b,this.map=c,this.graphicsLayer=e,this.textGraphicsLayer=d,this.init();else throw"Invalid SIDC Found";}catch(g){console.log("Can not initialize Symbol Engine")}},
init:function(){this.symbolData=JSON.parse(r);var a=this.SIDC.getSID();this.SIDC.getSIDC();var b=this.SIDC.getSIDC().substr(4,2);this.currentSymbol=this.symbolData[b+a]},getSymbol:function(a){if(void 0!=this.currentSymbol)return this.mapper=new p(this.currentSymbol.Class),new (this.mapper.getInstance())(this.map,a);throw"SIDC not found";},getEchelon:function(){if(void 0!=this.SIDC)return this.SIDC._sidc.substr(8,2);throw"SIDC not found";},initialize:function(a,b,c,e){try{void 0===e&&(e=!1);var d=
this.getSymbol(a.IS_LINE);d.amplifier=this.amplifier;endEvent=d.on("onDrawEnd",dojo.partial(this.drawSymEnd,this));drawProgressEvent=d.on("onDrawProgress",dojo.partial(this.symDrawProgress,this));drawClickEvent=d.on("onDrawClick",dojo.partial(this.symDrawClick,this));drawBaseLineEndEvent=d.on("onBaseLineDrawEnd",dojo.partial(this.baseLineDrawEnd,this));var f=null;void 0!==b&&b.hasOwnProperty("textSize")&&(this.settings.textSize=b.textSize);this.labelOptions=c;if("Point"===this.currentSymbol.SymGeoType||
"FPoint"===this.currentSymbol.SymGeoType)f=this.SIDC.getMarker(d.symGeometricType,d.isObstacle,this.currentSymbol.Fill),void 0!==b&&("Point"===this.currentSymbol.SymGeoType&&(b.hasOwnProperty("lineWidth")&&(f.outline.width=b.lineWidth),b.hasOwnProperty("size")&&(a.SIZE=b.size),b.hasOwnProperty("opacity")&&(f.outline.color.a=b.opacity,"000110"!==a.SID&&(f.color.a=b.opacity),a.opacity=b.opacity)),"FPoint"===this.currentSymbol.SymGeoType&&(b.hasOwnProperty("size")&&(a.size=b.size),b.hasOwnProperty("opacity")&&
(a.opacity=b.opacity))),!0===e&&(a.hasOwnProperty("GEOM")&&(a.GEOM=this.reProject(a.GEOM,this.map.spatialReference)),a.hasOwnProperty("OPTIONS")&&a.OPTIONS.hasOwnProperty("GEOM")&&(a.OPTIONS.GEOM=this.reProject(a.OPTIONS.GEOM,this.map.spatialReference))),d.init(a,f,this.SIDC.getSID(),this.currentSymbol.Name,this.currentSymbol.Offset,this.SIDC._sidc);else{f=this.SIDC.getMarker(d.symGeometricType,d.isObstacle);void 0!==b&&(b.hasOwnProperty("lineWidth")&&(f.width=b.lineWidth),b.hasOwnProperty("opacity")&&
(f.color.a=b.opacity,a.opacity=b.opacity));if(!0===e){if(a.hasOwnProperty("CTRL_PTS"))for(b=0;b<a.CTRL_PTS.length;b++)a.CTRL_PTS[b]=this.reProject(a.CTRL_PTS[b],this.map.spatialReference);a.hasOwnProperty("BASE_LN_PTS")&&(a.BASE_LN_PTS.hasOwnProperty("startPt")&&(a.BASE_LN_PTS.startPt=this.reProject(a.BASE_LN_PTS.startPt,this.map.spatialReference)),a.BASE_LN_PTS.hasOwnProperty("midPt")&&(a.BASE_LN_PTS.midPt=this.reProject(a.BASE_LN_PTS.midPt,this.map.spatialReference)),a.BASE_LN_PTS.hasOwnProperty("endPt")&&
(a.BASE_LN_PTS.endPt=this.reProject(a.BASE_LN_PTS.endPt,this.map.spatialReference)))}d.init(a,f)}}catch(g){}},drawSymEnd:function(a,b){var c;if("polyline"==b.geometry.type||"point"==b.geometry.type||"polygon"==b.geometry.type)c=b.marker;else throw"Implement it, please";c=new m(b.geometry,c);var e=a.generateUUID();b.drawEssentials.SIDC=a.SIDC.getSIDC();c.drawEssentials=b.drawEssentials;c.id=!1===a.attrs.hasOwnProperty("symbolId")||void 0===a.attrs.symbolId||null===a.attrs.symbolId?e:a.attrs.symbolId;
c.attributes=a.attrs;a.graphicsLayer.add(c);isDrawing=!1;endEvent.remove();drawProgressEvent.remove();drawClickEvent.remove();drawBaseLineEndEvent.remove();e=0;c.drawEssentials.hasOwnProperty("ISFHAND")&&(e=c.drawEssentials.ISFHAND);b.drawEssentials.labelOptions=a.labelOptions;var d={};"000110"===c.drawEssentials.SID?d.opacity=b.marker.color.a:d=a.getOpacityValue(c);q.annotate(a.textGraphicsLayer,b.geometry,b.drawEssentials.AMPLIFIER,b.drawEssentials,c.id,a.settings.textSize,e,a.labelOptions,d);b.drawEssentials.hasOwnProperty("opacity")&&
delete b.drawEssentials.opacity;a.emit("symDrawEnd",{isDone:"done",drawEssentials:b.drawEssentials,id:c.id,graphic:c})},getOpacityValue:function(a){var b={};"polyline"===a.geometry.type||"polygon"===a.geometry.type?b.opacity=a.symbol.color.a:"Point"===a.drawEssentials.SYM_GEO_TYPE&&(b.opacity=a.symbol.outline.color.a);return b},symDrawProgress:function(a,b){a.emit("symDrawProgress",{currentDrawEssentials:b.currentDrawEssentials,currentGeometry:b.currentGeometry,currentMarker:b.currentMarker})},symDrawClick:function(a,
b){a.emit("symDrawClick",{currentPts:b.currentPts})},baseLineDrawEnd:function(a,b){a.emit("baseLineDrawEnd",{currentPts:b.currentPts})},generateUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){return(16*Math.random()|0).toString(16)})},supplySpatialRef:function(a,b,c,e){var d=new g;void 0!==c?d=c:"WGS1SP"===e?d=new g(4326):"WGS2SP"===e?d=new g(this.WGS2SP):"LCC1SP"===e?d=new g(this.LCC1SP):"LCC2SP"===e&&(d=new g(this.LCC2SP));return new h(a,b,d)},stripSpatialRef:function(a){var b;
a.spatialReference.hasOwnProperty("wkid")?a.spatialReference.wkid===this.WGS1SP&&(b="WGS1SP"):a.spatialReference.hasOwnProperty("wkt")&&(a.spatialReference.wkt===this.WGS2SP?b="WGS2SP":a.spatialReference.wkt===this.LCC1SP?b="LCC1SP":a.spatialReference.wkt===this.LCC2SP&&(b="LCC2SP"));a=new h(a.x,a.y);delete a.spatialReference;a.sp=b;return a},reProject:function(a,b){var c,e;e=b.hasOwnProperty("wkid")?b.wkid:b.wkt;a.hasOwnProperty("spatialReference")?a.spatialReference.hasOwnProperty("wkid")?c=a.spatialReference.wkid:
a.spatialReference.hasOwnProperty("wkt")&&(c=a.spatialReference.wkt):a.hasOwnProperty("sp")&&("WGS1SP"===a.sp?c=this.WGS1PROJSP:"WGS2SP"===a.sp?c=this.WGS1PROJSP:"LCC1SP"===a.sp?c=this.LCC1SP:"LCC2SP"===a.sp&&(c=this.LCC2SP),delete a.sp);e===this.WGS1SP&&(e=this.WGS1PROJSP);c===this.WGS1SP&&(c=this.WGS1PROJSP);c=proj4(c,e,[a.x,a.y]);a.x=c[0];a.y=c[1];a.spatialReference=new g(b);return a}})});
