import Graphic from '@arcgis/core/Graphic';
import Point from '@arcgis/core/geometry/Point';
import MapView from '@arcgis/core/views/MapView';
import SceneView from '@arcgis/core/views/SceneView';
export interface MissionTerrainFeature {
    rank: number;
    type: string;
    name: string;
    point: Point;
    elevationM: number;
    prominenceM: number;
    elevationAdvantageM: number;
    viewshedPct: number;
    deadGroundPct: number;
    defensibilityScore: number;
    mobilityInfluenceScore: number;
    corridorControlScore: number;
    compositeScore: number;
    recommendedUse: string;
    cautions: string[];
}
export declare class MissionPlannerEngine {
    static readonly FEATURE_LAYER_ID = "mission-planner-ranked-features";
    static readonly AO_LAYER_ID = "mission-planner-ao";
    static readonly OBSERVER_LAYER_ID = "mission-planner-observers";
    static readonly CORRIDOR_LAYER_ID = "mission-planner-corridor-influence";
    static readonly LABEL_LAYER_ID = "mission-planner-labels";
    static readonly SNAPSHOT_LAYER_ID = "mission-planner-report-snapshot";
    private _view;
    private _selectedGraphic;
    private _panelEl;
    private _featureLayer;
    private _aoLayer;
    private _observerLayer;
    private _corridorLayer;
    private _labelLayer;
    private _snapshotLayer;
    private _localPeaks;
    private _keyTerrain;
    private _deadGround;
    private _posDef;
    private _opRanker;
    private _ocoka;
    private _observers;
    private _results;
    private _corridors;
    private _running;
    constructor();
    initialize(view: MapView | SceneView): void;
    onViewChanged(view: MapView | SceneView): void;
    open(graphic?: Graphic, view?: MapView | SceneView): void;
    openWidget(view?: MapView | SceneView): void;
    close(): void;
    destroy(): void;
    runAnalysis(): Promise<void>;
    clearResults(updateUi?: boolean): void;
    generateReport(): string;
    private _scoreCandidate;
    private _mergeCandidates;
    private _corridorInfluence;
    private _recommendUse;
    private _buildCautions;
    private _resolveCenter;
    private _resolveExtent;
    private _activeObservers;
    private _addObserver;
    private _drawAoi;
    private _drawCorridors;
    private _drawResults;
    private _renderObservers;
    private _renderResults;
    private _renderReport;
    private _ensurePanel;
    private _activateTab;
    private _setStatus;
    private _setRunDisabled;
    private _num;
    private _selectValue;
    private _toCsv;
    private _toGeoJson;
    private _download;
    private _injectStyles;
}
export default MissionPlannerEngine;
