/**
 * CollabSettingsManifest.ts
 *
 * Settings surface for the Collab engine — ⚙ Settings menu and Ctrl+K palette.
 * Every entry maps to a path under `collab` in Settings.json, except the master
 * switch which lives at `features.collab` alongside the other engine toggles.
 */

import type { SettingDescriptor } from '../../Support/SettingsWidget';

export const collabSettingsManifest: SettingDescriptor[] = [
  {
    path: ['features', 'collab'],
    label: 'Collaboration',
    group: 'Session',
    type: 'boolean',
    help: 'Master switch. When on, this workstation joins the collaboration room and shares map symbols, slide edits, cursors and drawing previews with everyone else in the same room. Off by default — nothing is transmitted while it is off.',
    keywords: ['collab', 'collaborate', 'multi user', 'share', 'live', 'team', 'realtime'],
  },
  {
    path: ['collab', 'room'],
    label: 'Room name',
    group: 'Session',
    type: 'string',
    help: 'Everyone using the same room name sees each other. Use one room per operation or per planning cell (e.g. "OPORD-12"). Changing this reconnects immediately.',
    keywords: ['room', 'channel', 'session', 'group'],
  },
  {
    path: ['collab', 'userName'],
    label: 'Your name',
    group: 'Session',
    type: 'string',
    help: 'Shown on your cursor and in the online list. Leave blank to be auto-named. Your colour is derived from your workstation and stays the same on every screen.',
    keywords: ['name', 'user', 'callsign', 'identity'],
  },
  {
    path: ['collab', 'transport'],
    label: 'Connection',
    group: 'Session',
    type: 'enum',
    options: [
      { value: 'sse', label: 'LAN relay (SSE)' },
      { value: 'broadcast', label: 'This PC only (windows/tabs)' },
    ],
    help: 'LAN relay talks to the small fan-out relay hosted by whatever serves the app — no database, no second service. "This PC only" uses BroadcastChannel to link windows on this machine with no server at all: the quickest way to try the feature.',
    keywords: ['transport', 'sse', 'broadcast', 'relay', 'connection', 'lan'],
  },
  {
    path: ['collab', 'relayUrl'],
    label: 'Relay URL',
    group: 'Session',
    type: 'string',
    help: 'Leave blank to use the same origin that served the app — correct in almost every case. Set an absolute URL (e.g. http://ops-pc:6600) only when the relay runs separately from the web server.',
    keywords: ['relay', 'url', 'server', 'host', 'endpoint'],
  },
  {
    path: ['collab', 'showRoster'],
    label: 'Show online list',
    group: 'Session',
    type: 'boolean',
    help: 'The small chip in the top-right showing connection state and a coloured initial per person. Its colours match the cursors on the map.',
    keywords: ['roster', 'online', 'users', 'presence', 'who'],
  },

  {
    path: ['collab', 'syncMap'],
    label: 'Share map symbols',
    group: 'What to share',
    type: 'boolean',
    help: 'Share creating, moving, editing and deleting of map symbols. Turn off to keep your own map private while still seeing other people’s cursors.',
    keywords: ['map', 'symbols', 'graphics', 'sync', 'share'],
  },
  {
    path: ['collab', 'syncSlides'],
    label: 'Share briefing deck',
    group: 'What to share',
    type: 'boolean',
    help: 'Share slides and live co-editing of objects inside a slide. Requires the Briefing engine to be enabled. Note: captured map screenshots are not transmitted (they can be megabytes) — a shared slide shows its annotations over the live map.',
    keywords: ['slides', 'briefing', 'deck', 'editor', 'co-edit'],
  },
  {
    path: ['collab', 'syncView'],
    label: 'Shared map view',
    group: 'What to share',
    type: 'boolean',
    help: 'Link everyone to the same location and scale — pan or zoom and the whole room follows. Whoever moves last has priority for a moment, so two people panning at once cannot fight over the map. You can also click a person in the online list to follow just them; moving the map yourself stops following. Between a 2D and a 3D window only the centre and scale are shared, so nobody loses their own camera angle. Also toggleable from the link button on the online chip.',
    keywords: [
      'view',
      'camera',
      'sync',
      'shared',
      'follow',
      'pan',
      'zoom',
      'extent',
      'lock view',
      'presenter',
    ],
  },
  {
    path: ['collab', 'sharePresentation'],
    label: 'Shared briefing',
    group: 'What to share',
    type: 'boolean',
    help: 'Let one person drive the deck for the room. Whoever takes the podium (the microphone button on the collaboration rail) advances the slides and everyone follows; their laser, pen and spotlight are shared too. Navigating a slide yourself steps out of it and offers Rejoin. Going fullscreen with the briefer is always your own choice — nobody can force your screen into present mode.',
    keywords: ['brief', 'briefing', 'present', 'presenter', 'podium', 'slides', 'follow', 'deck'],
  },
  {
    path: ['collab', 'shareInk'],
    label: 'Share briefer’s mark-up',
    group: 'What to share',
    type: 'boolean',
    help: 'Share the laser pointer, pen ink and spotlight of whoever is briefing. Their strokes are drawn on your screen but never added to your own deck — mark-up you did not draw cannot end up in your saved plan.',
    keywords: ['ink', 'laser', 'pen', 'spotlight', 'pointer', 'markup', 'annotate'],
  },
  {
    path: ['collab', 'chat'],
    label: 'Room chat',
    group: 'What to share',
    type: 'boolean',
    help: 'A text channel for the room, on the collaboration rail. Nothing is stored on the relay: your scrollback is what you heard while you were here, and a late joiner is handed the last 50 lines by a peer. Turn this off and no chat listener runs at all.',
    keywords: ['chat', 'message', 'text', 'talk', 'im'],
  },
  {
    path: ['collab', 'shareViewport'],
    label: 'Share where I am looking',
    group: 'What to share',
    type: 'boolean',
    help: 'Broadcast the extent of your own map about once a second, so peers who have turned on “Show peer viewports” can see which area you are working in. Turn this off to keep your area of interest to yourself.',
    keywords: ['viewport', 'extent', 'looking', 'area', 'privacy', 'where'],
  },
  {
    path: ['collab', 'slideImageMaxKb'],
    label: 'Max slide thumbnail (KB)',
    group: 'What to share',
    type: 'number',
    min: 0,
    max: 4096,
    step: 32,
    help: 'Slide thumbnails larger than this are dropped before sending, to keep one capture from flooding the network. 0 never sends thumbnails.',
    keywords: ['thumbnail', 'image', 'size', 'bandwidth', 'kb'],
  },

  {
    path: ['collab', 'showCursors'],
    label: 'Show cursors',
    group: 'Presence',
    type: 'boolean',
    help: 'Other people’s pointers, each with a name chip in their colour, positioned at the geographic point they are hovering.',
    keywords: ['cursor', 'pointer', 'mouse', 'presence'],
  },
  {
    path: ['collab', 'showTrails'],
    label: 'Show mouse trails',
    group: 'Presence',
    type: 'boolean',
    help: 'A short fading tail behind each cursor. Makes it obvious who is gesturing at what during a discussion.',
    keywords: ['trail', 'tail', 'mouse', 'movement', 'gesture'],
  },
  {
    path: ['collab', 'trailLength'],
    label: 'Trail length',
    group: 'Presence',
    type: 'number',
    min: 2,
    max: 40,
    step: 1,
    help: 'How many recent positions each trail keeps. Longer trails are easier to follow but busier on a crowded map.',
    keywords: ['trail', 'length', 'history', 'points'],
  },
  {
    path: ['collab', 'showPreviews'],
    label: 'Show drawings in progress',
    group: 'Presence',
    type: 'boolean',
    help: 'Draw other people’s unfinished shapes as a dashed ghost that updates as they draw, replaced by the real symbol the moment they finish.',
    keywords: ['preview', 'ghost', 'in progress', 'drawing', 'live'],
  },
  {
    path: ['collab', 'showPings'],
    label: 'Show location pings',
    group: 'Presence',
    type: 'boolean',
    help: 'Draw the “look here” markers other people drop — an expanding ring in their colour with their name, which fades after a few seconds. Drop your own with the pin button on the collaboration rail, then click the map.',
    keywords: ['ping', 'look here', 'point', 'attention', 'marker', 'highlight'],
  },
  {
    path: ['collab', 'showViewports'],
    label: 'Show peer viewports',
    group: 'Presence',
    type: 'boolean',
    help: 'Outline the area each peer is looking at as a dashed rectangle with their name. Off by default because it is busy on a crowded map; a peer looking at much the same place as you is never drawn, since the rectangle would just trace your own screen edge.',
    keywords: ['viewport', 'extent', 'rectangle', 'where', 'looking', 'awareness'],
  },
  {
    path: ['collab', 'activityLog'],
    label: 'Log who did what',
    group: 'Presence',
    type: 'boolean',
    help: 'Write a line to the Engine Log whenever somebody adds, edits or deletes something — “Maj Ali added Phase Line”, “Capt Roy moved 3 symbols”. One gesture is summarised as one line rather than logged per object. Useful during planning and as the nearest thing to an after-action record.',
    keywords: ['activity', 'log', 'audit', 'history', 'who', 'aar', 'feed'],
  },
  {
    path: ['collab', 'cursorHz'],
    label: 'Cursor updates / sec',
    group: 'Presence',
    type: 'number',
    min: 1,
    max: 60,
    step: 1,
    help: 'How often your pointer position is broadcast. 20 is smooth on a LAN; reduce it on a congested or wireless network.',
    keywords: ['rate', 'hz', 'throttle', 'bandwidth', 'frequency'],
  },

  {
    path: ['collab', 'locks'],
    label: 'Lock objects while editing',
    group: 'Editing',
    type: 'boolean',
    help: 'Selecting a symbol or slide object claims it: others see a padlock in your colour and cannot edit it until you deselect. This is what prevents two people fighting over the same graphic. With it off, the last edit to arrive simply wins.',
    keywords: ['lock', 'claim', 'conflict', 'exclusive', 'editing'],
  },
  {
    path: ['collab', 'showLocks'],
    label: 'Show lock badges',
    group: 'Editing',
    type: 'boolean',
    help: 'Draw the padlock marker on things other people are currently editing — on map symbols, and around objects inside the slide editor.',
    keywords: ['lock', 'badge', 'padlock', 'indicator'],
  },
  {
    path: ['collab', 'lockTtlMs'],
    label: 'Lock timeout (ms)',
    group: 'Editing',
    type: 'number',
    min: 2000,
    max: 60000,
    step: 1000,
    help: 'A lock is refreshed while in use and released automatically this long after its holder goes quiet — so a closed browser or a dropped connection never leaves an object stuck.',
    keywords: ['lock', 'timeout', 'ttl', 'expire', 'stale'],
  },

  {
    path: ['collab', 'token'],
    label: 'Relay token',
    group: 'Session',
    type: 'string',
    help: 'Optional shared secret. Leave blank for the normal isolated-LAN posture, where anyone who can reach the relay can join. When set, the relay must be started with the same value in COLLAB_TOKEN and every client needs it too — changing this reconnects. It travels in the URL, so treat it as a gate against casual access, not as encryption.',
    keywords: ['token', 'secret', 'auth', 'password', 'security', 'relay'],
  },
  {
    path: ['collab', 'debug'],
    label: 'Trace to console',
    group: 'Diagnostics',
    type: 'boolean',
    help: 'Log every step of the sync chain to the browser console — observers attached, change detected, op sent, op received, op applied. Turn this on when something is not appearing on the other machine: the last line printed tells you where the chain stops. Also available at runtime as window.collabDebug(true).',
    keywords: ['debug', 'trace', 'log', 'diagnostic', 'troubleshoot', 'console'],
  },
];
