/**
 * BriefingSettingsManifest.ts
 *
 * Briefing / Present mode — slide capture, goTo playback, full-screen
 * present mode, and staged reveal builds (appear / fade / flyIn / drawOn).
 */

import type { SettingDescriptor } from '../Support/SettingsWidget';

export const briefingSettingsManifest: SettingDescriptor[] = [
  {
    path: ['features', 'briefing'],
    label: 'Briefing engine',
    group: 'Engine',
    type: 'boolean',
    help: 'Master switch for the Briefing / Present mode engine (slide capture, playback, builds).',
    keywords: ['enable', 'disable', 'present', 'slides', 'presentation'],
  },
  {
    path: ['briefing', 'defaultTransitionMs'],
    label: 'Transition (ms)',
    group: 'Playback',
    type: 'number',
    min: 0,
    max: 5000,
    step: 100,
    help: 'Default goTo duration when entering a slide. Stored per slide at capture time.',
    keywords: ['duration', 'goto', 'speed'],
  },
  {
    path: ['briefing', 'defaultEffect'],
    label: 'Default build effect',
    group: 'Builds',
    type: 'enum',
    options: [
      { value: 'appear', label: 'Appear' },
      { value: 'fade', label: 'Fade' },
      { value: 'flyIn', label: 'Fly in' },
      { value: 'drawOn', label: 'Draw on' },
    ],
    help: 'Effect used when a build step is added without an explicit effect.',
    keywords: ['animation', 'reveal', 'stagger'],
  },
  {
    path: ['briefing', 'autoplayIntervalMs'],
    label: 'Autoplay interval (ms)',
    group: 'Playback',
    type: 'number',
    min: 500,
    max: 60000,
    step: 500,
    help: 'Delay between slides when autoplay is running (briefingEngine.startAutoplay()).',
    keywords: ['auto', 'advance', 'loop'],
  },
  {
    path: ['briefing', 'autoplayLoop'],
    label: 'Autoplay loops',
    group: 'Playback',
    type: 'boolean',
    help: 'Restart from the first slide instead of stopping when autoplay reaches the end.',
    keywords: ['auto', 'repeat', 'loop', 'kiosk'],
  },
  {
    path: ['briefing', 'fullscreen'],
    label: 'Fullscreen on present',
    group: 'Present mode',
    type: 'boolean',
    help: 'Take the browser into real fullscreen when the slideshow starts. Leaving fullscreen (Esc / F11) also ends the slideshow.',
    keywords: ['present', 'screen', 'projector', 'f11'],
  },
  {
    path: ['briefing', 'presenterPanel'],
    label: 'Open presenter view',
    group: 'Present mode',
    type: 'boolean',
    help: 'Show the presenter view (speaker notes, timer, next slide, jump grid) as soon as the slideshow starts. N toggles it at any time; it can be popped out to a second screen.',
    keywords: ['notes', 'speaker', 'timer', 'presenter', 'second screen'],
  },
  {
    path: ['briefing', 'controlsIdleMs'],
    label: 'Hide controls after (ms)',
    group: 'Present mode',
    type: 'number',
    min: 600,
    max: 20000,
    step: 250,
    help: 'Idle delay before the present-mode control bar, counter and mouse cursor fade out. Any mouse movement brings them back.',
    keywords: ['idle', 'cursor', 'toolbar', 'auto-hide'],
  },
  {
    path: ['briefing', 'penColor'],
    label: 'Pen colour',
    group: 'Present mode',
    type: 'color',
    help: 'Ink colour for the present-mode pen (P). Ink is session-only unless you choose to keep it when the slideshow ends.',
    keywords: ['ink', 'draw', 'annotate', 'markup'],
  },
  {
    path: ['briefing', 'penWidth'],
    label: 'Pen width',
    group: 'Present mode',
    type: 'number',
    min: 0.0005,
    max: 0.02,
    step: 0.0005,
    help: 'Pen stroke width as a fraction of view height, so it keeps its proportion at any screen size.',
    keywords: ['ink', 'thickness', 'stroke'],
  },
  {
    path: ['briefing', 'spotlightRadius'],
    label: 'Spotlight radius',
    group: 'Present mode',
    type: 'number',
    min: 0.03,
    max: 0.6,
    step: 0.01,
    help: "Spotlight hole size (S) as a fraction of the view's smaller side. [ and ] resize it while presenting.",
    keywords: ['dim', 'focus', 'highlight', 'mask'],
  },
];
