/**
 * DeclutterSettingsManifest.ts
 *
 * Annotation / symbol / cluster / label / disperse / ladder declutter. Every
 * sub-system has its own group; the master toggle gates the whole engine.
 */

import type { SettingDescriptor } from '../Support/SettingsWidget';

export const declutterSettingsManifest: SettingDescriptor[] = [
  {
    path: ['declutter', 'enabled'],
    label: 'Declutter engine',
    group: 'Engine',
    type: 'boolean',
    help: 'Master switch. Turns the entire declutter system on or off.',
    keywords: ['enable', 'disable'],
  },

  // ── Annotations ────────────────────────────────────────────────────────────
  {
    path: ['declutter', 'annotations', 'mode'],
    label: 'Annotation mode',
    group: 'Annotations',
    type: 'enum',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'zoom', label: 'Zoom threshold' },
      { value: 'minscale', label: 'ArcGIS minScale' },
      { value: 'density', label: 'Per-symbol density' },
    ],
    help: 'How label visibility is controlled. Zoom threshold = hide below a zoom level. Density = hide labels colliding in an NxN pixel cell.',
  },
  {
    path: ['declutter', 'annotations', 'zoomThreshold'],
    label: 'Label hide zoom',
    group: 'Annotations',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'Labels hide below this zoom level (1 = world, 22 = street).',
  },
  {
    path: ['declutter', 'annotations', 'densityMinPx'],
    label: 'Density cell (px)',
    group: 'Annotations',
    type: 'number',
    min: 5,
    max: 200,
    step: 5,
    help: 'In density mode, hide a label if another already occupies an NxN pixel cell.',
  },
  {
    path: ['declutter', 'annotations', 'fadeMs'],
    label: 'Fade (ms)',
    group: 'Annotations',
    type: 'number',
    min: 0,
    max: 2000,
    step: 50,
    help: 'Duration of the label fade animation. 0 = instant.',
  },

  // ── Symbols ────────────────────────────────────────────────────────────────
  {
    path: ['declutter', 'symbols', 'hideBelow'],
    label: 'Hide symbols when zoomed out',
    group: 'Symbols',
    type: 'boolean',
    help: 'When on, symbols (not just labels) also hide below the symbol threshold.',
  },
  {
    path: ['declutter', 'symbols', 'zoomThreshold'],
    label: 'Symbol hide zoom',
    group: 'Symbols',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'Symbols hide below this zoom. Should be lower (more zoomed-out) than the label threshold.',
  },
  {
    path: ['declutter', 'symbols', 'echelonBased'],
    label: 'Echelon-based visibility',
    group: 'Symbols',
    type: 'boolean',
    help: 'Show large echelons (Army, Corps) at low zoom; smaller echelons (Platoon, Squad) only at high zoom.',
  },
  {
    path: ['declutter', 'symbols', 'fadeMs'],
    label: 'Fade (ms)',
    group: 'Symbols',
    type: 'number',
    min: 0,
    max: 2000,
    step: 50,
    help: 'Duration of the symbol fade animation. 0 = instant.',
  },

  // ── Cluster badges ─────────────────────────────────────────────────────────
  {
    path: ['declutter', 'cluster', 'enabled'],
    label: 'Cluster badges',
    group: 'Cluster badges',
    type: 'boolean',
    help: 'Aggregate nearby symbols into a single count badge to reduce clutter at low zoom.',
  },
  {
    path: ['declutter', 'cluster', 'minClusterSize'],
    label: 'Min cluster size',
    group: 'Cluster badges',
    type: 'number',
    min: 2,
    max: 50,
    step: 1,
    help: 'Minimum nearby symbols before aggregation kicks in.',
  },
  {
    path: ['declutter', 'cluster', 'radiusPx'],
    label: 'Cluster radius (px)',
    group: 'Cluster badges',
    type: 'number',
    min: 10,
    max: 400,
    step: 5,
    help: 'Screen-pixel radius searched for cluster neighbours around each seed symbol.',
  },
  {
    path: ['declutter', 'cluster', 'maxZoom'],
    label: 'Disable above zoom',
    group: 'Cluster badges',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'Above this zoom the scene is sparse enough that clustering is skipped.',
  },
  {
    path: ['declutter', 'cluster', 'fadeMs'],
    label: 'Fade (ms)',
    group: 'Cluster badges',
    type: 'number',
    min: 0,
    max: 2000,
    step: 50,
    help: 'Cluster layer fade-in / fade-out duration.',
  },
  {
    path: ['declutter', 'cluster', 'respectIdentity'],
    label: 'Respect identity',
    group: 'Cluster badges',
    type: 'boolean',
    help: 'When on, friendly and hostile symbols cluster separately.',
  },
  {
    path: ['declutter', 'cluster', 'promoteMode'],
    label: 'Promote mode',
    group: 'Cluster badges',
    type: 'enum',
    options: [
      { value: 'badge', label: 'Badge (circle + count)' },
      { value: 'seed', label: 'Seed (highest member + ×N)' },
    ],
    help: 'Badge: replace cluster with a generic circle. Seed: keep the highest-priority member visible with an ×N tag.',
  },

  // ── Label placement ────────────────────────────────────────────────────────
  {
    path: ['declutter', 'labels', 'enabled'],
    label: 'Maplex label placer',
    group: 'Label placement',
    type: 'boolean',
    help: 'Try-fit labels around their parent symbol in 8 positions; resolve collisions with displacement and leader lines.',
  },
  {
    path: ['declutter', 'labels', 'offsetPx'],
    label: 'Offset (px)',
    group: 'Label placement',
    type: 'number',
    min: 4,
    max: 100,
    step: 1,
    help: 'Pixel distance between a symbol and its preferred label position.',
  },
  {
    path: ['declutter', 'labels', 'leaderThresholdPx'],
    label: 'Leader threshold (px)',
    group: 'Label placement',
    type: 'number',
    min: 0,
    max: 200,
    step: 1,
    help: 'Draw a leader line only when the label is displaced more than this many pixels.',
  },
  {
    path: ['declutter', 'labels', 'leaderColor'],
    label: 'Leader color',
    group: 'Label placement',
    type: 'color',
    colorAsRgb: true,
    help: 'Color of leader lines.',
  },
  {
    path: ['declutter', 'labels', 'leaderWidth'],
    label: 'Leader width',
    group: 'Label placement',
    type: 'number',
    min: 0.25,
    max: 6,
    step: 0.25,
    help: 'Width of leader lines in pixels.',
  },
  {
    path: ['declutter', 'labels', 'leaderOpacity'],
    label: 'Leader opacity',
    group: 'Label placement',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Opacity of leader lines.',
  },
  {
    path: ['declutter', 'labels', 'maxToPlace'],
    label: 'Max labels per solve',
    group: 'Label placement',
    type: 'number',
    min: 50,
    max: 5000,
    step: 50,
    help: 'Hard cap on labels processed per solve. Lower values keep dense scenes fast.',
  },
  {
    path: ['declutter', 'labels', 'abbreviateOnOverflow'],
    label: 'Abbreviate on overflow',
    group: 'Label placement',
    type: 'boolean',
    help: 'When the full text doesn\'t fit, retry with a truncated version (e.g. "Bravo Company" → "Bravo Co…").',
  },
  {
    path: ['declutter', 'labels', 'abbreviateMaxChars'],
    label: 'Abbreviate max chars',
    group: 'Label placement',
    type: 'number',
    min: 2,
    max: 40,
    step: 1,
    help: 'Maximum characters kept before the ellipsis when abbreviating.',
  },
  {
    path: ['declutter', 'labels', 'hideOnOverflow'],
    label: 'Hide on overflow',
    group: 'Label placement',
    type: 'boolean',
    help: 'When no position fits (even abbreviated), hide the label rather than overlap.',
  },

  // ── Disperse markers ───────────────────────────────────────────────────────
  {
    path: ['declutter', 'disperse', 'enabled'],
    label: 'Disperse markers',
    group: 'Disperse markers',
    type: 'boolean',
    help: 'Radially fan out symbols stacked at the same coordinate so each is visible at high zoom.',
  },
  {
    path: ['declutter', 'disperse', 'minZoom'],
    label: 'Activate above zoom',
    group: 'Disperse markers',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'Disperse only runs at or above this zoom; below this, clustering handles overlap.',
  },
  {
    path: ['declutter', 'disperse', 'maxZoom'],
    label: 'Disable above zoom',
    group: 'Disperse markers',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'At very high zoom symbols return to their true positions for individual inspection.',
  },
  {
    path: ['declutter', 'disperse', 'thresholdPx'],
    label: 'Stack threshold (px)',
    group: 'Disperse markers',
    type: 'number',
    min: 2,
    max: 100,
    step: 1,
    help: 'Symbols within this screen-pixel distance are treated as a stack.',
  },
  {
    path: ['declutter', 'disperse', 'radiusPx'],
    label: 'Fan radius (px)',
    group: 'Disperse markers',
    type: 'number',
    min: 4,
    max: 120,
    step: 1,
    help: 'Distance each member is moved from the centroid when fanned out.',
  },
  {
    path: ['declutter', 'disperse', 'maxGroupSize'],
    label: 'Max stack size',
    group: 'Disperse markers',
    type: 'number',
    min: 2,
    max: 60,
    step: 1,
    help: 'Beyond this stack size, extras stay at the centroid (safety valve).',
  },

  // ── Ladder ─────────────────────────────────────────────────────────────────
  {
    path: ['declutter', 'ladder', 'enabled'],
    label: 'Ladder (flag halyard)',
    group: 'Ladder',
    type: 'boolean',
    help: 'Stack nearby same-identity symbols into a vertical chain connected by a thin spine down to their centroid. Highest echelon on top.',
  },
  {
    path: ['declutter', 'ladder', 'minZoom'],
    label: 'Activate above zoom',
    group: 'Ladder',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'Ladders only form at or above this zoom level.',
  },
  {
    path: ['declutter', 'ladder', 'maxZoom'],
    label: 'Disable above zoom',
    group: 'Ladder',
    type: 'number',
    min: 1,
    max: 22,
    step: 1,
    help: 'Above this zoom symbols return to their true positions.',
  },
  {
    path: ['declutter', 'ladder', 'thresholdPx'],
    label: 'Stack threshold (px)',
    group: 'Ladder',
    type: 'number',
    min: 2,
    max: 400,
    step: 1,
    help: 'Symbols within this screen-pixel radius gather into the same ladder.',
  },
  {
    path: ['declutter', 'ladder', 'minRungs'],
    label: 'Min rungs',
    group: 'Ladder',
    type: 'number',
    min: 2,
    max: 30,
    step: 1,
    help: 'Skip stacks smaller than this.',
  },
  {
    path: ['declutter', 'ladder', 'maxRungs'],
    label: 'Max rungs',
    group: 'Ladder',
    type: 'number',
    min: 2,
    max: 100,
    step: 1,
    help: 'Stacks larger than this are released to true positions (likely cluster candidates).',
  },
  {
    path: ['declutter', 'ladder', 'layout'],
    label: 'Layout',
    group: 'Ladder',
    type: 'enum',
    options: [
      { value: 'side', label: 'Side (halyard)' },
      { value: 'center', label: 'Center (vertical chain)' },
    ],
    help: 'Side: rungs offset from the spine (flag-halyard). Center: rungs centred on the spine.',
  },
  {
    path: ['declutter', 'ladder', 'sideOffsetPx'],
    label: 'Side offset (px)',
    group: 'Ladder',
    type: 'number',
    min: 4,
    max: 120,
    step: 1,
    help: 'In side layout: horizontal distance between the spine and each rung.',
  },
  {
    path: ['declutter', 'ladder', 'rungSpacingPx'],
    label: 'Rung spacing (px)',
    group: 'Ladder',
    type: 'number',
    min: 6,
    max: 100,
    step: 1,
    help: 'Vertical pixel spacing between consecutive rungs.',
  },
  {
    path: ['declutter', 'ladder', 'spineColor'],
    label: 'Spine color',
    group: 'Ladder',
    type: 'color',
    colorAsRgb: true,
    help: 'Color of the spine line (and tie-lines).',
  },
  {
    path: ['declutter', 'ladder', 'spineWidth'],
    label: 'Spine width',
    group: 'Ladder',
    type: 'number',
    min: 0.25,
    max: 6,
    step: 0.25,
    help: 'Width of the spine in pixels.',
  },
  {
    path: ['declutter', 'ladder', 'spineOpacity'],
    label: 'Spine opacity',
    group: 'Ladder',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Opacity of the spine. Tie-lines render at 60% of this value.',
  },
  {
    path: ['declutter', 'ladder', 'respectIdentity'],
    label: 'Respect identity',
    group: 'Ladder',
    type: 'boolean',
    help: 'When on, friendly / hostile / neutral symbols form separate ladders.',
  },
  {
    path: ['declutter', 'ladder', 'showTieLines'],
    label: 'Show tie-lines',
    group: 'Ladder',
    type: 'boolean',
    help: 'In side layout: thin perpendicular lines from the spine to each rung. Ignored when layout=center.',
  },
  {
    path: ['declutter', 'ladder', 'altitudeMode'],
    label: 'Altitude mode (3D)',
    group: 'Ladder',
    type: 'boolean',
    help: 'Stack rungs vertically in altitude with a stem from ground to the top rung — like flags up a halyard. Visible in 3D only.',
  },
  {
    path: ['declutter', 'ladder', 'altitudeSpacingM'],
    label: 'Altitude spacing (m)',
    group: 'Ladder',
    type: 'number',
    min: 1,
    max: 20000,
    step: 10,
    help: 'Vertical distance in metres between consecutive rungs in altitude mode.',
  },
  {
    path: ['declutter', 'ladder', 'stemBaseAltitudeM'],
    label: 'Stem base altitude (m)',
    group: 'Ladder',
    type: 'number',
    min: 0,
    max: 10000,
    step: 1,
    help: 'Offset above ground where the stem starts. Lifts the whole ladder.',
  },

  // ── Diagnostics ────────────────────────────────────────────────────────────
  {
    path: ['declutter', 'perfHud'],
    label: 'Performance HUD',
    group: 'Diagnostics',
    type: 'boolean',
    help: 'Show an overlay with last-solve time, spatial-index size, and per-step durations. Useful for tuning cluster radius / max-to-place.',
  },
];
