/**
 * DrawingCuesSettingsManifest.ts
 *
 * Live drawing aids — rubber band, coordinate readout, angular snap guides,
 * distance rings, nearby highlight, adaptive ring scaling, magnetic compass.
 */

import type { SettingDescriptor } from '../Support/SettingsWidget';

export const drawingCuesSettingsManifest: SettingDescriptor[] = [
  {
    path: ['features', 'drawingCues'],
    label: 'Drawing cues engine',
    group: 'Engine',
    type: 'boolean',
    help: 'Master switch for every drawing aid below — rubber band, angular guides, distance rings, etc.',
    keywords: ['enable', 'disable'],
  },

  // ── Rubber band ────────────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'rubberBand', 'enabled'],
    label: 'Rubber band',
    group: 'Rubber band',
    type: 'boolean',
    help: 'Dashed line from the last placed control point to the cursor, showing live length and bearing.',
  },
  {
    path: ['drawingCues', 'rubberBand', 'lineOpacity'],
    label: 'Opacity',
    group: 'Rubber band',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Opacity of the rubber band line.',
  },

  // ── Coordinate readout ────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'coordinateDisplay', 'enabled'],
    label: 'Coordinate readout',
    group: 'Coordinate readout',
    type: 'boolean',
    help: 'Floating lat/lon readout that follows the cursor while drawing.',
    keywords: ['lat', 'lon', 'mgrs', 'position'],
  },

  // ── Angular guides ─────────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'angularGuides', 'enabled'],
    label: 'Angular guides',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Snap lines at 0°/45°/90°/… from the last placed control point. Hold cursor near one to snap.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'snapIntervalDeg'],
    label: 'Snap interval °',
    group: 'Angular guides',
    type: 'number',
    min: 5,
    max: 90,
    step: 5,
    help: 'Show a guide every N degrees (e.g. 45 → guides at 0°/45°/90°…).',
  },
  {
    path: ['drawingCues', 'angularGuides', 'snapThresholdDeg'],
    label: 'Snap threshold °',
    group: 'Angular guides',
    type: 'number',
    min: 2,
    max: 30,
    step: 1,
    help: 'Cursor snaps to a guide when within this many degrees of it.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'lineColor'],
    label: 'Color',
    group: 'Angular guides',
    type: 'color',
    colorAsRgb: true,
    help: 'Color of the angular guide lines.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'lineOpacity'],
    label: 'Opacity',
    group: 'Angular guides',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Opacity of the guide lines.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'lineWidth'],
    label: 'Line width',
    group: 'Angular guides',
    type: 'number',
    min: 0.5,
    max: 10,
    step: 0.5,
    help: 'Width of the guide lines in pixels.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'showLabel'],
    label: 'Show angle label',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Print the angle (e.g. "045°") on each guide.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'fontSize'],
    label: 'Label size',
    group: 'Angular guides',
    type: 'number',
    min: 8,
    max: 20,
    step: 1,
    help: 'Font size for angle labels.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'showArc'],
    label: 'Protractor arc',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Draw a protractor-style arc connecting the angular guides.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'arcRadiusKm'],
    label: 'Arc radius (km)',
    group: 'Angular guides',
    type: 'number',
    min: 0.1,
    max: 20,
    step: 0.1,
    help: 'Radius of the protractor arc in kilometres.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'showFan'],
    label: 'Snap fan',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Show a fan-shaped snap zone around each guide line.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'showSnapPoint'],
    label: 'Snap point marker',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Render a small marker where the cursor will snap on the guide.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'showAnchor'],
    label: 'Anchor cross',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Cross marker at the last-placed control point, where guides originate.',
  },
  {
    path: ['drawingCues', 'angularGuides', 'relativeSegment'],
    label: 'Relative segment angle',
    group: 'Angular guides',
    type: 'boolean',
    help: 'Add a guide aligned with the previous segment so you can lay out perpendicular / parallel lines.',
  },

  // ── Distance rings ─────────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'distanceRings', 'enabled'],
    label: 'Distance rings',
    group: 'Distance rings',
    type: 'boolean',
    help: 'Concentric distance rings from the last placed control point.',
  },
  {
    path: ['drawingCues', 'distanceRings', 'intervalKm'],
    label: 'Interval (km)',
    group: 'Distance rings',
    type: 'number',
    min: 0.1,
    max: 100,
    step: 0.1,
    help: 'Spacing between consecutive rings.',
  },
  {
    path: ['drawingCues', 'distanceRings', 'ringCount'],
    label: 'Ring count',
    group: 'Distance rings',
    type: 'number',
    min: 1,
    max: 10,
    step: 1,
    help: 'Number of rings drawn.',
  },
  {
    path: ['drawingCues', 'distanceRings', 'lineColor'],
    label: 'Color',
    group: 'Distance rings',
    type: 'color',
    colorAsRgb: true,
    help: 'Color of the rings.',
  },
  {
    path: ['drawingCues', 'distanceRings', 'lineOpacity'],
    label: 'Opacity',
    group: 'Distance rings',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Opacity of the rings.',
  },
  {
    path: ['drawingCues', 'distanceRings', 'lineWidth'],
    label: 'Width',
    group: 'Distance rings',
    type: 'number',
    min: 0.5,
    max: 10,
    step: 0.5,
    help: 'Width of the ring lines.',
  },

  // ── Nearby highlight ───────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'nearbyHighlight', 'enabled'],
    label: 'Nearby highlight',
    group: 'Nearby highlight',
    type: 'boolean',
    help: 'Ring around existing symbols that fall within a proximity radius of the cursor.',
  },
  {
    path: ['drawingCues', 'nearbyHighlight', 'radiusKm'],
    label: 'Detection radius (km)',
    group: 'Nearby highlight',
    type: 'number',
    min: 0.1,
    max: 200,
    step: 0.5,
    help: 'Symbols within this radius of the cursor are highlighted.',
  },
  {
    path: ['drawingCues', 'nearbyHighlight', 'ringRadiusKm'],
    label: 'Ring size (km)',
    group: 'Nearby highlight',
    type: 'number',
    min: 0.1,
    max: 10,
    step: 0.1,
    help: 'Radius of the highlight ring around each detected symbol.',
  },

  // ── Adaptive scaling ───────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'adaptive', 'enabled'],
    label: 'Adaptive ring intervals',
    group: 'Adaptive scaling',
    type: 'boolean',
    help: 'Auto-pick distance ring spacing based on map zoom for readable rings at any scale.',
  },
  {
    path: ['drawingCues', 'adaptive', 'coverageFraction'],
    label: 'Coverage fraction',
    group: 'Adaptive scaling',
    type: 'number',
    min: 0.05,
    max: 0.75,
    step: 0.05,
    help: 'Target fraction of the visible map covered by the outermost ring.',
  },
  {
    path: ['drawingCues', 'adaptive', 'maxOuterKm'],
    label: 'Max outer (km)',
    group: 'Adaptive scaling',
    type: 'number',
    min: 1,
    max: 10000,
    step: 10,
    help: 'Cap on the outermost ring radius regardless of zoom.',
  },

  // ── Magnetic compass ───────────────────────────────────────────────────────
  {
    path: ['drawingCues', 'magneticCompass', 'enabled'],
    label: 'Magnetic compass',
    group: 'Magnetic compass',
    type: 'boolean',
    help: 'Interactive magnetic compass overlay. Place multiple compasses on the map and drag the bezel to set bearing.',
  },
  {
    path: ['drawingCues', 'magneticCompass', 'declination'],
    label: 'Declination °',
    group: 'Magnetic compass',
    type: 'number',
    min: -180,
    max: 180,
    step: 0.1,
    help: 'Magnetic declination offset applied to the compass readout. Positive = east of true north.',
  },
];
