/**
 * ExportToolsSettingsManifest.ts
 *
 * PowerPoint (.pptx) deck export — mode (flat screenshots vs editable
 * shapes), image format, explode-builds, speaker notes.
 */

import type { SettingDescriptor } from '../Support/SettingsWidget';

export const exportToolsSettingsManifest: SettingDescriptor[] = [
  {
    path: ['features', 'exportTools'],
    label: 'Export tools',
    group: 'Engine',
    type: 'boolean',
    help: 'Master switch for the PowerPoint deck exporter.',
    keywords: ['enable', 'disable', 'pptx', 'powerpoint'],
  },
  {
    path: ['exportTools', 'mode'],
    label: 'Export mode',
    group: 'Deck',
    type: 'enum',
    options: [
      { value: 'flat', label: 'Flat screenshots (Mode A)' },
      { value: 'editable', label: 'Editable shapes (Mode B)' },
    ],
    help: 'Flat: each slide is one map screenshot. Editable: simple lines / areas / text become native, selectable PowerPoint shapes over a basemap raster (unit icons and decorated tactical graphics stay in the image). In 2D the shapes align exactly; in 3D they are projected from the current camera over terrain and are APPROXIMATE — expect small offsets on steep relief. Choose the view accordingly.',
    keywords: ['flat', 'editable', 'shapes', 'native', 'vector', 'mode', '2d', '3d'],
  },
  {
    path: ['exportTools', 'format'],
    label: 'Image format',
    group: 'Deck',
    type: 'enum',
    options: [
      { value: 'png', label: 'PNG (lossless)' },
      { value: 'jpeg', label: 'JPEG (smaller file)' },
    ],
    help: 'Format of the map screenshot placed on each slide.',
    keywords: ['png', 'jpeg', 'quality', 'size'],
  },
  {
    path: ['exportTools', 'explodeBuilds'],
    label: 'Explode builds',
    group: 'Deck',
    type: 'boolean',
    help: 'Emit one extra slide per staged-reveal build step (base state + cumulative reveals).',
    keywords: ['builds', 'staged', 'reveal', 'animation'],
  },
  {
    path: ['exportTools', 'includeNotes'],
    label: 'Include speaker notes',
    group: 'Deck',
    type: 'boolean',
    help: 'Attach each briefing slide’s notes as PowerPoint speaker notes.',
    keywords: ['notes', 'speaker'],
  },
  {
    path: ['exportTools', 'layout'],
    label: 'Slide size',
    group: 'Deck',
    type: 'enum',
    options: [
      { value: '16x9', label: '16:9 — 10 × 5.63in' },
      { value: '16x10', label: '16:10 — 10 × 6.25in' },
      { value: '4x3', label: '4:3 — 10 × 7.5in' },
      { value: 'wide', label: 'Widescreen — 13.3 × 7.5in' },
      { value: 'custom', label: 'Custom (deck width / height below)' },
    ],
    help: 'Slide dimensions of the exported deck. “Custom” uses the deck width/height below, read as pixels at 96 DPI (so 1280 × 720 = 13.33 × 7.5in, the same as Widescreen).',
    keywords: ['layout', 'size', 'aspect', '16:9', '4:3', 'widescreen', 'dimensions'],
  },
  {
    path: ['exportTools', 'deckWidth'],
    label: 'Custom deck width (px)',
    group: 'Deck',
    type: 'number',
    min: 96,
    max: 5376,
    step: 16,
    help: 'Only used when Slide size is “Custom”. Pixels at 96 DPI.',
    keywords: ['width', 'custom', 'size', 'pixels'],
  },
  {
    path: ['exportTools', 'deckHeight'],
    label: 'Custom deck height (px)',
    group: 'Deck',
    type: 'number',
    min: 96,
    max: 5376,
    step: 16,
    help: 'Only used when Slide size is “Custom”. Pixels at 96 DPI.',
    keywords: ['height', 'custom', 'size', 'pixels'],
  },
  {
    path: ['exportTools', 'compress'],
    label: 'Compress package',
    group: 'Deck',
    type: 'boolean',
    help: 'Zip-deflate the .pptx. Screenshots are already compressed so a flat deck barely shrinks, but Mode B’s shape XML compresses several times over. Costs extra time on export.',
    keywords: ['compress', 'zip', 'deflate', 'size', 'smaller'],
  },
  {
    path: ['exportTools', 'useMaster'],
    label: 'Header & footer',
    group: 'Header / footer',
    type: 'boolean',
    help: 'Draw the deck’s furniture: classification banners top and bottom, a header and footer strip, the slide-number stamp, and a real title placeholder so slide titles appear in PowerPoint’s outline view. These strips now show on the slide editor canvas and in the slideshow as well as in the .pptx. The map is fitted BETWEEN them rather than over them, so it becomes slightly smaller. Every field below is a DEFAULT — a briefing that sets its own keeps it, so the classification travels with the document.',
    keywords: [
      'master',
      'template',
      'banner',
      'classification',
      'header',
      'footer',
      'placeholder',
      'outline',
    ],
  },
  {
    path: ['exportTools', 'classification'],
    label: 'Classification banner',
    group: 'Header / footer',
    type: 'string',
    help: 'Text for the banner strips, e.g. “UNCLASSIFIED//FOUO”. Blank = no banners. The strip colour follows the marking (UNCLASSIFIED green, CONFIDENTIAL/RESTRICTED blue, SECRET red, TOP SECRET orange, CUI purple). Requires “Header & footer”.',
    keywords: ['classification', 'banner', 'unclassified', 'secret', 'fouo', 'cui', 'marking'],
  },
  {
    path: ['exportTools', 'headerText'],
    label: 'Header text',
    group: 'Header / footer',
    type: 'string',
    help: 'Header strip text, drawn just below the top banner. Tokens: {DTG}, {DATE}, {TITLE} (deck), {SLIDE} (this slide’s title), {SECTION}, {PAGE}, {PAGES}, {COMPANY}, {AUTHOR}, {SUBJECT}. Requires “Header & footer”.',
    keywords: ['header', 'strip', 'section', 'title', 'top'],
  },
  {
    path: ['exportTools', 'footerText'],
    label: 'Footer text',
    group: 'Header / footer',
    type: 'string',
    help: 'Footer strip text. Tokens: {DTG} (military date-time group), {DATE}, {TITLE} (deck), {SLIDE} (this slide’s title), {SECTION}, {PAGE}, {PAGES}, {COMPANY}, {AUTHOR}, {SUBJECT}. Requires “Header & footer”.',
    keywords: ['footer', 'dtg', 'date', 'unit', 'master'],
  },
  {
    path: ['exportTools', 'slideNumbers'],
    label: 'Slide numbers',
    group: 'Header / footer',
    type: 'boolean',
    help: 'Stamp the slide number at the right end of the footer strip. In the exported deck this is PowerPoint’s own slide-number field, so it renumbers itself if the recipient reorders the deck. Without “Header & footer” it falls back to a plain bottom-right stamp.',
    keywords: ['page', 'number', 'numbering', 'footer', 'stamp'],
  },
  {
    path: ['exportTools', 'numberFormat'],
    label: 'Slide number style',
    group: 'Header / footer',
    type: 'enum',
    options: [
      { value: 'n', label: '7' },
      { value: 'n-of-m', label: '7 / 24' },
    ],
    help: 'Whether the stamp shows the deck length too. OOXML has no total-slides field, so “7 / 24” writes the total as static text beside PowerPoint’s live number — and is omitted entirely when “Explode builds” makes the emitted slide count differ from the briefing’s.',
    keywords: ['number', 'total', 'of', 'page', 'count'],
  },
  {
    path: ['exportTools', 'skipFirst'],
    label: 'Not on the title slide',
    group: 'Header / footer',
    type: 'boolean',
    help: 'Leave slide 1 bare — PowerPoint’s own “Don’t show on title slide”. The slide fills the whole page and keeps its number. Individual slides can opt out too, from Deck setup in the slide editor.',
    keywords: ['title', 'first', 'skip', 'cover', 'slide 1'],
  },
  {
    path: ['exportTools', 'headFont'],
    label: 'Heading font',
    group: 'Theme',
    type: 'string',
    help: 'Deck default heading font (PowerPoint theme). Blank leaves PptxGenJS’ own default. Must be a font the recipient has installed.',
    keywords: ['font', 'heading', 'typeface', 'theme'],
  },
  {
    path: ['exportTools', 'bodyFont'],
    label: 'Body font',
    group: 'Theme',
    type: 'string',
    help: 'Deck default body font (PowerPoint theme). Blank leaves PptxGenJS’ own default.',
    keywords: ['font', 'body', 'typeface', 'theme'],
  },
  {
    path: ['exportTools', 'useSchemeColors'],
    label: 'Theme-aware chrome',
    group: 'Theme',
    type: 'boolean',
    help: 'Emit the exporter’s own chrome (title, footer, slide numbers) as PowerPoint theme colours instead of fixed hexes, so the deck re-skins when the recipient changes theme. Your own annotation colours and the classification banner are never changed — those are deliberate choices.',
    keywords: ['scheme', 'theme', 'colour', 'color', 'restyle', 'palette'],
  },
  {
    path: ['exportTools', 'rtl'],
    label: 'Right-to-left',
    group: 'Theme',
    type: 'boolean',
    help: 'Mark the deck right-to-left (Arabic, Hebrew, Farsi).',
    keywords: ['rtl', 'arabic', 'hebrew', 'farsi', 'direction', 'bidi'],
  },
  {
    path: ['exportTools', 'deckTitle'],
    label: 'Document title',
    group: 'Properties',
    type: 'string',
    help: 'Written to the pptx document properties (PowerPoint → File → Info).',
    keywords: ['title', 'metadata', 'properties', 'provenance'],
  },
  {
    path: ['exportTools', 'author'],
    label: 'Author',
    group: 'Properties',
    type: 'string',
    help: 'Document author. Blank leaves PptxGenJS’ own default.',
    keywords: ['author', 'creator', 'metadata', 'properties', 'provenance'],
  },
  {
    path: ['exportTools', 'company'],
    label: 'Company / unit',
    group: 'Properties',
    type: 'string',
    help: 'Document company field — normally the issuing unit or formation.',
    keywords: ['company', 'unit', 'formation', 'metadata', 'properties'],
  },
  {
    path: ['exportTools', 'subject'],
    label: 'Subject',
    group: 'Properties',
    type: 'string',
    help: 'Document subject — e.g. the operation or exercise name.',
    keywords: ['subject', 'operation', 'metadata', 'properties'],
  },
  {
    path: ['exportTools', 'revision'],
    label: 'Revision',
    group: 'Properties',
    type: 'string',
    help: 'Document revision number.',
    keywords: ['revision', 'version', 'metadata', 'properties'],
  },
];
