/**
 * ExportToolsSettingsManifest.ts
 *
 * PowerPoint (.pptx) deck export — mode (flat screenshots vs editable
 * shapes), image format, explode-builds, speaker notes.
 */

import type { SettingDescriptor } from '../Support/SettingsWidget';

export const exportToolsSettingsManifest: SettingDescriptor[] = [
  {
    path: ['features', 'exportTools'],
    label: 'Export tools',
    group: 'Engine',
    type: 'boolean',
    help: 'Master switch for the PowerPoint deck exporter.',
    keywords: ['enable', 'disable', 'pptx', 'powerpoint'],
  },
  {
    path: ['exportTools', 'mode'],
    label: 'Export mode',
    group: 'Deck',
    type: 'enum',
    options: [
      { value: 'flat', label: 'Flat screenshots (Mode A)' },
      { value: 'editable', label: 'Editable shapes (Mode B)' },
    ],
    help: 'Flat: each slide is one map screenshot. Editable: simple lines / areas / text become native, selectable PowerPoint shapes over a basemap raster (unit icons and decorated tactical graphics stay in the image). In 2D the shapes align exactly; in 3D they are projected from the current camera over terrain and are APPROXIMATE — expect small offsets on steep relief. Choose the view accordingly.',
    keywords: ['flat', 'editable', 'shapes', 'native', 'vector', 'mode', '2d', '3d'],
  },
  {
    path: ['exportTools', 'format'],
    label: 'Image format',
    group: 'Deck',
    type: 'enum',
    options: [
      { value: 'png', label: 'PNG (lossless)' },
      { value: 'jpeg', label: 'JPEG (smaller file)' },
    ],
    help: 'Format of the map screenshot placed on each slide.',
    keywords: ['png', 'jpeg', 'quality', 'size'],
  },
  {
    path: ['exportTools', 'explodeBuilds'],
    label: 'Explode builds',
    group: 'Deck',
    type: 'boolean',
    help: 'Emit one extra slide per staged-reveal build step (base state + cumulative reveals).',
    keywords: ['builds', 'staged', 'reveal', 'animation'],
  },
  {
    path: ['exportTools', 'includeNotes'],
    label: 'Include speaker notes',
    group: 'Deck',
    type: 'boolean',
    help: 'Attach each briefing slide’s notes as PowerPoint speaker notes.',
    keywords: ['notes', 'speaker'],
  },
  {
    path: ['exportTools', 'layout'],
    label: 'Slide size',
    group: 'Deck',
    type: 'enum',
    options: [
      { value: '16x9', label: '16:9 — 10 × 5.63in' },
      { value: '16x10', label: '16:10 — 10 × 6.25in' },
      { value: '4x3', label: '4:3 — 10 × 7.5in' },
      { value: 'wide', label: 'Widescreen — 13.3 × 7.5in' },
      { value: 'custom', label: 'Custom (deck width / height below)' },
    ],
    help: 'Slide dimensions of the exported deck. “Custom” uses the deck width/height below, read as pixels at 96 DPI (so 1280 × 720 = 13.33 × 7.5in, the same as Widescreen).',
    keywords: ['layout', 'size', 'aspect', '16:9', '4:3', 'widescreen', 'dimensions'],
  },
  {
    path: ['exportTools', 'deckWidth'],
    label: 'Custom deck width (px)',
    group: 'Deck',
    type: 'number',
    min: 96,
    max: 5376,
    step: 16,
    help: 'Only used when Slide size is “Custom”. Pixels at 96 DPI.',
    keywords: ['width', 'custom', 'size', 'pixels'],
  },
  {
    path: ['exportTools', 'deckHeight'],
    label: 'Custom deck height (px)',
    group: 'Deck',
    type: 'number',
    min: 96,
    max: 5376,
    step: 16,
    help: 'Only used when Slide size is “Custom”. Pixels at 96 DPI.',
    keywords: ['height', 'custom', 'size', 'pixels'],
  },
  {
    path: ['exportTools', 'slideNumbers'],
    label: 'Slide numbers',
    group: 'Deck',
    type: 'boolean',
    help: 'Stamp a page number in the bottom-right corner of every slide.',
    keywords: ['page', 'number', 'numbering', 'footer'],
  },
  {
    path: ['exportTools', 'compress'],
    label: 'Compress package',
    group: 'Deck',
    type: 'boolean',
    help: 'Zip-deflate the .pptx. Screenshots are already compressed so a flat deck barely shrinks, but Mode B’s shape XML compresses several times over. Costs extra time on export.',
    keywords: ['compress', 'zip', 'deflate', 'size', 'smaller'],
  },
  {
    path: ['exportTools', 'useMaster'],
    label: 'Use slide master',
    group: 'Master',
    type: 'boolean',
    help: 'Build the deck on a generated slide master: classification banners top and bottom, a footer strip, and a real title placeholder so slide titles appear in PowerPoint’s outline view and can be restyled from the master. The map is fitted BETWEEN the banners rather than over them, so it becomes slightly smaller.',
    keywords: ['master', 'template', 'banner', 'classification', 'placeholder', 'outline'],
  },
  {
    path: ['exportTools', 'classification'],
    label: 'Classification banner',
    group: 'Master',
    type: 'string',
    help: 'Text for the banner strips, e.g. “UNCLASSIFIED//FOUO”. Blank = no banners. The strip colour follows the marking (UNCLASSIFIED green, CONFIDENTIAL/RESTRICTED blue, SECRET red, TOP SECRET orange, CUI purple). Requires “Use slide master”.',
    keywords: ['classification', 'banner', 'unclassified', 'secret', 'fouo', 'cui', 'marking'],
  },
  {
    path: ['exportTools', 'footerText'],
    label: 'Footer text',
    group: 'Master',
    type: 'string',
    help: 'Footer strip text. Tokens: {DTG} (military date-time group), {DATE}, {TITLE}, {COMPANY}, {AUTHOR}, {SUBJECT}. Requires “Use slide master”.',
    keywords: ['footer', 'dtg', 'date', 'unit', 'master'],
  },
  {
    path: ['exportTools', 'headFont'],
    label: 'Heading font',
    group: 'Theme',
    type: 'string',
    help: 'Deck default heading font (PowerPoint theme). Blank leaves PptxGenJS’ own default. Must be a font the recipient has installed.',
    keywords: ['font', 'heading', 'typeface', 'theme'],
  },
  {
    path: ['exportTools', 'bodyFont'],
    label: 'Body font',
    group: 'Theme',
    type: 'string',
    help: 'Deck default body font (PowerPoint theme). Blank leaves PptxGenJS’ own default.',
    keywords: ['font', 'body', 'typeface', 'theme'],
  },
  {
    path: ['exportTools', 'useSchemeColors'],
    label: 'Theme-aware chrome',
    group: 'Theme',
    type: 'boolean',
    help: 'Emit the exporter’s own chrome (title, footer, slide numbers) as PowerPoint theme colours instead of fixed hexes, so the deck re-skins when the recipient changes theme. Your own annotation colours and the classification banner are never changed — those are deliberate choices.',
    keywords: ['scheme', 'theme', 'colour', 'color', 'restyle', 'palette'],
  },
  {
    path: ['exportTools', 'rtl'],
    label: 'Right-to-left',
    group: 'Theme',
    type: 'boolean',
    help: 'Mark the deck right-to-left (Arabic, Hebrew, Farsi).',
    keywords: ['rtl', 'arabic', 'hebrew', 'farsi', 'direction', 'bidi'],
  },
  {
    path: ['exportTools', 'deckTitle'],
    label: 'Document title',
    group: 'Properties',
    type: 'string',
    help: 'Written to the pptx document properties (PowerPoint → File → Info).',
    keywords: ['title', 'metadata', 'properties', 'provenance'],
  },
  {
    path: ['exportTools', 'author'],
    label: 'Author',
    group: 'Properties',
    type: 'string',
    help: 'Document author. Blank leaves PptxGenJS’ own default.',
    keywords: ['author', 'creator', 'metadata', 'properties', 'provenance'],
  },
  {
    path: ['exportTools', 'company'],
    label: 'Company / unit',
    group: 'Properties',
    type: 'string',
    help: 'Document company field — normally the issuing unit or formation.',
    keywords: ['company', 'unit', 'formation', 'metadata', 'properties'],
  },
  {
    path: ['exportTools', 'subject'],
    label: 'Subject',
    group: 'Properties',
    type: 'string',
    help: 'Document subject — e.g. the operation or exercise name.',
    keywords: ['subject', 'operation', 'metadata', 'properties'],
  },
  {
    path: ['exportTools', 'revision'],
    label: 'Revision',
    group: 'Properties',
    type: 'string',
    help: 'Document revision number.',
    keywords: ['revision', 'version', 'metadata', 'properties'],
  },
];
