import Graphic from '@arcgis/core/Graphic';
import GraphicsLayerManager from '../Managers/GraphicsLayerManager';
import DrawEssentials from '../Support/DrawEssentials';
import Amplifier from '../Support/Amplifier';
export default class ImportExportEngine {
    private _layerManager;
    constructor(getLayerManager: () => GraphicsLayerManager);
    private _serializePoint;
    private _toPlanPoint;
    private _isPointLike;
    private _cloneDrawEssForPlan;
    private _planPointToArcGisPoint;
    private _drawEssToGeometry;
    private _fallbackSymbolForGeometry;
    private _layerIdForDrawEss;
    private _buildPlanDrawEss;
    private _buildRuntimeDrawEss;
    private _loadFallbackGraphicFromDrawEss;
    private _downloadJSON;
    saveSymbolToJSON(graphic: Graphic): object;
    loadSymbolFromJSON(data: any): Graphic | null;
    private generateUUID;
    exportLayerToJSON(): object[];
    importLayerFromJSON(data: object[]): void;
    saveToFile(filename?: string): void;
    saveSymbolToFile(graphic: Graphic): void;
    savePlanToFile(filename?: string): void;
    loadPlanFromFile(onNeedsInit?: (de: DrawEssentials, amplifier: Amplifier, id: string) => void): void;
    loadFromFile(onNeedsInit?: (de: DrawEssentials, amplifier: Amplifier, id: string) => void): void;
    saveTemplateToFile(graphic: Graphic): void;
    loadTemplateFromFile(onNeedsInit?: (de: DrawEssentials, amplifier: Amplifier, name: string) => void): void;
    applyTemplateData(data: any, onNeedsInit?: (de: DrawEssentials, amplifier: Amplifier, name: string) => void): void;
    exportToGeoJSON(): object;
    importFromGeoJSON(geojson: any): void;
    saveToGeoJSONFile(filename?: string): void;
    loadFromGeoJSONFile(): void;
}
