/**
 * VisualizationSettingsManifest.ts
 *
 * Render quality, layer effects, coverage rings, force ratio grid, convex
 * hull footprint, extruded 3D footprints.
 */

import type { SettingDescriptor } from '../Support/SettingsWidget';

const layerEffectOptions = [
  { value: '', label: 'None' },
  { value: 'bloom(1, 0.5px, 0.1)', label: 'Bloom soft' },
  { value: 'bloom(1.8, 1px, 0.1)', label: 'Bloom strong' },
  { value: 'bloom(2.5, 2px, 0)', label: 'Bloom intense' },
  { value: 'drop-shadow(0px, 0px, 8px, #0050ff, 0.8)', label: 'Blue shadow' },
  { value: 'drop-shadow(0px, 0px, 8px, #ffffff, 0.6)', label: 'White glow' },
  { value: 'drop-shadow(0px, 0px, 10px, #ff3030, 0.8)', label: 'Red glow' },
  { value: 'drop-shadow(2px, 2px, 4px, #000000, 0.7)', label: 'Hard shadow' },
  { value: 'saturate(200%) brightness(1.2)', label: 'Vivid' },
  { value: 'grayscale(100%)', label: 'Grayscale' },
  { value: 'sepia(80%)', label: 'Sepia' },
  { value: 'invert(100%)', label: 'Invert' },
  { value: 'hue-rotate(90deg)', label: 'Hue rotate 90°' },
  { value: 'hue-rotate(180deg)', label: 'Hue rotate 180°' },
  { value: 'brightness(1.5) contrast(1.2)', label: 'High contrast' },
  { value: 'brightness(0.6) contrast(1.4)', label: 'Dim contrast' },
  { value: 'blur(1px)', label: 'Blur 1px' },
  { value: 'blur(2px) brightness(1.3)', label: 'Soft blur' },
  { value: 'opacity(50%)', label: '50% opacity' },
];

export const visualizationSettingsManifest: SettingDescriptor[] = [
  {
    path: ['features', 'visualizationEngine'],
    label: 'Visualization engine',
    group: 'Engine',
    type: 'boolean',
    help: 'Master switch for tactical overlays: coverage rings, force ratio grid, footprints, layer glow.',
    keywords: ['enable', 'disable'],
  },

  // ── 3D render settings ────────────────────────────────────────────────────
  {
    path: ['visualization', 'render', 'highQuality3D'],
    label: 'High-quality 3D',
    group: '3D render',
    type: 'boolean',
    help: 'Use ArcGIS SceneView high-quality profile. Sharper at the cost of frame rate.',
  },
  {
    path: ['visualization', 'render', 'disableSceneShadows'],
    label: 'Disable 3D shadows',
    group: '3D render',
    type: 'boolean',
    help: 'Turn off direct shadows and ambient occlusion. Makes imagery and symbols brighter.',
  },
  {
    path: ['visualization', 'render', 'highAtmosphereQuality'],
    label: 'High atmosphere quality',
    group: '3D render',
    type: 'boolean',
    help: 'Use the high-quality SceneView atmosphere model.',
  },
  {
    path: ['visualization', 'render', 'liftForcePoints'],
    label: 'Lift force points',
    group: '3D render',
    type: 'boolean',
    help: 'Lift UEI / force point symbols above terrain for crispness in 3D.',
  },
  {
    path: ['visualization', 'render', 'liftTacticalPoints'],
    label: 'Lift tactical points',
    group: '3D render',
    type: 'boolean',
    help: 'Lift tactical point symbols (without lifting lines or areas).',
  },
  {
    path: ['visualization', 'render', 'liftLinesAreas'],
    label: 'Lift lines / areas',
    group: '3D render',
    type: 'boolean',
    help: 'Lift tactical line and area graphics. Often best left off in rugged terrain.',
  },
  {
    path: ['visualization', 'render', 'symbolElevationOffset'],
    label: 'Lift offset (m)',
    group: '3D render',
    type: 'number',
    min: 0,
    max: 5000,
    step: 1,
    help: 'Metres above terrain used by the lift toggles above.',
  },
  {
    path: ['visualization', 'render', 'forcePointDropLines'],
    label: 'Drop line under force points',
    group: '3D render',
    type: 'boolean',
    help: 'Draw a vertical line from each lifted force point down to its ground position (3D only).',
  },
  {
    path: ['visualization', 'render', 'dropLineColor'],
    label: 'Drop line color',
    group: '3D render',
    type: 'color',
    colorAsRgb: true,
    help: 'Color of the drop line.',
  },
  {
    path: ['visualization', 'render', 'dropLineWidth'],
    label: 'Drop line width',
    group: '3D render',
    type: 'number',
    min: 0.5,
    max: 10,
    step: 0.5,
    help: 'Width of the drop line in pixels.',
  },
  {
    path: ['visualization', 'render', 'dropLineOpacity'],
    label: 'Drop line opacity',
    group: '3D render',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Opacity of the drop line.',
  },

  // ── Layer effects (2D only) ───────────────────────────────────────────────
  {
    path: ['visualization', 'layerEffects', 'enabled'],
    label: 'Layer effects',
    group: 'Layer effects (2D)',
    type: 'boolean',
    help: 'Apply CSS-filter glow / shadow effects to symbol layers. Renders only in 2D MapView (ignored in 3D).',
  },
  {
    path: ['visualization', 'layerEffects', 'forceEffect'],
    label: 'Force layer effect',
    group: 'Layer effects (2D)',
    type: 'enum',
    options: layerEffectOptions,
    help: 'Effect for UEI / Force symbols.',
  },
  {
    path: ['visualization', 'layerEffects', 'tactPtEffect'],
    label: 'Tact point effect',
    group: 'Layer effects (2D)',
    type: 'enum',
    options: layerEffectOptions,
    help: 'Effect for tactical point symbols.',
  },
  {
    path: ['visualization', 'layerEffects', 'tactEffect'],
    label: 'Tact line/area effect',
    group: 'Layer effects (2D)',
    type: 'enum',
    options: layerEffectOptions,
    help: 'Effect for tactical line / area graphics.',
  },

  // ── Coverage rings ────────────────────────────────────────────────────────
  {
    path: ['visualization', 'coverageRings', 'enabled'],
    label: 'Coverage rings',
    group: 'Coverage rings',
    type: 'boolean',
    help: 'Geodesic coverage rings around point symbols. Overlap zone shown in a warning colour.',
  },
  {
    path: ['visualization', 'coverageRings', 'radiusKm'],
    label: 'Radius (km)',
    group: 'Coverage rings',
    type: 'number',
    min: 0.5,
    max: 500,
    step: 0.5,
    help: 'Buffer radius for coverage rings.',
  },
  {
    path: ['visualization', 'coverageRings', 'showOverlap'],
    label: 'Highlight overlap',
    group: 'Coverage rings',
    type: 'boolean',
    help: 'Shade contested zones where friendly and enemy rings overlap.',
  },
  {
    path: ['visualization', 'coverageRings', 'fillOpacity'],
    label: 'Fill opacity',
    group: 'Coverage rings',
    type: 'number',
    min: 0,
    max: 0.5,
    step: 0.01,
    help: 'Opacity of the ring fill.',
  },
  {
    path: ['visualization', 'coverageRings', 'outlineWidth'],
    label: 'Outline width',
    group: 'Coverage rings',
    type: 'number',
    min: 0.5,
    max: 8,
    step: 0.5,
    help: 'Outline width in pixels.',
  },

  // ── Force ratio grid ──────────────────────────────────────────────────────
  {
    path: ['visualization', 'forceRatioGrid', 'enabled'],
    label: 'Force ratio grid',
    group: 'Force ratio grid',
    type: 'boolean',
    help: 'Grid coloured by the friendly:enemy ratio — blue = favorable, grey = parity, red = unfavorable.',
  },
  {
    path: ['visualization', 'forceRatioGrid', 'cellSizeKm'],
    label: 'Cell size (km)',
    group: 'Force ratio grid',
    type: 'number',
    min: 1,
    max: 500,
    step: 1,
    help: 'Approximate grid cell side-length.',
  },
  {
    path: ['visualization', 'forceRatioGrid', 'fillOpacity'],
    label: 'Fill opacity',
    group: 'Force ratio grid',
    type: 'number',
    min: 0,
    max: 0.6,
    step: 0.01,
    help: 'Opacity of grid cell fill.',
  },

  // ── Convex hull ───────────────────────────────────────────────────────────
  {
    path: ['visualization', 'convexHull', 'enabled'],
    label: 'Force footprint (hull)',
    group: 'Force footprint',
    type: 'boolean',
    help: 'Convex hull around all friendly and enemy point symbols to show force footprints.',
  },
  {
    path: ['visualization', 'convexHull', 'fillOpacity'],
    label: 'Fill opacity',
    group: 'Force footprint',
    type: 'number',
    min: 0,
    max: 0.5,
    step: 0.01,
    help: 'Opacity of the hull fill.',
  },
  {
    path: ['visualization', 'convexHull', 'outlineWidth'],
    label: 'Outline width',
    group: 'Force footprint',
    type: 'number',
    min: 0.5,
    max: 8,
    step: 0.5,
    help: 'Outline width in pixels.',
  },

  // ── Extruded footprints (3D) ──────────────────────────────────────────────
  {
    path: ['visualization', 'extrudedFootprints', 'enabled'],
    label: 'Extruded footprints (3D)',
    group: 'Extruded footprints',
    type: 'boolean',
    help: 'Extrude tactical line & area graphics into 3D walls and blocks. SceneView only.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'extrudePolygons'],
    label: 'Extrude polygons',
    group: 'Extruded footprints',
    type: 'boolean',
    help: 'Render polygon graphics as extruded 3D blocks.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'polygonHeightM'],
    label: 'Polygon height (m)',
    group: 'Extruded footprints',
    type: 'number',
    min: 1,
    max: 10000,
    step: 10,
    help: 'Block height for extruded polygons.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'polygonShowEdges'],
    label: 'Polygon edges',
    group: 'Extruded footprints',
    type: 'boolean',
    help: 'Draw solid edges on extruded polygon blocks.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'extrudeLines'],
    label: 'Extrude lines',
    group: 'Extruded footprints',
    type: 'boolean',
    help: 'Render polyline graphics as vertical walls along the path.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'lineWallHeightM'],
    label: 'Wall height (m)',
    group: 'Extruded footprints',
    type: 'number',
    min: 1,
    max: 10000,
    step: 10,
    help: 'Wall height for extruded polylines.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'lineWallThicknessM'],
    label: 'Wall thickness (m)',
    group: 'Extruded footprints',
    type: 'number',
    min: 0.5,
    max: 500,
    step: 0.5,
    help: 'Wall thickness (path width) for extruded polylines.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'fillOpacity'],
    label: 'Fill opacity',
    group: 'Extruded footprints',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.01,
    help: 'Opacity of the extruded shells.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'colorMode'],
    label: 'Color mode',
    group: 'Extruded footprints',
    type: 'enum',
    options: [
      { value: 'identity', label: 'Identity (friendly/enemy/neutral)' },
      { value: 'inherit', label: 'Inherit from underlying symbol' },
      { value: 'single', label: 'Single colour' },
    ],
    help: 'Source of the extrusion colour.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'singleColor'],
    label: 'Single color',
    group: 'Extruded footprints',
    type: 'color',
    colorAsRgb: true,
    help: 'Colour used when Color mode = Single.',
  },
  {
    path: ['visualization', 'extrudedFootprints', 'edgeColor'],
    label: 'Edge color',
    group: 'Extruded footprints',
    type: 'color',
    colorAsRgb: true,
    help: 'Edge colour for extruded polygon blocks.',
  },
];
