import Graphic from "@arcgis/core/Graphic";
import GraphicsLayer from "@arcgis/core/layers/GraphicsLayer";
import SimpleLineSymbol from "@arcgis/core/symbols/SimpleLineSymbol";
import SimpleFillSymbol from "@arcgis/core/symbols/SimpleFillSymbol";
import PictureFillSymbol from "@arcgis/core/symbols/PictureFillSymbol";
import MapView from "@arcgis/core/views/MapView";
import SceneView from "@arcgis/core/views/SceneView";
export declare const MINEFIELD_TEXTURE_FILL_KEY = "MINEFIELD_TEXTURE_FILL";
export declare const MINEFIELD_TEXTURE_FILL_ROLE = "minefield-texture-fill";
export interface MinefieldTextureMetadata {
    url: string;
    imageWidth?: number;
    imageHeight?: number;
    pictureWidth?: number;
    pictureHeight?: number;
    opacity?: number;
    tileWidthMapUnits?: number;
    tileHeightMapUnits?: number;
    anchorX?: number;
    anchorY?: number;
}
type ViewType = MapView | SceneView;
export declare function setMinefieldTextureMetadata(drawEssentials: any, metadata: MinefieldTextureMetadata): MinefieldTextureMetadata;
export declare function getMinefieldTextureMetadata(drawEssentials: any): MinefieldTextureMetadata | null;
export declare function isMinefieldTextureGraphic(graphic: Graphic | null | undefined): boolean;
export declare function createMinefieldPrimaryFillSymbol(view: ViewType, outline: SimpleLineSymbol | any, metadata: MinefieldTextureMetadata): PictureFillSymbol | SimpleFillSymbol;
export declare function createMinefieldPreviewFillSymbol(view: ViewType, outline: SimpleLineSymbol | any, metadata: MinefieldTextureMetadata, fallbackColor: [number, number, number]): PictureFillSymbol | SimpleFillSymbol;
export declare function applyMinefieldPrimarySymbolForView(graphic: Graphic, view: ViewType): void;
export declare function createMinefieldTextureGraphic(parentGraphic: Graphic, view: ViewType): Graphic | null;
export declare function syncMinefieldTextureGraphic(layer: GraphicsLayer | null | undefined, parentGraphic: Graphic, view: ViewType): Graphic | null;
export declare function removeMinefieldTextureForGraphic(layer: GraphicsLayer | null | undefined, graphicOrId: Graphic | string): void;
export declare function syncMinefieldTextureGraphicsForLayer(layer: GraphicsLayer | null | undefined, view: ViewType): void;
export {};
